BIBLE.register({
  id: "m01",
  part: 1,
  title: "How the Rich Get Rich",
  icon: "💎",
  summary: "The one idea under every fortune in history: own income-producing assets, borrow against them, never sell, and pass them on. This module shows you the math, the history, and the honest risks.",
  minutes: 95,
  lessons: [
    {
      id: "m01-01",
      title: "Assets vs. Liabilities",
      minutes: 10,
      blocks: [
        { h: "The only definition that matters", p: "Most people were taught that an asset is anything you own that has value. That definition will keep you poor, because by that logic your car, your furniture, and your house are all assets, and you can own all three while going broke. Robert Kiyosaki's core idea in Rich Dad Poor Dad, first self-published in 1997, is simpler and sharper. An asset is something that puts money in your pocket every month. A liability is something that takes money out of your pocket every month. Judge everything you own by the direction the cash flows, not by what it would sell for.\n\nBy this test, a rental house that collects more rent than it costs to own is an asset. The same house, if you live in it, is a liability. It costs you a mortgage payment, taxes, insurance, and repairs, and it pays you nothing until the day you sell it. That does not mean owning your home is a bad decision. It means you should stop counting it as the thing that will make you wealthy. Wealth comes from the column that pays you." },
        { h: "Two documents the rich read and the poor ignore", p: "A balance sheet is a snapshot of what you own and what you owe on one day. Assets on one side, liabilities on the other, and the difference is your net worth. An income statement is a movie, not a snapshot. It shows what came in and what went out over a month or a year. Rich people read both for themselves the way a business owner reads them for a business. The pattern they are looking for is a balance sheet where the assets column generates the income statement. In other words, the things they own produce the money they live on, instead of their labor producing it." },
        { formula: "Net worth = Assets − Liabilities.  Monthly cash flow = Income − Expenses." },
        { example: "You own a car worth $15,000 with a $12,000 loan, have $3,000 in savings, and owe $6,000 on cards. Net worth = (15,000 + 3,000) − (12,000 + 6,000) = $0. Monthly: you earn $4,500, spend $4,300. Cash flow = $200. Nothing on this balance sheet pays you. Every dollar of income comes from your time." },
        { carry: "An asset puts money in your pocket. A liability takes it out. Your house is not an asset in this frame." },
        { trap: "Buying a nicer car or a bigger house because you got a raise. Kiyosaki's point is that the middle class spends raises on liabilities that look like assets, so their expenses grow with their income and they never build the column that pays them. Every raise should buy something that pays you back." },
        { sources: [ { t: "Rich Dad Poor Dad (Wikipedia overview and publication history)", u: "https://en.wikipedia.org/wiki/Rich_Dad_Poor_Dad" } ] }
      ]
    },
    {
      id: "m01-02",
      title: "The Four Ways a Rental Pays You",
      minutes: 12,
      blocks: [
        { h: "Why real estate beats a savings account", p: "A rental property pays you four different ways at the same time. Most investments pay one way. A stock can go up in price, and some pay a dividend, but nobody else pays your stock off for you and the tax code does not let you deduct the wear and tear on it. A rental gives you cash flow, appreciation, loan paydown by the tenant, and tax benefits all at once. Learn these four and you will understand why nearly every wealthy family in history owned real estate." },
        { h: "One and two: cash flow and appreciation", p: "One, cash flow. Cash flow is what is left of the rent after you pay everything: the mortgage principal and interest, property taxes, insurance, and any association dues, which lenders call PITIA, plus the money you set aside for vacancy, repairs, big-ticket replacements, and management. If the rent is $1,900 and everything costs $1,860, your cash flow is $40 a month. That is small, and as of late 2026 with the thirty-year fixed mortgage averaging about 7.28 percent, a house bought at full retail price often cash flows that thin or worse. That is exactly why the rest of this curriculum teaches you to buy below market and add value. Cash flow is the smallest of the four on day one, but it is the one that keeps you alive.\n\nTwo, appreciation. Appreciation is the rise in the property's value over time. It is not guaranteed in any given year, and in 2008 it ran hard in reverse, which the last lesson in this module covers. Over long periods, though, houses have tended to rise with or a little above inflation because the land under them is scarce and the cost to build a new one keeps rising. You do not count on appreciation to make a deal work. You accept it as a bonus that, over a decade, usually dwarfs the cash flow." },
        { h: "Three and four: loan paydown and tax benefits", p: "Three, loan paydown by the tenant. Every month, part of your mortgage payment reduces the loan balance. You did not pay that. The tenant did, with rent. On a $150,000 loan at 7.25 percent, roughly $1,450 of the first year's payments goes to principal. That number grows every year because less of each payment goes to interest. After ten years the balance is down about $20,500 and you never wrote a check for it. This is the quietest of the four and the one beginners forget to count.\n\nFour, tax benefits. The IRS lets you deduct the cost of the building, not the land, over 27.5 years as depreciation, even though the building is probably going up in value. On a $200,000 house where the building is worth $160,000, that is about $5,800 a year of deduction that cost you nothing in cash. You also deduct mortgage interest, taxes, insurance, repairs, management, and travel. In many years a rental shows a loss on paper while putting cash in your pocket. Depreciation is recaptured when you sell, which is one more reason the wealthy do not sell. Confirm your own situation with a CPA." },
        { example: "The $200,000 house, year one. Buy for $200,000 with $50,000 down and a $150,000 loan at 7.25 percent for thirty years. Payment is $1,023. Taxes $250, insurance $150, so PITIA is $1,423. Rent $1,900. Set aside 5 percent for vacancy ($95), 10 percent for repairs and replacements ($190), 8 percent for management ($152). Cash flow: 1,900 − 1,423 − 437 = $40 a month, $480 a year. Appreciation at 3 percent: $6,000. Loan paydown: $1,452. Depreciation: $160,000 ÷ 27.5 = $5,818 of deductions. Total wealth gain before taxes: about $7,900 on $50,000 invested, close to 16 percent, and the depreciation shelters the small cash flow from tax entirely." },
        { carry: "Total return = cash flow + appreciation + principal paydown + tax savings. Depreciation: building cost ÷ 27.5 years." },
        { trap: "Counting appreciation to rescue a deal with negative cash flow. If the house does not go up, you feed it every month until you are forced to sell at the worst time. Cash flow first. The other three are the reward for surviving." },
        { sources: [
          { t: "IRS Publication 527, Residential Rental Property (27.5-year depreciation, deductible expenses)", u: "https://www.irs.gov/publications/p527" },
          { t: "Freddie Mac PMMS, 30-year fixed averaged 7.28% as of October 1, 2026", u: "https://freddiemac.gcs-web.com/news-releases/news-release-details/mortgage-rates-average-728" }
        ] }
      ]
    },
    {
      id: "m01-03",
      title: "What the Rich Have Done for Centuries",
      minutes: 14,
      blocks: [
        { h: "Land was the first fortune", p: "For most of recorded history, wealth meant land, and the income from land meant rent. The European aristocracy did not get rich by working. They owned the fields, and the people who worked the fields paid them for the right to do so. In Victorian Britain, the question of how few people owned how much land became so politically charged that Parliament ordered a national survey, the Return of Owners of Land of 1873, to settle it. The exact shares were argued about for decades, but the basic structure was never in doubt: a small class owned the ground, everyone else paid to use it, and the ownership passed from parent to child. That is the oldest wealth machine there is, and it still works." },
        { h: "John Jacob Astor and Manhattan", p: "Astor made his first fortune in the fur trade, then spent the rest of his life converting it into Manhattan land. His approach was to buy farmland north of the settled part of the island, ahead of where the city was obviously going to grow, and wait. He bought aggressively when others were desperate, including during the Panic of 1837 when he picked up property from owners facing foreclosure. He preferred to lease land to developers rather than build himself, so the tenant paid the taxes and maintenance and he kept the ground. When he died in 1848 he was widely considered the richest man in America, and the fortune came from the land, not the furs. A remark is often attributed to him that if he could live his life again he would buy every foot of land on Manhattan. That line is repeated everywhere and reliably sourced nowhere, so treat it as a legend that captures the strategy rather than a verified quote. The strategy itself is documented: buy at the edge of growth, hold through panics, collect rent, never sell." },
        { h: "The Rothschilds and lending against assets", p: "The Rothschild family built the most powerful banking network of the nineteenth century from a different direction. Starting from Frankfurt, Mayer Amschel Rothschild placed his five sons in five European financial capitals. The London branch, founded by Nathan Mayer Rothschild in 1798, moved money for the British government during the Napoleonic Wars, supplied coin to the Bank of England during the liquidity crisis of 1825, and in 1875 financed Britain's purchase of a controlling interest in the Suez Canal. The lesson for you is not the scale. It is the principle: the family did not spend its capital, it lent it against things of value and collected interest, and it kept ownership inside the family across generations. Lending against collateral and keeping the asset is the same idea you will use when a bank lends you money against a house." },
        { h: "Twentieth-century dynasties", p: "The pattern repeats in the modern era. The Rockefeller family established a family office in 1882 to manage the family's holdings, and from 1933 it occupied a full floor of 30 Rockefeller Plaza known as Room 5600. Its job was not to make the family rich; the family was already rich. Its job was to keep the assets working and intact for the next generation. In Dallas, Trammell Crow built his first warehouse in 1948 and leased it to a battery company; by 1971 Forbes called him the largest landlord in the United States, and his company eventually controlled hundreds of millions of square feet. He built for tenants and kept the buildings. Sam Zell earned the nickname the Grave Dancer by buying distressed property in downturns when nobody else would, and in 2007, near the top of the market, sold his office company Equity Office to Blackstone for 39 billion dollars, at the time the largest private equity deal in history. Zell is the exception that teaches the rule: he did sell, but only at a price that made sense, and he bought when prices were broken." },
        { h: "The common thread", p: "Across six centuries, three continents, and every kind of personality, the people who stayed rich did the same four things. They owned assets that produced income. They borrowed against those assets instead of selling them. They held through panics and bought more during them. And they passed the assets to the next generation instead of cashing out. None of them got rich from a paycheck. The rest of this module breaks the four moves into mechanics you can use." },
        { carry: "The pattern: own income-producing assets, borrow against them, never sell, pass them on." },
        { sources: [
          { t: "Return of Owners of Land, 1873 (Wikipedia)", u: "https://en.wikipedia.org/wiki/Return_of_Owners_of_Land,_1873" },
          { t: "John Jacob Astor: The making of a hardnosed speculator (The Real Deal)", u: "https://therealdeal.com/magazine/new-york-june-2008/john-jacob-astor-the-making-of-a-hardnosed-speculator/" },
          { t: "Grid Millionaire: John Jacob Astor (Museum of the City of New York)", u: "https://thegreatestgrid.mcny.org/greatest-grid/john-jacob-astor" },
          { t: "Rothschild banking family of England (Wikipedia)", u: "https://en.wikipedia.org/wiki/Rothschild_banking_family_of_England" },
          { t: "Rockefellers leaving 30 Rockefeller Plaza (Family Business Magazine)", u: "https://familybusinessmagazine.com/rockefellers-leaving-30-rockefeller-plaza" },
          { t: "Trammell Crow (Wikipedia)", u: "https://en.wikipedia.org/wiki/Trammell_Crow" },
          { t: "Sam Zell obituary (The Real Deal)", u: "https://therealdeal.com/national/2023/05/18/sam-zell-contrarian-billionaire-real-estate-investor-dies/" }
        ] }
      ]
    },
    {
      id: "m01-04",
      title: "Buy, Borrow, Die",
      minutes: 10,
      blocks: [
        { h: "Three words that explain the tax code", p: "Buy, Borrow, Die is a phrase coined in the mid-1990s by Edward McCaffery, a tax law professor at the University of Southern California, to teach his students how the wealthy legally avoid income tax. The steps are exactly what they sound like. Buy an asset that will grow in value. Borrow against it when you need cash instead of selling it. Die holding it, so your heirs receive it with the gain wiped away. None of this is a loophole in the sense of a mistake. It is how the system is written." },
        { h: "Why borrowing beats selling", p: "When you sell an asset for more than you paid, the profit is a capital gain and it is taxed. For 2025, long-term capital gains are taxed at zero, 15, or 20 percent depending on your income, and the depreciation you took on a rental is recaptured at up to 25 percent. When you borrow against that same asset, you receive cash and owe nothing to the IRS, because a loan is not income. You have to pay it back, with interest, but the interest rate on a loan secured by real estate is almost always lower than the tax you would have paid by selling. This is the engine inside a cash-out refinance, which is the R in BRRRR. You pull your money back out of a house without selling the house." },
        { h: "What happens at death", p: "Under Internal Revenue Code section 1014, property you inherit gets a new tax basis equal to its fair market value on the date of death. This is called a stepped-up basis. If your parent bought a house for $35,000 and it is worth $400,000 when they die, your basis is $400,000. If you sell it the next day for $400,000, your taxable gain is zero. The entire lifetime of appreciation is never taxed as income to anyone. The loans against the property are paid off from the estate or carried by the heirs, and the family keeps the asset.\n\nThe estate tax, as of 2026. The federal estate tax only reaches very large estates. Legislation signed in July 2025, often called the One Big Beautiful Bill Act, set the federal estate and gift tax exemption at 15 million dollars per person, 30 million for a married couple, starting January 1, 2026, indexed for inflation and with no scheduled expiration. For almost everyone reading this, the step-up in basis is the rule that matters, not the estate tax. Confirm your plan with a CPA and an estate attorney; rules change and states differ." },
        { example: "You own a rental worth $300,000 that you bought for $150,000, with a $100,000 loan. Sell it: you owe capital gains tax on $150,000 of profit plus depreciation recapture, and you walk away with maybe $160,000 after tax and costs. Borrow instead: refinance to a $225,000 loan, receive $125,000 tax-free, keep the house, keep the rent, and the tenant pays the new loan. Hold until death and the gain is erased for your heirs." },
        { carry: "Buy, Borrow, Die: a loan is not income, so refinancing is tax-free. IRC §1014 steps up basis at death, erasing lifetime gains." },
        { trap: "Borrowing against an asset without the cash flow to carry the new payment. Buy, Borrow, Die only works if the asset pays its own debt. Pulling cash out of a rental that then runs negative every month is how people lose the asset before they ever get to the third step." },
        { sources: [
          { t: "USC Gould School of Law, 'Buy, borrow, die' gains new life (origin of the phrase)", u: "https://gould.usc.edu/news/buy-borrow-die-gains-new-life/" },
          { t: "26 U.S. Code §1014, Basis of property acquired from a decedent", u: "https://www.law.cornell.edu/uscode/text/26/1014" },
          { t: "IRS Topic 409, Capital Gains and Losses (rates and §1250 recapture)", u: "https://www.irs.gov/taxtopics/tc409" },
          { t: "Morgan Lewis, Estate Tax Alert: New $15 Million Federal Exemption (2025)", u: "https://www.morganlewis.com/pubs/2025/08/estate-tax-alert-new-15-million-federal-exemption-becomes-law" }
        ] }
      ]
    },
    {
      id: "m01-05",
      title: "Inflation and Fixed-Rate Debt",
      minutes: 9,
      blocks: [
        { h: "Inflation is a policy, not an accident", p: "Inflation is the slow rise in prices, which is the same thing as the slow fall in what a dollar buys. The Federal Reserve openly targets 2 percent inflation per year over the long run as its definition of price stability. In practice it has run higher. According to Bureau of Labor Statistics data, 100 dollars in 1996 buys what about 213 dollars buys in 2026, an average of roughly 2.5 percent a year. The dollar you earn today is designed to be worth less in ten years. Savers lose to this. Borrowers with the right kind of debt win from it." },
        { h: "Why a thirty-year fixed mortgage is a bet in your favor", p: "A thirty-year fixed-rate mortgage locks your payment in today's dollars for three decades. The payment never rises. Rents, on the other hand, tend to rise with inflation because landlords' costs rise and tenants' wages rise. So every year, the gap between the rent you collect and the fixed payment you owe tends to widen. You are repaying the bank with dollars that are worth less than the ones you borrowed, and the tenant is handing you those dollars. There is no other consumer loan in America where an ordinary person can borrow hundreds of thousands of dollars for thirty years at a fixed rate secured by something that produces income. It is the single most favorable financial instrument available to you." },
        { formula: "Real cost of debt ≈ Interest rate − Inflation rate" },
        { example: "You lock a $1,023 payment in 2026. If rents and prices rise 3 percent a year, the $1,900 rent becomes about $2,550 in ten years and $3,430 in twenty. The payment is still $1,023. Cash flow went from $40 a month to several hundred, and you changed nothing." },
        { carry: "Fixed payment, rising rent. Inflation shrinks your debt while the tenant pays it. Thirty-year fixed debt on income property is the most favorable loan an ordinary person can get." },
        { trap: "Adjustable-rate or short-term balloon debt on a long-term hold. If your rate can reset, inflation is no longer your friend, because the bank gets to reprice. Use short-term money to buy and fix, then refinance into long-term fixed debt as fast as the deal allows." },
        { sources: [
          { t: "Federal Reserve FAQ: Why does the Federal Reserve aim for inflation of 2 percent?", u: "https://www.federalreserve.gov/faqs/economy_14400.htm" },
          { t: "BLS CPI data via in2013dollars: value of 1996 dollars in 2026", u: "https://www.in2013dollars.com/us/inflation/1996" }
        ] }
      ]
    },
    {
      id: "m01-06",
      title: "Compounding and the Velocity of Money",
      minutes: 10,
      blocks: [
        { h: "The Rule of 72", p: "Compounding means your returns earn returns. The fastest way to feel it is the Rule of 72: divide 72 by your annual rate of return and you get roughly the number of years it takes your money to double. At 3 percent, money doubles every 24 years. At 8 percent, every 9 years. At 12 percent, every 6 years. The rule is an approximation that works well for rates between about 6 and 10 percent, but it is close enough for planning at any rate you will realistically see." },
        { formula: "Years to double ≈ 72 ÷ annual return (%)" },
        { h: "Velocity: the whole point of BRRRR", p: "Compounding describes what happens when money sits and grows. Velocity describes how many times you can use the same dollar. If you put $50,000 down on a rental and leave it there, that money works once. If you buy a distressed house for $120,000, put $40,000 into it, and it appraises at $220,000, a lender will often refinance you at 75 percent of the new value, which is $165,000. That pays off your purchase and rehab and returns almost all of your original cash. Now the same $50,000 can buy the next house while the first one keeps paying you. That is the Repeat in Buy, Rehab, Rent, Refinance, Repeat. The strategy is not about getting a good deal. It is about getting your money back so you can get a good deal again." },
        { example: "Doubling in practice. $25,000 compounding at 15 percent a year becomes about $50,000 in five years and about $101,000 in ten. Now imagine recycling that $25,000 through a new deal every twelve months instead, where each deal leaves you with a house carrying $30,000 of equity and modest cash flow. After ten years you have ten houses and roughly $300,000 of equity from the same $25,000, before any appreciation or loan paydown. Velocity beats sitting still." },
        { carry: "Rule of 72: years to double = 72 ÷ rate. BRRRR is velocity: get the same dollar back and use it again." },
        { trap: "Chasing velocity so hard that you leave no cash in the deal and no reserves in the bank. Pulling 100 percent of your money out of a thin deal is a loan against hope. Leave reserves. Speed only matters if you survive." },
        { sources: [
          { t: "Rule of 72 (Wikipedia, derivation and accuracy)", u: "https://en.wikipedia.org/wiki/Rule_of_72" },
          { t: "Stanford EE204: The Rule of 72", u: "https://web.stanford.edu/class/ee204/TheRuleof72.html" }
        ] }
      ]
    },
    {
      id: "m01-07",
      title: "The Cash Flow Quadrant",
      minutes: 8,
      blocks: [
        { h: "Four ways people earn", p: "In his follow-up book, Cashflow Quadrant, Kiyosaki sorts every earner into four boxes by how the money arrives. E is Employee: you have a job and trade hours for a paycheck. S is Self-employed: you own a job, like a plumber or an agent, and you still trade hours, just at a better rate and with more risk. B is Business owner: you own a system that other people run, so the business earns whether you show up or not. I is Investor: your money earns the money. The left side, E and S, is where your income is capped by your hours. The right side, B and I, is where income is capped by nothing but the size of the system or the portfolio." },
        { h: "Why a paycheck caps you", p: "There are only so many hours in a year, and every one you sell has a price. Even a high earner on the left side has a ceiling, and that ceiling comes with the heaviest taxes in the code, because wage income is taxed before you ever see it. The right side gets paid from assets, taxed later and less, and does not stop when you stop. Most of the wealthy people in the history lesson spent some time on the left, usually early, to earn the seed capital, and then moved to the right as fast as they could. Your job is not the problem. Your job is the funding source. The mistake is staying there." },
        { h: "What this means for two partners starting from zero", p: "You will start on the left side. That is fine. Treat the paycheck as the engine that buys your first asset, and treat every dollar you keep from it as a dollar that moves you toward the I quadrant. The first house makes you an investor in a small way. The tenth makes you one in a real way. Somewhere along the path, managing the portfolio starts to look like a B: systems, contractors, property managers, and a partner who runs it with you." },
        { carry: "E and S trade hours for money and are capped. B and I own systems and assets, and are not. Use the left side to fund the right side." },
        { trap: "Quitting the job before the assets replace the income. The left side is your lender's favorite thing about you: a W-2 is what makes conventional mortgages easy. Keep it until the right side can carry you." },
        { sources: [ { t: "Rich Dad's Cashflow Quadrant (Goodreads book record)", u: "https://www.goodreads.com/book/show/81923" } ] }
      ]
    },
    {
      id: "m01-08",
      title: "The Millionaire Math",
      minutes: 10,
      blocks: [
        { h: "What a million actually looks like", p: "A million dollars of net worth sounds abstract until you count it in doors. Ten houses with $100,000 of equity each is a million. Twenty houses with $50,000 each is a million. Four small apartment buildings can be a million. For context, the Federal Reserve's 2022 Survey of Consumer Finances put the median American family's net worth at $192,900 and the average at about $1,063,700, and that average is pulled up by families who own businesses and real estate. A million is unusual. It is not magic. It is a countable number of ordinary houses." },
        { h: "The cash flow version", p: "Net worth is one way to measure. Income is the one that changes your life. If your goal is to replace a $6,000-a-month salary, and a stabilized rental nets you $300 a month after everything, you need twenty doors. If you can get $500 a door, you need twelve. These are rough, and your market sets the real numbers, but the point is that financial independence through rentals is a door count, and a door count is a plan you can write on one page." },
        { h: "Honest timelines", p: "Here is where most books lie to you. Two partners working day jobs and investing part-time can realistically add somewhere around two to six doors a year in the early years, depending on capital, deal flow, and how fast refinances return your money. That is a typical range from experience, not a statistic, and plenty of people do less. At three doors a year, ten houses takes a bit over three years. At $30,000 to $50,000 of equity created per BRRRR plus loan paydown and modest appreciation, the equity side of a million is plausible in six to ten years of steady work. The cash flow side takes longer because early deals are thin at today's rates. Nobody does this in eighteen months without a lot of money or a lot of luck, and you should be suspicious of anyone who says otherwise." },
        { example: "Doors needed = target monthly income ÷ net cash flow per door. Target $6,000 a month. Net $400 a door. Doors needed = 6,000 ÷ 400 = 15. At three doors a year, that is five years of acquisition, then several more years of rent growth and loan paydown pushing each door's cash flow higher." },
        { carry: "A million is ten houses with $100K equity each. Part-time, two to six doors a year early on is realistic. Plan in doors, not dreams." },
        { trap: "Measuring progress by net worth alone. Equity you cannot touch does not pay bills. Track both numbers every month: equity and net monthly cash flow. One without the other is half a plan." },
        { sources: [ { t: "Federal Reserve, Changes in U.S. Family Finances from 2019 to 2022 (SCF), median and mean net worth", u: "https://www.federalreserve.gov/publications/files/scf23.pdf" } ] }
      ]
    },
    {
      id: "m01-09",
      title: "Leverage Cuts Both Ways",
      minutes: 12,
      blocks: [
        { h: "Why 2008 happened to landlords", p: "Everything in this module runs on borrowed money, and borrowed money magnifies losses exactly as much as gains. From a peak around 2006, national home prices fell roughly 30 percent by 2009. In 2010 alone about 1.2 million homes were repossessed by lenders, the highest annual total on record. Many of those were not owner-occupants. They were small investors who bought at full price with little down, counted on appreciation, had no reserves, and carried adjustable or short-term loans that reset when values fell and refinancing disappeared. When rent could not cover the new payment, they could not sell, could not refinance, and lost the house." },
        { h: "The arithmetic of a 30 percent drop", p: "Buy a $200,000 house with 20 percent down. You have $40,000 of equity and a $160,000 loan. Prices fall 30 percent. The house is worth $140,000 and you owe $160,000. Your $40,000 became negative $20,000. You did not lose 30 percent. You lost 150 percent of your money. Leverage did that. The only thing that saves you in that moment is the rent. If the tenant keeps paying and the payment is fixed, you ride it out and prices recover, as they did by 2012. If you have no cash flow and no reserves, the drop is fatal." },
        { h: "The rules that let the rich survive what killed everyone else", p: "First, cash flow from day one. A property that pays for itself does not care what it would appraise for. Second, long-term fixed-rate debt. Nothing that can reset or come due in a downturn. Third, reserves. Lenders typically want to see six months of PITIA per rental for conventional loans, and that is the floor, not the ceiling. Fourth, moderate leverage. Pulling 75 percent of value out on a refinance is normal; pulling 100 percent out with a second loan is how you get buried. Fifth, buy below market. The equity you create at purchase is the cushion that absorbs a price drop. Every one of these is a brake. You will be tempted to remove them when things are going well. That is exactly when you need them." },
        { h: "What over-leverage looks like before it kills you", p: "It looks like winning. It looks like six houses in a year with none of your own money in any of them. It looks like cash-out refinances funding a lifestyle instead of the next deal. It looks like a spreadsheet where every number is the best case. Sam Zell made his fortune buying from people who had done exactly that. Decide now which side of that trade you want to be on." },
        { carry: "Leverage multiplies losses as much as gains. Survive with cash flow, fixed-rate debt, six-plus months of reserves, moderate LTV, and equity created at purchase." },
        { trap: "Removing the brakes during a good market. Reserves feel like idle cash when prices are rising. They are the only reason you will still own the houses when prices stop rising." },
        { sources: [
          { t: "Lincoln Institute of Land Policy, Housing, Land, and the Economic Crisis (price decline roughly 30% by 2009)", u: "https://www.lincolninst.edu/publications/articles/housing-land-economic-crisis/" },
          { t: "2010 United States foreclosure crisis (Wikipedia; 1.2 million repossessions in 2010)", u: "https://en.wikipedia.org/wiki/2010_United_States_foreclosure_crisis" },
          { t: "Fannie Mae Selling Guide B3-4.1-01, Minimum Reserve Requirements (six months PITIA for investment property)", u: "https://selling-guide.fanniemae.com/sel/b3-4.1-01/minimum-reserve-requirements" }
        ] }
      ]
    }
  ],
  cards: [
    { id: "m01-c01", type: "term", q: "What is an asset, in the Kiyosaki frame?", a: "Something that puts money in your pocket every month. A rental that nets $300 after all costs is an asset; the car you drive to work is not." },
    { id: "m01-c02", type: "term", q: "What is a liability, in the Kiyosaki frame?", a: "Something that takes money out of your pocket every month. Your primary residence is a liability in this frame because it costs you and pays you nothing until sold." },
    { id: "m01-c03", type: "term", q: "What is a personal balance sheet?", a: "A snapshot on one day of what you own (assets) and what you owe (liabilities). The difference is your net worth." },
    { id: "m01-c04", type: "term", q: "What is a personal income statement?", a: "A record of money in and money out over a period, usually a month. Income minus expenses equals cash flow." },
    { id: "m01-c05", type: "formula", q: "Net worth formula?", a: "Net worth = Assets − Liabilities. Example: $18,000 of stuff and savings, $18,000 of loans, net worth $0." },
    { id: "m01-c06", type: "scenario", q: "You get a $500-a-month raise. Your partner wants to upgrade both of your cars. What do you do?", a: "Say no. A car payment is a liability that grows your expenses with your income. Route the raise into the deal fund so it buys something that pays you back." },
    { id: "m01-c07", type: "trap", q: "Why does counting your house as your biggest asset hold you back?", a: "It makes you feel wealthy while nothing you own produces income. You stop building the asset column because you think you already have one." },
    { id: "m01-c08", type: "term", q: "What are the four ways a rental pays you?", a: "Cash flow, appreciation, loan paydown by the tenant, and tax benefits (mainly depreciation and deductible expenses)." },
    { id: "m01-c09", type: "term", q: "What is PITIA?", a: "Principal, Interest, Taxes, Insurance, and Association dues: the full monthly cost of owning a financed property. Lenders measure rent against it." },
    { id: "m01-c10", type: "formula", q: "How do you calculate monthly cash flow on a rental?", a: "Rent − PITIA − reserves for vacancy, repairs/replacements, and management. Example: 1,900 − 1,423 − 437 = $40." },
    { id: "m01-c11", type: "number", q: "Over how many years does the IRS depreciate residential rental buildings?", a: "27.5 years under MACRS. Land is not depreciable. A $160,000 building gives about $5,818 of deduction per year." },
    { id: "m01-c12", type: "formula", q: "Annual depreciation on a rental?", a: "Building value (purchase price minus land) ÷ 27.5. Example: $200,000 house, $40,000 land → $160,000 ÷ 27.5 = $5,818 per year." },
    { id: "m01-c13", type: "number", q: "On a $150,000 loan at 7.25% for 30 years, roughly how much principal does the tenant pay down in year one?", a: "About $1,450, out of a $1,023 monthly payment. It grows every year as less of each payment goes to interest." },
    { id: "m01-c14", type: "number", q: "What was the Freddie Mac 30-year fixed average as of October 1, 2026?", a: "7.28 percent, up from 7.03 the week before. At these rates full-price retail purchases rarely cash flow, which is why BRRRR buys below market." },
    { id: "m01-c15", type: "trap", q: "What is wrong with buying a negative-cash-flow property because it will appreciate?", a: "If it does not appreciate on your schedule you feed it monthly until you are forced to sell at the worst time. Cash flow is the survival requirement; appreciation is the bonus." },
    { id: "m01-c16", type: "scenario", q: "A deal shows $40 a month cash flow, 3% appreciation, $1,450 of paydown, and $5,800 of depreciation on $50,000 down. Is it a good return?", a: "Total wealth gain is about $7,900, close to 16 percent on your cash, and the depreciation shelters the cash flow from tax. Thin cash flow but a real return; the question is whether $40 covers surprises." },
    { id: "m01-c17", type: "term", q: "What is depreciation recapture?", a: "When you sell, the IRS taxes the depreciation you took, at up to 25 percent for real property under section 1250. One more reason the wealthy refinance rather than sell." },
    { id: "m01-c18", type: "term", q: "What was the original form of wealth for centuries?", a: "Land and the rent from it. The aristocracy owned the ground, everyone else paid to use it, and ownership passed from parent to child." },
    { id: "m01-c19", type: "number", q: "What was the Return of Owners of Land?", a: "An 1873 British parliamentary survey ordered to settle how concentrated land ownership was. It confirmed the basic structure: a small class owned the land and collected the rent." },
    { id: "m01-c20", type: "term", q: "What was John Jacob Astor's Manhattan strategy?", a: "Buy farmland north of the settled city ahead of growth, buy more during panics like 1837, lease to developers so tenants paid taxes and upkeep, and never sell. Richest man in America at his death in 1848." },
    { id: "m01-c21", type: "trap", q: "Why should you not quote Astor saying he would buy every foot of Manhattan?", a: "The remark is widely attributed to him but not reliably sourced. Teach the documented strategy, not the legend. Never put quote marks around words you cannot verify." },
    { id: "m01-c22", type: "term", q: "What is the Rothschild lesson for a BRRRR investor?", a: "Capital lent against collateral earns interest while the lender keeps the asset. A bank lending against your house is doing what the Rothschilds did for governments; you want to be the one who owns the collateral." },
    { id: "m01-c23", type: "number", q: "When did the Rockefeller family office start, and what was Room 5600?", a: "Established 1882. From 1933 it occupied a full floor of 30 Rockefeller Plaza. Its job was to keep the family's assets working and intact across generations." },
    { id: "m01-c24", type: "term", q: "How did Trammell Crow build the largest landlord position in America?", a: "Started with one Dallas warehouse in 1948 leased to a battery company, built for tenants, and kept the buildings. Forbes called him the largest landlord in the U.S. in 1971." },
    { id: "m01-c25", type: "term", q: "Why was Sam Zell called the Grave Dancer?", a: "He bought distressed real estate in downturns when others were selling. In 2007 he sold Equity Office to Blackstone for $39 billion near the market top." },
    { id: "m01-c26", type: "term", q: "What is the common thread across every wealthy dynasty?", a: "Own income-producing assets, borrow against them instead of selling, hold through panics and buy more, and pass the assets to the next generation." },
    { id: "m01-c27", type: "term", q: "What is Buy, Borrow, Die?", a: "A phrase coined by USC tax professor Edward McCaffery in the mid-1990s. Buy appreciating assets, borrow against them for cash instead of selling, and die holding them so heirs get a stepped-up basis." },
    { id: "m01-c28", type: "term", q: "Why is a loan not taxed?", a: "Borrowed money is not income because you have to pay it back. A cash-out refinance puts money in your hand with no tax due, unlike a sale." },
    { id: "m01-c29", type: "term", q: "What is stepped-up basis?", a: "Under IRC §1014, inherited property gets a new basis equal to fair market value at the date of death. A $35,000 house worth $400,000 at death has a $400,000 basis; sell for $400,000 and the gain is zero." },
    { id: "m01-c30", type: "number", q: "What are the 2025 long-term capital gains rates?", a: "0, 15, or 20 percent depending on taxable income, plus up to 25 percent on unrecaptured section 1250 gain from depreciation. Confirm current-year thresholds with a CPA." },
    { id: "m01-c31", type: "number", q: "What is the federal estate tax exemption starting in 2026?", a: "$15 million per person, $30 million per married couple, indexed for inflation, with no sunset, under the July 2025 tax law. Most readers will never be subject to it; the step-up is what matters." },
    { id: "m01-c32", type: "scenario", q: "Your rental is worth $300,000, you paid $150,000, owe $100,000, and need $100,000 for the next deal. Sell or refinance?", a: "Refinance. A 75% loan is $225,000, netting about $125,000 tax-free while you keep the house and the rent. Selling triggers capital gains plus recapture and ends the income." },
    { id: "m01-c33", type: "trap", q: "What is the hidden failure mode of Buy, Borrow, Die?", a: "Borrowing against an asset whose cash flow cannot carry the new payment. The strategy only works when the asset pays its own debt. Negative cash flow after a refinance loses the asset." },
    { id: "m01-c34", type: "number", q: "What inflation rate does the Federal Reserve target?", a: "2 percent per year over the long run, measured by the PCE price index. In practice it has averaged about 2.5 percent over the last thirty years." },
    { id: "m01-c35", type: "number", q: "What is $100 from 1996 worth in 2026 dollars?", a: "About $213, per BLS CPI data. Prices roughly doubled in thirty years, so a fixed debt from 1996 is being repaid with half-value dollars." },
    { id: "m01-c36", type: "term", q: "Why is a 30-year fixed mortgage on a rental a bet in your favor?", a: "The payment never changes while rent and prices rise with inflation. You repay the bank in cheaper dollars, and the tenant hands you those dollars." },
    { id: "m01-c37", type: "formula", q: "Real cost of debt?", a: "Interest rate − inflation rate. A 7% mortgage with 3% inflation costs about 4% in real terms, and rising rent offsets more of that each year." },
    { id: "m01-c38", type: "scenario", q: "Rent is $1,900 and payment is $1,023 today. Rents rise 3% a year. What does year ten look like?", a: "Rent about $2,550, payment still $1,023. Cash flow grew from $40 to several hundred a month without you changing anything." },
    { id: "m01-c39", type: "trap", q: "What kind of debt turns inflation against you?", a: "Adjustable-rate or short-term balloon debt on a long-term hold. If the rate can reset, the bank reprices and you lose the inflation edge. Refinance into long-term fixed as soon as the deal allows." },
    { id: "m01-c40", type: "formula", q: "Rule of 72?", a: "Years to double ≈ 72 ÷ annual return percent. At 8 percent, money doubles in about 9 years; at 12 percent, about 6." },
    { id: "m01-c41", type: "number", q: "How long does money take to double at 3 percent?", a: "About 24 years (72 ÷ 3). That is roughly the pace of inflation, which is why a savings account barely keeps up." },
    { id: "m01-c42", type: "term", q: "What is velocity of money in BRRRR?", a: "How many times you can use the same dollar. Refinancing returns your capital so one down payment buys house after house, while each house keeps paying you." },
    { id: "m01-c43", type: "scenario", q: "You buy for $120,000, put in $40,000, and it appraises at $220,000. The lender refinances at 75% of value. What happens to your cash?", a: "New loan is $165,000, which repays the $160,000 of purchase and rehab and returns nearly all your cash. You keep the house with about $55,000 of equity and reuse the capital." },
    { id: "m01-c44", type: "trap", q: "What goes wrong when you chase velocity too hard?", a: "You pull 100 percent of your cash out of thin deals and keep no reserves. One vacancy or roof wipes you out. Speed only matters if you survive." },
    { id: "m01-c45", type: "term", q: "What are the four Cashflow Quadrant boxes?", a: "E Employee, S Self-employed, B Business owner, I Investor. E and S trade hours for money; B and I own systems and assets." },
    { id: "m01-c46", type: "term", q: "Why does a paycheck cap your wealth?", a: "Hours are finite and wage income is taxed first and heaviest. Asset income has no hour limit, is taxed later and less, and continues when you stop working." },
    { id: "m01-c47", type: "scenario", q: "Your partner wants to quit the job to go full-time in real estate after two houses. Your move?", a: "Keep the job. Rental income from two houses will not replace a salary, and a W-2 is what makes conventional and many DSCR-alternative loans easy. Quit when assets carry you." },
    { id: "m01-c48", type: "number", q: "How many houses with $100,000 of equity each equals a million-dollar net worth?", a: "Ten. Or twenty with $50,000 each. A million is a countable number of ordinary houses." },
    { id: "m01-c49", type: "number", q: "What were median and mean U.S. family net worth in the Fed's 2022 survey?", a: "Median $192,900, mean about $1,063,700. The gap exists because the average is pulled up by families who own businesses and real estate." },
    { id: "m01-c50", type: "formula", q: "How many doors do you need to replace an income?", a: "Target monthly income ÷ net cash flow per door. $6,000 ÷ $400 = 15 doors." },
    { id: "m01-c51", type: "number", q: "How many doors a year can part-time partners realistically add early on?", a: "Typically around two to six, depending on capital, deal flow, and refinance speed. This is a range from experience, not a statistic, and many do less." },
    { id: "m01-c52", type: "trap", q: "Why is tracking only net worth half a plan?", a: "Equity you cannot touch does not pay bills. Track equity and net monthly cash flow every month; one without the other hides your real position." },
    { id: "m01-c53", type: "number", q: "How far did national home prices fall from the 2006 peak to 2009?", a: "Roughly 30 percent. Prices did not post a yearly gain again until 2012." },
    { id: "m01-c54", type: "number", q: "How many homes were repossessed in 2010?", a: "About 1.2 million, the highest annual total on record. Many belonged to small investors with no cash flow, no reserves, and resetting loans." },
    { id: "m01-c55", type: "scenario", q: "You buy a $200,000 house with 20% down and prices fall 30%. What is your equity?", a: "Negative $20,000. The house is worth $140,000 and you owe $160,000. Your $40,000 became −$20,000, a 150 percent loss. Only rent and fixed debt let you ride it out." },
    { id: "m01-c56", type: "term", q: "What are the five brakes that let investors survive a crash?", a: "Cash flow from day one, long-term fixed-rate debt, reserves of six-plus months PITIA per property, moderate leverage, and equity created by buying below market." },
    { id: "m01-c57", type: "number", q: "How many months of reserves does Fannie Mae require for an investment property?", a: "Six months of PITIA for the subject property, plus a percentage of unpaid balances on other financed rentals. Treat six as the floor, not the goal." },
    { id: "m01-c58", type: "trap", q: "What does over-leverage look like before it hurts?", a: "It looks like winning: six houses with none of your money in, refinances funding lifestyle, spreadsheets where every number is best-case. Zell made his fortune buying from those people." },
    { id: "m01-c59", type: "scenario", q: "Prices have risen three years straight and your reserves feel like idle cash. Your partner wants to deploy them into one more deal. What do you do?", a: "Keep the reserves. Good markets are when people remove the brakes, and the reserves are the only reason you will still own the houses when the market turns." },
    { id: "m01-c60", type: "state", q: "Does owning your own home get a property tax break that a rental does not?", a: "FL: Homestead exemption cuts taxable value by up to $50,000 and Save Our Homes caps assessment growth at 3% or CPI, whichever is lower; rentals get neither and the cap resets on sale. | OH: The owner-occupancy credit reduces tax on your principal residence only; rental homes and apartments are explicitly excluded." },
    { id: "m01-c61", type: "trap", q: "Why is a property tax bill on a rental often higher than the seller's bill?", a: "The seller may have had homestead or owner-occupancy breaks that vanish when you buy as an investor, and in Florida the assessment cap resets to market value on sale. Underwrite with the un-exempted tax, not the seller's bill." }
  ],
  quiz: [
    { id: "m01-q01", q: "In the Kiyosaki frame, which of these is an asset?", opts: ["A rental that nets $250 a month after all costs", "Your paid-off primary residence", "A new truck with no loan", "A boat you could sell for $30,000"], correct: 0, explain: "Only the rental puts money in your pocket every month. Resale value does not make something an asset in this frame." },
    { id: "m01-q02", q: "Your assets total $38,000 and your liabilities total $41,000. Your net worth is:", opts: ["$79,000", "$3,000", "−$3,000", "$41,000"], correct: 2, explain: "Net worth = assets − liabilities = 38,000 − 41,000 = −$3,000." },
    { id: "m01-q03", q: "Which of the four ways a rental pays you is usually smallest on day one at late-2026 interest rates?", opts: ["Appreciation", "Loan paydown", "Cash flow", "Depreciation deduction"], correct: 2, explain: "At a 7.28% average mortgage rate, full-price purchases cash flow thinly or not at all. That is why BRRRR buys below market." },
    { id: "m01-q04", q: "A $200,000 house has a $40,000 land value. Annual depreciation is about:", opts: ["$7,273", "$4,000", "$8,000", "$5,818"], correct: 3, explain: "Only the building depreciates: $160,000 ÷ 27.5 = $5,818." },
    { id: "m01-q05", q: "On the $200,000 example (rent $1,900, PITIA $1,423, reserves $437), monthly cash flow is:", opts: ["$477", "$40", "$0", "$140"], correct: 1, explain: "1,900 − 1,423 − 437 = $40. Thin, which is the honest picture at today's rates for a retail-priced house." },
    { id: "m01-q06", q: "Which best describes John Jacob Astor's documented Manhattan strategy?", opts: ["Build luxury hotels and sell them quickly", "Buy land ahead of the city's growth, lease it, and never sell", "Flip farmland to developers at auction", "Lend to developers and foreclose"], correct: 1, explain: "Astor bought north of the settled city, bought more in the Panic of 1837, leased to developers, and held. The famous deathbed quote is unverified; the strategy is documented." },
    { id: "m01-q07", q: "What business did the Rothschild London bank famously finance in 1875?", opts: ["The Erie Canal", "The British purchase of Suez Canal shares", "The first transatlantic cable", "The Bank of England's founding"], correct: 1, explain: "Lionel de Rothschild's bank financed Britain's 1875 acquisition of a controlling interest in the Suez Canal." },
    { id: "m01-q08", q: "Who coined the phrase Buy, Borrow, Die?", opts: ["Edward McCaffery", "Sam Zell", "Robert Kiyosaki", "Trammell Crow"], correct: 0, explain: "McCaffery, a USC tax law professor, coined it in the mid-1990s to teach how the wealthy avoid income tax legally." },
    { id: "m01-q09", q: "Why is a cash-out refinance not taxed?", opts: ["Real estate is exempt from income tax", "Loan proceeds are not income because you must repay them", "The IRS only taxes sales over $500,000", "Refinances are taxed, but at the 0% bracket"], correct: 1, explain: "Borrowed money is not income. That is the Borrow step and the engine of the BRRRR refinance." },
    { id: "m01-q10", q: "Under IRC §1014, heirs who inherit a $400,000 house bought for $35,000 and sell it immediately for $400,000 owe capital gains tax on:", opts: ["$365,000", "$400,000", "$35,000", "$0"], correct: 3, explain: "Stepped-up basis resets the basis to $400,000 at death. The lifetime gain is never taxed as income." },
    { id: "m01-q11", q: "The federal estate tax exemption per person starting January 1, 2026 is:", opts: ["$5 million", "$13.99 million", "$15 million", "$30 million"], correct: 2, explain: "The July 2025 law set it at $15 million per person ($30 million per couple), indexed, with no sunset." },
    { id: "m01-q12", q: "Per BLS CPI data, $100 in 1996 is worth about how much in 2026?", opts: ["$213", "$150", "$300", "$125"], correct: 0, explain: "About $213, roughly 2.5% a year. A fixed 1996 debt is being repaid with half-value dollars." },
    { id: "m01-q13", q: "Why does inflation favor a landlord with a 30-year fixed mortgage?", opts: ["Property taxes are frozen for 30 years", "Insurance costs fall with inflation", "The lender forgives part of the loan", "The payment is fixed while rent tends to rise"], correct: 3, explain: "The payment never changes; rent and prices rise. The gap widens every year and the tenant pays with inflating dollars." },
    { id: "m01-q14", q: "Using the Rule of 72, money earning 8 percent doubles in about:", opts: ["6 years", "12 years", "24 years", "9 years"], correct: 3, explain: "72 ÷ 8 = 9 years." },
    { id: "m01-q15", q: "You buy for $120,000, rehab for $40,000, and it appraises at $220,000. A 75% refinance returns a loan of:", opts: ["$120,000", "$150,000", "$165,000", "$220,000"], correct: 2, explain: "220,000 × 0.75 = $165,000, which repays the $160,000 you spent and returns nearly all your cash to use again." },
    { id: "m01-q16", q: "In the Cashflow Quadrant, a plumber who owns his own one-man shop is in which box?", opts: ["E", "S", "B", "I"], correct: 1, explain: "Self-employed. He owns a job, not a system, and still trades hours for money." },
    { id: "m01-q17", q: "You want $6,000 a month and each door nets $400. How many doors?", opts: ["15", "10", "12", "20"], correct: 0, explain: "6,000 ÷ 400 = 15 doors." },
    { id: "m01-q18", q: "A realistic early pace for two part-time partners is roughly:", opts: ["One door every five years", "Two to six doors a year", "Twenty doors a year", "Fifty doors in eighteen months"], correct: 1, explain: "Two to six a year is a typical range from experience, not a statistic. Anyone promising much faster with no money is selling something." },
    { id: "m01-q19", q: "You buy a $200,000 house with 20% down and prices fall 30%. Your equity is now:", opts: ["$28,000", "$0", "−$60,000", "−$20,000"], correct: 3, explain: "Worth $140,000, owe $160,000. The $40,000 became −$20,000, a 150% loss, which is what leverage does on the way down." },
    { id: "m01-q20", q: "Which is NOT one of the brakes that let investors survive a downturn?", opts: ["Pulling 100% of your cash out with a second loan", "Long-term fixed-rate debt", "Six-plus months of reserves per property", "Buying below market to create equity"], correct: 0, explain: "Pulling 100% out removes your cushion. Moderate leverage, around 75% of value, is the brake." }
  ],
  drills: [
    "Tonight, write your personal balance sheet on one page: every asset and its value on the left, every debt on the right, net worth at the bottom. Circle anything on the left that actually pays you monthly. Do the same for your partner and compare.",
    "Write a one-month personal income statement from your last bank statement: income in, expenses out, cash flow at the bottom. That number is your current deal-fund speed.",
    "Calculate your doubling time at 3, 8, 12, and 15 percent with the Rule of 72. Then write what each one means in years for $25,000.",
    "Rebuild the $200,000 example with a real listing in your target area: price, 25% down, today's rate, taxes, insurance, and a conservative rent. Compute all four returns. Does it cash flow at retail price?",
    "Pick one dynasty from lesson three, read one source on it for twenty minutes, and write three sentences on how they used the four moves: own, borrow, hold, pass on.",
    "Write your door-count plan: target monthly income, realistic net per door in your market, doors needed, doors per year, years to get there. Put the date on it.",
    "List the five brakes from lesson nine and, next to each, write the specific rule you and your partner will hold yourselves to, with a number (months of reserves, maximum refinance LTV, minimum day-one cash flow)."
  ]
});
