BIBLE.register({
  id: "m02",
  part: 1,
  title: "Money Foundation",
  icon: "🧱",
  summary: "Before a lender gives you a dollar they will read your credit, your debt, your reserves, and your paperwork. This module builds all four so you look like a borrower who gets approved.",
  minutes: 85,
  lessons: [
    {
      id: "m02-01",
      title: "How a Credit Score Is Built",
      minutes: 10,
      blocks: [
        { h: "What a score actually is", p: "A credit score is a number, usually between 300 and 850, that predicts how likely you are to pay a debt back on time. The score most mortgage lenders use is a FICO score, and FICO publishes exactly what goes into it. Five factors, with five weights. Learn them and you stop guessing about what moves your number." },
        { h: "The five factors and their weights", p: "Payment history is 35 percent of your score: whether you have paid past accounts on time. Amounts owed is 30 percent: mostly how much of your available revolving credit you are using. Length of credit history is 15 percent: how long your accounts have been open and how old your oldest one is. New credit is 10 percent: how many accounts you have opened recently and how many hard inquiries you have. Credit mix is 10 percent: whether you have handled different kinds of credit, like cards and installment loans. Payment history and amounts owed together are 65 percent. If you fix nothing else, fix those two." },
        { formula: "FICO = Payment history 35% + Amounts owed 30% + Length of history 15% + New credit 10% + Credit mix 10%" },
        { example: "Two borrowers each have a 680. One has a single 30-day late payment from two years ago and otherwise perfect history. The other has never been late but carries cards at 85 percent of their limits. The first one can do almost nothing but wait. The second one can pay the cards down to under 10 percent and likely see a meaningful jump within one or two statement cycles." },
        { carry: "35 payment history, 30 amounts owed, 15 length, 10 new credit, 10 mix. Never be late; keep utilization low." },
        { trap: "Closing old cards to simplify. You shorten your average account age and you shrink your total available credit, which raises utilization on everything else. Leave old no-fee cards open and use them for a small purchase a few times a year." },
        { sources: [ { t: "myFICO, What's in my FICO Scores", u: "https://www.myfico.com/credit-education/whats-in-your-credit-score" } ] }
      ]
    },
    {
      id: "m02-02",
      title: "Utilization and the Statement Date",
      minutes: 8,
      blocks: [
        { h: "The fastest lever you have", p: "Utilization is your revolving balances divided by your revolving limits, measured per card and across all cards. It is nearly a third of your score and, unlike payment history, it has no memory. The bureaus see whatever balance your card issuer reports this month. Pay it down and the score responds the next time the issuer reports. Experian's guidance is to keep utilization below about 30 percent to avoid a significant hit, and notes that people with exceptional scores tend to run it in the single digits." },
        { h: "The statement date is what gets reported", p: "Here is the detail almost nobody is taught. Most card issuers report your balance to the bureaus on or just after your statement closing date, not your payment due date. If you charge $2,000 on a $2,500 card during the month and pay it in full by the due date, you still paid on time, but the bureaus saw an 80 percent utilization snapshot taken on the closing date. The fix is to pay most of the balance down a few days before the statement closes, so the snapshot is small. You can find the closing date on any statement, and most issuers let you move it." },
        { formula: "Utilization = Reported balances ÷ Total credit limits" },
        { example: "Card limit $5,000, closing date the 20th, due date the 15th of the next month. You spend $1,800 during the month. Pay $1,600 on the 17th. Statement closes at $200, which is 4 percent utilization. Pay the remaining $200 by the due date. Same spending, same on-time payment, dramatically different reported number." },
        { carry: "Utilization is reported on the statement closing date. Pay down before the close, not just before the due date. Under 10 percent is the goal; under 30 is the floor." },
        { trap: "Running every card to zero and never using them. Experian notes zero utilization is no better than single digits, and unused cards get closed or their limits cut, which hurts you. Use each card a few times a year and pay it off." },
        { sources: [ { t: "Experian, Is 0% Utilization Good for Credit Scores? (reporting date, ideal range)", u: "https://www.experian.com/blogs/ask-experian/is-no-credit-utilization-good-for-credit-scores/" } ] }
      ]
    },
    {
      id: "m02-03",
      title: "Debt-to-Income and What Lenders Want",
      minutes: 10,
      blocks: [
        { h: "DTI defined", p: "Debt-to-income, or DTI, is your total monthly debt payments divided by your gross monthly income. Lenders count the minimum payments on cards, car loans, student loans, your housing payment, and the payments on any rentals you own, offset by a portion of the rent those rentals bring in. They do not count utilities, groceries, or insurance that is not part of a loan payment. DTI is how a conventional lender decides whether you can carry one more payment.\n\nWhat conventional lenders accept. Fannie Mae's Selling Guide sets the maximum DTI for manually underwritten loans at 36 percent, stretching to 45 percent with strong credit and reserves, and allows up to 50 percent when the loan is run through its automated system, Desktop Underwriter. In practice, the lower your DTI the smoother everything goes, and a DTI near 50 percent means the next rental may not fit. This matters because conventional investment-property loans are the cheapest long-term money available, and a day job with a W-2 is what makes them easy to get." },
        { h: "DSCR lenders mostly ignore DTI", p: "There is a second category of lender you will use constantly in BRRRR. A DSCR lender, short for debt service coverage ratio, qualifies the property rather than you. They divide the property's rent by its full monthly payment, and they generally want that ratio at or above about 1.10 to 1.25 depending on credit. Many programs do not ask for tax returns or pay stubs and do not compute your personal DTI at all. The trade is a higher rate, a larger down payment of roughly 20 to 25 percent, and a credit score minimum that is typically around 680 for the best terms. When your DTI fills up on conventional loans, DSCR is where you go next." },
        { formula: "DTI = Total monthly debt payments ÷ Gross monthly income.   DSCR = Monthly rent ÷ Monthly PITIA" },
        { example: "You earn $6,000 a month gross. Car $400, cards $150, student loan $250, housing $1,500. DTI = 2,300 ÷ 6,000 = 38 percent. A new rental with a $1,400 payment and $1,900 rent adds net debt of roughly $1,400 − (0.75 × 1,900) = −$25, so it barely moves your DTI. That is why a cash-flowing rental does not block the next loan the way a car payment does." },
        { carry: "Conventional: DTI max 36–45% manual, 50% through DU. DSCR lenders qualify the property (rent ÷ PITIA ≥ about 1.10–1.25) and mostly ignore DTI." },
        { trap: "Financing a car or furniture the year you plan to buy rentals. A $500 car payment consumes as much DTI as roughly $100,000 of mortgage. Buy the house first, the truck later." },
        { sources: [
          { t: "Fannie Mae Selling Guide B3-6-02, Debt-to-Income Ratios", u: "https://selling-guide.fanniemae.com/sel/b3-6-02/debt-income-ratios" },
          { t: "LendingOne, A Guide to DSCR Loans (2026): ratios, credit, LTV, reserves", u: "https://lendingone.com/insight/a-guide-to-dscr-loans-for-real-estate-investors/" }
        ] }
      ]
    },
    {
      id: "m02-04",
      title: "Reserves: Months of PITIA",
      minutes: 8,
      blocks: [
        { h: "What reserves are", p: "Reserves are liquid money the lender wants to see after closing, measured in months of PITIA, which is the full monthly cost of a property: principal, interest, taxes, insurance, and association dues. Reserves are not the down payment and not closing costs. They are what is left in your accounts the day after you close, proving you can survive a vacancy or a repair without missing a payment." },
        { h: "The numbers lenders use", p: "Fannie Mae requires six months of PITIA in reserves for an investment property. If you own other financed rentals, it adds a percentage of their total unpaid loan balances: 2 percent if you have one to four financed properties, 4 percent for five or six, 6 percent for seven to ten. There is no reserve requirement on a one-unit primary residence. DSCR lenders vary widely; a common ask is in the range of six to nine months of PITIA, sometimes reduced for higher credit scores. What counts as reserves also varies: checking and savings count fully, retirement accounts often count at a discount, and money that showed up last week with no paper trail may not count at all." },
        { formula: "Required reserves ≈ 6 × PITIA on the new property + (2–6% × unpaid balances on other financed rentals)" },
        { example: "New rental PITIA is $1,400, so six months is $8,400. You already own two financed rentals with $240,000 of combined balances; 2 percent is $4,800. Total reserves the lender wants to see after closing: about $13,200. If you are putting every dollar into the down payment, you will be declined even with great credit." },
        { carry: "Conventional investment property: six months PITIA, plus 2–6 percent of other rentals' balances. Reserves are counted after closing, and seasoned money counts; mystery money does not." },
        { trap: "Scraping together the down payment and arriving at closing with nothing left. The file dies in underwriting. Build reserves before the deal fund, and keep them in an account you do not touch." },
        { sources: [
          { t: "Fannie Mae Selling Guide B3-4.1-01, Minimum Reserve Requirements", u: "https://selling-guide.fanniemae.com/sel/b3-4.1-01/minimum-reserve-requirements" },
          { t: "LendingOne, DSCR loan reserves (around 9 months PITIA typical, may be reduced)", u: "https://lendingone.com/insight/a-guide-to-dscr-loans-for-real-estate-investors/" }
        ] }
      ]
    },
    {
      id: "m02-05",
      title: "Separate Business and Personal Money",
      minutes: 9,
      blocks: [
        { h: "Why one account is a disaster", p: "Mixing business and personal money in one account is called commingling, and it costs you three ways. It makes your bookkeeping impossible, because every transaction has to be sorted after the fact. It makes a lender's job harder, because they cannot see what the business earns. And if you operate through a limited liability company, it is one of the main things a court looks at when deciding whether to ignore the LLC and hold you personally liable, which lawyers call piercing the veil. Courts look for commingled funds, personal use of company assets, undercapitalization, and failure to keep records. Keep the money separate and you avoid all of it." },
        { h: "The minimum setup", p: "Open a dedicated business checking account the day you form the entity, even if the balance is $100. Add a business savings account for reserves and a business credit card used for nothing else. Pay yourself by transfer from business to personal, labeled as an owner draw, and fund the business from personal by transfer labeled as an owner contribution. Never pay a personal bill from the business card and never buy a water heater on your personal card. If you do slip, record it as a contribution or draw the same week, not at tax time. Each partner should have read access to every account. Transparency between partners is not optional." },
        { h: "If you have not formed an entity yet", p: "You can still separate the money. A second personal checking account used only for real estate does most of the bookkeeping work and starts the habit. Talk to a CPA and a local real estate attorney about whether and when to form an LLC in your state; the answer depends on your lending plans, because conventional loans are made to people, not LLCs, and moving a property into an entity afterward has consequences. Confirm with a local real estate attorney." },
        { carry: "One business checking, one business savings, one business card. Owner draws out, owner contributions in, nothing else crosses the line." },
        { trap: "Using the business card for a personal emergency because it had room. One charge is a bookkeeping entry; a habit is evidence of commingling that can cost you the liability protection you formed the LLC for." },
        { state: { fl: "A Florida LLC must file an annual report with the Division of Corporations each year; the fee is $138.75 and a $400 late fee applies after May 1. Miss it long enough and the LLC is administratively dissolved.", oh: "Ohio does not require LLCs to file an annual report, so there is no yearly state filing fee to keep the entity in good standing." } },
        { sources: [
          { t: "Wolters Kluwer, Piercing the veil of small business: factors and prevention", u: "https://www.wolterskluwer.com/en/expert-insights/piercing-the-veil-of-small-business-what-the-owners-of-llcs-and-corporations-need-to-know" },
          { t: "Florida Division of Corporations, Annual Report filing and fees", u: "https://dos.fl.gov/sunbiz/manage-business/efile/annual-report/" },
          { t: "Northwest Registered Agent, Ohio annual report requirements (none for LLCs)", u: "https://www.northwestregisteredagent.com/annual-report/ohio" }
        ] }
      ]
    },
    {
      id: "m02-06",
      title: "Bookkeeping Basics for a Rental",
      minutes: 10,
      blocks: [
        { h: "What you are building toward", p: "Every rental you own will eventually be reported on Schedule E of your tax return, one column per property, with rent on top and a fixed list of expense lines below. If your books use those same lines all year, tax time is an export, not an archaeology project. A chart of accounts is just the list of categories you sort money into. Build yours from the IRS list and you never have to invent one." },
        { h: "The chart of accounts, straight from the IRS", p: "Income: rents received, and other income such as late fees or pet rent. Expenses, in the order Publication 527 lists them: advertising, auto and travel, cleaning and maintenance, commissions, insurance, legal and other professional fees, management fees, mortgage interest, other interest, repairs, supplies, taxes, utilities, and depreciation. Add two more that are not expenses but you must track: capital improvements, which are not deducted in the year paid but added to the property's basis and depreciated, and the loan principal paid, which is not an expense at all. Keeping repairs and improvements separate is the one distinction that trips up almost everyone. A repair keeps the property in working order; an improvement adds value or extends its life. A new faucet is a repair. A new roof is an improvement." },
        { h: "What to keep and how", p: "Keep every receipt, invoice, closing statement, lease, and bank statement. Photograph paper receipts the day you get them and file them by property and month in a cloud folder you both can see. Record transactions at least weekly; monthly is the absolute maximum before memory fails. Reconcile each account to its statement every month, meaning your books and the bank agree to the penny. Use real bookkeeping software or at minimum one spreadsheet per property with the IRS categories as columns. Whatever you choose, the test is simple: could you hand a lender a profit and loss statement for any property for any twelve-month window within ten minutes? If not, the system is not done." },
        { carry: "Chart of accounts = the Schedule E lines from IRS Publication 527. Separate repairs from improvements. Reconcile monthly. Receipts photographed the same day." },
        { trap: "Treating a $12,000 roof as a repair to get the deduction this year. It is an improvement that must be capitalized and depreciated. Misclassifying it invites an audit adjustment plus penalties. When in doubt, ask your CPA before you file, not after." },
        { sources: [ { t: "IRS Publication 527, Residential Rental Property (expense categories; repairs vs. improvements; depreciation)", u: "https://www.irs.gov/publications/p527" } ] }
      ]
    },
    {
      id: "m02-07",
      title: "The Personal Financial Statement",
      minutes: 9,
      blocks: [
        { h: "What a PFS is and who asks for it", p: "A personal financial statement, or PFS, is your personal balance sheet and income summary on a lender's form. Small banks, credit unions, hard money lenders, private lenders, and partners will ask for it, often before they ask for anything else. The most widely used template is the Small Business Administration's Form 413, which the SBA requires from every owner of 20 percent or more of a business and from every guarantor. Even when nobody requires that specific form, building yours to its structure means you can answer any lender in minutes." },
        { h: "What goes on it", p: "Assets: cash in each bank account, retirement accounts, stocks and bonds, the market value of each real estate property, vehicles, life insurance cash value, and other personal property. Liabilities: every loan with its lender, balance, monthly payment, and what secures it, plus credit card balances, unpaid taxes, and any other debts. The form then asks for your income sources, and for contingent liabilities, which are debts you would owe only if something happens, like a loan you co-signed. Separate schedules list each real estate property with its purchase date, cost, current value, mortgage balance, and the rent it brings in. Net worth is assets minus liabilities at the bottom." },
        { h: "How to build it so it survives scrutiny", p: "Use the values you can prove. A lender will ask for the statements behind every number, so a bank balance is the figure on last month's statement, a property value is a recent appraisal or a conservative estimate you can defend, and a car is what a pricing guide says, not what you hope. Update it every quarter and date each version. Keep a folder with the backup documents in the same order as the lines on the form. A clean PFS with backup attached tells a lender more about how you will manage their money than your credit score does. If you are married, note that SBA Form 413 requires your spouse's information and signature when you hold 20 percent or more." },
        { carry: "Build your PFS on the SBA Form 413 structure: assets, liabilities, income, contingent liabilities, and a real estate schedule. Update quarterly, keep the backup documents behind every line." },
        { trap: "Inflating asset values to look stronger. The lender will find the real number, and once they catch one soft figure every other number on your statement is suspect. Understate if anything." },
        { sources: [ { t: "NerdWallet, SBA Form 413: How to Fill Out the Personal Financial Statement (sections and who must complete it)", u: "https://www.nerdwallet.com/business/loans/learn/sba-form-413" } ] }
      ]
    },
    {
      id: "m02-08",
      title: "Emergency Fund vs. Deal Fund",
      minutes: 7,
      blocks: [
        { h: "Three buckets, three jobs", p: "Money you set aside needs a label, or the first good deal will eat your safety net. The emergency fund is personal: the money that keeps your household running if a job ends or a transmission dies. The Federal Reserve Bank of St. Louis and most planners put it at three to six months of essential expenses, in a savings or money market account that is easy to reach but not attached to your debit card. The reserve account is the property version of the same thing, and lesson four covered the months of PITIA lenders want to see. The deal fund is the money that goes into the next house: earnest money, down payment, rehab, closing costs. It is the only one of the three you are allowed to spend on purpose." },
        { h: "The order of operations", p: "Fund the emergency account first, at least to one month of essentials, then build the deal fund and the reserve account together. The reason is not caution for its own sake. It is that an investor with no personal cushion makes bad decisions under pressure: taking the first offer, skipping the inspection, accepting a bad tenant because the mortgage is due. The emergency fund buys you the ability to say no. Once the first property closes, the reserve requirement in lesson four becomes the floor for the reserve account, and the deal fund restarts from zero." },
        { formula: "Emergency fund = 3–6 × monthly essential expenses.   Reserve account ≥ 6 × PITIA per rental.   Deal fund = everything above those two." },
        { example: "Household essentials are $3,500 a month. Emergency fund target: $10,500 to $21,000. First target is $3,500. After that, every month's savings splits between the deal fund and the reserve account until the reserve account holds $8,400 (six months of a $1,400 PITIA). Only then does the deal fund get everything." },
        { carry: "Three accounts with three names: emergency (3–6 months of essentials), reserves (6+ months PITIA per door), deal fund. Never let one raid another." },
        { trap: "Calling the emergency fund the deal fund when a great house appears. Then a car breaks the month after closing, you borrow at card rates, your utilization spikes, and your score drops before the refinance. One account, one job." },
        { sources: [ { t: "Federal Reserve Bank of St. Louis, When the Unexpected Happens, Be Ready with an Emergency Fund (2025)", u: "https://www.stlouisfed.org/publications/page-one-economics/2025/sep/when-unexpected-happens-be-ready-with-emergency-fund" } ] }
      ]
    },
    {
      id: "m02-09",
      title: "Credit Repair: What Is Legit and What Is a Scam",
      minutes: 10,
      blocks: [
        { h: "The legitimate moves", p: "There are exactly four things that reliably raise a damaged score, and all four are free. One: dispute errors. Under the Fair Credit Reporting Act you can dispute inaccurate information with each bureau and with the company that reported it, and the furnisher generally must investigate and respond within 30 days. You do this yourself, in writing, with documents, and it costs nothing. Two: pay revolving balances down, ideally below 10 percent of limits, before the statement closes. Three: become an authorized user on a long-standing, perfectly paid card held by a trusted family member; that account's history can appear on your report. Four: pay every bill on time from today forward and let time do the rest. Negative marks fade in weight long before they fall off." },
        { h: "What does not work", p: "Nobody can remove accurate negative information. A paid collection, a real late payment, and a legitimate charge-off are all accurate, and disputing accurate information as a strategy is something the Consumer Financial Protection Bureau explicitly lists as a red flag. Paid tradeline services, where a stranger adds you to their card for a fee, are discouraged by Experian: the boost is temporary, the cost often exceeds a thousand dollars, you hand your Social Security number to a stranger, and lenders may treat the inflated score as fraud. A new credit identity, a CPN, or any suggestion to use a number other than your own Social Security number is fraud, full stop." },
        { h: "How to spot the scam", p: "The Credit Repair Organizations Act makes it illegal for a credit repair company to charge you before it has completed the promised services. So the first red flag is any upfront fee. The CFPB lists the rest: guarantees of a specific score increase, promises to remove accurate information, advice not to contact the bureaus directly, and failure to tell you that disputing errors is your free legal right. If a company does any of those, walk away. If you want help, a nonprofit credit counselor is a different thing from a credit repair company, and the CFPB explains how to tell them apart." },
        { carry: "Legit and free: dispute real errors, drop utilization, authorized user with family, pay on time. Red flags: upfront fees, guaranteed results, disputing accurate items, CPNs." },
        { trap: "Paying a company to flood the bureaus with disputes on accurate accounts. At best nothing changes; at worst the bureaus flag the disputes as frivolous, and you have paid for a worse file. Your credit improves by paying down and paying on time, not by paperwork tricks." },
        { sources: [
          { t: "CFPB, How do I dispute an error on my credit report?", u: "https://www.consumerfinance.gov/ask-cfpb/how-do-i-dispute-an-error-on-my-credit-report-en-314/" },
          { t: "CFPB, How can I tell a credit repair scam from a reputable credit counselor?", u: "https://www.consumerfinance.gov/ask-cfpb/how-can-i-tell-a-credit-repair-scam-from-a-reputable-credit-counselor-en-1343/" },
          { t: "Experian, What Is Credit Card Piggybacking? (authorized users and paid tradelines)", u: "https://www.experian.com/blogs/ask-experian/what-is-piggybacking-credit/" }
        ] }
      ]
    }
  ],
  cards: [
    { id: "m02-c01", type: "number", q: "What are the five FICO factors and their weights?", a: "Payment history 35%, amounts owed 30%, length of credit history 15%, new credit 10%, credit mix 10%." },
    { id: "m02-c02", type: "number", q: "What share of your FICO score comes from payment history plus amounts owed?", a: "65 percent. If you fix nothing else, never be late and keep balances low." },
    { id: "m02-c03", type: "term", q: "What is a hard inquiry?", a: "A lender's credit pull when you apply for credit. It falls under the new credit factor, 10 percent of your score. Shopping for one mortgage within a short window is generally treated as one inquiry." },
    { id: "m02-c04", type: "trap", q: "Why should you not close an old no-fee credit card?", a: "You shorten your average account age (15% of score) and shrink total available credit, which raises utilization on remaining cards (30% of score). Keep it open and use it occasionally." },
    { id: "m02-c05", type: "scenario", q: "Two partners both have a 680. One has a two-year-old 30-day late; the other has perfect payments but cards at 85% utilization. Who can improve fastest?", a: "The high-utilization partner. Paying cards under 10% before the statement closes can move the score within one or two cycles. The late payment only fades with time." },
    { id: "m02-c06", type: "term", q: "What is credit utilization?", a: "Revolving balances divided by revolving limits, per card and overall. Example: $400 balance on a $5,000 limit is 8 percent." },
    { id: "m02-c07", type: "number", q: "What utilization levels does Experian describe?", a: "Below about 30 percent avoids a significant hit; people with exceptional scores typically run single digits. Zero is no better than single digits." },
    { id: "m02-c08", type: "term", q: "What is the statement closing date and why does it matter?", a: "The day your card issuer totals the month and, for most issuers, reports the balance to the bureaus. Whatever you owe that day is your reported utilization, regardless of when you pay." },
    { id: "m02-c09", type: "scenario", q: "You spend $1,800 on a $5,000 card each month and always pay in full by the due date, but your utilization shows 36%. What do you change?", a: "Pay most of it a few days before the statement closes, not just before the due date. Close the statement at $200 and reported utilization drops to 4 percent." },
    { id: "m02-c10", type: "trap", q: "What happens when you stop using cards entirely to keep utilization at zero?", a: "No benefit over single digits, and issuers may cut limits or close dormant accounts, which hurts both utilization and account age. Use each card a few times a year and pay it off." },
    { id: "m02-c11", type: "formula", q: "How do you calculate DTI?", a: "Total monthly debt payments ÷ gross monthly income. Example: $2,300 of payments on $6,000 income = 38 percent." },
    { id: "m02-c12", type: "number", q: "What DTI limits does Fannie Mae set?", a: "36 percent for manually underwritten loans, up to 45 with strong credit and reserves, and up to 50 percent when run through Desktop Underwriter." },
    { id: "m02-c13", type: "term", q: "What does a DTI calculation include and exclude?", a: "Includes minimum card payments, auto, student, housing, and other loan payments. Excludes utilities, groceries, and non-loan insurance." },
    { id: "m02-c14", type: "term", q: "What is a DSCR lender?", a: "A lender that qualifies the property by its debt service coverage ratio, rent ÷ PITIA, instead of your personal income. Most do not compute DTI or ask for tax returns." },
    { id: "m02-c15", type: "formula", q: "DSCR formula and a target?", a: "DSCR = monthly rent ÷ monthly PITIA. Programs commonly want about 1.10 to 1.25. $1,900 rent on $1,520 PITIA = 1.25." },
    { id: "m02-c16", type: "number", q: "Typical DSCR loan terms as of 2026?", a: "Roughly 20 to 25 percent down (75–80% LTV on purchases), credit minimum often around 680 for best terms, reserves commonly in the 6–9 month range, higher rate than conventional. Terms vary by lender." },
    { id: "m02-c17", type: "scenario", q: "Your DTI is 49% after three conventional rentals and the bank says no more. What is your next financing path?", a: "A DSCR loan. It qualifies the property's rent against its payment and mostly ignores your DTI. Expect a higher rate and larger down payment." },
    { id: "m02-c18", type: "trap", q: "Why is a new car loan so damaging the year you plan to buy rentals?", a: "A $500 car payment uses about as much DTI as roughly $100,000 of mortgage payment. Buy the house first, the truck later." },
    { id: "m02-c19", type: "scenario", q: "A rental you are buying has a $1,400 payment and $1,900 rent. How much does it add to your DTI debt?", a: "Lenders typically count 75% of rent: 1,400 − (0.75 × 1,900) = about −$25. A cash-flowing rental barely moves your DTI." },
    { id: "m02-c20", type: "term", q: "What are reserves, to a lender?", a: "Liquid funds left after closing, measured in months of PITIA, proving you can carry the payment through a vacancy or repair. Not the down payment, not closing costs." },
    { id: "m02-c21", type: "number", q: "How many months of reserves does Fannie Mae require on an investment property?", a: "Six months of PITIA. Second home: two months. One-unit primary residence: none." },
    { id: "m02-c22", type: "number", q: "What extra reserves does Fannie Mae add for other financed rentals you own?", a: "2% of their total unpaid balances for 1–4 financed properties, 4% for 5–6, 6% for 7–10." },
    { id: "m02-c23", type: "formula", q: "Reserves needed: new PITIA $1,400, two other rentals with $240,000 total balance?", a: "6 × 1,400 = $8,400 plus 2% × 240,000 = $4,800. About $13,200 after closing." },
    { id: "m02-c24", type: "trap", q: "What kills a loan file even with great credit and a full down payment?", a: "Arriving at closing with no reserves left. Build reserves before the deal fund and keep them in an untouched account." },
    { id: "m02-c25", type: "term", q: "What is seasoned money?", a: "Funds that have sat in your account long enough, typically shown on two months of statements, that the lender can trace. A large unexplained deposit last week may be excluded from reserves." },
    { id: "m02-c26", type: "term", q: "What is commingling?", a: "Mixing business and personal money in the same account or on the same card. It wrecks bookkeeping and is a leading factor courts cite when piercing an LLC's liability shield." },
    { id: "m02-c27", type: "term", q: "What is piercing the veil?", a: "A court ignoring your LLC and holding you personally liable. Courts look for commingled funds, personal use of company assets, undercapitalization, and missing records." },
    { id: "m02-c28", type: "term", q: "What is the minimum business money setup?", a: "One business checking, one business savings for reserves, one business credit card used for nothing else. Partners both have read access." },
    { id: "m02-c29", type: "term", q: "What are an owner draw and an owner contribution?", a: "A draw is money moved from the business to you, labeled as such. A contribution is money you put into the business. These labels are how money crosses the line legally." },
    { id: "m02-c30", type: "scenario", q: "You paid for a rental's water heater on your personal card because the business card was at the office. What do you do?", a: "Record it the same week as an owner contribution, attach the receipt to the property's file, and reimburse yourself by transfer. Fixing it at tax time is how commingling starts." },
    { id: "m02-c31", type: "state", q: "Does your LLC have a yearly state filing to stay in good standing?", a: "FL: Yes. Annual report with the Division of Corporations, $138.75, with a $400 late fee after May 1 and administrative dissolution if ignored. | OH: No annual report is required for LLCs." },
    { id: "m02-c32", type: "trap", q: "Why is using the business card for one personal emergency dangerous?", a: "One charge is a bookkeeping entry; a pattern is evidence of commingling that can cost you the liability protection the LLC exists to provide." },
    { id: "m02-c33", type: "term", q: "What is a chart of accounts?", a: "The list of categories you sort money into. For a rental, build it from the Schedule E expense lines in IRS Publication 527 so tax time is an export." },
    { id: "m02-c34", type: "term", q: "Name the rental expense categories from IRS Publication 527.", a: "Advertising, auto and travel, cleaning and maintenance, commissions, insurance, legal and professional fees, management fees, mortgage interest, other interest, repairs, supplies, taxes, utilities, depreciation." },
    { id: "m02-c35", type: "term", q: "Repair vs. improvement?", a: "A repair keeps the property in working order and is deducted this year (a new faucet). An improvement adds value or extends life and is capitalized and depreciated (a new roof)." },
    { id: "m02-c36", type: "trap", q: "What goes wrong if you expense a $12,000 roof as a repair?", a: "It is an improvement that must be depreciated. Misclassifying it invites an audit adjustment plus penalties. Ask your CPA before filing." },
    { id: "m02-c37", type: "term", q: "What does it mean to reconcile an account?", a: "Matching your books to the bank statement so they agree to the penny, every month. It is how you catch missed transactions and errors." },
    { id: "m02-c38", type: "scenario", q: "A lender asks for a twelve-month profit and loss on one of your rentals. How fast should you produce it?", a: "Within ten minutes. If you cannot, your bookkeeping system is not finished. One set of books per property using the IRS categories makes this an export." },
    { id: "m02-c39", type: "term", q: "What is loan principal in your books?", a: "Not an expense. The principal portion of each mortgage payment reduces a liability; only the interest is an expense. Track it separately." },
    { id: "m02-c40", type: "term", q: "What is a personal financial statement (PFS)?", a: "Your personal balance sheet and income summary on a lender's form: assets, liabilities, income sources, contingent liabilities, and a real estate schedule. Net worth at the bottom." },
    { id: "m02-c41", type: "number", q: "What is SBA Form 413 and who must complete it?", a: "The SBA's personal financial statement, required from every owner of 20 percent or more of the business and every guarantor. Spouses must be included and sign at that threshold." },
    { id: "m02-c42", type: "term", q: "What is a contingent liability?", a: "A debt you owe only if something happens, such as a loan you co-signed for a relative. Lenders want to see it on your PFS." },
    { id: "m02-c43", type: "term", q: "What goes on the real estate schedule of a PFS?", a: "Each property's address, purchase date, cost, current value, mortgage balance, lender, payment, and rent received." },
    { id: "m02-c44", type: "trap", q: "Why is inflating asset values on a PFS self-defeating?", a: "The lender verifies every number against statements. One soft figure makes every other figure suspect. Use provable values and understate if anything." },
    { id: "m02-c45", type: "scenario", q: "A private lender asks for your PFS and you have never made one. What is your 48-hour plan?", a: "Download SBA Form 413, fill it from last month's statements, attach a backup document for every line in order, date it, and send. Then set a quarterly reminder to update it." },
    { id: "m02-c46", type: "term", q: "What are the three money buckets and their jobs?", a: "Emergency fund (personal survival, 3–6 months of essentials), reserve account (6+ months PITIA per rental), deal fund (the only one you spend on purpose)." },
    { id: "m02-c47", type: "number", q: "How large should an emergency fund be?", a: "Three to six months of essential expenses in an accessible savings or money market account, per the St. Louis Fed and most planners. First milestone: one month." },
    { id: "m02-c48", type: "formula", q: "Household essentials are $3,500 a month. Emergency fund target?", a: "3–6 × 3,500 = $10,500 to $21,000. Hit $3,500 first, then split savings between reserves and the deal fund." },
    { id: "m02-c49", type: "trap", q: "What happens when the emergency fund becomes the deal fund for one great house?", a: "The next surprise goes on a card, utilization spikes, your score drops before the refinance, and you may lose the deal that caused it. One account, one job." },
    { id: "m02-c50", type: "term", q: "What are the four legitimate, free ways to raise a damaged credit score?", a: "Dispute real errors in writing, pay utilization down before statements close, become an authorized user on a trusted family member's old perfect card, and pay on time from today forward." },
    { id: "m02-c51", type: "number", q: "How long does a furnisher have to respond to a credit dispute?", a: "Generally 30 days from receiving it, under the Fair Credit Reporting Act. If the error is confirmed they must correct it and notify the bureaus." },
    { id: "m02-c52", type: "term", q: "How does being an authorized user help your credit?", a: "The primary cardholder's payment history and account age appear on your report, helping the 35% and 15% factors. Only do it with someone you trust who pays perfectly." },
    { id: "m02-c53", type: "trap", q: "Why does Experian discourage paid tradeline services?", a: "The boost is temporary, it often costs over $1,000, you give a stranger your Social Security number, and lenders may treat the inflated score as fraud." },
    { id: "m02-c54", type: "number", q: "What does the Credit Repair Organizations Act prohibit?", a: "Charging any fee before promised services are completed, and deceptive practices. Any upfront fee is the first red flag." },
    { id: "m02-c55", type: "scenario", q: "A company guarantees a 100-point increase in 60 days for $499 up front and says they will dispute everything. What do you do?", a: "Walk away. Upfront fees violate CROA, guaranteed results and disputing accurate items are CFPB red flags, and no one can remove accurate negatives." }
  ],
  quiz: [
    { id: "m02-q01", q: "Which FICO factor carries the most weight?", opts: ["Payment history (35%)", "Amounts owed (30%)", "Length of history (15%)", "Credit mix (10%)"], correct: 0, explain: "Payment history is 35 percent. Amounts owed is next at 30, and together they are 65 percent of the score." },
    { id: "m02-q02", q: "You close a ten-year-old no-fee card you never use. The most likely effect is:", opts: ["Your score rises because you have less credit", "No effect", "Your score may fall as account age and available credit shrink", "Your payment history resets"], correct: 2, explain: "Closing it shortens average account age and raises utilization on remaining cards. Keep old cards open." },
    { id: "m02-q03", q: "Most card issuers report your balance to the bureaus:", opts: ["On or just after the statement closing date", "On the payment due date", "On the first of the month", "Only when you miss a payment"], correct: 0, explain: "The closing-date balance is what gets reported. Pay down before the close to lower reported utilization." },
    { id: "m02-q04", q: "A $5,000 card closes its statement at $200. Reported utilization is:", opts: ["2%", "20%", "0.4%", "4%"], correct: 3, explain: "200 ÷ 5,000 = 4 percent." },
    { id: "m02-q05", q: "Experian's guidance on utilization is best summarized as:", opts: ["Zero is ideal", "Below 30% avoids a big hit; single digits is where top scores live", "Anything under 50% is fine", "Utilization does not affect FICO"], correct: 1, explain: "Under 30 is the floor, single digits the goal, and zero is no better than single digits." },
    { id: "m02-q06", q: "Gross income $6,000; payments: car $400, cards $150, student loan $250, housing $1,500. DTI is:", opts: ["28%", "33%", "38%", "43%"], correct: 2, explain: "2,300 ÷ 6,000 = 38 percent." },
    { id: "m02-q07", q: "The maximum DTI Fannie Mae allows through Desktop Underwriter is:", opts: ["36%", "43%", "45%", "50%"], correct: 3, explain: "DU allows up to 50 percent; manual underwriting is 36, stretching to 45 with strong compensating factors." },
    { id: "m02-q08", q: "A DSCR lender primarily qualifies the loan using:", opts: ["Your tax returns and W-2s", "Your debt-to-income ratio", "Your employer's verification", "The property's rent divided by its PITIA"], correct: 3, explain: "DSCR lenders qualify the property. Most do not compute DTI or require income documents." },
    { id: "m02-q09", q: "Rent $1,900, PITIA $1,520. DSCR is:", opts: ["0.80", "1.10", "1.25", "1.52"], correct: 2, explain: "1,900 ÷ 1,520 = 1.25, which meets most programs' target." },
    { id: "m02-q10", q: "Fannie Mae's reserve requirement for an investment property is:", opts: ["None", "Two months PITIA", "Six months PITIA", "Twelve months PITIA"], correct: 2, explain: "Six months of PITIA, plus a percentage of unpaid balances on other financed rentals." },
    { id: "m02-q11", q: "New PITIA $1,400; you own two other financed rentals with $240,000 total balance. Reserves required are about:", opts: ["$8,400", "$4,800", "$16,800", "$13,200"], correct: 3, explain: "6 × 1,400 = 8,400 plus 2% × 240,000 = 4,800, total $13,200." },
    { id: "m02-q12", q: "Which is a factor courts weigh when deciding whether to pierce an LLC's veil?", opts: ["The LLC has only one member", "The LLC owns real estate", "Commingling business and personal funds", "The LLC has a business credit card"], correct: 2, explain: "Commingling, personal use of company assets, undercapitalization, and missing records are the classic factors." },
    { id: "m02-q13", q: "You paid a rental's $900 plumbing bill on your personal card. The correct bookkeeping move is:", opts: ["Ignore it; it was your money", "Record an owner contribution and reimburse by transfer the same week", "Deduct it on your personal return", "Wait until tax season to sort it out"], correct: 1, explain: "Label it as an owner contribution, attach the receipt, and reimburse yourself. Fast correction prevents commingling." },
    { id: "m02-q14", q: "Replacing a rental's entire roof for $12,000 is treated as:", opts: ["An improvement that is capitalized and depreciated", "A repair deducted this year", "Mortgage interest", "A management fee"], correct: 0, explain: "It adds value and extends life, so it is an improvement. Repairs keep the property in working order." },
    { id: "m02-q15", q: "Which is NOT one of the Schedule E expense categories listed in IRS Publication 527?", opts: ["Advertising", "Loan principal", "Insurance", "Management fees"], correct: 1, explain: "Principal reduces a liability; it is not an expense. Only the interest portion is deductible." },
    { id: "m02-q16", q: "SBA Form 413 is required from:", opts: ["Only the primary applicant", "Only owners of 50% or more", "The business's accountant", "Every owner of 20% or more and every guarantor"], correct: 3, explain: "Owners of 20 percent or more and all guarantors, with spouses included at that threshold." },
    { id: "m02-q17", q: "A loan you co-signed for your brother belongs on your PFS as:", opts: ["An asset", "Income", "A contingent liability", "Nothing; it is his debt"], correct: 2, explain: "You owe it only if he does not pay, which is exactly what a contingent liability is." },
    { id: "m02-q18", q: "The St. Louis Fed's guidance on emergency fund size is:", opts: ["3–6 months of essential expenses", "One month of income", "Twelve months of all expenses", "Whatever is left after investing"], correct: 0, explain: "Three to six months of essentials, in an accessible but not too accessible account." },
    { id: "m02-q19", q: "Under the Fair Credit Reporting Act, a furnisher that receives your dispute generally must respond within:", opts: ["7 days", "90 days", "30 days", "One year"], correct: 2, explain: "Generally 30 days. If the item is confirmed inaccurate they must fix it and notify the bureaus." },
    { id: "m02-q20", q: "Which is a red flag for a credit repair scam under CROA and CFPB guidance?", opts: ["They ask for an upfront fee before doing anything", "They tell you disputing errors is free", "They suggest paying down card balances", "They recommend a nonprofit counselor"], correct: 0, explain: "Charging before services are complete is illegal under CROA. Guaranteed results and disputing accurate items are the other flags." }
  ],
  drills: [
    "Pull your free credit reports from all three bureaus at annualcreditreport.com tonight, and your partner's. Circle every error. Draft one written dispute per error with the supporting document attached.",
    "For every credit card you hold, write the limit, current balance, statement closing date, and due date on one page. Set a calendar alert three days before each closing date to pay the balance down below 10 percent.",
    "Calculate your DTI from your last pay stub and your actual minimum payments. Then calculate it again as if you added a $1,400 rental payment with $1,900 rent (counting 75 percent of rent). Write both numbers down.",
    "Open the business checking, business savings, and second account you are missing this week, even with $50 each. Name them Operating, Reserves, and Deal Fund in the bank app.",
    "Build your personal financial statement on the SBA Form 413 layout in a spreadsheet, with a folder of backup documents in the same order as the lines. Date it, and set a quarterly reminder to update it.",
    "Create one spreadsheet or bookkeeping file with the Publication 527 expense categories as columns and a separate column for capital improvements and loan principal. Enter last month's real estate transactions, then reconcile it to the bank statement."
  ]
});
