BIBLE.register({
  id: "m05",
  part: 2,
  title: "Rehab & Contractors",
  icon: "🔨",
  summary: "How to walk a house, price the repairs in twenty minutes, write a scope a contractor cannot wiggle out of, pay in a way that protects you, and carry the right contingency before you ever make an offer.",
  minutes: 95,
  lessons: [
    {
      id: "m05-01",
      title: "How a Contractor Thinks",
      minutes: 8,
      blocks: [
        { h: "Every price is materials plus labor plus the trip", p: "A contractor builds a price from three pieces. Materials are the stuff: shingles, pipe, paint, a toilet. Labor is the hours a person spends installing it, priced by the hour or by the unit. The trip charge is the cost of showing up at all: driving, loading the truck, setting up, cleaning up. On a big job the trip disappears into the total. On a small job it is most of the price. That is why swapping one light fixture might cost you a hundred and fifty dollars but swapping twelve in the same visit costs nowhere near twelve times that. When you bundle small tasks into one visit you are not negotiating, you are removing trips." },
        { h: "Units of measure", p: "Contractors price in four units and you should learn to speak them. Square feet, written sqft, covers flooring, paint, drywall, roofing and tile. Roofers also use the square, which is one hundred square feet of roof. Linear feet, written lf, covers anything long and thin: baseboard, gutters, fence, pipe, cabinets. Each covers single items: a door, a toilet, a window, a fixture. Lump sum is one number for a whole task, and it is the unit that hides the most. A lump sum is fine for a tiny job. On anything over a few thousand dollars, ask for the units underneath it." },
        { h: "Rental grade, durable, neutral", p: "Retail grade is what a homeowner picks for the house they will live in: wood cabinets, quartz, designer tile, specialty paint colors. Rental grade is what survives tenants and still rents fast: luxury vinyl plank floors, a single neutral paint color throughout, stock cabinets, laminate or prefab stone counters, basic white or chrome fixtures, solid doors. The goal of a BRRRR rehab is not a beautiful house. It is a house that appraises at the after repair value, rents at market, and does not need a service call for ten years. Every dollar you spend above rental grade is a dollar the appraiser may not give back and the tenant will not pay for." },
        { carry: "Price = materials + labor + trip charge. Units: sqft, square (100 sqft of roof), lf, each, lump sum. Standard: rental grade, durable, neutral." },
        { trap: "Choosing finishes you would want in your own home. The appraiser values the house against comparable sales, not against your taste, and the tenant values it against the rent. Pick one paint color, one floor, one fixture style, and use them in every house you buy so your pricing becomes automatic." },
        { example: "Three single tasks priced separately: change a bathroom faucet, swap a light fixture, replace a door knob. Each one might carry its own trip. Bundled into one handyman half-day, you pay one trip and three units of labor. Same work, meaningfully lower total." }
      ]
    },
    {
      id: "m05-02",
      title: "The Walkthrough Order",
      minutes: 8,
      blocks: [
        { h: "Always walk the same way", p: "Walk every house in the same order so you never forget a category, and so your partner can walk a different house and produce a sheet you can read. Start outside and go top down: roof, chimney, gutters, soffit and fascia, siding or stucco, windows and doors, foundation and grading, driveway and walks, fence and yard. Then find the systems: electrical panel, water heater, HVAC equipment inside and out, the main water line and shutoff, the sewer cleanout, any crawlspace or attic access. Only then go inside, room by room, in the same loop every time: kitchen, each bath, then bedrooms and living areas, ending at the laundry and garage. Photograph everything, including the panel label, the HVAC data plate, and the water heater date." },
        { h: "Source, symptom, scope", p: "Train one habit: when you see a symptom, find the source before you write the scope. A water stain on a ceiling is a symptom. The source might be a roof leak, a plumbing leak, or a bathtub overflow from years ago. The scope is completely different for each: a roof repair, a plumber, or a patch and paint. A door that will not latch is a symptom. The source might be humidity, a bad hinge, or foundation movement. If you only write down the symptom, you will price a paint job and buy a foundation problem. Ask yourself three times on every defect: what is the source, what is the symptom, what is the scope." },
        { h: "Age the systems from the labels", p: "The data plate on an HVAC condenser and the sticker on a water heater both carry a serial number that encodes the manufacture date, and most brands print the year plainly. The electrical panel has a brand name on the cover. The roof has no label, so look for curling or missing shingles, moss, more than one layer at the edge, and ask the seller for the permit date. Write the age next to every system on your sheet. Age is what tells you whether the number you carry is a repair or a replacement." },
        { carry: "Outside top down, then systems, then inside room by room. Source → symptom → scope, every defect." },
        { trap: "Walking the pretty rooms first. Buyers get anchored by a nice kitchen and go easy on the roof and the panel, which cost more than the kitchen. Do the boring, expensive stuff first while your judgment is fresh." },
        { example: "You see a soft spot in the hallway floor. Symptom. You open the crawlspace: the drain line under the bathroom has been leaking for years. Source. Scope: plumber to replace the drain section, remove and replace damaged subfloor, new floor in the hall and bath, and a moisture check for rot in the joists. That is a different number than a floor patch." }
      ]
    },
    {
      id: "m05-03",
      title: "Big-Ticket Systems: The Numbers to Carry",
      minutes: 12,
      blocks: [
        { h: "Roof", p: "Every number in this lesson is a national typical range published by cost guides in 2026. Your market will differ, sometimes by a lot, so use these to estimate on the hood of your car and get local quotes before you close. The roof comes first because a lender and an insurer will both ask about it. Angi reports a 2026 national average around ten thousand five hundred dollars for an asphalt shingle replacement, with most projects between seventy five hundred and twenty four thousand. HomeAdvisor's guide puts the average near ninety six hundred with a typical range of roughly fifty nine hundred to thirteen thousand four hundred, and asphalt shingles at about three to seven dollars per square foot installed, which is three hundred to seven hundred dollars per square. A roof on a fifteen hundred square foot single-story house usually lands somewhere in the fifty eight hundred to fourteen thousand seven hundred range. Steeper pitch, two layers to tear off, and plywood replacement push it up." },
        { h: "HVAC, water heater and electrical panel", p: "A three-ton split system is the common size for a fourteen to eighteen hundred square foot house. Angi's 2026 guide puts a full HVAC replacement at about seventy five hundred on average, ranging from five thousand to twelve thousand five hundred, with the three-ton equipment alone around three thousand before labor. Ductwork replacement is extra and can push the whole job past twenty thousand. A standard forty or fifty gallon tank water heater installed runs about eight hundred to twenty five hundred dollars with a national average near thirteen hundred fifty. An electrical panel replacement averages about thirteen hundred fifty, typically five hundred to twenty two hundred, but a full two hundred amp service upgrade with a new meter base and permit can reach forty five hundred. Carry the high end whenever the panel is a brand on the red-flag list in lesson six." },
        { h: "Plumbing: repipe and sewer", p: "A whole-house repipe, meaning all the supply lines inside the house, runs roughly fifteen hundred to fifteen thousand with a national average near seventy five hundred. PEX is the rental-grade choice; copper costs more. A main sewer line replacement averages about thirty three hundred, with a range from a few hundred for a spot repair to ten thousand or more for a full run, priced at roughly fifty to two hundred fifty dollars per linear foot whether dug or trenchless." },
        { h: "Windows and foundation", p: "Replacement windows run about three hundred to twenty five hundred dollars per opening installed depending on size and frame, with vinyl at the low end and whole-house projects averaging roughly seven hundred fifty per window. Foundation repair is the one category where you do not estimate: you get an engineer or a specialist. For a sense of scale, published 2026 figures put the average foundation repair near fifty two hundred with a typical range of about twenty two hundred to eighty one hundred, piers at one to three thousand each, mud-jacking a slab at roughly five hundred fifty to thirteen hundred, wall reinforcement at four to twelve thousand, and a full lift and level above twenty thousand." },
        { carry: "Carry (national typical, late 2026): roof on 1,500 sqft $9,000–$15,000 ($300–$700 per square) | 3-ton HVAC $7,000–$12,500 | tank water heater $1,000–$2,500 | 200A panel $2,000–$4,500 | PEX repipe $5,000–$10,000 | sewer $50–$250 per lf, full run $4,000–$10,000 | vinyl window $500–$900 per opening | foundation: specialist bid only, piers $1,000–$3,000 each." },
        { trap: "Pricing a system as a repair when its age says replacement. A twenty year old condenser that still runs is a replacement on your sheet, not a zero. The appraiser may not care, but the next summer will." },
        { sources: [
          { t: "Angi, How Much Does a Shingle Roof Cost (2026)", u: "https://www.angi.com/articles/how-much-does-shingle-roof-cost.htm" },
          { t: "HomeAdvisor, Roof Replacement Cost", u: "https://www.homeadvisor.com/cost/roofing/install-a-roof/" },
          { t: "Angi, HVAC Replacement Cost (2026)", u: "https://www.angi.com/articles/insider-s-price-guide-new-heating-and-cooling-system.htm" },
          { t: "Angi, Water Heater Replacement Cost (2026)", u: "https://www.angi.com/articles/how-much-does-water-heater-installation-cost.htm" },
          { t: "Angi, Cost to Replace Electrical Panel (2026)", u: "https://www.angi.com/articles/cost-replace-circuit-breaker-box.htm" },
          { t: "Angi, Pipe Replacement Cost (2026)", u: "https://www.angi.com/articles/how-much-does-installing-or-replacing-plumbing-pipes-cost.htm" },
          { t: "Angi, Sewer Line Replacement Cost (2026)", u: "https://www.angi.com/articles/how-much-does-sewer-line-replacement-or-repair-cost.htm" },
          { t: "Angi, Window Replacement Cost (2026)", u: "https://www.angi.com/articles/how-much-does-window-replacement-cost.htm" },
          { t: "This Old House (Angi data), Foundation Repair Cost (2026)", u: "https://www.thisoldhouse.com/foundations/foundation-repair-cost" }
        ] }
      ]
    },
    {
      id: "m05-04",
      title: "Interior Line Items",
      minutes: 10,
      blocks: [
        { h: "Kitchen, rental grade", p: "A rental kitchen is stock cabinets, a laminate or prefab stone counter, a basic stainless or white appliance package, a drop-in sink, and a single-handle faucet. Angi's 2026 data puts stock cabinets at about one hundred to three hundred dollars per linear foot, countertop installation at eighteen hundred to forty four hundred on average, a sink install near four hundred twenty and a faucet near two hundred sixty. A minor kitchen remodel that keeps the layout runs roughly ten to twenty thousand nationally, while the average full remodel is near twenty seven thousand, which is retail grade and not your number. Keep the layout. Moving plumbing or walls is how a kitchen doubles." },
        { h: "Bath, rental grade", p: "A rental bath is a tub with a surround or a prefab shower, a prefab vanity with top, a standard toilet, a light bar, an exhaust fan, and LVP or tile on the floor. Angi puts a small bathroom remodel at an average of sixty five hundred and a small full bath around forty five hundred to six thousand, with a prefab vanity from about one hundred to twenty six hundred, a toilet installed from two hundred twenty five, and a shower from four hundred up. Reglazing a sound tub instead of replacing it is one of the highest-return moves in a rental rehab." },
        { h: "Flooring and paint", p: "Luxury vinyl plank, called LVP, is the rental floor: waterproof, scratch resistant, and one product for the whole house. Angi reports LVP materials at about one dollar fifty to twelve dollars per square foot and labor at one to ten, so a rental-grade installed number lands in the lower half of that. Interior paint runs about two to six dollars per square foot of floor area, averaging two seventy five for walls alone and about four seventy with trim and ceilings. One color on every wall, one white on every ceiling and trim, in every house you own." },
        { h: "Drywall, doors, trim, fixtures", p: "Drywall repair averages about six hundred per job nationally, with small holes at twenty to one hundred twenty, large holes fifty to two hundred, and water-damaged areas six hundred to fifteen hundred fifty. A prehung interior door installed runs about four hundred fifty to one thousand, and a slab door into an existing frame three to five hundred. Light fixtures, outlets, switches and cover plates are each items: price the unit and bundle them into one electrician visit. Replace every outlet and switch with new white devices in a rehab; it is cheap per unit and the whole house looks new." },
        { carry: "Carry (national typical, late 2026): rental kitchen, same layout $8,000–$15,000, stock cabinets $100–$300 per lf | bath refresh $4,500–$8,000 | LVP installed $4–$7 per sqft | paint, walls, ceilings and trim $3–$5 per sqft of floor area | drywall patch $50–$200 small, $600–$1,500 water damage | prehung door $450–$1,000 | devices and fixtures priced per each, bundled." },
        { trap: "Pricing a kitchen by looking at the finished ones online. Those are retail kitchens with moved walls. Count your linear feet of cabinet, pick stock, keep the plumbing where it is, and your number stays sane." },
        { sources: [
          { t: "Angi, Kitchen Remodel Cost (2026)", u: "https://www.angi.com/articles/how-much-should-kitchen-remodel-cost.htm" },
          { t: "Angi, Small Bathroom Remodel Cost (2026)", u: "https://www.angi.com/articles/how-much-does-it-cost-remodel-small-bathrooms-and-half-baths.htm" },
          { t: "Angi, Vinyl Flooring Installation Cost (2026)", u: "https://www.angi.com/articles/how-much-does-installing-vinyl-or-linoleum-flooring-cost.htm" },
          { t: "Angi, Cost to Paint Interior of a House (2026)", u: "https://www.angi.com/articles/how-much-does-it-cost-paint-interior-house.htm" },
          { t: "Angi, Drywall Repair Cost (2026)", u: "https://www.angi.com/articles/how-much-does-drywall-repair-cost-small-holes.htm" },
          { t: "Angi, Interior Door Installation Cost (2026)", u: "https://www.angi.com/articles/how-much-does-it-cost-install-interior-door.htm" }
        ] }
      ]
    },
    {
      id: "m05-05",
      title: "Exterior Line Items",
      minutes: 8,
      blocks: [
        { h: "Siding and stucco", p: "Exterior skin problems are priced by the square foot of damaged area, not the whole wall. Stucco repair averages about sixteen hundred thirty dollars per job nationally, typically six hundred to twenty seven hundred, at roughly eight to fifty dollars per square foot depending on depth and texture matching. Siding repair follows the same logic: find the source of the damage first, because rotten siding usually means water from a gutter, a roof edge, or grading, and the siding is the symptom. Carry the patch plus the fix for the source." },
        { h: "Gutters, soffit and fascia", p: "Gutters are linear feet. Angi's 2026 figures put installation at about four to forty dollars per linear foot, with aluminum at three to fifteen and vinyl at three to seven, and a typical whole-house job between about six hundred thirty and seventeen hundred forty. Soffit and fascia repair runs roughly three hundred to over seven thousand depending on how much is rotten, with water-damage repair at about ten to twenty three dollars per linear foot and dry-rot repair from five hundred to four thousand. Peeling fascia is a flag to look harder at the roof edge." },
        { h: "Fence, concrete, landscaping", p: "Fencing is linear feet: about six to fifty dollars per foot installed with a national average near twenty three, wood privacy at ten to forty five and chain link at eight to forty. A concrete driveway runs roughly eight to twenty dollars per square foot. Curb appeal is the cheapest appraisal and rent booster you have: mulch, trimmed shrubs, a pressure-washed walk, a painted front door and new house numbers. Price it as a lump sum because it is small, and do it last so it is fresh for photos and the appraiser." },
        { carry: "Gutters $4–$15 per lf aluminum. Fence $10–$45 per lf wood. Concrete flatwork $8–$20 per sqft. Stucco repair $8–$50 per sqft of damage. National typical, late 2026." },
        { trap: "Skipping the exterior because the appraiser walks inside. Insurers and lenders photograph the outside first. Peeling paint, missing fascia, and a bad roof edge can hold up a policy or a refinance appraisal before anyone sees your new kitchen." },
        { sources: [
          { t: "Angi, Stucco Repair Cost (2026)", u: "https://www.angi.com/articles/how-much-stucco-repair-cost.htm" },
          { t: "Angi, Gutter Installation Cost (2026)", u: "https://www.angi.com/articles/how-much-does-gutter-replacement-cost.htm" },
          { t: "Angi, Soffit and Fascia Repair Cost (2026)", u: "https://www.angi.com/articles/how-much-does-it-cost-repair-fascia-and-soffit.htm" },
          { t: "Angi, Fence Installation Cost (2026)", u: "https://www.angi.com/articles/how-much-does-fence-installation-cost.htm" },
          { t: "Angi, Concrete Driveway Cost (2026)", u: "https://www.angi.com/articles/how-much-does-concrete-driveway-cost.htm" }
        ] }
      ]
    },
    {
      id: "m05-06",
      title: "Red Flags That Kill Refinances and Insurance",
      minutes: 12,
      blocks: [
        { h: "Why these matter more than cost, starting with plumbing", p: "Most repairs are just money. The defects in this lesson are different: an insurer may refuse to write a policy, a lender may refuse to close a refinance, or the law may require a certified contractor. Any one of them can stop the R in BRRRR that stands for refinance. For each one you carry a contingency, which means a dollar amount you hold in your rehab number until an inspection or a specialist rules the problem out. If the problem is confirmed, the contingency becomes a line item. If it is ruled out, you get to lower your number. Start with plumbing. Cast iron drain lines are common in older houses and fail from the inside out; a camera inspection of the sewer and the under-slab drains is the only way to know. Carry a full sewer line replacement until a camera says otherwise. Polybutylene supply pipe, a gray plastic used in some houses from the late seventies into the mid nineties, is known for failures, and many insurers will not cover a house that has it. Carry a full repipe until a plumber confirms the supply lines are copper, CPVC or PEX." },
        { h: "Electrical red flags", p: "Certain older panel brands, including Federal Pacific Stab-Lok, Zinsco and Challenger, have a reputation among inspectors and insurers for breakers that fail to trip, and many insurers will decline or require replacement. Aluminum branch wiring, used in some houses from the mid sixties into the mid seventies for the regular fifteen and twenty amp circuits, is a known fire concern and also an insurance issue. Knob-and-tube is the very old open-wire system found in houses built before roughly the nineteen forties; most insurers will not cover it active. Read the panel label and open a few outlets with the power off, or have your electrician do it." },
        { h: "Roof, water, pests, structure", p: "A roof over fifteen to twenty years old is commonly a problem for insurers regardless of how it looks; some will insist on replacement or a roof certification before binding a policy, so carry a full replacement on any roof you cannot date. Active leaks and visible mold mean remediation plus finding the source; carry a remediation bid, not a paint number. Termites and other wood destroying organisms, called WDO, require a licensed inspection and treatment plus repair of the damaged wood. Foundation movement, meaning stair-step cracks in block, doors out of square on one side of the house, or sloping floors, requires an engineer before you write a number." },
        { h: "Asbestos and lead paint", p: "Asbestos was used in some older floor tile, mastic, popcorn ceilings, siding and duct wrap, generally in houses built before the mid nineteen eighties; disturbing it requires testing and often a licensed abatement contractor, so carry a test plus abatement for any suspect material you plan to remove. Lead paint is governed by a federal rule. The EPA's Renovation, Repair and Painting rule, called RRP, covers any paid work that disturbs paint in housing built before nineteen seventy eight. The firm doing the work must be EPA certified, must use a certified renovator and lead-safe work practices, and must give the occupants the required pamphlet. Minor work that disturbs six square feet or less of paint per interior room, or twenty square feet or less on the exterior, is exempt, but window replacement and demolition are always covered. Hiring an uncertified contractor to scrape a pre-1978 house exposes you, the owner, to serious federal penalties." },
        { carry: "Contingency to carry until ruled out (national typical, late 2026): cast iron drains $4,000–$10,000 pending camera scope | polybutylene: full PEX repipe $5,000–$10,000 | flagged panel brand: 200A replacement $2,500–$4,500 | aluminum branch or knob-and-tube: electrician rewire bid | roof over 15–20 years: full replacement $9,000–$15,000 | mold, WDO, foundation, asbestos: specialist bid, never a guess | pre-1978: assume lead; EPA RRP-certified contractor required, exempt only under 6 sqft per interior room or 20 sqft exterior, windows and demolition never exempt." },
        { trap: "Letting a seller or a handyman tell you a flagged panel or old pipe is fine because it has worked for forty years. The insurer and the lender do not care that it worked. Get the written clearance or carry the replacement. This lesson touches federal and state rules; confirm with a local real estate attorney and a licensed inspector before relying on it." },
        { sources: [
          { t: "EPA, Renovation, Repair and Painting Program: Contractors", u: "https://www.epa.gov/lead/renovation-repair-and-painting-program-contractors" },
          { t: "EPA, Lead RRP Program Rules", u: "https://www.epa.gov/lead/lead-renovation-repair-and-painting-program-rules" },
          { t: "Angi, Sewer Line Replacement Cost (2026)", u: "https://www.angi.com/articles/how-much-does-sewer-line-replacement-or-repair-cost.htm" },
          { t: "Angi, Pipe Replacement Cost (2026)", u: "https://www.angi.com/articles/how-much-does-installing-or-replacing-plumbing-pipes-cost.htm" },
          { t: "Angi, Cost to Replace Electrical Panel (2026)", u: "https://www.angi.com/articles/cost-replace-circuit-breaker-box.htm" }
        ] }
      ]
    },
    {
      id: "m05-07",
      title: "Building the Scope of Work",
      minutes: 8,
      blocks: [
        { h: "A scope is a list a stranger could build from", p: "The scope of work, called the SOW, is the document that turns your walkthrough into a contract. It is a numbered list, room by room, of exactly what gets done, in what material, to what standard. Not kitchen refresh. Instead: remove existing cabinets and counter; install fourteen linear feet of white shaker stock cabinets per attached layout; install laminate counter, color per sample; install stainless drop-in sink and single-handle faucet, model numbers attached; install four-piece stainless appliance package, models attached. If a line could be read two ways, it will be built the cheaper way and billed the expensive way." },
        { h: "Allowances and who buys materials", p: "An allowance is a dollar amount the contract sets aside for an item you have not picked yet, such as a two thousand dollar appliance allowance. Use them sparingly, because every allowance is a change order waiting to happen. Decide in writing who buys what. Many investors buy the finish materials themselves, meaning flooring, fixtures, cabinets, paint, and have the contractor supply the rough materials and labor. That keeps your rental-grade standard consistent and removes markup, but it makes you responsible for delivery timing. Either way, the scope says who buys each category." },
        { h: "Change orders and photos", p: "A change order is a written, signed addition to the scope with a price and a schedule impact, agreed before the work happens. Your contract should say that no change is paid unless it was approved in writing first. Verbal approvals on site are how a forty thousand dollar job becomes fifty five. Photograph every room before work starts, during demo when the walls are open, and after completion. Those photos settle disputes, support your insurance and appraisal, and become your marketing when you rent." },
        { carry: "Scope = numbered line items by room, material and model specified, who buys what, allowances listed, change orders only in writing, photos before, open-wall, and after." },
        { trap: "Writing a scope from memory the night after the walkthrough. Write it on site from your photos and measurements, or you will miss the things that did not seem important in the moment and discover them as change orders." },
        { example: "Line item: Bath 1. Remove existing vanity, toilet and floor. Install 30 inch prefab vanity with top, model attached. Install standard elongated toilet, model attached. Install LVP floor to match house. Install three-piece tub surround over existing tub after reglaze by owner's vendor. Install light bar and exhaust fan, models attached. Paint walls and ceiling, house colors. Owner supplies vanity, toilet, flooring, fixtures. Contractor supplies all else." }
      ]
    },
    {
      id: "m05-08",
      title: "Getting and Comparing Bids",
      minutes: 8,
      blocks: [
        { h: "Three bids, same scope, same units", p: "Send the exact same written scope to at least three contractors and ask each to price it line by line. That is the only way to compare apples to apples. If one bid is a single lump sum and the others are line items, you cannot compare them, and the lump sum is usually hiding something: either a huge margin or a misunderstanding of the work. When one bid is far below the others, it is not a bargain, it is a contractor who missed something or plans to make it up in change orders. Throw out the outlier or ask them to walk you through every line." },
        { h: "Red flags in a bid", p: "Lump sum only with no breakdown. No license number on the bid. No proof of insurance. A demand for a large deposit, sometimes a third or half of the job, before any work. Pressure to sign today. A bid written on the back of a card or by text with no scope attached. No schedule. Any of these alone is a reason to slow down; two or more is a reason to walk." },
        { h: "Verify the license and the insurance yourself", p: "Ask for the license number and look it up on the state licensing site; do not accept a photo of a card. Ask for a certificate of insurance, called a COI, that shows general liability and workers compensation, and ask the contractor's insurance agent to send it directly to you with your entity listed as certificate holder. A COI sent by the contractor can be expired or edited. Call the agent on the certificate and confirm the policy is active. If a worker is hurt on your property and the contractor has no workers comp, you may be the one getting sued." },
        { carry: "Three bids on one written scope, line items only. Verify license on the state site and get the COI direct from the agent, with you as certificate holder." },
        { state: { fl: "Florida licenses contractors through the Department of Business and Professional Regulation; verify at myfloridalicense.com. Roofing, electrical, plumbing, HVAC and general contracting require state licenses.", oh: "Ohio licenses electrical, HVAC, plumbing, hydronics and refrigeration contractors through the Ohio Construction Industry Licensing Board; general contractors and remodelers are licensed or registered locally by city or county, so check with the building department where the house sits." } },
        { trap: "Taking the lowest bid because your deal math needs it to work. If the deal only works at the lowest bid, the deal does not work. Price the middle bid, add contingency, and let the lowest bidder earn the job by explaining the gap." },
        { sources: [
          { t: "Florida DBPR License Verification", u: "https://www.myfloridalicense.com/wl11.asp" },
          { t: "Ohio Construction Industry Licensing Board", u: "https://com.ohio.gov/divisions-and-programs/industrial-compliance/boards/ohio-construction-industry-licensing-board" }
        ] }
      ]
    },
    {
      id: "m05-09",
      title: "Paying Contractors",
      minutes: 9,
      blocks: [
        { h: "Draws tied to milestones, not to dates", p: "A draw is a payment released when a defined piece of the work is complete and inspected by you. A draw schedule lists the milestones and the dollar amount for each: for example, demo and rough plumbing and electrical complete and passed inspection, then drywall and paint complete, then flooring and cabinets installed, then final punch list complete. Never tie a draw to a calendar date or to a percentage of time elapsed. You pay for finished work you have seen, period." },
        { h: "Keep the up-front money small", p: "Many investors cap the initial deposit at ten to twenty percent of the contract, a typical practice rather than a rule, and only release it when materials are actually delivered to the site or work begins. A contractor who needs half the money to start is financing their last job with your deposit. Florida has a specific statute here: when a residential contractor takes more than ten percent of the contract price up front, they must apply for necessary permits within thirty days and start work within ninety days of the permits being issued, or face a demand to refund." },
        { h: "Lien waivers, retainage, and the punch list", p: "A mechanic's lien is a legal claim a contractor or a supplier can file against your property for unpaid work, and in many states a subcontractor can lien your house even if you paid the general contractor in full. A lien waiver is a signed document saying a party has been paid for a stage and gives up the right to lien for it. Collect a conditional waiver with each draw request and an unconditional waiver once the check clears, from the general contractor and from every sub and supplier who has sent you a notice. Retainage is a portion, often around ten percent, held back from every draw and paid only after the final punch list is done. The punch list is the written list of every unfinished or defective item you find on the final walk. Nobody gets the last check until the list is empty." },
        { carry: "Deposit: 10–20% max, typical practice. Draws only on inspected milestones. Lien waiver with every draw. Retainage ~10% until punch list is complete." },
        { state: { fl: "Florida Statute 489.126: a deposit over 10% requires the contractor to apply for permits within 30 days and start within 90 days of permit issuance. Florida's construction lien law also lets subs and suppliers lien your property; respond to every Notice to Owner and collect releases.", oh: "Ohio has no statutory deposit cap for residential remodeling; your protection is the contract, the draw schedule and lien waivers under Ohio's mechanics lien statutes." } },
        { trap: "Paying the final draw to get the keys back and finish the punch list later. The punch list never gets finished once the money is gone. Hold the retainage until you have walked every room with the list in hand. Lien law varies by state; confirm with a local real estate attorney." },
        { sources: [
          { t: "Florida Statutes 489.126, Moneys received by contractors", u: "https://m.flsenate.gov/statutes/489.126" }
        ] }
      ]
    },
    {
      id: "m05-10",
      title: "Managing the Job",
      minutes: 9,
      blocks: [
        { h: "Visit cadence and weekly cost tracking", p: "Visit the job at least twice a week, unannounced at least once, and always at the moment a draw is requested. Walk the scope line by line with the list in your hand and check off what is actually done. Keep a single spreadsheet with three columns per line item: bid, paid to date, and projected final. Update it every week. The projected final is the number that matters, because it tells you today whether the job is drifting before the drift becomes a crisis. Add a running total of approved change orders at the bottom and compare it to your contingency." },
        { h: "Permits and inspections", p: "Any work that touches structure, electrical, plumbing, HVAC, roofing or windows typically requires a permit, pulled by the licensed contractor doing that trade. Unpermitted work can block your refinance appraisal, void your insurance, and come back as a code violation when you sell. Confirm the permit is pulled before the first draw, and never release a draw on rough work until the inspector has signed off. Ask for a copy of every passed inspection for your file." },
        { h: "Ten signs a contractor is burning you", p: "One, asking for the next draw before the current milestone is done. Two, materials you paid for are not on site. Three, the crew shrinks to one person or disappears for days. Four, a new change order every visit. Five, subs or suppliers call you about not being paid. Six, permits were never pulled. Seven, the schedule slips and you hear about it from the neighbor. Eight, excuses about weather or other jobs on indoor work. Nine, text-only communication that avoids anything in writing. Ten, the quality of the finished rooms gets worse as the job goes on. Two of these is a serious conversation. Three is a termination plan." },
        { h: "When and how to fire one", p: "Fire a contractor when they have stopped performing and will not cure it in writing within a short deadline you set, when they have lied about permits or payments, or when the work is unsafe. Do it by written notice under the termination clause of your contract, document the state of the work with photos and video the same day, change the locks, collect every lien waiver you can, and bring in your second-bid contractor to price the completion. Do not pay the final draw to make them go away; pay only for inspected, completed work less any cost to correct." },
        { carry: "Two visits a week. One spreadsheet: bid, paid, projected final. No draw on rough work before the inspector signs. Two warning signs is a talk; three is a termination plan." },
        { trap: "Becoming friends with your contractor and letting the paperwork slide. The best relationships survive because the contract, the draws and the waivers are boring and automatic, not because anyone trusts anyone." }
      ]
    },
    {
      id: "m05-11",
      title: "Contingency Math",
      minutes: 6,
      blocks: [
        { h: "Contingency is part of the rehab number, not a hope", p: "Contingency is the money you add to your rehab estimate for the things you did not see. It is not optional and it is not profit. A common investor rule of thumb, not a statistic, is ten to twenty percent of the estimated rehab for a cosmetic job on a house with known-good systems, and twenty to twenty five percent for an older house, a house with unknown systems, or any house where you could not get into the attic or crawlspace. Add more for red flags from lesson six until they are ruled out." },
        { h: "Apply it before the max offer, never after", p: "Your maximum allowable offer comes from the after repair value times your purchase percentage minus the rehab. The rehab that goes into that formula is the estimate plus contingency. If you compute the offer first and then try to find room for contingency, there is no room, and you have just agreed to fund your surprises out of your own pocket at the refinance. Contingency goes in the rehab line first, then the offer comes out." },
        { formula: "Rehab Budget = Estimate × (1 + Contingency %) ; then MAO = (ARV × Purchase %) − Rehab Budget" },
        { example: "Estimate $38,000 on a 1962 house with an unknown sewer line. Contingency 25%. Rehab budget = 38,000 × 1.25 = $47,500. ARV $210,000 at 70% = $147,000. MAO = 147,000 − 47,500 = $99,500. Without contingency you would have offered $109,000 and eaten the $9,500 yourself." },
        { carry: "Cosmetic, known systems: +10–20%. Older or unknown systems: +20–25%. Add to the rehab BEFORE computing the max offer. Rule of thumb, not a statistic." },
        { trap: "Spending the contingency on upgrades because the surprises did not show up by week two. The surprises show up when the walls are open and at the final inspection. Contingency stays untouched until the punch list is done; then it is your cushion at the refinance." }
      ]
    }
  ],
  cards: [
    { id: "m05-c01", type: "term", q: "What are the three parts of every contractor price?", a: "Materials, labor, and the trip charge. Bundling small tasks into one visit removes trips, which is why twelve fixtures in one visit cost far less than twelve separate visits." },
    { id: "m05-c02", type: "term", q: "What is a square in roofing?", a: "One hundred square feet of roof surface. A 1,500 sqft single-story roof with overhangs is roughly 17 to 20 squares depending on pitch." },
    { id: "m05-c03", type: "term", q: "What does lf mean on a bid?", a: "Linear feet, used for long thin items: baseboard, gutters, fence, pipe, cabinets. Example: 14 lf of stock cabinets." },
    { id: "m05-c04", type: "term", q: "What is rental grade?", a: "Durable, neutral finishes that survive tenants and rent fast: LVP floors, one paint color, stock cabinets, laminate or prefab counters, basic fixtures. Chosen for appraisal and rent, not for taste." },
    { id: "m05-c05", type: "trap", q: "Why is a lump-sum-only bid a problem?", a: "You cannot compare it to other bids or verify what is included, and disputes default to the contractor's interpretation. Require line items on anything over a few thousand dollars." },
    { id: "m05-c06", type: "term", q: "What is the walkthrough order?", a: "Outside top-down (roof to grading), then systems (panel, water heater, HVAC, water main, sewer cleanout, attic and crawl), then inside room by room in the same loop every time." },
    { id: "m05-c07", type: "term", q: "What is the source, symptom, scope habit?", a: "For every defect, find the source before you price the fix. A ceiling stain (symptom) from a roof leak (source) needs a roofer plus a patch (scope), not just paint." },
    { id: "m05-c08", type: "scenario", q: "You see a soft spot in the hallway floor. What do you do?", a: "Find the source: open the crawl or look below. Likely a drain leak. Scope becomes plumbing repair, subfloor replacement, new flooring and a rot check, not a floor patch." },
    { id: "m05-c09", type: "number", q: "Roof replacement, asphalt shingle, 1,500 sqft house: what do you carry?", a: "About $9,000–$15,000 for a full replacement; roughly $300–$700 per square installed. National typical as of late 2026. Get local quotes." },
    { id: "m05-c10", type: "number", q: "HVAC 3-ton split system replacement: what do you carry?", a: "About $7,000–$12,500 installed, ductwork extra. National typical as of late 2026." },
    { id: "m05-c11", type: "number", q: "Tank water heater installed: what do you carry?", a: "About $1,000–$2,500 for a 40 or 50 gallon tank. National typical as of late 2026." },
    { id: "m05-c12", type: "number", q: "Electrical panel upgrade to 200 amps: what do you carry?", a: "About $2,000–$4,500 including meter base and permit. National typical as of late 2026." },
    { id: "m05-c13", type: "number", q: "Whole-house PEX repipe: what do you carry?", a: "About $5,000–$10,000 for a typical single-family house. National typical as of late 2026." },
    { id: "m05-c14", type: "number", q: "Sewer line replacement: what do you carry?", a: "About $50–$250 per linear foot, roughly $4,000–$10,000 for a full run from house to street. National typical as of late 2026." },
    { id: "m05-c15", type: "number", q: "Replacement vinyl window, rental grade: what do you carry per opening?", a: "About $500–$900 installed per opening. National typical as of late 2026." },
    { id: "m05-c16", type: "number", q: "Foundation piers: what do they run?", a: "About $1,000–$3,000 per pier; a full lift and level can exceed $20,000. Never estimate foundation yourself; carry a specialist bid. National typical as of late 2026." },
    { id: "m05-c17", type: "number", q: "Rental kitchen, same layout, all in: what do you carry?", a: "About $8,000–$15,000 with stock cabinets at $100–$300 per lf, laminate or prefab counter, and a basic appliance package. National typical as of late 2026." },
    { id: "m05-c18", type: "number", q: "Rental bath refresh: what do you carry?", a: "About $4,500–$8,000 for tub surround or prefab shower, prefab vanity, toilet, floor and paint. National typical as of late 2026." },
    { id: "m05-c19", type: "number", q: "LVP flooring installed per sqft?", a: "Carry about $4–$7 per sqft installed for rental grade. National typical as of late 2026." },
    { id: "m05-c20", type: "number", q: "Interior paint per sqft of floor area?", a: "Carry about $3–$5 per sqft for walls, ceilings and trim. National typical as of late 2026." },
    { id: "m05-c21", type: "number", q: "Prehung interior door installed?", a: "About $450–$1,000 each; a slab into an existing frame is $300–$500. National typical as of late 2026." },
    { id: "m05-c22", type: "number", q: "Drywall repair numbers to know?", a: "Small holes $20–$120, large holes $50–$200, water-damaged area $600–$1,550. National typical as of late 2026." },
    { id: "m05-c23", type: "number", q: "Aluminum gutters per linear foot?", a: "About $3–$15 per lf installed; a whole house typically $630–$1,740. National typical as of late 2026." },
    { id: "m05-c24", type: "number", q: "Wood privacy fence per linear foot?", a: "About $10–$45 per lf installed. National typical as of late 2026." },
    { id: "m05-c25", type: "number", q: "Concrete flatwork per square foot?", a: "About $8–$20 per sqft for a driveway or walk. National typical as of late 2026." },
    { id: "m05-c26", type: "number", q: "Stucco repair per square foot of damage?", a: "About $8–$50 per sqft, with a typical job $600–$2,700. National typical as of late 2026." },
    { id: "m05-c27", type: "trap", q: "The seller says the 22-year-old AC runs fine. How do you price it?", a: "As a full replacement. Age governs, not whether it ran today. Carry $7,000–$12,500 and let the refinance appraisal and next summer prove you right." },
    { id: "m05-c28", type: "term", q: "What is cast iron drain risk and how do you clear it?", a: "Old cast iron drains fail from the inside. Only a camera scope of the sewer and under-slab drains clears it. Carry $4,000–$10,000 until the scope is clean." },
    { id: "m05-c29", type: "term", q: "What is polybutylene and why does it matter?", a: "Gray plastic supply pipe used roughly late 1970s to mid 1990s with a failure history; many insurers will not cover it. Carry a full PEX repipe until ruled out." },
    { id: "m05-c30", type: "number", q: "Which panel brands are insurance red flags?", a: "Federal Pacific Stab-Lok, Zinsco and Challenger are the names inspectors and insurers flag. Carry $2,500–$4,500 for a 200A replacement when you see one." },
    { id: "m05-c31", type: "term", q: "What is aluminum branch wiring?", a: "Aluminum wire used for ordinary 15 and 20 amp circuits in some mid-1960s to mid-1970s houses; a fire and insurance concern. Get an electrician's rewire or remediation bid before offering." },
    { id: "m05-c32", type: "term", q: "What is knob-and-tube?", a: "Open single-conductor wiring on ceramic knobs, found in houses from before roughly the 1940s. Most insurers will not cover it active. Carry a rewire bid." },
    { id: "m05-c33", type: "number", q: "At what roof age do insurers commonly push back?", a: "Roughly 15–20 years for asphalt shingles; many require replacement or a certification to bind. Carry a full replacement on any roof you cannot date." },
    { id: "m05-c34", type: "term", q: "What does WDO mean?", a: "Wood destroying organisms: termites and similar pests. Requires a licensed inspection, treatment, and repair of damaged wood. Carry a specialist bid." },
    { id: "m05-c35", type: "number", q: "Lead paint: what year and what rule?", a: "Housing built before 1978 is assumed to contain lead paint. The EPA RRP rule requires any paid contractor disturbing paint to be EPA certified and use lead-safe practices." },
    { id: "m05-c36", type: "number", q: "RRP exemption thresholds?", a: "Minor work disturbing 6 sqft or less of paint per interior room, or 20 sqft or less on the exterior, is exempt. Window replacement and demolition are never exempt." },
    { id: "m05-c37", type: "trap", q: "A handyman offers to scrape and paint your 1965 house cheap and says lead rules do not apply to small guys.", a: "Wrong. The RRP rule applies to anyone paid to disturb paint in pre-1978 housing, including sole proprietors. Hire an EPA-certified firm or you carry the federal exposure." },
    { id: "m05-c38", type: "term", q: "What is asbestos risk in a rehab?", a: "Older floor tile and mastic, popcorn ceilings, siding and duct wrap, generally pre-mid-1980s, may contain asbestos. Test before disturbing; abatement often requires a licensed contractor." },
    { id: "m05-c39", type: "scenario", q: "Stair-step cracks in the block, doors out of square on one side, sloping floor. What do you do?", a: "Those are foundation movement symptoms. Do not estimate. Order a structural engineer report before you write an offer, and carry a specialist bid as your number." },
    { id: "m05-c40", type: "term", q: "What is a scope of work?", a: "A numbered, room-by-room list of exactly what gets done, in what material and model, to what standard, and who buys what. A stranger should be able to build from it." },
    { id: "m05-c41", type: "term", q: "What is an allowance in a contract?", a: "A dollar amount set aside for an item not yet chosen, like a $2,000 appliance allowance. Use sparingly; every allowance is a change order waiting to happen." },
    { id: "m05-c42", type: "term", q: "What is a change order?", a: "A written, signed addition to the scope with a price and schedule impact, approved before the work happens. Your contract should pay no change that was not approved in writing first." },
    { id: "m05-c43", type: "trap", q: "Why do verbal approvals on site cost so much?", a: "They have no price attached and no record. A $40,000 job becomes $55,000 one friendly yes at a time. Say: write it up and I will sign it tonight." },
    { id: "m05-c44", type: "term", q: "What are the three photo sets you take on every rehab?", a: "Before work starts, during demo with the walls open, and after completion. They settle disputes, support insurance and appraisal, and become your rental marketing." },
    { id: "m05-c45", type: "number", q: "How many bids and on what?", a: "At least three, on the identical written scope, priced line by line. Any bid that cannot be laid side by side with the others is not a bid." },
    { id: "m05-c46", type: "trap", q: "One bid comes in 40% below the other two. What is it?", a: "A contractor who missed something or plans to recover it with change orders. Ask them to walk every line, or throw it out and price the middle bid." },
    { id: "m05-c47", type: "term", q: "What is a COI and how do you get it?", a: "Certificate of insurance showing general liability and workers compensation. Have the contractor's agent send it directly to you with your entity as certificate holder, then call the agent to confirm it is active." },
    { id: "m05-c48", type: "trap", q: "Contractor texts you a photo of his license card. Good enough?", a: "No. Look the number up on the state licensing site yourself. Cards are easy to fake or expire. Unlicensed work can block permits, insurance and your refinance." },
    { id: "m05-c49", type: "state", q: "Where do you verify a contractor license?", a: "FL: Department of Business and Professional Regulation at myfloridalicense.com; roofing, electrical, plumbing, HVAC and GC are state licensed. | OH: Electrical, HVAC, plumbing, hydronics and refrigeration through the Ohio Construction Industry Licensing Board; general contractors are licensed or registered by the local city or county." },
    { id: "m05-c50", type: "term", q: "What is a draw schedule?", a: "A list of payment milestones tied to completed, inspected work: for example rough-in passed, drywall and paint done, floors and cabinets in, punch list complete. Never tied to dates." },
    { id: "m05-c51", type: "number", q: "How much deposit up front?", a: "Typical investor practice caps it at 10–20% of the contract, released when materials hit the site or work starts. This is practice, not law, except where a state statute adds rules." },
    { id: "m05-c52", type: "state", q: "What happens when a contractor takes a big deposit?", a: "FL: Under Statute 489.126, a deposit over 10% requires the contractor to apply for permits within 30 days and start within 90 days of permit issuance or face a refund demand. | OH: No statutory deposit cap for residential remodeling; your protection is the contract, the draw schedule and lien waivers." },
    { id: "m05-c53", type: "term", q: "What is a mechanic's lien?", a: "A legal claim a contractor, sub or supplier can file against your property for unpaid work. In many states a sub can lien you even if you paid the general in full." },
    { id: "m05-c54", type: "term", q: "What is a lien waiver and when do you collect it?", a: "A signed release of lien rights for a paid stage. Collect a conditional waiver with each draw request and an unconditional waiver once the payment clears, from the general and every sub and supplier." },
    { id: "m05-c55", type: "term", q: "What is retainage?", a: "A portion, often about 10%, held back from every draw and paid only after the final punch list is complete. It is the only leverage you have at the end." },
    { id: "m05-c56", type: "term", q: "What is a punch list?", a: "The written list of every unfinished or defective item found on the final walkthrough. Nobody gets the last check until the list is empty." },
    { id: "m05-c57", type: "trap", q: "Contractor asks for the final draw now and promises to finish the punch list next week.", a: "No. The punch list never gets done once the money is gone. Walk every room with the list, then release retainage only when it is empty." },
    { id: "m05-c58", type: "number", q: "How often do you visit the job?", a: "At least twice a week, once unannounced, and always when a draw is requested. Walk the scope line by line with the list in hand." },
    { id: "m05-c59", type: "term", q: "What three columns does your cost tracker need per line item?", a: "Bid, paid to date, and projected final. Projected final is the number that tells you today whether the job is drifting." },
    { id: "m05-c60", type: "trap", q: "Why never release a rough-in draw before the inspection?", a: "Once drywall covers the work, nobody can verify it. Failed rough inspections after cover mean tearing out finished walls at your expense. Inspector signs first, then you pay." },
    { id: "m05-c61", type: "scenario", q: "A supplier calls asking why they have not been paid for your cabinets. You already paid the contractor's draw.", a: "Red flag and lien risk. Stop all draws, demand paid receipts and lien waivers from every sub and supplier, and consider paying suppliers directly with joint checks going forward." },
    { id: "m05-c62", type: "scenario", q: "The crew has shrunk to one guy, materials you paid for are not on site, and a new change order appears every visit.", a: "That is three warning signs. Issue a written cure notice with a short deadline under your contract, photograph everything, and line up your second-bid contractor to price completion." },
    { id: "m05-c63", type: "scenario", q: "You decide to fire the contractor. What is the sequence?", a: "Written termination notice per the contract, same-day photos and video of the job state, change the locks, collect all lien waivers you can, bring in the second bidder, and pay only for inspected completed work less cost to correct." },
    { id: "m05-c64", type: "formula", q: "How do you build the rehab budget and max offer?", a: "Rehab Budget = Estimate × (1 + Contingency %), then MAO = (ARV × Purchase %) − Rehab Budget. Example: $38,000 × 1.25 = $47,500; $210,000 × 0.70 − $47,500 = $99,500." },
    { id: "m05-c65", type: "number", q: "Contingency percentages to carry?", a: "Rule of thumb: 10–20% for cosmetic work on known-good systems; 20–25% for older houses, unknown systems, or no attic or crawl access. Add more for unresolved red flags." },
    { id: "m05-c66", type: "trap", q: "You computed your offer, then realized you forgot contingency. What now?", a: "Lower the offer. Contingency goes into the rehab number before the MAO formula, never squeezed in after. If the deal only works without contingency, it does not work." },
    { id: "m05-c67", type: "trap", q: "Week two, no surprises yet, and you want to upgrade the counters with the contingency.", a: "Do not. Surprises appear when walls are open and at final inspection. Contingency stays untouched until the punch list is done, then it is your cushion at the refinance." },
    { id: "m05-c68", type: "scenario", q: "Rehab estimate $30,000 on a 1958 house, cast iron drains not yet scoped, panel is a flagged brand. What is your rehab budget?", a: "Add 25% contingency for age and unknowns: $37,500. Keep the sewer and panel contingencies inside that number until the camera scope and electrician clear or confirm them." }
  ],
  quiz: [
    { id: "m05-q01", q: "A contractor quotes $150 to swap one light fixture. You have twelve to swap. The best move is to:", opts: ["Pay $1,800 and move on","Hire twelve different handymen","Skip the fixtures","Bundle all twelve into one visit to eliminate repeated trip charges"], correct: 3, explain: "Every price is materials plus labor plus the trip. Bundling removes trips, which dominate small-job pricing." },
    { id: "m05-q02", q: "A roofing square equals:", opts: ["1 square foot", "10 square feet", "100 square feet", "1,000 square feet"], correct: 2, explain: "A square is 100 sqft of roof surface. A 1,500 sqft single-story roof is roughly 17 to 20 squares." },
    { id: "m05-q03", q: "What is the correct walkthrough order?", opts: ["Outside top-down, then systems, then inside room by room","Kitchen, baths, then outside","Systems first, then whatever looks worst","Inside first because that is what the appraiser sees"], correct: 0, explain: "Do the boring expensive stuff first while judgment is fresh: outside top-down, systems, then rooms in the same loop every time." },
    { id: "m05-q04", q: "A water stain on a ceiling is a:", opts: ["Source","Scope","Symptom","Change order"], correct: 2, explain: "The stain is the symptom. The source could be roof, plumbing or an old overflow, and each has a completely different scope." },
    { id: "m05-q05", q: "National typical range to carry for a full asphalt roof on a 1,500 sqft house, late 2026:", opts: ["$2,000–$4,000","$30,000–$40,000","$500–$700 total","$9,000–$15,000"], correct: 3, explain: "Published 2026 guides put installed asphalt at roughly $300–$700 per square, landing a 1,500 sqft house around $9,000–$15,000. Get local quotes." },
    { id: "m05-q06", q: "A 3-ton HVAC split system replacement, national typical late 2026, is closest to:", opts: ["$1,000–$2,000", "$3,000 installed", "$7,000–$12,500", "$25,000+"], correct: 2, explain: "Equipment alone is around $3,000 but installed systems typically run $5,000–$12,500; ductwork is extra." },
    { id: "m05-q07", q: "A full PEX repipe of a single-family house typically runs:", opts: ["$5,000–$10,000","$500–$1,000","$25,000–$40,000","Under $300 per fixture"], correct: 0, explain: "Angi's 2026 range is $1,500–$15,000 with an average near $7,500; carry $5,000–$10,000 for a typical house." },
    { id: "m05-q08", q: "Which finish choice is rental grade?", opts: ["Custom wood cabinets with quartz", "Designer tile and three accent colors", "LVP floors, one neutral color, stock cabinets, laminate counter", "Hardwood and specialty lighting"], correct: 2, explain: "Rental grade is durable and neutral; it appraises and rents without costing more than the appraiser gives back." },
    { id: "m05-q09", q: "Before disturbing paint in a 1970 house, the contractor must:", opts: ["Nothing special; the rule only applies to schools","Only wear a dust mask","Be EPA RRP certified and use lead-safe practices","Get the tenant's verbal OK"], correct: 2, explain: "The EPA RRP rule covers paid work disturbing paint in pre-1978 housing. Firm certification and lead-safe practices are required." },
    { id: "m05-q10", q: "Which job is NEVER exempt from the RRP rule regardless of square footage?", opts: ["Patching a 2 sqft hole","Touching up a door frame","Caulking a 1 lf crack","Window replacement"], correct: 3, explain: "Minor work under 6 sqft per interior room or 20 sqft exterior is exempt, but window replacement and demolition are always covered." },
    { id: "m05-q11", q: "You find a Federal Pacific panel. The seller says it has worked for 40 years. You should:", opts: ["Carry a 200A panel replacement, about $2,500–$4,500, in your rehab","Accept it; it works","Ask the seller to sign a note saying it is fine","Ignore it because the appraiser will not notice"], correct: 0, explain: "Insurers and lenders flag these brands regardless of function. Carry the replacement or get written clearance." },
    { id: "m05-q12", q: "The only way to clear cast iron drain risk is:", opts: ["Run the faucets and watch","Ask the neighbor","Check the water heater date","A camera scope of the sewer and under-slab drains"], correct: 3, explain: "Cast iron fails from the inside out. Carry $4,000–$10,000 until a camera says the lines are sound." },
    { id: "m05-q13", q: "A good scope of work line reads:", opts: ["Refresh kitchen", "Make bathroom nice", "Install 30 inch prefab vanity with top, model attached; owner supplies", "Fix whatever is wrong"], correct: 2, explain: "A scope specifies material, model, standard and who buys. Anything that can be read two ways will be built cheap and billed expensive." },
    { id: "m05-q14", q: "Your contract should state that change orders are paid:", opts: ["Whenever the contractor says the work was needed","At the end of the job as a lump sum","Only if approved in writing before the work happens","Never"], correct: 2, explain: "Verbal site approvals have no price and no record. Writing first is how you keep a $40,000 job from becoming $55,000." },
    { id: "m05-q15", q: "Three bids: $42,000 line-itemed, $45,000 line-itemed, $26,000 lump sum. Best move:", opts: ["Take the $26,000; it saves $16,000", "Price the middle bid plus contingency and make the low bidder explain every line", "Average all three", "Take the highest to be safe"], correct: 1, explain: "A far-low lump sum signals missed scope or planned change orders. If the deal only works at the low bid, it does not work." },
    { id: "m05-q16", q: "The right way to get a certificate of insurance is:", opts: ["Directly from the contractor's insurance agent with you named as certificate holder, then call to confirm","A photo from the contractor's phone","Trust the license lookup; it covers insurance","Ask for it after the job"], correct: 0, explain: "A contractor-supplied COI can be expired or edited. Agent-direct plus a phone call confirms it is active." },
    { id: "m05-q17", q: "Draws should be released based on:", opts: ["Calendar dates in the contract", "Percentage of time elapsed", "Completed, inspected milestones", "The contractor's cash needs"], correct: 2, explain: "You pay for finished work you have seen. Dates and time elapsed pay for promises." },
    { id: "m05-q18", q: "In Florida, a contractor who takes more than 10% up front must apply for permits within:", opts: ["7 days","90 days","There is no requirement","30 days"], correct: 3, explain: "Florida Statute 489.126: permits applied for within 30 days of payment and work started within 90 days of permit issuance." },
    { id: "m05-q19", q: "A lien waiver protects you by:", opts: ["Guaranteeing the work quality","Replacing the need for permits","Releasing a party's right to lien your property for a paid stage","Lowering your insurance premium"], correct: 2, explain: "Collect conditional waivers with draw requests and unconditional waivers after payment clears, from the general and every sub and supplier." },
    { id: "m05-q20", q: "Retainage is typically:", opts: ["About 10% held from each draw until the punch list is complete","Paid up front as a deposit","A fee the contractor charges you","Only used on commercial jobs"], correct: 0, explain: "Retainage is your last leverage. The punch list never gets finished once all the money is gone." },
    { id: "m05-q21", q: "A rough electrical draw is requested. Drywall is scheduled tomorrow. The inspection has not happened. You:", opts: ["Pay; the schedule matters", "Refuse the draw until the inspector signs off", "Pay half", "Pay and inspect it yourself"], correct: 1, explain: "Once covered, rough work cannot be verified, and a failed inspection means tearing out finished walls at your cost." },
    { id: "m05-q22", q: "Estimate $38,000, older house with unknown sewer, ARV $210,000 at 70%. Using 25% contingency, your MAO is:", opts: ["$109,000","$147,000","$89,000","$99,500"], correct: 3, explain: "Rehab budget = 38,000 × 1.25 = 47,500. MAO = 147,000 − 47,500 = $99,500. Contingency goes in before the offer." },
    { id: "m05-q23", q: "Contingency rule of thumb for a cosmetic job with known-good systems:", opts: ["0%","40–50%","10–20%","100%"], correct: 2, explain: "Cosmetic with known systems: 10–20%. Older or unknown systems: 20–25%. Add more for unresolved red flags." },
    { id: "m05-q24", q: "How many of the ten warning signs should trigger a termination plan?", opts: ["Three","One","Seven","All ten"], correct: 0, explain: "Two warning signs is a serious conversation; three is a termination plan with a written cure notice and a backup contractor." }
  ],
  drills: [
    "Walk one house (yours, a friend's, or a listing with an open house) in the exact order: outside top-down, systems, rooms. Photograph the panel label, HVAC data plate and water heater sticker. Price the whole thing in 20 minutes using the carry numbers.",
    "Call three contractors in your target market and ask for their license numbers and who their insurance agent is. Look up every license on the state site before you hang up.",
    "Write a one-page rental-grade finish standard: your one paint color, one trim white, one LVP product, one cabinet line, one faucet, one light fixture. Save it; it goes in every scope you ever write.",
    "Take a photo of any ceiling stain, cracked wall or soft floor you can find this week and write source, symptom, scope under each.",
    "Build your cost tracker: one sheet, one row per scope line, three columns (bid, paid, projected final), a change-order total, and a contingency line. Fill it with a pretend $40,000 job.",
    "Pull up the EPA RRP contractor page and find the search tool for certified firms in your area. Save three names.",
    "Compute MAO on a real listing: estimate the rehab from photos, add 20–25% contingency, apply ARV × 70%, and compare your number to the list price."
  ]
});
