BIBLE.register({
  id: "m06",
  part: 2,
  title: "Landlording & Property Management",
  icon: "🔑",
  summary: "How to set rent, find and screen a tenant legally, write a lease that holds up, run maintenance and collections as systems, and decide when to hand the keys to a property manager.",
  minutes: 90,
  lessons: [
    {
      id: "m06-01",
      title: "Setting the Rent",
      minutes: 9,
      blocks: [
        { h: "Rent comes from comps, not from your mortgage", p: "Market rent is what tenants are paying right now for similar houses nearby. It has nothing to do with what your payment is. To find it, pull at least three rentals within about a mile that match your bedroom and bath count, square footage within a few hundred feet, and condition, that were leased in the last few months. Listing prices are asks; leased prices are facts. Call a local property manager and ask what they would list it for. Drive the comps. Then price at or slightly below the middle of the range, because a vacant month costs more than ten dollars a month of extra rent ever recovers." },
        { h: "Rent-to-price as a screening ratio", p: "Rent-to-price is monthly rent divided by total cost in the property, purchase plus rehab. If a house costs you one hundred fifty thousand all in and rents for fifteen hundred, rent-to-price is one percent. It is a quick filter, not a decision tool: it ignores taxes, insurance and rates. Use it to sort a list of candidates in thirty seconds, then run the real numbers on the ones that pass. Whatever ratio your market produces, know it, so you can spot a deal that is above it." },
        { formula: "Rent-to-price = Monthly rent ÷ (Purchase + Rehab). Example: $1,450 ÷ $145,000 = 1.0%" },
        { h: "What the appraiser's rent schedule looks at", p: "When you refinance, the lender usually orders a Single-Family Comparable Rent Schedule, Fannie Mae Form 1007, along with the appraisal. The appraiser picks three rental comparables and adjusts each one for rent concessions, location and view, design and appeal, age and condition, room and bedroom count, gross living area, and other features such as a basement or garage, then reports an indicated market rent. That number, not your lease, is often what the lender uses for the debt service coverage test. So document your comps the same way the appraiser will, and if your lease is above the schedule, be ready to show why." },
        { carry: "Three leased comps within a mile, same beds and baths, last few months. Price at or just under the middle. Form 1007 adjusts for concessions, location, condition, rooms, square footage and features." },
        { trap: "Pricing to your payment. If the market says $1,400 and your payment needs $1,600, the house sits vacant at $1,600 and you lose $1,400 a month proving a point. The fix was in the purchase price, not the rent." },
        { sources: [
          { t: "Fannie Mae Form 1007, Single-Family Comparable Rent Schedule", u: "https://singlefamily.fanniemae.com/media/12351/display" }
        ] }
      ]
    },
    {
      id: "m06-02",
      title: "Marketing the Unit and Showings",
      minutes: 7,
      blocks: [
        { h: "Photos and the listing", p: "Take photos in daylight with every light on, after the cleaners leave, from the corners of each room at chest height. Lead with the exterior, then kitchen, then living room, then baths and bedrooms. Your listing text states beds, baths, square footage, rent, deposit, lease length, pet policy, utilities the tenant pays, parking, laundry, and the application steps and fee. Say what your screening criteria are in plain language so unqualified applicants screen themselves out. Post on the major rental sites through one syndication tool so you answer one inbox, not six." },
        { h: "Pre-screen before you drive", p: "Before any showing, ask every inquiry the same short list by text or form: desired move-in date, number of occupants, pets, monthly gross income, and whether anyone on the lease has an eviction filing. Ask every person the same questions in the same order. Anyone who meets your written criteria gets a showing. Anyone who does not gets a polite, identical message stating that they do not meet the posted requirements. Group showings, where several prospects see the house in the same hour, save you trips and create urgency." },
        { h: "Showings and safety", p: "Meet at the property, never alone at night, and tell your partner where you are. Use a lockbox with a code you change after each leasing cycle. Walk the prospect through, answer questions, and hand them the application link on the spot. Do not negotiate rent on the porch; the price is the price, and the first qualified complete application wins." },
        { carry: "Same pre-screen questions to every inquiry, in the same order. Written criteria in the listing. First complete qualified application wins. Lockbox code changes every turnover." },
        { trap: "Chatting instead of screening. Friendly conversation about where someone is from, their family, or their church is how fair housing complaints start. Stick to the house and the written criteria." }
      ]
    },
    {
      id: "m06-03",
      title: "Screening and Fair Housing",
      minutes: 12,
      blocks: [
        { h: "The federal protected classes", p: "The federal Fair Housing Act makes it illegal to refuse to rent, set different terms, advertise a preference, or treat anyone differently in housing because of race, color, national origin, religion, sex, familial status or disability. Familial status means having children under eighteen, being pregnant, or being in the process of adopting; you cannot refuse families with kids or steer them to certain units. Disability includes an obligation to allow reasonable accommodations and modifications, which includes assistance animals that are not pets under your pet policy. Many states and cities add classes such as source of income, age, marital status or sexual orientation, so check your state and local law too." },
        { h: "Written criteria, applied the same way every time", p: "Your defense against a discrimination claim is a written screening standard that you apply identically to every applicant, in the order applications are completed. A common industry standard, not a law, is gross monthly income of at least three times the rent, verified by pay stubs, offer letter or bank statements. Add a minimum credit score or a rule about collections and recent bankruptcies, verifiable rental history with no evictions in a set number of years, and photo identification matching the applicant. Write it down, post it in the listing, and never make an exception, because an exception for one person is evidence against you with the next." },
        { h: "Criminal history: HUD's guidance", p: "In April 2016 HUD issued guidance saying that a blanket ban on anyone with a criminal record is likely to violate the Fair Housing Act because of its disparate impact on protected groups, even if you never intend to discriminate. Denying someone based only on an arrest, with no conviction, cannot be justified. Convictions can be considered, but your policy should distinguish by the nature and severity of the offense and how long ago it happened, and should allow an individualized look rather than an automatic no. Write a specific, narrow criminal history standard, apply it to everyone, and keep notes on every decision." },
        { carry: "Seven federal classes: race, color, national origin, religion, sex, familial status, disability. Written criteria, same order, no exceptions. No blanket criminal bans; never deny on arrest alone." },
        { trap: "Verbal exceptions. You like one applicant and waive the income rule; the next applicant you deny on income is a protected-class member. Your waiver is now their evidence. Write it, post it, follow it." },
        { p: "Fair housing law is enforced federally, by states and by cities. Confirm your criteria with a local real estate attorney before you use them." },
        { sources: [
          { t: "HUD, Housing Discrimination Under the Fair Housing Act", u: "https://www.hud.gov/helping-americans/fair-housing-act-overview" },
          { t: "Fair Housing Project summary of HUD April 2016 criminal history guidance", u: "https://www.fairhousingnc.org/2016/hud-issues-guidance-on-criminal-history-and-fair-housing/" }
        ] }
      ]
    },
    {
      id: "m06-04",
      title: "The Lease",
      minutes: 9,
      blocks: [
        { h: "Use your state's standard form, then add your rules", p: "Start with a lease written for your state by a landlord association or a real estate attorney, because the required disclosures and the language a judge expects differ by state. Then add your house rules as an addendum. The essential clauses are: the parties and every adult occupant named, the term and the exact dates, the rent amount, due date and how it is paid, the late fee and when it starts, the security deposit amount and where it is held, who pays which utilities, the pet policy and any pet fee or rent, who handles which maintenance, the landlord entry notice rule, the rules for guests and subletting, the renewal and notice-to-vacate terms, and the required lead paint disclosure for any pre-1978 house." },
        { h: "Late fees, pets, maintenance", p: "Set the late fee as a fixed amount or a percentage that starts after a short grace period, and write exactly when it is charged. Some states cap late fees, so check your statute. Decide your pet policy before you list: allowed with a fee or monthly pet rent and a size or count limit, or not allowed. Assistance animals for a disability are not pets and cannot be charged pet fees. For maintenance, the lease should make the tenant responsible for light bulbs, smoke detector batteries, filters, drain clogs they cause, lawn care if you choose, and prompt reporting of leaks, while you remain responsible for the systems and the structure." },
        { h: "Entry notice", p: "You own the house, but the tenant has the right to possess it. Your lease and your state law require you to give advance notice before entering for repairs or inspections except in an emergency. Write the rule into the lease, then follow it every single time, because an entry without notice can be a defense to your eviction later." },
        { carry: "State-specific form plus addendum. Name every adult. Rent, due date, late fee trigger, deposit, utilities, pets, maintenance split, entry notice, renewal terms, lead disclosure if pre-1978." },
        { state: { fl: "Florida Statute 83.53 requires at least 24 hours notice before entering for repairs, between 7:30 a.m. and 8:00 p.m. Florida has no statutory late fee cap, but the fee must be stated in the lease.", oh: "Ohio Revised Code 5321.04 requires reasonable notice before entry and treats 24 hours as presumed reasonable. Ohio has no statutory late fee cap; courts look at whether the fee is reasonable." } },
        { trap: "Downloading a free generic lease. Missing a state-required disclosure or using a clause your state voids can cost you the whole case in eviction court. Pay for the right form once, and confirm your lease with a local real estate attorney; lease law is state law." },
        { sources: [
          { t: "Florida Statutes 83.53, Landlord's access to dwelling unit", u: "https://www.flsenate.gov/Laws/Statutes/2024/83.53" },
          { t: "Ohio Revised Code 5321.04, Landlord obligations", u: "https://codes.ohio.gov/ohio-revised-code/section-5321.04" },
          { t: "EPA, Lead disclosure for rentals of pre-1978 housing", u: "https://www.epa.gov/lead/lead-renovation-repair-and-painting-program-rules" }
        ] }
      ]
    },
    {
      id: "m06-05",
      title: "Condition Reports and Security Deposits",
      minutes: 10,
      blocks: [
        { h: "Move-in and move-out condition reports", p: "A condition report is a room-by-room checklist of the state of every surface, fixture and appliance, signed by you and the tenant at move-in and again at move-out. Pair it with dated photos or a walkthrough video of every room, every closet, inside the oven and under the sinks. At move-out, walk the same list in the same order and photograph everything again. The difference between the two reports, minus normal wear and tear, is what you may deduct from the deposit. Without the move-in report you have no baseline, and in a dispute the tenant wins." },
        { h: "Deposits: follow your state statute exactly", p: "There is no federal security deposit law. Every state sets its own rules on how much you can collect, whether it must sit in a separate account, whether it earns interest, how many days you have to return it, and what your itemized deduction notice must say. Missing the deadline or the format usually means you forfeit the right to deduct anything, and some states add penalties on top. Put the return deadline on your calendar the day the tenant gives notice. Deduct only for damage beyond normal wear, unpaid rent and charges the lease allows, with receipts, and send the itemized statement by the method your statute requires." },
        { carry: "Signed, photographed condition report at move-in and move-out. Deposit rules are state law: know your deadline, your notice format and your account rules, and calendar the deadline the day notice is given." },
        { state: { fl: "Florida Statute 83.49: return the full deposit within 15 days after the tenancy ends if you make no claim; to claim any part, send written notice of intent by certified mail or email within 30 days, and the tenant has 15 days to object. Miss the 30 days and you forfeit the right to deduct.", oh: "Ohio Revised Code 5321.16: return the deposit with an itemized written list of deductions within 30 days after termination, to the forwarding address the tenant provides. Deposits over $50 or one month's rent earn 5% annual interest once the tenant has stayed six months or more. Wrongful withholding exposes you to double damages plus attorney fees." } },
        { trap: "Treating the deposit as your money. In Florida, deducting carpet cleaning without sending the certified notice inside 30 days means you return every dollar and can still be sued. In Ohio, wrongful withholding is doubled plus attorney fees." },
        { p: "Deposit rules are strictly enforced. Confirm with a local real estate attorney and read your state statute yourself." },
        { sources: [
          { t: "Florida Statutes 83.49, Deposit money or advance rent", u: "https://www.flsenate.gov/Laws/Statutes/2025/83.49" },
          { t: "Ohio Revised Code 5321.16, Security deposits", u: "https://codes.ohio.gov/ohio-revised-code/section-5321.16" }
        ] }
      ]
    },
    {
      id: "m06-06",
      title: "Maintenance as a System",
      minutes: 8,
      blocks: [
        { h: "Response times and a vendor list", p: "Decide your response standards before the first call comes. A reasonable standard many landlords use: emergencies such as no heat in winter, active flooding, sewage backup, no water or an electrical hazard get a call back within an hour and a vendor the same day; urgent items such as no hot water, a failed appliance or a non-working toilet in a one-bath house within twenty four hours; everything else within a few business days. Build a vendor list before you need it: a plumber, an electrician, an HVAC company, a handyman, an appliance tech, a locksmith and a cleaner, each with a backup. Give tenants one way to submit requests, in writing, with photos, so every request is documented." },
        { h: "Preventive schedule", p: "Preventive maintenance is cheaper than emergency maintenance and it protects the systems you just paid to replace. Twice a year, in spring and fall, have the HVAC serviced and the filter changed and have the tenant confirm the smoke and carbon monoxide detectors work. Once a year, flush the water heater, check the anode rod on a tank unit, walk the roof edges and gutters, check caulk at tubs and windows, run every faucet and flush every toilet looking for slow leaks, and test the GFCI outlets. Every lease renewal, do a full interior inspection with the same condition checklist and photos, with proper notice." },
        { h: "Who pays", p: "The lease decides. You pay for systems, structure, appliances you supplied, and anything that fails from age. The tenant pays for damage they or their guests cause, clogs from things flushed or poured, lost keys, and the small items the lease assigns them. Bill tenant-caused repairs promptly with the invoice attached. Never let a tenant arrange their own repairs on your systems; you choose the vendor, you pay the vendor, and you bill back if the lease allows." },
        { carry: "Emergency: call back within the hour, vendor same day. Urgent: 24 hours. Routine: a few business days. Spring and fall HVAC service. Annual water heater flush, roof and gutter walk, leak check. Full inspection every renewal." },
        { trap: "Ignoring a small leak report because the tenant did not follow up. A dripping supply line becomes a rotted subfloor and a mold claim. Every written request gets a written response and a closed-out date." }
      ]
    },
    {
      id: "m06-07",
      title: "Rent Collection, Late Rent, and the Eviction Mindset",
      minutes: 10,
      blocks: [
        { h: "Collect electronically and on a schedule", p: "Rent is due on the first, every month, through an online portal that records the date and amount automatically. Do not take cash, and do not take partial payments unless your lease and your attorney say how to do it, because accepting partial rent can reset the eviction clock in some states. The process when rent is late is the same every month for every tenant: a reminder on the due date, a late fee when the grace period ends, a written notice on the day your state statute allows, and a filing the day the notice expires if rent has not arrived in full. No exceptions, no favorites, no stories. Consistency is both your legal protection and your tenant's clearest signal." },
        { h: "The eviction mindset: follow the statute exactly", p: "Eviction is a court process and the court is unforgiving about procedure. The notice must contain the words your statute requires, give the exact number of days it requires, be delivered the way it requires, and be followed by a filing in the right court with the right fee. One wrong day on the notice and the judge dismisses the case; you start over and lose another month. Self-help eviction, which means changing the locks, shutting off utilities, removing doors or belongings, or threatening the tenant, is illegal in every state and turns a tenant who owes you money into a tenant who can sue you. Use an eviction attorney for your first several cases and copy their paperwork exactly." },
        { carry: "Due on the first, paid online. Same late process every month for every tenant. Notice with the exact statutory words, days and delivery. Never self-help. Attorney for the first cases." },
        { state: { fl: "Florida Statute 83.56: nonpayment requires a written 3-day notice, excluding Saturdays, Sundays and legal holidays, before filing. Other curable lease violations require a 7-day notice to cure.", oh: "Ohio Revised Code 1923.04: at least 3 days written notice before filing, and the notice must conspicuously include the statutory language telling the tenant they are being asked to leave and may seek legal assistance. Ohio has no required grace period before the notice." } },
        { trap: "Accepting half the rent on the tenth because they promised the rest Friday. In some states that payment voids your notice and restarts the clock. Decide the rule with your attorney and put it in the lease before it ever happens." },
        { p: "Eviction procedure is strictly statutory. Confirm with a local real estate attorney before serving any notice." },
        { sources: [
          { t: "Florida Statutes 83.56, Termination of rental agreement", u: "https://www.flsenate.gov/laws/statutes/2024/83.56" },
          { t: "Ohio Revised Code 1923.04, Notice; service", u: "https://codes.ohio.gov/ohio-revised-code/section-1923.04" }
        ] }
      ]
    },
    {
      id: "m06-08",
      title: "Section 8 and the Housing Choice Voucher",
      minutes: 9,
      blocks: [
        { h: "How the program works", p: "The Housing Choice Voucher program, still commonly called Section 8, is a federal rental subsidy run locally by a public housing agency, called a PHA. A voucher holder finds a unit on the open market. The PHA inspects it, checks that your rent is reasonable compared to unassisted units nearby, and signs a Housing Assistance Payment contract with you. Each month the PHA pays its share directly to you and the tenant pays the rest. The tenant's share is generally the greater of thirty percent of adjusted monthly income or ten percent of gross income, and at initial lease-up the family cannot be made to pay more than forty percent of adjusted income. The PHA's payment standard, which caps the subsidy, is set between ninety and one hundred ten percent of HUD's Fair Market Rent for the area, or at the ZIP code level where Small Area Fair Market Rents apply." },
        { h: "The inspection", p: "Your unit must pass a housing quality inspection before the contract starts and periodically afterward. HUD is moving voucher inspections from the older Housing Quality Standards to NSPIRE, the National Standards for the Physical Inspection of Real Estate, which focuses on health, safety and function; HUD's latest notice lets PHAs keep using the older standard until February 1, 2027. Common failure points are missing or dead smoke and carbon monoxide detectors, peeling paint in a pre-1978 house, missing outlet covers, non-working GFCI outlets, broken window locks, trip hazards, and a water heater without a proper relief valve discharge. A rental-grade BRRRR rehab usually passes if you fix those." },
        { h: "Pros and cons", p: "Pros: the PHA share arrives on time every month, demand for voucher-ready houses is deep in most markets, and tenants who lose a voucher for lease violations have strong incentive to comply. Cons: lease-up takes longer because of the inspection and paperwork, you cannot charge the tenant more than the approved rent, you must re-inspect, and your rent is capped by rent reasonableness and the payment standard. Some states and cities make source of income a protected class, which means you may not refuse an applicant because they hold a voucher; check your local law before you write your criteria." },
        { carry: "Tenant pays about 30% of adjusted income; PHA pays the rest up to a payment standard set at 90–110% of Fair Market Rent. Unit must pass inspection; NSPIRE replaces HQS for vouchers by February 1, 2027. Never charge a voucher tenant above the approved rent." },
        { trap: "Leaving a voucher applicant waiting while you lease to a cash applicant in a jurisdiction where source of income is protected. Know whether your state or city has a source-of-income law before you set criteria." },
        { sources: [
          { t: "HUD, HCV Guidebook: Payment Standards (June 2025)", u: "https://www.hud.gov/sites/dfiles/PIH/documents/HCV_Guidebook_Payment-Standards_June-2025_final.pdf" },
          { t: "HUD Notice PIH 2026-18, NSPIRE compliance date for HCV extended to February 1, 2027", u: "https://www.hud.gov/sites/default/files/PIH/documents/PIH-2026-18.pdf" },
          { t: "HUD, NSPIRE overview", u: "https://www.hud.gov/reac/nspire" },
          { t: "24 CFR Part 982, Housing Choice Voucher Program", u: "https://www.ecfr.gov/current/title-24/subtitle-B/chapter-IX/part-982" }
        ] }
      ]
    },
    {
      id: "m06-09",
      title: "Self-Manage or Hire, and the Math of Turnover",
      minutes: 9,
      blocks: [
        { h: "What a property manager costs", p: "A property manager, called a PM, typically charges a monthly fee of about eight to twelve percent of collected rent for long-term rentals, plus a leasing or tenant placement fee of roughly half to a full month's rent each time they fill the unit. Many also charge a lease renewal fee, a markup on repairs, and a minimum monthly fee on low-rent units. These are published industry ranges as of 2026, not rules; get written fee schedules from three local companies. On a fifteen hundred dollar rent, ten percent plus a one-month leasing fee every two years is about two hundred twelve dollars a month on average, which is real money against your cash flow." },
        { h: "When to hand it off", p: "Self-manage your first few houses if they are within an hour of you and you have the temperament to enforce rules with strangers. You will learn what good management looks like, which is the only way to judge a PM later. Hand it off when the houses are far away, when your unit count makes the phone calls a second job, when you are consistently slow on maintenance or collections, or when a partner's time is worth more than the fee. When you hire, interview as you would a contractor: ask for the fee schedule, the lease they use, their eviction count last year, how they handle after-hours calls, and the names of three owners with houses like yours." },
        { h: "Turnover and vacancy math", p: "Turnover is the most expensive event in landlording. Add up the vacant days of rent, the cleaning and paint, the carpet or floor repair, the re-key, the marketing, the leasing fee, and your time. A two-month turnover on a fifteen hundred dollar house can easily cost a quarter of a year's rent before you count anything you replaced. That is why you underwrite vacancy as a line item every month even in a year with none, why you price rent to lease fast, and why a good tenant paying slightly under market who renews every year is often worth more than a new tenant at full market." },
        { formula: "Turnover cost = (Vacant days ÷ 30 × Rent) + Make-ready + Leasing fee + Re-key and marketing. Example: rent $1,500, vacant 45 days = $2,250; paint and clean $1,200; leasing fee $1,500; re-key and ads $200 → $5,150, about 29% of a year's rent" },
        { carry: "PM: about 8–12% of rent plus 50–100% of a month to lease, 2026 typical. Underwrite vacancy every month. A renewing tenant slightly under market usually beats a turnover at full market." },
        { trap: "Raising rent to market on a good tenant and losing them over $50 a month. The $600 a year you were chasing costs $5,000 in turnover. Raise steadily and modestly; keep good tenants." },
        { sources: [
          { t: "Baselane, How Much Do Property Managers Charge (2026)", u: "https://www.baselane.com/resources/how-much-do-property-managers-charge" }
        ] }
      ]
    },
    {
      id: "m06-10",
      title: "Bookkeeping Per Property and Insurance",
      minutes: 7,
      blocks: [
        { h: "One set of books per property", p: "Every house gets its own income and expense record from the day you go under contract, even if they all sit in one entity and one bank account. Track rent, late fees and other income; and expenses by category: mortgage interest, taxes, insurance, repairs, maintenance, utilities, management, legal and professional, advertising, and capital improvements. Keep every receipt, attach it to the transaction, and reconcile against the bank statement monthly. At year end your accountant will separate repairs, which are generally deductible in the year paid, from improvements, which are generally depreciated, and will need the purchase closing statement and the rehab total to set up depreciation. If you cannot produce a per-property profit and loss in five minutes, you do not know which houses are working." },
        { h: "Landlord insurance, not homeowners", p: "A homeowners policy is written for an owner who lives in the house, and insurers can deny a claim on a rented house covered by one. A rental needs a landlord policy, commonly written on a dwelling fire form such as a DP-3, which covers the structure, your appliances and fixtures, liability for injuries on the property, and often loss of rent while the house is uninhabitable after a covered loss. Tell your agent the house is a rental, confirm the liability limit, and ask about an umbrella policy once you have more than one or two houses. If the house will sit vacant during rehab, you need a vacant or builder's risk policy for that period, because standard policies often exclude vacant properties." },
        { h: "Require renters insurance", p: "Your landlord policy does not cover the tenant's belongings, and it is not the first line of defense when the tenant's cooking fire or overflowing tub damages the house. Require renters insurance in the lease, with your entity named as an interested party so you are notified if it lapses, and collect the certificate before you hand over keys. It is inexpensive for the tenant and shifts the first layer of risk off your policy." },
        { carry: "Per-property books from day one, reconciled monthly, receipts attached. Landlord policy (DP-3 type), vacant policy during rehab, umbrella as you grow. Renters insurance required in the lease with you as interested party." },
        { trap: "Leaving the seller's homeowners policy in place during a rehab, or your own after a tenant moves in. A denied fire claim on a leveraged BRRRR house is the end of the portfolio. Call the agent the day you close." },
        { p: "Tax treatment of repairs, improvements and depreciation is set by the IRS; see Publication 527 and confirm with a CPA." },
        { sources: [
          { t: "IRS Publication 527, Residential Rental Property", u: "https://www.irs.gov/publications/p527" }
        ] }
      ]
    }
  ],
  cards: [
    { id: "m06-c01", type: "term", q: "What is market rent?", a: "What tenants are actually paying now for similar nearby houses, found from leased comps, not asking prices and not your mortgage payment. Example: three leased 3/2 comps within a mile at $1,400–$1,500." },
    { id: "m06-c02", type: "formula", q: "How do you compute rent-to-price?", a: "Monthly rent ÷ (purchase + rehab). $1,450 ÷ $145,000 = 1.0%. A quick sorting filter, not a decision tool." },
    { id: "m06-c03", type: "term", q: "What is Fannie Mae Form 1007?", a: "The Single-Family Comparable Rent Schedule an appraiser completes for a rental refinance: three rental comps adjusted for concessions, location, condition, rooms, square footage and features, producing an indicated market rent." },
    { id: "m06-c04", type: "trap", q: "Your payment needs $1,600 but comps say $1,400. What do you do?", a: "List at $1,400 or just under. Holding out for $1,600 costs $1,400 a month in vacancy. The error was in the purchase price, not the rent." },
    { id: "m06-c05", type: "number", q: "How many rental comps and how close?", a: "At least three leased comps within about a mile, same beds and baths, square footage within a few hundred feet, leased in the last few months." },
    { id: "m06-c06", type: "scenario", q: "A prospect at a showing offers $100 more than list to skip the application. Your move?", a: "No. The price is the price, and every applicant goes through the same written screening in order. Skipping steps for one person is a fair housing problem with the next." },
    { id: "m06-c07", type: "term", q: "What is pre-screening?", a: "Asking every inquiry the same short questions in the same order before a showing: move-in date, occupants, pets, gross income, eviction history. Only applicants who meet written criteria get a showing." },
    { id: "m06-c08", type: "trap", q: "Why avoid friendly small talk at showings?", a: "Questions about family, origin or religion touch protected classes and can become evidence in a complaint. Talk about the house and the written criteria only." },
    { id: "m06-c09", type: "number", q: "What are the seven federal fair housing protected classes?", a: "Race, color, national origin, religion, sex, familial status, and disability. States and cities often add more, such as source of income." },
    { id: "m06-c10", type: "term", q: "What does familial status mean?", a: "Having children under 18, being pregnant, or adopting. You cannot refuse families with kids or steer them to particular units." },
    { id: "m06-c11", type: "term", q: "What is a reasonable accommodation?", a: "A change in rules or services for a person with a disability, such as allowing an assistance animal despite a no-pet policy, with no pet fee. Required under the Fair Housing Act." },
    { id: "m06-c12", type: "number", q: "What is the common income screening standard?", a: "Gross monthly income of at least three times the rent, verified by pay stubs, offer letter or bank statements. An industry norm, not a law. Write it down and apply it to everyone." },
    { id: "m06-c13", type: "trap", q: "You waive the income rule for an applicant you like. Why is that dangerous?", a: "The next applicant you deny on income may be in a protected class, and your waiver becomes their evidence of different treatment. No exceptions, ever." },
    { id: "m06-c14", type: "number", q: "What did HUD's April 2016 guidance say about criminal screening?", a: "Blanket bans on anyone with a record likely violate the Fair Housing Act through disparate impact. Denials based on arrests alone cannot be justified. Consider nature, severity and recency of convictions, individually." },
    { id: "m06-c15", type: "scenario", q: "Your background check shows an arrest from six years ago, no conviction. Can you deny on that?", a: "No. HUD guidance says denial based solely on an arrest record cannot be justified under the Fair Housing Act. Apply your written conviction-based standard only." },
    { id: "m06-c16", type: "term", q: "What is a screening criteria sheet?", a: "Your written, posted standard: income multiple, credit floor, rental and eviction history window, ID match, and a narrow criminal history rule. Applied in application order to every applicant without exception." },
    { id: "m06-c17", type: "term", q: "What are the essential lease clauses?", a: "Parties and all adults, term and dates, rent and due date, late fee trigger, deposit, utilities split, pet policy, maintenance split, entry notice, guests and subletting, renewal and notice terms, lead disclosure if pre-1978." },
    { id: "m06-c18", type: "trap", q: "Why not use a free generic internet lease?", a: "It may omit a state-required disclosure or include a clause your state voids, and a judge may toss your case. Use a state-specific form from a landlord association or attorney." },
    { id: "m06-c19", type: "state", q: "How much entry notice must you give for repairs?", a: "FL: At least 24 hours, and only between 7:30 a.m. and 8:00 p.m., per Statute 83.53. | OH: Reasonable notice under ORC 5321.04, with 24 hours presumed reasonable." },
    { id: "m06-c20", type: "term", q: "Are assistance animals pets?", a: "No. An assistance animal for a disability is a reasonable accommodation, not a pet; you cannot charge pet fees or pet rent for it, though the tenant remains liable for damage." },
    { id: "m06-c21", type: "number", q: "Which houses require a lead paint disclosure in the lease?", a: "Any house built before 1978. The federal lead disclosure and pamphlet are required at lease signing." },
    { id: "m06-c22", type: "term", q: "What is a move-in condition report?", a: "A signed, room-by-room checklist with dated photos or video documenting the state of every surface, fixture and appliance when the tenant takes possession. It is your baseline for deposit deductions." },
    { id: "m06-c23", type: "trap", q: "No move-in report, tenant leaves holes in the walls. Can you deduct?", a: "You will likely lose. Without a baseline the tenant can claim the damage was pre-existing. Always sign and photograph at move-in." },
    { id: "m06-c24", type: "term", q: "What is normal wear and tear?", a: "Gradual deterioration from ordinary use: minor scuffs, small nail holes, carpet traffic patterns, faded paint. You cannot deduct for it. Holes, stains, broken fixtures and unpaid rent are deductible." },
    { id: "m06-c25", type: "state", q: "What is the deposit return deadline?", a: "FL: 15 days to return in full with no claim; 30 days to send certified-mail or email notice of intent to claim, or you forfeit deductions (Statute 83.49). | OH: 30 days to return with an itemized written list, to the tenant's forwarding address (ORC 5321.16)." },
    { id: "m06-c26", type: "state", q: "What penalties apply to deposit mistakes?", a: "FL: Miss the 30-day notice and you forfeit the right to deduct; you must return the deposit and sue separately for damages. | OH: Wrongful withholding costs you the amount withheld, an equal amount in damages, and the tenant's attorney fees." },
    { id: "m06-c27", type: "state", q: "Does a security deposit earn interest?", a: "FL: Only if the landlord chooses an interest-bearing account; the statute allows several holding options and requires disclosure. | OH: Yes, 5% per year on the amount over $50 or one month's rent, once the tenant has stayed six months or more." },
    { id: "m06-c28", type: "scenario", q: "Tenant moves out of your Florida house on the 1st. You find damage. What is the sequence?", a: "Within 30 days send written notice of intent to impose a claim by certified mail or email, itemized. The tenant has 15 days to object. Then return the balance. Calendar day 30 the day they move." },
    { id: "m06-c29", type: "number", q: "What response times should your maintenance system set?", a: "Emergencies: call back within an hour, vendor same day. Urgent: within 24 hours. Routine: within a few business days. Write them down and tell tenants." },
    { id: "m06-c30", type: "term", q: "What is a maintenance emergency?", a: "No heat in winter, active flooding, sewage backup, no water, gas smell or an electrical hazard. Anything that threatens health, safety or the structure right now." },
    { id: "m06-c31", type: "number", q: "What is the preventive maintenance calendar?", a: "Spring and fall: HVAC service, filter, detector check. Annually: water heater flush and anode check, roof edge and gutter walk, caulk, leak check at every fixture, GFCI test. Every renewal: full inspection with photos." },
    { id: "m06-c32", type: "trap", q: "Tenant mentions a slow drip under the sink and never follows up. You let it go. What happens?", a: "Rotted cabinet floor, subfloor and a mold complaint. Every written request gets a written response and a closed date, whether or not the tenant chases it." },
    { id: "m06-c33", type: "term", q: "Who pays for a clogged toilet?", a: "The lease decides. Clogs caused by what the tenant flushed are typically tenant-paid with the invoice attached; failures from age or a sewer line defect are yours." },
    { id: "m06-c34", type: "term", q: "Why keep a vendor list before you need it?", a: "At 9 p.m. on a Saturday with water on the floor you need a plumber who already knows you. Build plumber, electrician, HVAC, handyman, appliance, locksmith and cleaner, each with a backup." },
    { id: "m06-c35", type: "term", q: "What is the standard rent collection setup?", a: "Due on the first, paid through an online portal that timestamps every payment. No cash. Partial payments only if the lease and your attorney define how." },
    { id: "m06-c36", type: "trap", q: "Why can accepting a partial payment hurt you?", a: "In some states accepting rent after serving notice voids the notice and restarts your eviction clock. Decide the rule with your attorney and write it in the lease first." },
    { id: "m06-c37", type: "term", q: "What is self-help eviction?", a: "Changing locks, shutting off utilities, removing doors or belongings, or threatening a tenant to make them leave. Illegal in every state and exposes you to damages." },
    { id: "m06-c38", type: "state", q: "What notice is required before filing for nonpayment?", a: "FL: Written 3-day notice excluding Saturdays, Sundays and legal holidays (Statute 83.56); 7-day notice to cure for other violations. | OH: At least 3 days written notice containing the required statutory language about seeking legal assistance (ORC 1923.04)." },
    { id: "m06-c39", type: "scenario", q: "Your Ohio tenant is 10 days late. You hand-write a note saying pay or leave in 3 days. Valid?", a: "Probably not. ORC 1923.04 requires the specific statutory language, displayed conspicuously, and proper service. Use the exact form your attorney gives you or the case gets dismissed." },
    { id: "m06-c40", type: "trap", q: "You counted 3 calendar days on a Florida nonpayment notice served Friday. Problem?", a: "Yes. Florida excludes Saturdays, Sundays and legal holidays from the 3 days. A notice that expires too early is defective and the case gets dismissed." },
    { id: "m06-c41", type: "term", q: "What is the Housing Choice Voucher program?", a: "The federal rental subsidy, still called Section 8, administered locally by a public housing agency. The PHA inspects the unit, approves the rent, and pays its share directly to you each month." },
    { id: "m06-c42", type: "number", q: "How much does a voucher tenant pay?", a: "Generally the greater of 30% of adjusted monthly income or 10% of gross income; at initial lease-up the family cannot be required to pay more than 40% of adjusted income." },
    { id: "m06-c43", type: "number", q: "What is a payment standard?", a: "The PHA's cap on the subsidy, set between 90% and 110% of HUD's Fair Market Rent for the area, or by ZIP code where Small Area FMRs apply." },
    { id: "m06-c44", type: "number", q: "What is NSPIRE and when does it apply to vouchers?", a: "HUD's newer inspection standard focused on health, safety and function. HUD Notice PIH 2026-18 lets PHAs keep the older HQS standard until February 1, 2027." },
    { id: "m06-c45", type: "term", q: "What are common voucher inspection failures?", a: "Dead or missing smoke and CO detectors, peeling paint in a pre-1978 house, missing outlet covers, failed GFCI, broken window locks, trip hazards, water heater relief valve not piped." },
    { id: "m06-c46", type: "trap", q: "Can you charge a voucher tenant a side payment above the approved rent?", a: "No. Charging more than the PHA-approved rent violates the HAP contract and can get you barred from the program and sued." },
    { id: "m06-c47", type: "scenario", q: "A voucher holder and a cash applicant apply the same day with equal qualifications. Your city protects source of income. What do you do?", a: "Process in order of completed application under your written criteria. Refusing the voucher holder because of the voucher is illegal where source of income is protected." },
    { id: "m06-c48", type: "number", q: "What does a property manager typically charge?", a: "About 8–12% of collected rent monthly for long-term rentals, plus a leasing fee of roughly 50–100% of one month's rent per placement, often a renewal fee and repair markup. Published 2026 ranges; get local quotes." },
    { id: "m06-c49", type: "scenario", q: "You own three houses two hours away and maintenance calls are eating your evenings. Hire a PM?", a: "Yes, that is the trigger: distance, unit count or slow response. Interview three, get fee schedules and their lease, ask eviction counts and owner references." },
    { id: "m06-c50", type: "formula", q: "How do you compute turnover cost?", a: "(Vacant days ÷ 30 × rent) + make-ready + leasing fee + re-key and marketing. Example: 45 days on $1,500 = $2,250, plus $1,200 paint and clean, $1,500 leasing, $200 misc = $5,150." },
    { id: "m06-c51", type: "trap", q: "Good tenant at $1,450; market is $1,500. Push to market?", a: "Usually no. The $600 a year you gain risks a $5,000 turnover. Raise modestly and steadily, and keep good tenants renewing." },
    { id: "m06-c52", type: "term", q: "Why underwrite vacancy every month?", a: "Turnover is lumpy but certain. Setting aside a vacancy allowance every month means the empty month is already paid for when it comes." },
    { id: "m06-c53", type: "term", q: "What does per-property bookkeeping mean?", a: "Each house has its own income and expense record by category from the day you go under contract, reconciled monthly with receipts attached, so you can produce a per-house profit and loss in minutes." },
    { id: "m06-c54", type: "term", q: "Repair versus improvement?", a: "A repair keeps the property in operating condition and is generally deductible in the year paid; an improvement adds value or extends life and is generally depreciated. See IRS Publication 527 and confirm with a CPA." },
    { id: "m06-c55", type: "term", q: "What is a landlord policy?", a: "Insurance written for a non-owner-occupied rental, commonly a dwelling fire form such as a DP-3, covering structure, your fixtures and appliances, liability, and often loss of rent after a covered loss." },
    { id: "m06-c56", type: "trap", q: "You left the homeowners policy in place after the tenant moved in. Risk?", a: "A claim on a rented house under an owner-occupied policy can be denied outright. Switch to a landlord policy before the lease starts, and carry a vacant policy during rehab." },
    { id: "m06-c57", type: "term", q: "Why require renters insurance?", a: "Your policy does not cover tenant belongings and should not be the first payer for tenant-caused damage. Require it in the lease, with you listed as interested party so you know if it lapses." },
    { id: "m06-c58", type: "scenario", q: "House is vacant for a 60-day rehab after closing. What insurance do you carry?", a: "A vacant or builder's risk policy for the rehab period, since standard policies often exclude vacant property, then switch to a landlord policy when the tenant moves in." }
  ],
  quiz: [
    { id: "m06-q01", q: "Market rent is best determined by:", opts: ["Your mortgage payment plus $200", "Asking prices of current listings", "Recently leased comparable houses nearby", "What the seller says it rented for"], correct: 2, explain: "Leased prices are facts; asking prices are hopes. Use at least three recent leased comps within about a mile." },
    { id: "m06-q02", q: "Purchase $110,000, rehab $35,000, rent $1,450. Rent-to-price is:", opts: ["1.3%","0.8%","4.1%","1.0%"], correct: 3, explain: "1,450 ÷ 145,000 = 1.0%. It is a quick sorting filter, not a decision tool." },
    { id: "m06-q03", q: "Fannie Mae Form 1007 is:", opts: ["The appraiser's comparable rent schedule using three rental comps","The lease addendum for pets","A HUD inspection checklist","The tenant's credit report"], correct: 0, explain: "The 1007 adjusts three rental comps for concessions, location, condition, rooms, size and features to indicate market rent for the lender." },
    { id: "m06-q04", q: "Which of these is NOT a federal fair housing protected class?", opts: ["Religion", "Familial status", "Source of income", "Disability"], correct: 2, explain: "The seven federal classes are race, color, national origin, religion, sex, familial status and disability. Source of income is protected only where state or local law adds it." },
    { id: "m06-q05", q: "An applicant has a six-year-old arrest with no conviction. Under HUD's 2016 guidance you:", opts: ["Deny; any record is disqualifying","Deny only if rent is above $1,500","Ask the applicant to explain in person before deciding","Cannot deny based solely on the arrest"], correct: 3, explain: "HUD said denials based solely on arrest records cannot be justified. Only convictions, weighed by nature, severity and recency, may be considered." },
    { id: "m06-q06", q: "The most important protection against a discrimination complaint is:", opts: ["Written criteria applied identically in application order", "A verbal explanation to each applicant", "Only renting to people you know", "Avoiding written records"], correct: 0, explain: "Consistency is the defense. Post the criteria, apply them in order, make no exceptions, keep notes." },
    { id: "m06-q07", q: "A tenant with a disability asks to keep an assistance dog in your no-pet house. You should:", opts: ["Allow it as a reasonable accommodation with no pet fee","Deny; the policy is no pets","Allow it and charge the standard pet fee","Allow it only with double deposit"], correct: 0, explain: "Assistance animals are not pets. The Fair Housing Act requires reasonable accommodation, and pet fees cannot be charged, though the tenant remains liable for damage." },
    { id: "m06-q08", q: "Florida landlord entry notice for repairs is:", opts: ["No notice required", "At least 12 hours", "At least 24 hours, between 7:30 a.m. and 8:00 p.m.", "At least 7 days"], correct: 2, explain: "Florida Statute 83.53 sets 24 hours and a 7:30 a.m. to 8:00 p.m. window. Ohio presumes 24 hours is reasonable under ORC 5321.04." },
    { id: "m06-q09", q: "Without a signed move-in condition report, a deposit deduction for wall damage will:", opts: ["Hold up easily","Be doubled automatically","Be decided by the tenant's photos","Likely fail because you have no baseline"], correct: 3, explain: "The move-in report plus photos is the baseline. Without it the tenant can claim damage was pre-existing and usually wins." },
    { id: "m06-q10", q: "In Florida, to deduct from a deposit you must send notice of intent to claim within:", opts: ["7 days", "15 days", "30 days", "60 days"], correct: 2, explain: "Statute 83.49: 15 days to return in full with no claim; 30 days to send certified-mail or email notice of a claim, or you forfeit the deductions." },
    { id: "m06-q11", q: "In Ohio, wrongful withholding of a security deposit exposes the landlord to:", opts: ["The amount withheld plus an equal amount in damages plus attorney fees","A $50 fine","Return of the deposit only","Nothing if the lease says deposit is non-refundable"], correct: 0, explain: "ORC 5321.16 awards the wrongfully withheld amount, damages equal to that amount, and reasonable attorney fees." },
    { id: "m06-q12", q: "Ohio deposits earn 5% interest when:", opts: ["Always", "The deposit exceeds $50 or one month's rent and the tenant stays six months or more", "Only on commercial leases", "Never"], correct: 1, explain: "ORC 5321.16: 5% per year on the excess over $50 or one month's rent, for tenancies of six months or longer." },
    { id: "m06-q13", q: "A sewage backup is reported at 8 p.m. Your standard should be:", opts: ["Respond next business day","Ask the tenant to fix it","Wait for a second complaint","Call back within the hour and get a vendor out the same day"], correct: 3, explain: "Sewage, flooding, no heat in winter, no water and electrical hazards are emergencies: hour call-back, same-day vendor." },
    { id: "m06-q14", q: "Why is accepting half the rent after serving a nonpayment notice risky?", opts: ["It is illegal everywhere", "In some states it voids the notice and restarts the eviction clock", "The tenant can then sue for harassment", "It automatically renews the lease"], correct: 1, explain: "Partial acceptance can waive the notice in some states. Decide the rule with your attorney and put it in the lease." },
    { id: "m06-q15", q: "Changing the locks on a non-paying tenant is:", opts: ["Illegal self-help eviction in every state","Allowed after 30 days late","Allowed with 24 hours notice","Allowed if the lease says so"], correct: 0, explain: "Self-help eviction is illegal everywhere and turns a tenant who owes you money into one who can sue you. Use the court process." },
    { id: "m06-q16", q: "Florida nonpayment notice gives the tenant:", opts: ["3 calendar days", "3 days excluding Saturdays, Sundays and legal holidays", "7 days", "14 days"], correct: 1, explain: "Statute 83.56 excludes weekends and legal holidays from the 3 days. Miscounting makes the notice defective." },
    { id: "m06-q17", q: "An Ohio eviction notice must:", opts: ["Be verbal","Give 30 days","Be filed with the county before service","Contain the statutory language advising the tenant they may seek legal assistance, displayed conspicuously"], correct: 3, explain: "ORC 1923.04 requires at least 3 days and the specific conspicuous language. Missing it gets the case dismissed." },
    { id: "m06-q18", q: "A Housing Choice Voucher payment standard is set at:", opts: ["Exactly the Fair Market Rent", "50–75% of FMR", "90–110% of FMR (or ZIP-level Small Area FMR)", "Whatever the landlord asks"], correct: 2, explain: "HUD's HCV guidebook sets the basic range at 90 to 110 percent of the applicable FMR." },
    { id: "m06-q19", q: "Under HUD Notice PIH 2026-18, PHAs may keep using the older HQS inspection standard for vouchers until:", opts: ["October 1, 2024","February 1, 2027","October 1, 2025","There is no deadline"], correct: 1, explain: "HUD extended the NSPIRE compliance date for voucher programs to February 1, 2027." },
    { id: "m06-q20", q: "Typical long-term property management fees as of 2026 are about:", opts: ["1–2% of rent", "8–12% of rent plus a leasing fee of 50–100% of a month", "25–40% of rent", "A flat $25 per month"], correct: 1, explain: "Published 2026 ranges put long-term PM at 8–12% plus a placement fee; short-term rentals cost far more. Get local fee schedules." },
    { id: "m06-q21", q: "Rent $1,500, vacant 45 days, $1,200 make-ready, one-month leasing fee, $200 re-key and ads. Turnover cost is:", opts: ["$5,150","$2,250","$3,900","$6,650"], correct: 0, explain: "2,250 + 1,200 + 1,500 + 200 = $5,150, about 29% of a year's rent. That is why keeping good tenants beats chasing market." },
    { id: "m06-q22", q: "The house will be vacant for a 60-day rehab after closing. The right insurance is:", opts: ["The seller's homeowners policy","No insurance until a tenant moves in","Renters insurance in your name","A vacant or builder's risk policy, then a landlord policy at lease-up"], correct: 3, explain: "Standard policies often exclude vacant property, and homeowners forms are for owner-occupants. Vacant coverage during rehab, DP-3 type landlord policy after." }
  ],
  drills: [
    "Pull three leased rental comps for one house in your target area, write them in the Form 1007 layout (rent, concessions, location, condition, rooms, square feet, features), and land on a rent.",
    "Write your one-page screening criteria sheet: income multiple, credit floor, rental and eviction history window, ID requirement, and a narrow conviction-based criminal standard. Have a local attorney review it.",
    "Download your state landlord association's lease or get one from a local attorney, and write a one-page house rules addendum covering pets, maintenance split, entry notice and late fees.",
    "Build your move-in condition checklist and test it on your own home: every room, every surface, photos from each corner, inside the oven and under every sink. Time it.",
    "Read your state's security deposit statute start to finish and write the return deadline, notice method and penalty on an index card you keep with your lease files.",
    "Call three property managers in your market, request their fee schedule and sample lease, and ask how many evictions they filed last year."
  ]
});
