BIBLE.register({
  id: "m07",
  part: 3,
  title: "Other People's Money",
  icon: "🏦",
  summary: "How a BRRRR deal is funded from purchase through refinance using lenders, private individuals, partners and your own home equity, what each source costs in late 2026, and how to keep leverage from killing you.",
  minutes: 95,
  lessons: [
    {
      id: "m07-01",
      title: "The Capital Stack of a BRRRR Deal",
      minutes: 10,
      blocks: [
        { h: "Four buckets of money, one deal", p: "Every BRRRR deal needs money in four places before the refinance. Purchase money buys the house. Rehab money pays for the renovation. Carrying costs cover interest, taxes, insurance, utilities and lender fees while the house sits empty. And refinance money is the long-term loan that pays the first three back. The word for how these pieces stack on top of each other is the capital stack. If you understand the stack, every lender conversation in this module makes sense, because each lender is just offering to fill one bucket at a price. Here is the worked deal we will use all module. You find a house you can buy for one hundred fifty thousand dollars. It needs forty thousand dollars of work. Fixed up, comparable sales say it is worth two hundred fifty thousand dollars, which is the after repair value or ARV. It will rent for one thousand nine hundred dollars a month. Total project cost is purchase plus rehab, so one hundred ninety thousand dollars. The house is worth sixty thousand dollars more than it costs to produce. That spread is what every lender in this module is really lending against." },
        { h: "Who fills each bucket", p: "A hard money or private lender typically fills most of the purchase and rehab buckets. You, a partner, a home equity line, or a credit strategy fills the rest, plus points, closing costs and carrying costs, because almost no lender funds one hundred percent of everything. Then a thirty year rental loan, usually a DSCR loan in late 2026 or a conventional cash-out refinance, replaces the short-term money. The refinance is sized off the new appraised value, not what you paid, which is the whole trick of BRRRR. If the appraisal supports a seventy five percent loan on two hundred fifty thousand dollars, you can borrow one hundred eighty seven thousand five hundred dollars. That number has to pay off the short-term lender and ideally hand some of your cash back." },
        { formula: "Refi proceeds = ARV × LTV. Cash back = Refi proceeds − short-term payoff − refi closing costs. Cash left in deal = Total cash out of pocket − Cash back." },
        { example: "Hard money at 90% of cost funds $171,000. You bring $19,000 down + about $3,400 in points + about $3,000 closing + roughly $12,000 carrying over six months ≈ $37,400 cash. Refi at 75% of $250,000 = $187,500. Pay off $171,000, pay about $5,000 refi costs → about $11,500 back. Cash left in: about $25,900, and you own a $250,000 rental with roughly $62,000 of equity." },
        { carry: "Capital stack = purchase + rehab + carrying costs, then the refinance pays them back. Refinance is sized off ARV × LTV (75% is the common cap in late 2026), not off what you paid." },
        { trap: "Beginners count only the down payment and forget points, closing costs on two loans, and six months of interest with no rent coming in. In the worked deal those add nearly $20,000 on top of the $19,000 down. Budget every bucket before you make an offer, and treat the refinance appraisal as a hope, not a promise." },
        { sources: [
          { t: "Fannie Mae Eligibility Matrix (Aug 5, 2026): 75% max LTV cash-out, 1-unit investment", u: "https://singlefamily.fanniemae.com/media/20786/display" },
          { t: "DSCR Authority, DSCR Cash-Out Refinance guide (Oct 2, 2026): 70–75% LTV typical", u: "https://dscrauthority.com/loan-types/cash-out-refinance/" }
        ] }
      ]
    },
    {
      id: "m07-02",
      title: "Hard Money: Speed You Pay For",
      minutes: 10,
      blocks: [
        { h: "What a hard money loan is", p: "A hard money loan, also called a fix-and-flip loan or bridge loan, is a short-term loan from a private lending company that is secured by the property itself. The lender cares most about the asset: what it is worth today, what the repairs cost, and what it will be worth finished. They close fast, often in one to two weeks, and they will lend on a house a bank would not touch because the kitchen is missing. You pay for that speed and flexibility with a high rate and upfront points." },
        { h: "Typical terms in late 2026", p: "As of fall 2026, published fix-and-flip rate surveys show interest rates of roughly nine to thirteen percent, one to three points charged at closing, and terms of six to eighteen months. A point is one percent of the loan amount, paid in cash at closing and not refundable. Lenders fund seventy to ninety percent of total project cost, called loan-to-cost or LTC, and cap the whole loan at roughly sixty five to eighty percent of the after repair value. Whichever cap is lower wins. These are national ranges and your quote will depend on your experience, credit score, and the deal." },
        { carry: "Hard money, late 2026: 9–13% interest, 1–3 points, 6–18 month term, 70–90% of cost, capped at 65–80% of ARV. Lower of the two caps governs." },
        { example: "Worked deal: 90% LTC on $190,000 = $171,000. 70% of ARV $250,000 = $175,000. The $171,000 LTC figure is lower, so that is your loan. Two points = $3,420 due at closing. Interest at 11% on $171,000 ≈ $1,568 a month, roughly $9,400 over six months." },
        { h: "Draws, inspections and what they underwrite", p: "The rehab portion is not handed to you at closing. It sits in a holdback and is released in draws as work is finished. You or your contractor pay for a stage of work, the lender sends an inspector to confirm it is done, and then they reimburse you, usually within a few days and often for a draw fee plus an inspection fee each time. That means you need enough cash to float the first stage of work. Hard money lenders underwrite the deal first, meaning your purchase contract, scope of work, contractor bids and comparable sales, and then your file, meaning your credit score, liquid reserves, and how many projects you have completed. First-time investors get less leverage and pay more, and many lenders want to see cash reserves equal to several months of payments." },
        { trap: "The draw schedule is the trap for beginners with no money. If the first draw requires finished demo and rough plumbing, you must pay the contractor for that work before the lender reimburses you. Ask every lender exactly how draws work, how many inspections, the fee per draw, and whether interest is charged on the full loan or only on funds actually disbursed. Also ask the extension fee, because a rehab that runs past the loan term can cost one or more points to extend." },
        { sources: [
          { t: "Hard Money Scout national rate survey (updated Oct 3, 2026): 9–13%, 1–3 pts, 6–12 months", u: "https://www.hardmoneyscout.com/rates" },
          { t: "Real Estate Skills, Hard Money Loans: Rates, Terms & Real Costs (updated Aug 2026)", u: "https://www.realestateskills.com/blog/hard-money-loan" }
        ] }
      ]
    },
    {
      id: "m07-03",
      title: "Private Money: Borrowing From People",
      minutes: 10,
      blocks: [
        { h: "What private money is and what it costs", p: "Private money is a loan from an individual rather than a lending company. The lender might be a retired tradesman with savings, a dentist who wants a better return than a bank CD, or anyone with a self-directed IRA, which is a retirement account held with a custodian that allows the owner to invest in things like real estate notes. You sign a promissory note, which is the promise to repay on stated terms, and you give the lender a mortgage or deed of trust recorded against the property so their loan is secured. The lender's money is protected by the house the same way a bank's would be. Industry guides for self-directed IRA lending describe private notes secured by real estate as typically yielding roughly eight to twelve percent in 2026, depending on loan-to-value, borrower quality and the market. Many private lenders charge no points and will fund one hundred percent of purchase and rehab if the deal has enough equity cushion, which is exactly what a no-money investor needs. Terms are negotiated person to person: interest-only monthly payments, or all interest paid at the refinance, are both common." },
        { carry: "Private money, 2026: typically 8–12% interest, often zero points, secured by a recorded mortgage or deed of trust plus a promissory note. Never unsecured. Never a handshake." },
        { h: "Self-directed IRA rules you must respect", p: "If a lender uses a self-directed IRA, the IRA custodian is named as the lender on the note and the mortgage, payments go to the custodian, and the IRA owner can never personally receive a payment or personally guarantee anything. Internal Revenue Code section 4975 bans loans between an IRA and disqualified persons, which include the IRA owner, their spouse, parents, children and businesses they control. So your parents cannot lend you their IRA money, but your friend's parents can lend you theirs. Tell every IRA lender to run the structure past their custodian." },
        { h: "How to find and pitch private money", p: "Use the deal first approach. Do not ask people for money. Analyze a real deal, build a one-page summary with the purchase price, rehab scope, ARV with comps, rent, your exit through the refinance, and the lender's position: loan amount, rate, term, loan-to-value, and how they are secured. Then show it to people who know you and ask one question: do you know anyone who would want to earn ten percent secured by this house? Pair it with a credibility kit: a one-page bio of you and your partner, your business entity, your team of contractor, agent, lender and attorney, and the deal analysis. The deal does the selling. Your job is to be organized and honest about the risks." },
        { trap: "Pooling money from several people into one fund, or advertising to the public for lenders, can make you an unregistered securities issuer. A single loan secured by a single property to one lender is a loan. A group of passive investors in your company is a security. Regulation D Rule 506(b) is the exemption most small real estate raises use, and it bans general solicitation and requires a Form D filing within fifteen days of the first sale, so get securities counsel before you ever pool money or post about returns. Confirm with a local real estate attorney." },
        { state: { fl: "Florida charges documentary stamp tax of $0.35 per $100 on promissory notes and mortgages, plus a separate nonrecurring intangible tax on recorded mortgages, so a private loan has real recording costs. Your title agent calculates both.", oh: "Ohio has no documentary stamp tax on notes; you pay county recording fees for the mortgage." } },
        { sources: [
          { t: "IRA Guidelines, Private Lending Inside a Self-Directed IRA (updated June 2026): 8–12% typical, IRC 4975 rules", u: "https://iraguidelines.com/private-lending-inside-a-self-directed-ira-complete-2026-guide/" },
          { t: "SEC, Private placements — Rule 506(b)", u: "https://www.sec.gov/resources-small-businesses/exempt-offerings/private-placements-rule-506b" },
          { t: "Florida Dept. of Revenue, Documentary Stamp Tax (GT-800014)", u: "https://floridarevenue.com/Forms_library/current/gt800014.pdf" }
        ] }
      ]
    },
    {
      id: "m07-04",
      title: "DSCR Loans: The Refinance Engine",
      minutes: 12,
      blocks: [
        { h: "What DSCR means", p: "DSCR stands for debt service coverage ratio. It is the property's monthly rent divided by the new monthly payment including principal, interest, taxes, insurance and any association dues, which lenders abbreviate PITIA. A DSCR loan qualifies the property, not your tax returns or your job. That is why it has become the default refinance for BRRRR investors: your personal income does not have to support the loan, the rent does. Most DSCR lenders will close in the name of your LLC with a personal guarantee, which conventional loans will not. To find the maximum payment a lender will allow, divide the rent by the required ratio. A ratio of 1.00 means rent exactly covers the payment. Most programs set their floor at 1.00, some go lower with a bigger down payment, and the best pricing usually unlocks at 1.20 to 1.25. On a cash-out refinance at seventy five percent loan-to-value, many lenders want at least 1.10 to 1.15. If your ratio falls short, two levers fix it: borrow less, or ask for an interest-only payment, which lowers the monthly debt service used in the ratio. Interest-only periods of five to ten years are common on DSCR loans." },
        { example: "Worked deal: $187,500 at 7% over 30 years ≈ $1,247 principal and interest. Add about $350 taxes and insurance → PITIA ≈ $1,597. DSCR = $1,900 ÷ $1,597 ≈ 1.19. Interest-only instead: $187,500 × 7% ÷ 12 ≈ $1,094 + $350 = $1,444 → DSCR ≈ 1.32. Or drop the loan to 70% ($175,000): P&I ≈ $1,164 + $350 = $1,514 → DSCR ≈ 1.25." },
        { h: "LTV, seasoning, FICO, the 1007, rates and prepayment penalties", p: "As of October 2026, DSCR cash-out refinances are generally capped at seventy to seventy five percent loan-to-value, with eighty percent reserved for very strong files, and rate-and-term refinances up to seventy five to eighty percent. Seasoning is how long you must own the property before the lender uses the new appraised value. Three tiers are common: three months at aggressive lenders, usually capped near seventy percent; six months at most lenders, to seventy five percent; and twelve months at conservative lenders. Some rate-and-term programs require no seasoning at all. Minimum credit scores run around 620 to 680 depending on the lender, with the best pricing at 720 to 760 and up. The appraiser completes Form 1007, the single-family comparable rent schedule, and lenders generally use the lower of the 1007 market rent or your signed lease. A vacant property is underwritten on the 1007 alone. Now the cost. One published DSCR rate tracker showed a base rate of 6.75 percent on October 2, 2026 for a 720 score, seventy five percent loan-to-value and a ratio between 1.00 and 1.24, with cash-out adding roughly an eighth to seven eighths of a point. Another tracker in September 2026 showed par rates of about 6.62 to 7.00 percent by loan-to-value. For reference, Freddie Mac's thirty year conventional average was 7.28 percent on October 1, 2026. DSCR loans almost always carry a prepayment penalty, most commonly a step-down such as 5-4-3-2-1, meaning five percent of the balance if you pay off in year one, four in year two, and so on to zero after year five. A 3-2-1 version is also common. You can usually buy the penalty down or out at closing for a rate bump or an upfront fee." },
        { carry: "DSCR = rent ÷ PITIA. Floors: 1.00 common, 1.20–1.25 best pricing. Cash-out LTV 70–75%. Seasoning 3, 6 or 12 months by program. Expect a 5-4-3-2-1 or 3-2-1 prepay. Late 2026 rates roughly 6.6–7.5% for strong files." },
        { trap: "Signing a tenant at a discount to fill the house fast lowers your DSCR, because the lender uses the lower of lease or market rent. And a 5-4-3-2-1 prepay on a $187,500 loan means a $9,375 penalty if you sell or refinance in year one. Price the penalty before you accept the rate, and match the penalty period to how long you actually plan to hold." },
        { state: { fl: "Several DSCR programs apply a tighter cash-out LTV cap, often 70 percent, in Florida and a handful of other states. Ask each lender for their Florida overlay.", oh: "Ohio Revised Code 1343.011 restricts prepayment penalties on loans secured by one or two unit residences: none at all under an annually indexed dollar threshold, and no more than one percent per year for the first five years above it. Expect DSCR lenders to offer a weaker penalty, and sometimes a higher rate, on small Ohio properties." } },
        { sources: [
          { t: "DSCR Authority, DSCR Cash-Out Refinance: 2026 Playbook (Oct 2, 2026)", u: "https://dscrauthority.com/loan-types/cash-out-refinance/" },
          { t: "Crowdfunded Wealth, How to Refinance a DSCR Loan in 2026 (May 19, 2026): seasoning tiers, 5-4-3-2-1 step-down", u: "https://www.crowdfundedwealth.com/articles/how-to-refinance-dscr-loan-2026" },
          { t: "HomeAbroad DSCR Loan Rates Today (Sept 2026)", u: "https://homeabroadinc.com/mortgages/dscr-loan-interest-rates/" },
          { t: "Freddie Mac PMMS release, Oct 1, 2026: 30-year average 7.28%", u: "https://freddiemac.gcs-web.com/news-releases/news-release-details/mortgage-rates-average-728" },
          { t: "Lendmire, The DSCR Appraisal: 1007 rent schedules", u: "https://www.lendmire.com/the-dscr-appraisal-1007-rent-schedules-comps-and-what-gets-ordered/" },
          { t: "Harpoon Capital, 2026 Guide to DSCR Prepayment Penalties (state restrictions)", u: "https://harpooncapital.com/dscr-loans-guide/complete-guide-to-dscr-loan-prepayment-penalties" },
          { t: "Ohio Revised Code 1343.011", u: "https://codes.ohio.gov/ohio-revised-code/section-1343.011" }
        ] }
      ]
    },
    {
      id: "m07-05",
      title: "Conventional Cash-Out and Delayed Financing",
      minutes: 9,
      blocks: [
        { h: "The conventional route", p: "A conventional loan is one that follows Fannie Mae or Freddie Mac guidelines and is sold to them. It is usually the cheapest thirty year money available, it has no prepayment penalty, and it qualifies you on your personal income, credit and debt-to-income ratio rather than the property's rent. For a BRRRR investor the catch is threefold: the loan must close in your personal name, not an LLC; you must document enough income to carry all your mortgages; and Fannie Mae counts financed properties, with the standard limit of ten." },
        { h: "What the Selling Guide says", p: "Fannie Mae Selling Guide section B2-1.3-03, Cash-Out Refinance Transactions, requires that at least one borrower has been on title for at least six months before the new loan disburses. Time the property was held by an LLC that you majority own counts toward the six months, but title must move into your individual name to close. The Eligibility Matrix dated August 5, 2026 caps a cash-out refinance on a one-unit investment property at seventy five percent loan-to-value, versus eighty percent on a one-unit primary residence." },
        { h: "The delayed financing exception", p: "The same section contains the delayed financing exception. If you bought the property with cash, meaning no mortgage was recorded at purchase, you can do a cash-out refinance before the six months are up. The new loan cannot exceed your documented initial investment, which is the purchase price plus closing costs, prepaids and points on the new loan, and you must document where the cash came from, for example a bank statement, a personal loan, or a HELOC on another property. The settlement statement must show no financing was used. In practice this means a private lender's money, if it was not recorded as a mortgage, or a HELOC draw, can buy the house and be repaid within weeks through delayed financing. It does not let you pull out the rehab-created equity early; it gets your purchase money back." },
        { example: "Worked deal bought with $150,000 from a HELOC and no recorded mortgage. Delayed financing could return up to about $150,000 plus costs, capped at 75% of the appraisal. After six months on title, a full cash-out at 75% of the $250,000 ARV ($187,500) captures the rehab equity too." },
        { carry: "Fannie Mae B2-1.3-03: six months on title for cash-out, LLC time counts, 75% LTV cap on 1-unit investment. Delayed financing: cash purchase, refinance anytime, loan capped at documented purchase cost." },
        { trap: "Conventional underwriting uses debt-to-income. Two partners with ordinary W-2 income may qualify for one or two rentals and then hit a wall as each new mortgage adds to their ratio. Plan which deals go conventional in a personal name and which go DSCR in the LLC before you buy. Confirm current guideline details with your loan officer and a local real estate attorney before relying on the LLC-to-personal title transfer." },
        { sources: [
          { t: "Fannie Mae Selling Guide B2-1.3-03, Cash-Out Refinance Transactions", u: "https://selling-guide.fanniemae.com/sel/b2-1.3-03/cash-out-refinance-transactions" },
          { t: "Fannie Mae Eligibility Matrix (Aug 5, 2026)", u: "https://singlefamily.fanniemae.com/media/20786/display" }
        ] }
      ]
    },
    {
      id: "m07-06",
      title: "Your Own House as Seed Capital",
      minutes: 7,
      blocks: [
        { h: "HELOC and cash-out on a primary home", p: "If you or your partner own a home with equity, that equity is the cheapest down payment money most beginners can access. A home equity line of credit, or HELOC, is a revolving line secured by your home: you draw what you need, pay interest only on what you draw, and pay it back when the BRRRR refinance funds, then use it again on the next deal. A cash-out refinance of your primary home instead replaces your whole mortgage with a bigger one and hands you a lump sum, which only makes sense if the new rate is close to your old one." },
        { h: "Limits and cost in late 2026", p: "Lenders cap the combined loan-to-value, or CLTV, which is your first mortgage plus the HELOC divided by your home's value. Fannie Mae allows up to eighty percent for a cash-out on a one-unit primary residence; many HELOC lenders go to eighty or eighty five percent CLTV, and some higher at a higher rate. The national average HELOC rate was 7.29 percent as of September 30, 2026 according to Bankrate. HELOC rates are variable and move with the prime rate, so your carrying cost can change mid-project." },
        { formula: "Available HELOC ≈ (Home value × max CLTV) − current mortgage balance." },
        { example: "Home worth $350,000, mortgage $200,000, lender allows 85% CLTV. $350,000 × 0.85 = $297,500 − $200,000 = $97,500 line. That covers the $37,400 cash the worked deal needs and leaves a cushion for overruns." },
        { carry: "HELOC = cheapest seed money for most beginners. Late 2026 average about 7.3%, variable. CLTV caps commonly 80–85%. Pay it down with every refinance so it is ready for the next deal." },
        { trap: "You are putting your family's house behind a rental. If the rehab runs over, the appraisal comes in low and the refinance falls short, the HELOC balance stays and the payment is yours. Never draw the whole line on one deal, keep a reserve inside the line, and agree with your spouse or partner in writing on the maximum you will ever put at risk." },
        { sources: [
          { t: "Bankrate, Current HELOC Rates (updated Oct 3, 2026): national average 7.29% as of Sept 30, 2026", u: "https://www.bankrate.com/home-equity/heloc-rates/" },
          { t: "Fannie Mae Eligibility Matrix (Aug 5, 2026): 80% cash-out, 1-unit principal residence", u: "https://singlefamily.fanniemae.com/media/20786/display" }
        ] }
      ]
    },
    {
      id: "m07-07",
      title: "Seller Financing and Subject-To",
      minutes: 10,
      blocks: [
        { h: "Seller financing", p: "With seller financing, the seller becomes your bank. Instead of you bringing a loan, you sign a promissory note to the seller and give them a recorded mortgage or deed of trust on the property, and you make payments to them. It fits when the seller owns the house free and clear, does not need all their cash at once, and wants steady income or a better price. You negotiate every term: price, down payment, rate, payment, and the balloon date, which is when the remaining balance comes due all at once, usually in three to seven years. For a BRRRR investor, seller financing on the purchase plus a private or credit-funded rehab, then a DSCR refinance to pay the seller off, is a complete no-bank path." },
        { h: "Subject-to", p: "Subject-to means you take title to the property while the seller's existing mortgage stays in place and in the seller's name, and you make the payments. It lets you step into a low rate from years ago. The risk is the due-on-sale clause in nearly every mortgage, which lets the lender call the whole loan due when the property transfers. The Garn-St Germain Act of 1982, codified at 12 U.S.C. 1701j-3, made due-on-sale clauses enforceable nationwide and lists specific exemptions for residential property with fewer than five units, such as transfers to a spouse or child, transfers on death, and transfers into a revocable trust where the borrower remains the beneficiary. A sale to an unrelated investor is not on that list. Lenders rarely call performing loans, but they can, and when rates have risen they have more reason to." },
        { carry: "Seller financing: note + recorded mortgage to the seller, negotiated rate and balloon. Subject-to: existing loan stays in seller's name; due-on-sale is enforceable under Garn-St Germain and a sale to an investor is not an exempt transfer." },
        { h: "Ethics and disclosure", p: "Subject-to leaves the seller's credit tied to a loan they no longer control. If you miss a payment, their credit takes the hit and their name is on the foreclosure. Do it only with full written disclosure, a third-party loan servicer that collects from you and pays the lender, proof of insurance naming everyone correctly, and a plan to refinance the seller off the loan by a fixed date. If a seller does not understand the risk, you do not have a deal, you have a future lawsuit. Many markets also require disclosures and licensed closing agents for these transactions. Confirm with a local real estate attorney before your first one." },
        { trap: "A balloon you cannot refinance is a foreclosure with a delay. If the seller carries a three-year balloon and in year three the property does not appraise or does not meet DSCR, you lose the house and your rehab money. Negotiate the longest balloon you can, ask for an extension option in the note, and only buy seller-financed deals that already meet DSCR math at today's rates." },
        { sources: [
          { t: "12 U.S.C. 1701j-3, Preemption of due-on-sale prohibitions (Garn-St Germain)", u: "https://www.law.cornell.edu/uscode/text/12/1701j-3" }
        ] }
      ]
    },
    {
      id: "m07-08",
      title: "Bridge, Gap and Transactional Funding",
      minutes: 7,
      blocks: [
        { h: "Three short-term tools", p: "A bridge loan is a short-term loan that gets you from one event to another, for example from purchase to the refinance when a hard money lender wants more rehab money than you have, or from an expiring hard money term to a delayed DSCR closing. Published 2026 bridge terms run roughly nine to twelve percent, one to two points, and six to twenty four months. Gap funding is money that fills the space between what your primary lender funds and what the deal needs: the down payment, points, or carrying costs. It usually comes from a private lender or partner in second position, meaning they get paid after the first lender, so they charge more and often want a share of the profit instead of just interest." },
        { h: "Transactional funding for double closings", p: "Transactional funding is same-day money for a wholesaler doing a double close, where you buy from the seller and resell to your end buyer in two back-to-back closings. The lender wires your purchase funds only after confirming the end buyer's money is already in escrow, so their risk is hours, not months. Industry guides in 2026 describe the cost as roughly one to two points of the purchase price for funding that lasts twenty four to seventy two hours, and some lenders charge a flat fee instead. It is not for holding property; it exists so you never have to assign a contract and show your fee." },
        { carry: "Bridge: 9–12%, 1–2 points, 6–24 months. Gap: second position, expensive, often profit share. Transactional: about 1–2 points for 24–72 hours, requires the end buyer's funds in escrow first." },
        { trap: "Stacking a first-position hard money loan and a second-position gap lender can leave you with more debt than the finished house is worth. If first plus second exceeds about seventy percent of ARV, the refinance cannot pay both back and the gap lender, who is often a friend, eats the loss. Add up every lien before you sign the second one." },
        { sources: [
          { t: "Hard Money Scout rate survey (Oct 3, 2026): bridge 9–12%, 1–2 pts, 6–24 months", u: "https://www.hardmoneyscout.com/rates" },
          { t: "Real Estate Skills, Double Closing Guide (Sept 2026): transactional funding about 1–2 points, 24–72 hours", u: "https://www.realestateskills.com/blog/double-closing" }
        ] }
      ]
    },
    {
      id: "m07-09",
      title: "Partnerships, JVs and a First Look at Syndication",
      minutes: 10,
      blocks: [
        { h: "Money partner, work partner", p: "The classic beginner partnership pairs a money partner, who brings the down payment, reserves and often the credit to sign on the loan, with a work partner, who finds the deal, manages the rehab, places the tenant and handles the refinance. A joint venture, or JV, is the same idea built for one deal at a time with its own written agreement, while a partnership or jointly owned LLC is meant to hold many deals. There is no standard split. Fifty-fifty is common when the money partner also signs the loan; a work partner who brings nothing but effort often earns twenty five to fifty percent of equity and cash flow. What matters is that the split is written before the first offer." },
        { h: "Decide this before deal one", p: "Write down who contributes what, in dollars and hours. Who signs personally on the loans and how that person is protected. How cash flow is split and when it is distributed. How capital calls work when the rehab runs over: who pays, and does it change the split. Who has final say on offers, contractors and the refinance. How a partner exits: buyout formula, right of first refusal, and what happens if someone dies, divorces or stops showing up. Whether a partner can do deals outside the partnership. Put it in an operating agreement drafted by an attorney, not a template. The cost of the document is small next to the cost of the argument." },
        { carry: "Before deal one, write down: contributions, who signs the loan, cash flow split, capital calls, decision rights, exit and buyout formula, outside deals. Attorney-drafted, signed by everyone." },
        { h: "What syndication is, in one block", p: "Syndication is when a sponsor raises money from a group of passive investors to buy a property the sponsor controls. The investors are buying a security, which puts the raise under federal and state securities law. Most small syndications rely on Regulation D Rule 506(b): unlimited accredited investors, up to thirty five non-accredited investors who are financially sophisticated, no general solicitation or advertising, disclosure documents for non-accredited investors, and a Form D filed with the SEC within fifteen days of the first sale. Rule 506(c) allows advertising but every investor must be verified accredited. You will not syndicate in your first year, but you should know the line: one active partner in a deal is a partnership; passive investors expecting profit from your effort is a security, and you need securities counsel before you take a dollar." },
        { trap: "The most common partnership failure is the money partner who thinks they are passive and the work partner who thinks they are in charge. If the money partner does nothing but wire funds, you may have sold a security, and you definitely have a resentment problem when the rehab runs long. Give every partner a real job and a real vote, and confirm the structure with a local real estate attorney." },
        { sources: [
          { t: "SEC, Private placements — Rule 506(b): investor limits, no general solicitation, Form D within 15 days", u: "https://www.sec.gov/resources-small-businesses/exempt-offerings/private-placements-rule-506b" }
        ] }
      ]
    },
    {
      id: "m07-10",
      title: "When Leverage Kills You",
      minutes: 10,
      blocks: [
        { h: "Leverage works both ways, starting with rate shock", p: "Borrowing other people's money magnifies your return when the deal goes right and your loss when it goes wrong. Four things break BRRRR investors: the refinance appraisal comes in low, rates jump between purchase and refinance, the property sits vacant, and reserves run out. None of these are rare, and all of them hit at once in a downturn. Start with rates. You underwrote the refinance at six and three quarters percent. Six months later rates are a point higher. Freddie Mac's thirty year average moved from 7.03 percent to 7.28 percent in one week ending October 1, 2026, and was 6.34 percent a year earlier, almost a full point of movement in twelve months. On the worked deal, moving from seven to eight percent raises the principal and interest on $187,500 from about $1,247 to about $1,376, which drops the DSCR from about 1.19 to about 1.10, which can cost you five points of loan-to-value or the deal. Underwrite every refinance at today's rate plus one percent." },
        { h: "The low appraisal", p: "You expected $250,000 and the appraiser says $225,000. At seventy five percent that is $168,750, which does not even pay off the $171,000 hard money loan. Now you bring money to your own refinance. Before you buy, check that the deal still works at ninety percent of your ARV. If it only works at full ARV, it does not work." },
        { example: "Stress test the worked deal: ARV $225,000 × 75% = $168,750 refi. Short-term payoff $171,000 + $5,000 costs = $176,000 needed. Shortfall $7,250 plus every dollar of your original $37,400 stays in. Would you still buy it? If yes, buy. If no, lower your offer." },
        { h: "Vacancy and the 2008 lesson", p: "In the 2008 housing crisis, national home prices fell roughly thirty percent from their 2006 peak by mid-2009. Investors who had borrowed to the maximum against appraised values, counted on refinancing or selling, and held little cash lost their properties when values dropped, lenders tightened and tenants lost jobs. Investors who held properties that cash flowed on conservative loan amounts with real reserves kept them and bought from the ones who did not. The lesson is not to avoid debt. It is that leverage must be paired with cash flow that covers the payment with room to spare and with reserves that outlast a bad year." },
        { carry: "Underwrite the refi at today's rate plus 1%. Make the deal work at 90% of ARV. Hold six months of PITIA per door in cash. Leverage without reserves is how 2008 happened to small investors." },
        { trap: "Pulling every dollar out at the refinance to buy the next house feels like winning and is how portfolios collapse. The cash you pull out is borrowed money with a payment attached. Leave enough equity that the property cash flows at a 1.20 ratio or better, and bank reserves before you shop for deal two." },
        { sources: [
          { t: "Freddie Mac PMMS release, Oct 1, 2026: 30-year 7.28%, prior week 7.03%, year ago 6.34%", u: "https://freddiemac.gcs-web.com/news-releases/news-release-details/mortgage-rates-average-728" },
          { t: "Lincoln Institute of Land Policy, Housing, Land, and the Economic Crisis: prices fell roughly 30% from 2006 peak to mid-2009", u: "https://www.lincolninst.edu/publications/articles/housing-land-economic-crisis/" },
          { t: "DSCR Authority (Oct 2, 2026): 6 months PITIA reserves typical, some lenders 12", u: "https://dscrauthority.com/loan-types/cash-out-refinance/" }
        ] }
      ]
    }
  ],
  cards: [
    { id: "m07-c01", type: "term", q: "What is the capital stack of a BRRRR deal?", a: "The layers of money that fund the deal: purchase money, rehab money, and carrying costs, followed by the long-term refinance that pays all of them back. Example: hard money for purchase and rehab, your HELOC for points and carrying, a DSCR loan to refinance." },
    { id: "m07-c02", type: "number", q: "In the module's worked deal, what are the purchase price, rehab, ARV and rent?", a: "Purchase $150,000, rehab $40,000, ARV $250,000, rent $1,900 a month. Total cost $190,000, so the spread between cost and value is $60,000." },
    { id: "m07-c03", type: "formula", q: "How do you calculate cash back at the refinance?", a: "Cash back = (ARV × LTV) − short-term payoff − refi closing costs. Worked deal: $250,000 × 0.75 = $187,500 − $171,000 − $5,000 ≈ $11,500 back." },
    { id: "m07-c04", type: "trap", q: "What costs do beginners leave out of their BRRRR cash budget?", a: "Points on the hard money loan, closing costs on both loans, and six months of interest, taxes, insurance and utilities with no rent. In the worked deal those add roughly $18,000 on top of a $19,000 down payment." },
    { id: "m07-c05", type: "term", q: "What is a point?", a: "One percent of the loan amount, charged by the lender as an origination fee and paid in cash at closing. Two points on a $171,000 loan is $3,420." },
    { id: "m07-c06", type: "number", q: "What are typical hard money terms as of late 2026?", a: "Roughly 9–13% interest, 1–3 points, 6–18 month terms, 70–90% loan-to-cost, capped at about 65–80% of ARV. Source: Hard Money Scout survey updated Oct 3, 2026 and Real Estate Skills Aug 2026 guide." },
    { id: "m07-c07", type: "term", q: "What is loan-to-cost (LTC)?", a: "The loan amount divided by total project cost, meaning purchase plus rehab. 90% LTC on a $190,000 project is $171,000; you bring the other $19,000." },
    { id: "m07-c08", type: "formula", q: "How do you find the maximum hard money loan when both an LTC cap and an ARV cap apply?", a: "Calculate both and take the lower. Worked deal: 90% LTC = $171,000; 70% of $250,000 ARV = $175,000. Loan = $171,000." },
    { id: "m07-c09", type: "term", q: "What is a rehab holdback and a draw?", a: "The rehab budget is held by the lender and released in draws after you complete a stage of work and their inspector confirms it. You pay the contractor first and get reimbursed, usually with a draw and inspection fee each time." },
    { id: "m07-c10", type: "trap", q: "Why does the draw schedule hurt investors who start with no money?", a: "You must pay for the first stage of work before the lender reimburses you. Ask how many draws, the fee per draw, and whether interest accrues on the full loan or only on disbursed funds, and keep enough cash to float the first stage." },
    { id: "m07-c11", type: "scenario", q: "A hard money lender quotes 10% and 2 points; another quotes 12% and 0 points on a six-month, $171,000 loan. Which is cheaper?", a: "Six months at 10% ≈ $8,550 interest plus $3,420 points = about $11,970. Six months at 12% ≈ $10,260 and no points. The 12% no-point loan is cheaper for a six-month hold; points matter more the shorter the loan." },
    { id: "m07-c12", type: "number", q: "What do hard money lenders underwrite first, and what else affects your terms?", a: "The deal: contract price, scope and bids, and ARV comps. Then your file: credit score, liquid reserves, and completed projects. First-timers get less leverage and pay more." },
    { id: "m07-c13", type: "trap", q: "What happens if your rehab runs past the hard money loan term?", a: "You pay an extension fee, often one point or more, or face default. Ask for the extension terms in writing before closing and build a buffer of at least two months into your timeline." },
    { id: "m07-c14", type: "term", q: "What is private money?", a: "A loan from an individual rather than a lending company, documented with a promissory note and secured by a recorded mortgage or deed of trust. Example: a retired neighbor lends $190,000 at 10% interest-only for 12 months." },
    { id: "m07-c15", type: "number", q: "What do private lenders typically earn on real-estate-secured notes in 2026?", a: "Roughly 8–12% depending on loan-to-value and borrower quality, often with no points. Source: IRA Guidelines private lending guide, updated June 2026." },
    { id: "m07-c16", type: "term", q: "What is a self-directed IRA and how does it lend?", a: "A retirement account at a custodian that allows alternative investments. The custodian is named as lender on the note and mortgage, payments go to the custodian, and the IRA owner can never personally receive payments or guarantee the loan." },
    { id: "m07-c17", type: "trap", q: "Your partner's father offers to lend from his self-directed IRA to the LLC your partner owns half of. Problem?", a: "Internal Revenue Code 4975 bars IRA loans to disqualified persons, which include the owner's children and entities they control. That loan is likely a prohibited transaction. Have him run it past his custodian and a tax professional first." },
    { id: "m07-c18", type: "term", q: "What is the deal-first approach to raising private money?", a: "Analyze a real deal, build a one-page summary showing the lender's position, and ask people who know you whether they know anyone who would want to earn ten percent secured by this house. The deal does the asking." },
    { id: "m07-c19", type: "term", q: "What goes in a one-page credibility kit?", a: "Who you and your partner are, your entity, your team of contractor, agent, lender and attorney, your process, and a sample deal analysis showing how a lender is secured and repaid. Honest about risk, no projected returns in bold type." },
    { id: "m07-c20", type: "trap", q: "When does raising money become a securities offering?", a: "When passive investors give you money expecting profit from your effort, especially pooled from several people or advertised publicly. One secured loan from one lender on one property is a loan. Get securities counsel before pooling or advertising." },
    { id: "m07-c21", type: "number", q: "What are the core rules of Regulation D Rule 506(b)?", a: "Unlimited accredited investors, up to 35 non-accredited but sophisticated investors, no general solicitation or advertising, disclosure to non-accredited investors, and a Form D filed within 15 days of the first sale. Source: SEC." },
    { id: "m07-c22", type: "state", q: "What does it cost to record a private mortgage and note?", a: "FL: Documentary stamp tax of $0.35 per $100 on the note plus a nonrecurring intangible tax on the recorded mortgage, calculated by your title agent. | OH: No documentary stamp tax on notes; county recording fees only." },
    { id: "m07-c23", type: "term", q: "What is DSCR?", a: "Debt service coverage ratio: monthly rent divided by monthly PITIA, which is principal, interest, taxes, insurance and association dues. $1,900 rent ÷ $1,597 PITIA = 1.19." },
    { id: "m07-c24", type: "formula", q: "What is the maximum PITIA a lender will allow at a given DSCR?", a: "Max PITIA = Rent ÷ required DSCR. At 1.25 and $1,900 rent, max PITIA = $1,520. At 1.00, max PITIA = $1,900." },
    { id: "m07-c25", type: "number", q: "What DSCR thresholds should you know?", a: "1.00 is the common floor; some programs go lower with more down. 1.10–1.15 is often required for a 75% LTV cash-out. 1.20–1.25 unlocks the best pricing. Source: DSCR Authority and Crowdfunded Wealth, 2026." },
    { id: "m07-c26", type: "scenario", q: "Your refinance pencils at a 1.14 DSCR and the lender wants 1.20 for the rate you were quoted. What are your two levers?", a: "Borrow less, which lowers the payment, or request an interest-only payment, which lowers the debt service used in the ratio. Worked deal: interest-only on $187,500 at 7% lifts DSCR from about 1.19 to about 1.32." },
    { id: "m07-c27", type: "number", q: "What are typical DSCR cash-out LTV caps in late 2026?", a: "70–75% for most lenders, with 80% reserved for very strong files at 1.25+ DSCR and 760+ FICO. Rate-and-term refinances run 75–80%. Source: DSCR Authority, Oct 2, 2026." },
    { id: "m07-c28", type: "term", q: "What is seasoning on a refinance?", a: "How long you must own the property before the lender will use the new appraised value instead of your purchase price. DSCR programs commonly use 3, 6 or 12 months; some rate-and-term programs require none." },
    { id: "m07-c29", type: "number", q: "What happens at each DSCR seasoning tier?", a: "Under 3 months: lender uses the lower of appraisal or cost. 3–6 months: cash-out often capped near 70% LTV. 6+ months: full appraised value to 75%. 12 months at conservative lenders or large loans. Source: Crowdfunded Wealth, May 2026; DSCR Authority, Oct 2026." },
    { id: "m07-c30", type: "term", q: "What is Form 1007?", a: "The single-family comparable rent schedule the appraiser completes to estimate market rent. DSCR lenders generally use the lower of the 1007 rent or your signed lease; a vacant property is underwritten on the 1007 alone." },
    { id: "m07-c31", type: "trap", q: "You sign a tenant $150 under market to fill the house before the refinance. What happens to your loan?", a: "The lender uses the lower of lease or 1007 market rent, so your DSCR drops with the discount. If the discount pushes you below 1.20, it can cost you pricing or loan-to-value. Lease at market or wait for the 1007." },
    { id: "m07-c32", type: "term", q: "What is a step-down prepayment penalty?", a: "A penalty that shrinks each year, written as 5-4-3-2-1 or 3-2-1: 5% of the balance if you pay off in year one, 4% in year two, and so on to zero. Most DSCR loans carry one; you can usually buy it down at closing." },
    { id: "m07-c33", type: "number", q: "What would a 5-4-3-2-1 prepay cost on the worked deal's $187,500 loan if you sold in year two?", a: "4% of the outstanding balance, about $7,500. Year one would be about $9,375. Match the penalty period to your real holding plan before accepting the rate." },
    { id: "m07-c34", type: "number", q: "What were DSCR and conventional rates in late 2026?", a: "A DSCR tracker showed a 6.75% base rate on Oct 2, 2026 for 720 FICO, 75% LTV; another showed 6.62–7.00% par by LTV in Sept 2026. Freddie Mac's 30-year conventional average was 7.28% on Oct 1, 2026. Check the day you lock." },
    { id: "m07-c35", type: "state", q: "How do prepayment penalties on small rental loans differ by state?", a: "FL: No state cap on DSCR prepays, but several programs apply a tighter 70% cash-out LTV overlay in Florida. | OH: ORC 1343.011 bars prepay penalties on 1–2 unit residential loans under an annually indexed threshold and caps them at 1% per year for five years above it." },
    { id: "m07-c36", type: "number", q: "What FICO scores do DSCR lenders look for in 2026?", a: "Minimums around 620–680 depending on the lender, with the best pricing at 720 and above and top-tier leverage at 760+. Source: DSCR Authority and HomeAbroad, 2026." },
    { id: "m07-c37", type: "term", q: "What does it mean that a DSCR loan can close in an LLC?", a: "Title and the loan are in your company's name, with the members signing a personal guarantee. Expect to provide the operating agreement and a certificate of good standing. Conventional loans must close in a personal name." },
    { id: "m07-c38", type: "number", q: "What does Fannie Mae B2-1.3-03 require for a cash-out refinance?", a: "At least one borrower on title for six months before disbursement. Time the property was held by an LLC the borrower majority-owns counts, but title must move to the individual to close. Source: Fannie Mae Selling Guide." },
    { id: "m07-c39", type: "number", q: "What is the Fannie Mae cash-out LTV cap on a one-unit investment property versus a primary residence?", a: "75% on a one-unit investment property; 80% on a one-unit principal residence. Source: Fannie Mae Eligibility Matrix dated Aug 5, 2026." },
    { id: "m07-c40", type: "term", q: "What is the delayed financing exception?", a: "A Fannie Mae rule letting a buyer who paid cash with no recorded mortgage do a cash-out refinance before six months, capped at the documented purchase price plus closing costs and prepaids, with the source of cash documented." },
    { id: "m07-c41", type: "scenario", q: "You bought the worked deal with $150,000 drawn from a HELOC, no mortgage recorded. Can you refinance before six months?", a: "Yes, under delayed financing, up to your documented purchase cost and no more than 75% of the appraisal. You recover the HELOC money early; you wait until six months on title for a full cash-out at 75% of ARV to capture the rehab equity." },
    { id: "m07-c42", type: "trap", q: "Why do W-2 partners hit a wall using conventional loans for rentals?", a: "Conventional underwriting uses debt-to-income and each new mortgage adds to the ratio, and Fannie Mae limits financed properties to ten. Decide before buying which deals go conventional in a personal name and which go DSCR in the LLC." },
    { id: "m07-c43", type: "term", q: "What is a HELOC?", a: "A home equity line of credit: a revolving, variable-rate line secured by your home. You draw what you need, pay interest only on the drawn balance, repay it when the BRRRR refinance funds, and reuse it." },
    { id: "m07-c44", type: "formula", q: "How much HELOC can you get?", a: "Available line ≈ (Home value × max CLTV) − current mortgage balance. $350,000 × 85% = $297,500 − $200,000 = $97,500." },
    { id: "m07-c45", type: "number", q: "What was the average HELOC rate in late 2026 and what are common CLTV caps?", a: "7.29% national average as of Sept 30, 2026 per Bankrate; rates are variable and track prime. CLTV caps commonly 80–85%. Fannie Mae allows 80% on a primary-residence cash-out." },
    { id: "m07-c46", type: "trap", q: "What is the real risk of funding deals with a HELOC on your family's home?", a: "If the rehab runs over or the appraisal comes in low, the HELOC balance and payment stay with you and your house is the collateral. Never draw the whole line on one deal and agree in writing on the maximum you will put at risk." },
    { id: "m07-c47", type: "term", q: "What is seller financing?", a: "The seller acts as the bank: you sign a promissory note to them and give them a recorded mortgage or deed of trust, then make payments. Terms, including a balloon date, are fully negotiable. Works best when the seller owns free and clear." },
    { id: "m07-c48", type: "term", q: "What is a balloon payment?", a: "The remaining loan balance that comes due all at once on a set date, commonly three to seven years into a seller-financed note. Your exit is a refinance or sale before that date." },
    { id: "m07-c49", type: "term", q: "What does buying subject-to mean?", a: "You take title while the seller's existing mortgage stays in place and in the seller's name, and you make the payments. It captures an old low rate but leaves the loan callable under its due-on-sale clause." },
    { id: "m07-c50", type: "number", q: "What does the Garn-St Germain Act (12 U.S.C. 1701j-3) actually do?", a: "It makes due-on-sale clauses enforceable nationwide and exempts specific transfers of residential property with fewer than five units, such as to a spouse or child, on death, or into a revocable trust where the borrower stays beneficiary. A sale to an investor is not exempt." },
    { id: "m07-c51", type: "trap", q: "A seller agrees to a subject-to deal but does not seem to understand their loan stays in their name. What do you do?", a: "Stop. Explain in writing that their credit is tied to your payments, use a third-party servicer, carry proper insurance, and set a refinance deadline. If they still do not understand, walk away. Confirm the structure with a local real estate attorney." },
    { id: "m07-c52", type: "scenario", q: "Seller offers to carry $150,000 at 6% with a three-year balloon. Rates are 7.3% and the deal is at a 1.05 DSCR today. Take it?", a: "Not at three years. If the property does not meet DSCR or appraise in year three, you lose it. Negotiate a longer balloon or an extension option, and only accept if the deal meets DSCR at today's rates plus one percent." },
    { id: "m07-c53", type: "term", q: "What is a bridge loan?", a: "A short-term loan that carries you from one event to another, such as an expiring hard money term to a DSCR closing. Late 2026 survey terms: roughly 9–12%, 1–2 points, 6–24 months." },
    { id: "m07-c54", type: "term", q: "What is gap funding?", a: "Money that fills the space between what the primary lender funds and what the deal needs, such as the down payment or carrying costs. It sits in second position, so it costs more and often takes a profit share." },
    { id: "m07-c55", type: "number", q: "What does transactional funding cost and how long does it last?", a: "Roughly 1–2 points of the purchase price for 24 to 72 hours, with some lenders using a flat fee. The lender wires only after the end buyer's funds are confirmed in escrow. Source: Real Estate Skills double closing guide, Sept 2026." },
    { id: "m07-c56", type: "trap", q: "First-position hard money plus a second-position gap loan: what number must you check?", a: "Total liens as a percent of ARV. If first plus second exceeds about 70% of ARV, the refinance cannot pay both back and the gap lender takes the loss. Add up every lien before signing the second." },
    { id: "m07-c57", type: "term", q: "What is the difference between a joint venture and a partnership?", a: "A JV is a written agreement for one deal with its own split and exit. A partnership or jointly owned LLC is built to hold many deals under one operating agreement." },
    { id: "m07-c58", type: "term", q: "What is a money partner / work partner split?", a: "One partner brings capital and often the credit to sign the loan; the other finds, rehabs, rents and refinances. Fifty-fifty is common when the money partner signs the loan; a work-only partner often earns 25–50%. The number matters less than writing it down first." },
    { id: "m07-c59", type: "number", q: "What must be decided in writing before deal one with a partner?", a: "Contributions in dollars and hours, who signs the loans, cash flow split and timing, capital calls on overruns, decision rights, exit and buyout formula, death and divorce, and outside deals. Attorney-drafted operating agreement." },
    { id: "m07-c60", type: "term", q: "What is syndication?", a: "A sponsor raises money from passive investors to buy a property the sponsor controls. The investors are buying a security, so the raise must fit a securities exemption such as Regulation D Rule 506(b) or 506(c), with counsel." },
    { id: "m07-c61", type: "trap", q: "Your money partner wires funds and does nothing else. Why is that a problem beyond resentment?", a: "A purely passive investor expecting profit from your effort may have bought a security, which triggers securities law. Give every partner a real role and a real vote, and confirm the structure with an attorney." },
    { id: "m07-c62", type: "number", q: "How much did rates move around the fall of 2026, and why does it matter for BRRRR?", a: "Freddie Mac's 30-year average was 7.28% on Oct 1, 2026, up from 7.03% the week before and 6.34% a year earlier. A one-point rise between purchase and refinance can drop a 1.19 DSCR to about 1.10. Underwrite the refi at today's rate plus 1%." },
    { id: "m07-c63", type: "scenario", q: "The refinance appraisal on the worked deal comes in at $225,000 instead of $250,000. What happens?", a: "75% of $225,000 = $168,750, which does not pay off the $171,000 hard money loan plus $5,000 in costs. You bring about $7,250 to your own refinance and all of your original cash stays in. Test every deal at 90% of ARV before you buy." },
    { id: "m07-c64", type: "number", q: "How far did national home prices fall in the 2008 crisis?", a: "Roughly 30% from the 2006 peak by mid-2009, per the Lincoln Institute of Land Policy. Investors leveraged to the max with no reserves lost properties; those with cash flow and cash kept theirs." },
    { id: "m07-c65", type: "formula", q: "What is the minimum reserve rule for a BRRRR rental?", a: "Six months of PITIA per property in cash before the deal is done. $1,597 PITIA × 6 ≈ $9,600 on the worked deal. Many DSCR lenders require 6 months at closing and some 12." },
    { id: "m07-c66", type: "trap", q: "Why is pulling every dollar out at the refinance dangerous?", a: "Cash out is borrowed money with a payment attached. Max cash-out pushes DSCR toward 1.0, leaving no cushion for vacancy or a rate move. Leave enough equity to hold a 1.20 ratio and bank reserves before deal two." },
    { id: "m07-c67", type: "scenario", q: "Two hard money quotes: 85% LTC with interest on the full loan from day one, or 80% LTC with interest only on disbursed funds. Rehab is $40,000 released over four months. Which costs less to carry?", a: "Usually the second. Interest on the undrawn $40,000 holdback at 11% is about $367 a month you never owe under the disbursed-only structure. Run both over your real draw schedule; the lower LTC may win on total cost." }
  ],
  quiz: [
    { id: "m07-q01", q: "In the worked deal, total project cost is $190,000 and the hard money lender offers 90% LTC capped at 70% of a $250,000 ARV. What is the loan?", opts: ["$175,000", "$171,000", "$190,000", "$187,500"], correct: 1, explain: "90% of $190,000 is $171,000; 70% of ARV is $175,000. The lower cap governs, so the loan is $171,000." },
    { id: "m07-q02", q: "What does a point on a loan mean?", opts: ["One tenth of a percent of the rate", "One month of interest", "One percent of the purchase price added to the loan", "One percent of the loan amount paid at closing"], correct: 3, explain: "A point is one percent of the loan amount, charged as an origination fee and paid in cash at closing." },
    { id: "m07-q03", q: "As of late 2026, published fix-and-flip hard money surveys show interest rates in roughly what range?", opts: ["4–6%", "6–8%", "9–13%", "15–20%"], correct: 2, explain: "Hard Money Scout's survey updated Oct 3, 2026 shows 9–13% with 1–3 points; Real Estate Skills' Aug 2026 guide agrees." },
    { id: "m07-q04", q: "How does rehab money on a hard money loan usually reach you?", opts: ["Released in draws after inspected work is complete", "Wired in full at closing", "Paid directly to the seller", "Added to the refinance"], correct: 0, explain: "Rehab funds sit in a holdback and are reimbursed in draws after an inspector confirms each stage, so you front the first stage." },
    { id: "m07-q05", q: "A private lender using a self-directed IRA wants to fund your deal. Who is named as lender on the note and mortgage?", opts: ["The IRA owner personally", "Your LLC", "The IRA custodian on behalf of the IRA", "The title company"], correct: 2, explain: "The custodian holds the note and mortgage for the IRA; the owner can never personally receive payments or guarantee the loan." },
    { id: "m07-q06", q: "Which of these is most likely a securities offering requiring counsel?", opts: ["One lender funds one property, secured by a recorded mortgage", "Your partner's HELOC funds the down payment", "Six acquaintances each wire $20,000 into your LLC to fund deals passively", "A seller carries a note on their own house"], correct: 2, explain: "Pooling passive investors who expect profit from your effort is a security. Rule 506(b) is the usual exemption; get securities counsel first." },
    { id: "m07-q07", q: "A DSCR lender requires 1.25. Rent is $1,900. What is the maximum PITIA?", opts: ["$1,900", "$1,615", "$1,520", "$1,425"], correct: 2, explain: "Max PITIA = $1,900 ÷ 1.25 = $1,520." },
    { id: "m07-q08", q: "Your refinance shows a 1.19 DSCR and the best pricing needs 1.20. Which single change raises the ratio without reducing the loan amount?", opts: ["Switch to an interest-only payment", "Increase the loan to 80% LTV", "Sign a tenant below market to close faster", "Add a prepayment penalty"], correct: 0, explain: "Interest-only lowers the monthly debt service used in the ratio. In the worked deal it moves DSCR from about 1.19 to about 1.32." },
    { id: "m07-q09", q: "Which seasoning pattern matched most DSCR lenders in 2026?", opts: ["No seasoning for any cash-out", "24 months for every refinance", "Seasoning applies only to conventional loans", "3 months to 70% LTV, 6 months to 75%, 12 months at conservative lenders"], correct: 3, explain: "DSCR Authority (Oct 2026) and Crowdfunded Wealth (May 2026) both describe 3, 6 and 12 month tiers with LTV stepping up at six months." },
    { id: "m07-q10", q: "On a 5-4-3-2-1 prepayment penalty, you pay off a $187,500 balance in year two. The penalty is about:", opts: ["$9,375", "$7,500", "$5,625", "$0"], correct: 1, explain: "Year two is 4%: $187,500 × 0.04 = $7,500." },
    { id: "m07-q11", q: "Your lease says $2,000 but the appraiser's Form 1007 market rent is $1,850. Most DSCR lenders will underwrite at:", opts: ["$2,000", "$1,925", "$1,850", "Whichever you choose"], correct: 2, explain: "Lenders generally use the lower of the signed lease or the 1007 market rent, so an above-market lease does not lift the ratio." },
    { id: "m07-q12", q: "Fannie Mae Selling Guide B2-1.3-03 requires how long on title before a standard cash-out refinance?", opts: ["No requirement", "Three months", "Six months", "Twelve months"], correct: 2, explain: "At least one borrower must have been on title for six months before disbursement; LLC ownership time counts if the borrower majority-owns the LLC." },
    { id: "m07-q13", q: "Under the delayed financing exception, the new loan amount is capped at:", opts: ["The documented purchase price plus closing costs and prepaids", "80% of the appraised value", "The ARV minus rehab", "Whatever the DSCR supports"], correct: 0, explain: "Delayed financing returns your documented initial investment, not the rehab-created equity, and never more than the LTV cap." },
    { id: "m07-q14", q: "Per the Aug 5, 2026 Fannie Mae Eligibility Matrix, the maximum cash-out LTV on a one-unit investment property is:", opts: ["70%", "75%", "80%", "85%"], correct: 1, explain: "75% on a one-unit investment property; a one-unit principal residence allows 80%." },
    { id: "m07-q15", q: "Home worth $350,000, mortgage $200,000, lender allows 85% CLTV. What HELOC can you get?", opts: ["$97,500", "$150,000", "$80,000", "$120,000"], correct: 0, explain: "$350,000 × 0.85 = $297,500 − $200,000 = $97,500." },
    { id: "m07-q16", q: "What was the national average HELOC rate reported by Bankrate as of Sept 30, 2026?", opts: ["5.29%", "6.29%", "7.29%", "8.29%"], correct: 2, explain: "Bankrate reported 7.29% as of Sept 30, 2026. HELOC rates are variable and track prime." },
    { id: "m07-q17", q: "Under the Garn-St Germain Act, which transfer of a single-family home is NOT exempt from a due-on-sale clause?", opts: ["Transfer to the borrower's child", "Transfer on the borrower's death to a relative", "Transfer into a revocable trust where the borrower remains beneficiary", "Sale to an unrelated investor who takes over payments"], correct: 3, explain: "12 U.S.C. 1701j-3(d) exempts family, death and revocable-trust transfers; a sale to an investor is not exempt, so the lender may call the loan." },
    { id: "m07-q18", q: "A seller will carry financing with a balloon in three years. What is the most important question before accepting?", opts: ["Whether the seller will lower the rate later", "Whether the deal meets DSCR and appraises for a refinance at today's rates plus 1%", "Whether you can skip title insurance", "Whether the balloon can be paid by credit card"], correct: 1, explain: "A balloon you cannot refinance is a foreclosure with a delay; the exit must work at conservative numbers before you sign." },
    { id: "m07-q19", q: "Transactional funding for a double close typically costs about:", opts: ["0.1% of the price", "10% annual interest", "Nothing if the end buyer pays cash", "1–2 points for 24–72 hours"], correct: 3, explain: "Industry guides in 2026 describe roughly one to two points for a one-to-three-day hold, funded only after the end buyer's money is in escrow." },
    { id: "m07-q20", q: "Hard money funds $171,000 in first position and a gap lender adds $25,000 in second position. ARV is $250,000. Why is this dangerous?", opts: ["Total liens of $196,000 are 78% of ARV, above what a 75% refinance can pay off", "Second liens are illegal on investment property", "The gap lender's rate must match the first", "The DSCR becomes negative"], correct: 0, explain: "A 75% refinance yields $187,500, less than $196,000 in liens plus costs, so the gap lender cannot be paid off." },
    { id: "m07-q21", q: "Under Regulation D Rule 506(b), how many non-accredited investors may participate?", opts: ["None", "Up to 35", "Up to 100", "Unlimited"], correct: 1, explain: "506(b) allows unlimited accredited investors and up to 35 non-accredited but sophisticated investors, with no general solicitation." },
    { id: "m07-q22", q: "Freddie Mac's 30-year average was 7.28% on Oct 1, 2026 versus 6.34% a year earlier. The lesson for BRRRR underwriting is:", opts: ["Underwrite the refinance at today's rate plus about 1%", "Lock the refinance rate before you buy", "Ignore rates because rents rise too", "Always use interest-only"], correct: 0, explain: "Nearly a point of movement in a year is normal. A one-point rise drops the worked deal's DSCR from about 1.19 to about 1.10." },
    { id: "m07-q23", q: "The appraisal comes in at $225,000 instead of $250,000. At 75% LTV, how does the refinance compare to the $171,000 hard money payoff?", opts: ["It covers the payoff with $16,500 to spare", "It yields $168,750, short of the payoff before closing costs", "It yields $187,500 as planned", "The appraisal does not affect the refinance"], correct: 1, explain: "75% of $225,000 is $168,750, below the $171,000 payoff, so you bring cash to close. Test every deal at 90% of ARV." },
    { id: "m07-q24", q: "What is the minimum reserve this module tells you to hold per rental before counting the deal done?", opts: ["One month of rent", "The next down payment", "Nothing if the DSCR is above 1.0", "Six months of PITIA in cash"], correct: 3, explain: "Six months of PITIA per property; many DSCR lenders require six months at closing and some require twelve." }
  ],
  drills: [
    "Call two hard money lenders today and request a written term sheet on the worked deal ($150,000 purchase, $40,000 rehab, $250,000 ARV). Record rate, points, LTC, ARV cap, term, draw count and fees, extension fee, and whether interest accrues on the full loan or disbursed funds.",
    "Call two DSCR lenders and ask: minimum DSCR for a 75% cash-out, seasoning months, FICO tiers, prepayment penalty options and buyout cost, whether they close in an LLC, and today's rate for a 720 score. Write the answers side by side.",
    "Write your one-page credibility kit: who you two are, your entity, your team (contractor, agent, lender, attorney, title), your process, and one sample deal showing how a private lender is secured and repaid. No projected returns in bold.",
    "Build a one-page deal summary for the worked deal from a private lender's point of view: loan amount, rate, term, LTV, position, how they are secured, and exit. Show it to three people you know and ask only: do you know anyone who would want to earn ten percent secured by this house?",
    "Pull your own home's current value and mortgage balance and calculate your available HELOC at 80% and 85% CLTV. Then call your bank or credit union for their actual CLTV cap, rate and annual fee.",
    "Stress test the worked deal three ways in a spreadsheet: refinance rate plus 1%, appraisal at 90% of ARV, and two months of vacancy. Write down whether you would still buy and at what maximum price.",
    "Draft the partner decision list with your partner: contributions, who signs loans, cash flow split, capital calls, decision rights, exit formula, outside deals. Agree on every line, then book a consult with a local real estate attorney to turn it into an operating agreement."
  ]
});
