BIBLE.register({
  id: "m08",
  part: 3,
  title: "Business Credit From Zero",
  icon: "💳",
  summary: "How two partners with no money build a business credit profile over six to twelve months, from entity and EIN through vendor accounts, business cards and lines of credit, so rehab materials and gap costs can be financed without wrecking personal credit before a refinance.",
  minutes: 70,
  lessons: [
    {
      id: "m08-01",
      title: "Entity, EIN and a Real Bank Account",
      minutes: 8,
      blocks: [
        { h: "Why business credit exists at all", p: "Business credit is a credit history that belongs to your company instead of to you. Lenders, vendors and card issuers report how the company pays, and business credit bureaus score it. For a BRRRR operator with no cash, the point is practical: a business card with a zero percent introductory period can float rehab materials, a vendor account can let you pay for flooring thirty days after it ships, and a business line of credit can cover a draw gap. None of that is possible until the business exists on paper in a way the bureaus can see. That means three things in order: a legal entity, an employer identification number, and a business bank account." },
        { h: "Entity and EIN", p: "Form a limited liability company or corporation in your state. The entity needs a real legal name, a registered agent, and a business address, which can be your home but should be consistent everywhere you ever type it. Then get an employer identification number, or EIN, from the IRS. The IRS states plainly that you never have to pay a fee for an EIN, the online application issues the number immediately when approved, and you can apply for only one EIN per responsible party per day. Any website charging you for an EIN is reselling a free form." },
        { h: "The business bank account", p: "Open a checking account in the entity's exact legal name using your formation documents and EIN letter. Run every business dollar through it and nothing personal. Lenders and card issuers look at this account's age and average balance, and it is what proves to a court that your LLC is a separate thing from you, which is the entire reason you formed it. A business phone number listed under the business name and a simple website with matching name and address round out the identity that bureaus and underwriters cross-check." },
        { carry: "Order of operations: entity, then EIN (free, instant, one per responsible party per day), then a business bank account in the exact legal name. Same name, address and phone everywhere." },
        { trap: "Mismatched identities kill applications. If your LLC is Oak Street Holdings LLC on the state filing, Oak St Holdings on the bank account, and Oakstreet Holdings on a vendor form, the bureaus may create duplicate files and lenders may decline for fraud flags. Write the exact legal name, address and phone on an index card and copy from it every time." },
        { sources: [
          { t: "IRS, Get an Employer Identification Number", u: "https://www.irs.gov/businesses/small-businesses-self-employed/get-an-employer-identification-number" }
        ] }
      ]
    },
    {
      id: "m08-02",
      title: "D-U-N-S and Paydex",
      minutes: 8,
      blocks: [
        { h: "What a D-U-N-S number is", p: "Dun and Bradstreet, usually called D and B, is the oldest business credit bureau. It identifies companies with a nine-digit D-U-N-S number. Dun and Bradstreet states there is no cost to request and receive one, with normal processing taking up to thirty business days, and offers a paid expedited service that delivers in about eight business days. Request it as soon as the entity exists so the clock starts. You will also see offers for paid credit-building products from the bureau itself; you do not need them to build a file, you need vendors that report." },
        { h: "What Paydex measures", p: "Paydex is D and B's payment score, ranging from one to one hundred. It is built only from how you pay the trade vendors who report to D and B, and it is dollar-weighted, so a large invoice counts more than a small one. A score of eighty means you pay on time, zero days beyond terms. A score of one hundred means you pay about thirty days early. Lenders generally treat eighty and above as good. Per Nav, you need at least two tradelines reporting and three trade experiences before a Paydex appears, which typically takes roughly ninety to one hundred twenty days after your first vendor orders." },
        { carry: "D-U-N-S: free, up to 30 business days. Paydex: 1–100, 80 = pays on time, 100 = pays 30 days early, dollar-weighted, needs 2 reporting tradelines and 3 experiences, first score around day 90–120." },
        { h: "The other bureaus", p: "Experian Business and Equifax Business also keep files on your company, and the Small Business Financial Exchange, or SBFE, is a data pool that many banks report to and read from. Some vendors report to one bureau, some to several. When you pick starter vendors, prefer ones that report to more than one so you are building three files, not one. Verify your own files a few months in; errors and duplicate entities are common." },
        { trap: "Paying on time earns an eighty. Paying early earns more. If you want a Paydex above eighty, pay vendor invoices the day they post, not on day thirty. Paying even a few days late on a reporting vendor drags a thin file hard because there is nothing else to average against it." },
        { sources: [
          { t: "Dun & Bradstreet, Get a D-U-N-S Number", u: "https://www.dnb.com/duns-number/get-a-duns.html" },
          { t: "Nav, Dun & Bradstreet PAYDEX Score explained", u: "https://www.nav.com/business-credit/dun-bradstreet-paydex/" }
        ] }
      ]
    },
    {
      id: "m08-03",
      title: "Net-30 Vendor Accounts That Report",
      minutes: 9,
      blocks: [
        { h: "What net-30 means", p: "A net-30 account is a vendor agreement that lets your business receive goods now and pay the invoice within thirty days. It is the first credit most new companies can get, because the vendor is only risking one order. The ones worth having are the ones that report your payments to a business bureau. A vendor account that does not report builds nothing. Your job in months one through three is to open three to five reporting vendor accounts, buy things you actually need, and pay early." },
        { h: "What the category looks like in 2026", p: "The reporting starter vendors are mostly office, shipping, industrial and building supply companies. A July 2026 Ramp review lists examples including an office supply retailer and a shipping supply company that report to Dun and Bradstreet and Experian, an industrial supplier and a building supply distributor that report to Dun and Bradstreet, and a few small businesses that exist mainly to sell starter tradelines and charge an annual or monthly fee for the privilege. Several require a minimum first order, often fifty to one hundred dollars, and some require your account to be open for a period before terms are extended. The review itself warns that bureau reporting and fees change often and tells you to confirm current terms with each vendor before you apply, which is exactly right. Do not rely on any list, including this one, without calling the vendor's credit department and asking which bureaus they report to today." },
        { h: "How to use them for a rehab business", p: "Pick vendors whose products you would buy anyway: fasteners, paint sundries, cleaning supplies, shipping boxes for your direct mail, printer paper, a shop vac. A building supply distributor that extends net-30 to contractors is more useful to a rehabber than a stationery company, but both build the file. Place a real order every month or two, pay within a few days of the invoice posting, and keep the receipts in your bookkeeping. After three or four months and a Paydex, you graduate to store cards and fleet cards from home improvement and fuel retailers, which usually require a D-U-N-S and some history, and then to bank cards." },
        { carry: "Months 1–3: open 3–5 net-30 vendors that you have personally confirmed report to a bureau, order what you actually need, pay early. Avoid vendors whose main product is the tradeline itself." },
        { trap: "Paying a monthly fee to a company whose only business is reporting your payments to bureaus is a thin signal that experienced underwriters discount, and some lenders flag it. Build the file with real vendors selling real goods. If a vendor cannot tell you in writing which bureau they report to, assume they do not report." },
        { sources: [
          { t: "Ramp, Best Net 30 Accounts to Build Business Credit (July 16, 2026)", u: "https://ramp.com/blog/best-net-30-accounts" }
        ] }
      ]
    },
    {
      id: "m08-04",
      title: "Business Credit Cards and Your Personal Report",
      minutes: 9,
      blocks: [
        { h: "Almost every business card checks you personally", p: "Business credit cards from major banks are approved on your personal credit score and income, with a personal guarantee, which means you personally owe the balance if the business cannot pay. Every application triggers a hard inquiry on your personal report. The question that matters for a BRRRR investor is a different one: once you have the card, does the issuer report the balance and payment history to your personal credit bureaus every month? If yes, a large rehab balance shows up as personal utilization and can drop your personal score right before a refinance." },
        { h: "Who reports what, as of 2026", p: "NerdWallet's reporting-policy roundup, updated April 22, 2026, describes most Capital One Spark business cards as reporting full activity to both business and personal bureaus, with a few of their premium business cards reporting only negative information. Discover's business card has historically reported to personal bureaus as well. By contrast, American Express, Bank of America, Chase, U.S. Bank and Wells Fargo business cards are described as reporting only negative information to personal bureaus, meaning a seriously delinquent account. Issuer policies change, so confirm with the issuer before you apply and re-check once a year." },
        { carry: "Full personal reporting: Capital One Spark cards (most) and Discover business. Negative-only: Amex, Bank of America, Chase, U.S. Bank, Wells Fargo. All of them pull your personal credit and require a personal guarantee. Verify before applying." },
        { h: "The utilization problem", p: "FICO states that amounts owed make up about thirty percent of your personal score, second only to payment history at thirty five percent. Utilization is your card balances divided by your limits. A twenty five thousand dollar materials balance on a card that reports personally can push you from low utilization to very high utilization in one statement, and the score drop can move you down a FICO tier on your DSCR refinance, costing rate or loan-to-value. A card that reports only negative information keeps that balance off your personal utilization as long as you pay on time." },
        { trap: "Opening a Capital One Spark card for its sign-up bonus, charging the whole rehab to it, and then applying for a DSCR refinance two months later is a classic way to lose a FICO tier. Use negative-only issuers for rehab balances, or pay a personally reporting card to near zero before the statement closes in the months leading up to any refinance application." },
        { sources: [
          { t: "NerdWallet, Do Business Credit Cards Affect Your Personal Credit Score? (updated Apr 22, 2026)", u: "https://www.nerdwallet.com/business/credit-cards/learn/do-business-credit-cards-affect-personal-credit-score" },
          { t: "myFICO, What's in your FICO Score", u: "https://www.myfico.com/credit-education/whats-in-your-credit-score" }
        ] }
      ]
    },
    {
      id: "m08-05",
      title: "The 0% Intro APR Rehab Strategy and Its Risks",
      minutes: 9,
      blocks: [
        { h: "The strategy", p: "Many business cards offer a zero percent introductory annual percentage rate on purchases. NerdWallet's roundup updated October 1, 2026 describes twelve months as the standard intro period, with some shorter, and ongoing variable rates after the intro period that run roughly sixteen to twenty eight percent depending on the card and your credit. The idea is simple: charge rehab materials, appliances and some contractor payments through a card processor during the intro period, finish the rehab, refinance, and pay the card to zero from the refinance proceeds before the intro period ends. Done right, you borrowed forty thousand dollars of materials for six months at zero interest and earned rewards." },
        { example: "Rehab materials $22,000 charged in months 1–3 on a 12-month 0% card. Refinance closes in month 7. Pay the card to $0 in month 7. Interest paid: $0. Compare to hard money at 11% on the same $22,000 for 7 months: about $1,410." },
        { h: "What goes wrong", p: "The refinance slips. Appraisals, seasoning and a slow tenant placement can turn month seven into month fourteen, and in month thirteen the balance starts accruing at twenty plus percent. Contractors often cannot take cards, or add a surcharge of around three percent that eats a chunk of the savings. Card limits for a new business are often five to fifteen thousand dollars, not forty. And if the card reports to your personal bureaus, the balance sits on your report during the exact months you are applying for the refinance. Finally, the personal guarantee means that if the deal fails, the debt follows you home at a rate that makes hard money look cheap." },
        { carry: "0% intro cards: 12 months is standard in late 2026, then roughly 16–28% variable. Use for materials only, on a negative-only issuer, with a payoff plan that assumes the refinance runs 3 months late." },
        { trap: "Minimum payments still come due every month during the zero percent period, and one missed payment can void the promotional rate under the card agreement. Set autopay for at least the minimum from the business account on day one. Never let the intro deadline be the only exit; know what the payment would be at the full rate and make sure the rental's cash flow or your reserves could carry it." },
        { sources: [
          { t: "NerdWallet, Best 0% APR Business Credit Cards (updated Oct 1, 2026)", u: "https://www.nerdwallet.com/business/credit-cards/best/zero-percent-apr" }
        ] }
      ]
    },
    {
      id: "m08-06",
      title: "The Build Order: Six to Twelve Months",
      minutes: 9,
      blocks: [
        { h: "Months one and two", p: "Form the entity, get the EIN, open the business bank account, set up a business phone and a one-page website, and request the D-U-N-S number. Apply for three to five net-30 vendor accounts you have confirmed report, and place small real orders. Pull both partners' personal credit reports, dispute errors, and pay every personal card below ten percent utilization, because every business card application in the next year will be judged on those personal reports." },
        { h: "Months three to five", p: "Keep ordering and paying early. Check that a Paydex has generated and that Experian Business shows your tradelines. Apply for one or two store cards from home improvement or fuel retailers under the business. If one partner has a personal score above seven hundred, apply for a first bank business card from an issuer that reports only negative information, ideally with a zero percent intro period, timed so the intro window covers your first rehab." },
        { h: "Months six to twelve", p: "Add a second bank business card from a different negative-only issuer so you are not dependent on one limit. After the business account has six to twelve months of deposits, apply for a business line of credit at the bank where you keep the account. Ask each card issuer for a credit line increase after six on-time months. Review all three business bureau files for errors. By month twelve a disciplined operator typically has a Paydex, several vendor lines, two bank cards and a small line of credit, which is enough to float materials and gap costs on a single rehab." },
        { carry: "Months 1–2: entity, EIN, bank, D-U-N-S, 3–5 reporting vendors, clean personal credit. Months 3–5: Paydex appears, store cards, first negative-only bank card. Months 6–12: second card, bank line of credit, limit increases, audit the bureau files." },
        { trap: "Applying for everything in month one is the fastest way to a stack of denials and a dozen hard inquiries. New credit is about ten percent of your FICO score, and underwriters read a burst of inquiries as desperation. Space applications at least thirty to sixty days apart and never apply for a business card within sixty days of a planned mortgage or DSCR application." },
        { sources: [
          { t: "myFICO, What's in your FICO Score: new credit 10%, amounts owed 30%", u: "https://www.myfico.com/credit-education/whats-in-your-credit-score" },
          { t: "Nav, PAYDEX timeline: score appears around day 90–120", u: "https://www.nav.com/business-credit/dun-bradstreet-paydex/" }
        ] }
      ]
    },
    {
      id: "m08-07",
      title: "Business Lines of Credit",
      minutes: 8,
      blocks: [
        { h: "What a business line of credit is", p: "A business line of credit is a revolving loan to your company: you draw what you need up to the limit, pay interest only on what is drawn, repay, and draw again. For a BRRRR operator it is the tool for floating a hard money draw, paying a contractor deposit, or covering carrying costs between purchase and refinance. Unlike a card, it funds by transfer to your bank account, so anyone can be paid from it." },
        { h: "Bank lines versus online lenders", p: "Banks offer the cheapest lines but want history. NerdWallet's October 2026 roundup lists a major bank line requiring a minimum personal score of six hundred eighty and six months in business, and online lenders requiring scores of six hundred to six hundred eighty, three to twelve months in business, and annual revenue minimums ranging from thirty thousand to one hundred twenty thousand dollars. Online lines approve fast and cost more; the roundup shows rates starting around seven point eight percent for the best files, with weaker files paying far more, and some online products pricing in weekly payments or factor rates rather than a simple interest rate." },
        { carry: "Bank line: roughly 680+ personal score, 6–12 months in business, cheapest. Online line: 600–680 score, 3–12 months, $30k–$120k revenue minimums, fast and more expensive. Figures from an Oct 2026 NerdWallet roundup; confirm with the lender." },
        { h: "What a new rental company can actually get", p: "A company with no revenue yet, which describes most first-year BRRRR operators, usually qualifies only for small lines based on the owners' personal credit, or for a secured line backed by a deposit. Rental income counts as revenue once it is flowing, so the realistic sequence is: use cards and vendors for the first deal, bank the rent for six months, then apply for a line at your deposit bank. Ask about a secured line early if you have even a few thousand dollars to pledge; it builds history at a low rate." },
        { trap: "Read how the rate is quoted. A factor rate of 1.25 on a six-month draw is not twenty five percent interest; it is closer to fifty percent annualized because you repay the whole amount over six months. Ask every lender for the annual percentage rate in writing and compare that number only." },
        { sources: [
          { t: "NerdWallet, Best Business Lines of Credit (Oct 2026)", u: "https://www.nerdwallet.com/business/loans/best/business-line-of-credit" }
        ] }
      ]
    },
    {
      id: "m08-08",
      title: "Funding Scams and How to Spot Them",
      minutes: 7,
      blocks: [
        { h: "The pitch you will hear", p: "Once your LLC is on record, you will be marketed to. The pitch is some version of guaranteed one hundred thousand dollars in business funding, no personal guarantee, zero percent, approval in days, for a fee paid up front or a percentage of the funding. Some of these are consultants who simply submit the same card applications you could submit yourself and charge you ten percent of the limits. Some are advance-fee frauds where the funding never comes. Some are merchant cash advances dressed up as credit lines." },
        { h: "What the FTC has flagged", p: "In a 2020 enforcement action the Federal Trade Commission described a business funder that promised no personal guaranty and no up-front costs, then delivered less money than promised, charged fees up front, required personal guarantees anyway, and used confessions of judgment, which are documents that let a lender get a court judgment against you without a hearing. The FTC's advice was to read every term before signing, get payment consequences in writing, and research options through the Small Business Administration. The pattern has not changed: the red flags are guarantees, fees before funding, pressure to sign today, and documents you are not allowed to take to a lawyer." },
        { carry: "Red flags: guaranteed approval, fee before funding, no-personal-guarantee promises from an unknown lender, confession of judgment, daily or weekly repayment, refusal to state an APR, and pressure to sign now. Nobody legitimate can guarantee funding." },
        { h: "What legitimate looks like", p: "Legitimate lenders state the APR, run credit before approving, require a personal guarantee from a new business and say so, charge fees at closing out of proceeds rather than before approval, and give you the agreement to review. If a funding consultant wants a fee, make it contingent on funded dollars and get the card issuers' names in advance so you can see that you are paying someone to fill out forms." },
        { trap: "A merchant cash advance sold as a line of credit can carry an effective annual rate well above fifty percent with daily automatic withdrawals from your business account. On a rental company with irregular deposits it can drain the account during a vacancy. If the repayment is daily or weekly, or the cost is quoted as a factor rate, it is not a line of credit and it does not belong in a BRRRR capital stack." },
        { sources: [
          { t: "FTC Consumer Alert, Fraudulent funders = big woes for small businesses (June 2020)", u: "https://consumer.ftc.gov/consumer-alerts/2020/06/fraudulent-funders-big-woes-small-businesses" }
        ] }
      ]
    }
  ],
  cards: [
    { id: "m08-c01", type: "term", q: "What is business credit?", a: "A credit history that belongs to your company rather than to you, built from how the company pays vendors, cards and loans, and scored by business bureaus. Example: a Paydex of 80 at Dun & Bradstreet." },
    { id: "m08-c02", type: "number", q: "What does the IRS say about getting an EIN?", a: "It is free, the online application issues the number immediately when approved, and you can apply for only one EIN per responsible party per day. Any site charging for an EIN is reselling a free form." },
    { id: "m08-c03", type: "term", q: "What is the correct order of operations to start a business credit file?", a: "Form the entity, get the EIN, open a business bank account in the exact legal name, then request the D-U-N-S number and open reporting vendor accounts." },
    { id: "m08-c04", type: "trap", q: "Your LLC's name appears three slightly different ways on your state filing, bank account and a vendor form. Why does that matter?", a: "Bureaus may create duplicate files and underwriters may flag fraud. Keep the exact legal name, address and phone identical on every application." },
    { id: "m08-c05", type: "term", q: "What is a D-U-N-S number?", a: "Dun & Bradstreet's nine-digit identifier for a business. D&B states there is no cost to request one; normal processing takes up to 30 business days, with a paid option in about eight." },
    { id: "m08-c06", type: "number", q: "What is the Paydex scale and what do 80 and 100 mean?", a: "1 to 100. 80 means you pay on time, zero days beyond terms. 100 means you pay about 30 days early. Lenders generally treat 80+ as good. Source: Nav." },
    { id: "m08-c07", type: "number", q: "What does it take to generate a Paydex score?", a: "At least two tradelines reporting and three trade experiences, which typically appears around day 90 to 120 after your first vendor orders. Source: Nav." },
    { id: "m08-c08", type: "term", q: "What does it mean that Paydex is dollar-weighted?", a: "Each payment experience is weighted by its dollar value, so paying a $2,000 invoice late hurts far more than paying a $60 one late." },
    { id: "m08-c09", type: "trap", q: "You pay every vendor invoice on day 30. Why is your Paydex stuck at 80?", a: "80 is the on-time score; higher scores require paying early. Pay the day the invoice posts to push above 80." },
    { id: "m08-c10", type: "term", q: "What are the other major business credit files besides D&B?", a: "Experian Business, Equifax Business, and the Small Business Financial Exchange (SBFE), a data pool many banks report to and read. Prefer vendors that report to more than one." },
    { id: "m08-c11", type: "term", q: "What is a net-30 account?", a: "A vendor agreement that lets your business receive goods now and pay the invoice within 30 days. It only builds credit if the vendor reports to a business bureau." },
    { id: "m08-c12", type: "number", q: "How many reporting net-30 vendors should you open in months one through three?", a: "Three to five, each confirmed in writing to report to at least one business bureau, buying things you actually need and paying early." },
    { id: "m08-c13", type: "trap", q: "A vendor's website says it builds business credit but cannot tell you which bureau it reports to. What do you assume?", a: "That it does not report. Ask the credit department which bureaus they report to today and get it in writing; reporting policies change often, as even 2026 vendor roundups warn." },
    { id: "m08-c14", type: "trap", q: "Why avoid vendors whose main product is the tradeline itself?", a: "A paid-subscription tradeline is a thin signal that experienced underwriters discount and some lenders flag. Build with real vendors selling real goods you use in rehabs." },
    { id: "m08-c15", type: "scenario", q: "You need paint sundries, fasteners and shipping boxes for direct mail this month. How do you turn that into credit?", a: "Buy them on net-30 accounts from vendors you have confirmed report, pay within days of the invoice posting, and keep the receipts. Real purchases, paid early, are the whole method." },
    { id: "m08-c16", type: "number", q: "What categories of vendors commonly offered reporting net-30 terms in 2026?", a: "Office supply, shipping supply, industrial supply and building supply distributors, several with $50–$100 minimum first orders. Source: Ramp, July 2026, which also says to confirm each vendor's current reporting." },
    { id: "m08-c17", type: "term", q: "What is a personal guarantee?", a: "Your personal promise to pay a business debt if the business cannot. Nearly every business credit card and new-business loan requires one, so the debt follows you home." },
    { id: "m08-c18", type: "number", q: "Which major issuers report full business card activity to personal credit bureaus as of 2026?", a: "Most Capital One Spark business cards, with a few premium ones negative-only; Discover's business card has historically reported personally too. Source: NerdWallet, updated Apr 22, 2026. Verify before applying." },
    { id: "m08-c19", type: "number", q: "Which major issuers report business cards to personal bureaus only when seriously delinquent, as of 2026?", a: "American Express, Bank of America, Chase, U.S. Bank and Wells Fargo, per NerdWallet (Apr 2026). Policies change; confirm with the issuer." },
    { id: "m08-c20", type: "number", q: "Does applying for a business credit card affect personal credit even if the card never reports?", a: "Yes. Every application triggers a hard inquiry on your personal report, and the approval is based on your personal score and income." },
    { id: "m08-c21", type: "number", q: "How much of a FICO score is amounts owed, and how much is payment history?", a: "Amounts owed about 30%, payment history about 35%, length of history 15%, new credit 10%, credit mix 10%. Source: myFICO." },
    { id: "m08-c22", type: "term", q: "What is credit utilization?", a: "Your revolving balances divided by your limits. A $20,000 rehab balance on a $25,000 card that reports personally is 80% utilization on that card and hits the amounts-owed part of your score." },
    { id: "m08-c23", type: "trap", q: "You charge $25,000 of rehab materials to a Capital One Spark card, then apply for a DSCR refinance the next month. What happens?", a: "The balance reports as personal utilization, your FICO can drop a tier, and the lender prices or sizes the loan on the lower score. Use a negative-only issuer or pay the card to near zero before the statement date." },
    { id: "m08-c24", type: "scenario", q: "Your partner has a 740 score and wants to open one business card before the first rehab. Which type should it be?", a: "A card from an issuer that reports only negative information to personal bureaus, with a 0% intro period timed to cover the rehab, so the materials balance stays off personal utilization during the refinance." },
    { id: "m08-c25", type: "number", q: "What were typical 0% intro periods and post-intro rates on business cards in late 2026?", a: "Twelve months is the standard intro period, some shorter; afterward roughly 16–28% variable APR depending on card and credit. Source: NerdWallet, updated Oct 1, 2026." },
    { id: "m08-c26", type: "formula", q: "How much does a 0% card save versus hard money on $22,000 of materials for 7 months?", a: "Hard money at 11%: $22,000 × 0.11 × 7 ÷ 12 ≈ $1,410. Card at 0%: $0. Savings about $1,410, if the card is paid off before the intro period ends." },
    { id: "m08-c27", type: "trap", q: "Your 0% intro period ends in month 12 and the refinance slips to month 14. What did you miss?", a: "Refinances slip for appraisal, seasoning and tenant reasons. Plan the payoff assuming a three-month delay, know the full-rate payment, and confirm reserves or cash flow could carry it." },
    { id: "m08-c28", type: "trap", q: "You skip one minimum payment during a 0% promo because the balance is interest-free. Problem?", a: "Minimum payments are still due monthly and a missed payment can void the promotional rate under the card agreement. Set autopay for at least the minimum from the business account on day one." },
    { id: "m08-c29", type: "number", q: "What do contractors typically charge to accept a credit card?", a: "Many cannot take cards at all; those who do often add a surcharge of around 3%, which eats into the 0% savings. Use cards mainly for materials and appliances." },
    { id: "m08-c30", type: "number", q: "What credit limits should a brand-new business expect on its first bank card?", a: "Often $5,000 to $15,000, not $40,000. Plan a rehab materials budget around real limits and ask for increases after six on-time months." },
    { id: "m08-c31", type: "number", q: "What belongs in months one and two of the build order?", a: "Entity, EIN, business bank account, business phone and website, D-U-N-S request, 3–5 reporting net-30 vendors with small real orders, and cleaning up both partners' personal credit reports." },
    { id: "m08-c32", type: "number", q: "What belongs in months three to five of the build order?", a: "Confirm a Paydex has generated, verify tradelines at Experian Business, add one or two retailer store or fleet cards, and open a first bank business card from a negative-only issuer with a 0% intro." },
    { id: "m08-c33", type: "number", q: "What belongs in months six to twelve of the build order?", a: "A second negative-only bank card from a different issuer, a business line of credit at your deposit bank once the account has 6–12 months of history, limit increases, and an audit of all three bureau files." },
    { id: "m08-c34", type: "trap", q: "Why not apply for every vendor, card and line in month one?", a: "A burst of hard inquiries and thin history produces denials, and new credit is about 10% of your FICO. Space applications 30–60 days apart and never within 60 days of a mortgage or DSCR application." },
    { id: "m08-c35", type: "scenario", q: "You plan a DSCR refinance in 45 days and a great business card offer appears. Apply?", a: "No. Wait until the refinance funds. A hard inquiry and a new account right before underwriting can cost a FICO tier and raise questions about undisclosed debt." },
    { id: "m08-c36", type: "number", q: "Why should both partners pull personal credit reports before the business credit build?", a: "Every business card and line in year one is approved on the partners' personal scores. Dispute errors and get personal utilization under about 10% before applying for anything." },
    { id: "m08-c37", type: "term", q: "What is a business line of credit?", a: "A revolving loan to your company: draw up to the limit, pay interest only on the drawn amount, repay and redraw. It funds by transfer to your bank account, so it can pay a contractor or float a hard money draw." },
    { id: "m08-c38", type: "number", q: "What did bank versus online business lines require in late 2026?", a: "A major bank line listed a 680 minimum score and 6 months in business; online lenders listed 600–680 scores, 3–12 months, and $30,000–$120,000 revenue minimums, with rates from about 7.8% for the best files. Source: NerdWallet, Oct 2026." },
    { id: "m08-c39", type: "scenario", q: "Your LLC has no revenue yet and you want a line of credit. What is realistic?", a: "A small line based on personal credit or a secured line backed by a deposit. Use cards and vendors for deal one, bank six months of rent, then apply at your deposit bank." },
    { id: "m08-c40", type: "term", q: "What is a secured business line of credit?", a: "A line backed by cash you deposit with the bank. It is easy to get, cheap, and builds bank history even before the company has revenue." },
    { id: "m08-c41", type: "trap", q: "A lender quotes a factor rate of 1.25 on a six-month advance. Is that 25% interest?", a: "No. You repay 125% of the advance in six months, roughly 50% annualized. Ask every lender for the APR in writing and compare only APRs." },
    { id: "m08-c42", type: "term", q: "What is a merchant cash advance?", a: "An advance against future revenue repaid by daily or weekly automatic withdrawals, priced as a factor rate. It is not a line of credit and its effective annual cost is usually far above 50%." },
    { id: "m08-c43", type: "trap", q: "Why is a merchant cash advance especially dangerous for a rental company?", a: "Daily withdrawals continue during a vacancy when deposits stop, draining the business account. Anything repaid daily or weekly does not belong in a BRRRR capital stack." },
    { id: "m08-c44", type: "number", q: "What red flags did the FTC describe in its 2020 business funder case?", a: "Promises of no personal guaranty and no up-front cost that were false, less funding than promised, up-front fees, personal guarantees required anyway, and confessions of judgment. Source: FTC consumer alert, June 2020." },
    { id: "m08-c45", type: "term", q: "What is a confession of judgment?", a: "A document that lets a lender obtain a court judgment against you without a hearing if you miss a payment. If it is in a funding agreement, walk away." },
    { id: "m08-c46", type: "scenario", q: "A company offers guaranteed $100,000 in 0% business funding for a 10% fee paid when you sign. What do you do?", a: "Decline. No legitimate lender can guarantee approval, and fees before funding are the signature of advance-fee fraud. If you use a consultant at all, pay only on funded dollars and get the issuers' names first." },
    { id: "m08-c47", type: "number", q: "What does legitimate business funding look like?", a: "A stated APR, a credit check before approval, a disclosed personal guarantee for a new business, fees taken at closing from proceeds, and an agreement you can take to a lawyer." },
    { id: "m08-c48", type: "scenario", q: "A funding consultant says they can get you $60,000 in cards for 10% of the limits. Is there any version worth doing?", a: "Only if the fee is contingent on funded limits, the issuers are named in advance, and you accept that you are paying someone to submit applications you could submit yourself after reading this module." },
    { id: "m08-c49", type: "term", q: "What is the Small Business Financial Exchange (SBFE)?", a: "A data pool where many banks and lenders report business loan and card performance and from which they pull. Bank cards and lines you pay well build this file." },
    { id: "m08-c50", type: "scenario", q: "Month 12: you have a Paydex, four vendor lines, two negative-only bank cards and a $10,000 secured line. What can this actually fund on a BRRRR deal?", a: "Materials and appliances on the 0% cards, small supplies on net-30, and a draw gap or deposit from the line. Not the purchase and not the full rehab; those still come from hard or private money." }
  ],
  quiz: [
    { id: "m08-q01", q: "What is the correct first three steps to start a business credit file?", opts: ["Form the entity, get the EIN, open a business bank account in the exact legal name", "Apply for a business card, then form an LLC, then open a bank account", "Request a D-U-N-S number, then form the entity", "Open net-30 accounts under your personal name"], correct: 0, explain: "The entity must exist, have an EIN and a bank account before bureaus and vendors can attach anything to it." },
    { id: "m08-q02", q: "According to the IRS, what does an EIN cost?", opts: ["$50", "$99 through an approved provider", "Nothing; it is free and issued immediately online", "It varies by state"], correct: 2, explain: "The IRS says you never have to pay for an EIN and issues it immediately online when approved, one per responsible party per day." },
    { id: "m08-q03", q: "What does Dun & Bradstreet say about the cost and timing of a D-U-N-S number?", opts: ["$229, instant", "Free but only for corporations", "Only available through a bank", "Free, up to 30 business days, with a paid expedited option"], correct: 3, explain: "D&B states there is no cost to request one, normal processing takes up to 30 business days, and expedited service is paid." },
    { id: "m08-q04", q: "A Paydex of 80 means your business:", opts: ["Pays 20 days late on average", "Pays about 30 days early", "Pays on time, zero days beyond terms", "Has 80 tradelines"], correct: 2, explain: "80 is the on-time score; 100 means paying roughly 30 days early. Lenders treat 80+ as good." },
    { id: "m08-q05", q: "Per Nav, what is needed before a Paydex score generates?", opts: ["Two tradelines reporting and three trade experiences", "One tradeline and one payment", "Five tradelines and a bank loan", "A business credit card only"], correct: 0, explain: "Two reporting tradelines and three experiences, which typically takes about 90 to 120 days after first orders." },
    { id: "m08-q06", q: "You pay every reporting vendor exactly on day 30. Your Paydex will likely settle around:", opts: ["100", "90", "80", "60"], correct: 2, explain: "On-time payment earns 80. Paying early is what moves a Paydex above 80." },
    { id: "m08-q07", q: "A net-30 vendor cannot tell you which bureau it reports to. The best assumption is:", opts: ["It reports to all three", "It reports to D&B only", "It does not report, so it builds nothing", "It reports to your personal credit"], correct: 2, explain: "Only reporting vendors build a file. Get the bureau names in writing; 2026 vendor roundups warn that reporting changes often." },
    { id: "m08-q08", q: "Which of these is the weakest signal to underwriters when building business credit?", opts: ["A building supply distributor you buy fasteners from", "A shipping supply account used for direct mail", "A paid subscription whose main product is reporting a tradeline", "A fuel card used for job-site trips"], correct: 2, explain: "Tradeline-for-a-fee products are thin signals that experienced underwriters discount and some lenders flag." },
    { id: "m08-q09", q: "As of NerdWallet's April 2026 roundup, which issuer family reports most business card activity to personal credit bureaus?", opts: ["American Express", "Chase", "Capital One Spark", "Wells Fargo"], correct: 2, explain: "Most Capital One Spark cards report full activity personally; Amex, Chase, Bank of America, U.S. Bank and Wells Fargo report negative information only. Verify before applying." },
    { id: "m08-q10", q: "Which part of a FICO score does a large reported card balance hit?", opts: ["Payment history (35%)", "Length of history (15%)", "Credit mix (10%)", "Amounts owed (30%)"], correct: 3, explain: "Utilization falls under amounts owed, about 30% of the score per myFICO." },
    { id: "m08-q11", q: "You charge $25,000 of materials to a business card that reports to your personal bureaus, then apply for a DSCR refinance. The likely result is:", opts: ["No effect; business debt is separate", "A FICO drop from utilization that can cost a pricing or LTV tier", "A higher DSCR", "An automatic denial"], correct: 1, explain: "Reported utilization lowers your personal score during underwriting. Use a negative-only issuer or pay down before the statement closes." },
    { id: "m08-q12", q: "What was the standard 0% intro period on business cards in late 2026, per NerdWallet?", opts: ["6 months", "21 months", "36 months", "12 months"], correct: 3, explain: "Twelve months is standard, some shorter, with roughly 16–28% variable APR afterward. Updated Oct 1, 2026." },
    { id: "m08-q13", q: "Compared with hard money at 11%, roughly how much does a 0% card save on $22,000 of materials carried 7 months and paid off in time?", opts: ["About $1,410", "About $400", "About $2,420", "Nothing"], correct: 0, explain: "$22,000 × 0.11 × 7 ÷ 12 ≈ $1,410 of hard money interest avoided." },
    { id: "m08-q14", q: "Which is the safest planning assumption for paying off a 0% rehab balance?", opts: ["The refinance closes exactly when scheduled", "The refinance runs about three months late and you know the full-rate payment", "The intro period will be extended on request", "The tenant's deposit will cover it"], correct: 1, explain: "Appraisals, seasoning and tenant placement slip. Plan the exit assuming delay and confirm reserves could carry the balance at the full rate." },
    { id: "m08-q15", q: "Why avoid applying for business credit within 60 days of a DSCR or mortgage application?", opts: ["It is illegal", "Hard inquiries and a new account can lower your FICO and raise underwriting questions", "Business credit cancels DSCR eligibility", "Lenders require 90 days of no spending"], correct: 1, explain: "New credit is about 10% of FICO and underwriters scrutinize fresh accounts. Space applications and protect the window before a refinance." },
    { id: "m08-q16", q: "In the build order, a business line of credit at your deposit bank is realistic:", opts: ["In month one with the EIN letter", "Only after ten rentals", "Never for an LLC", "After the business account shows 6–12 months of deposits"], correct: 3, explain: "Banks want account history and revenue. Rent deposits count as revenue once flowing, so the line follows deal one." },
    { id: "m08-q17", q: "A lender quotes a factor rate of 1.25 on a six-month advance. The annualized cost is closest to:", opts: ["12.5%", "25%", "50%", "6%"], correct: 2, explain: "You repay 125% in six months, roughly 50% annualized. Ask for the APR in writing and compare only APRs." },
    { id: "m08-q18", q: "Which repayment pattern tells you an offer is a merchant cash advance rather than a line of credit?", opts: ["Daily or weekly automatic withdrawals", "Interest-only monthly on the drawn balance", "Annual review of the limit", "A variable rate tied to prime"], correct: 0, explain: "Daily or weekly debits and factor-rate pricing mark an MCA, which can drain a rental company's account during a vacancy." },
    { id: "m08-q19", q: "Which of the following did the FTC describe in its 2020 business funder case?", opts: ["Lenders who refused to lend to LLCs", "Banks that reported to the wrong bureau", "Vendors that stopped offering net-30", "False no-personal-guaranty promises, up-front fees and confessions of judgment"], correct: 3, explain: "The FTC alert describes false promises, hidden fees, personal guarantees required anyway, and confessions of judgment that waive your day in court." },
    { id: "m08-q20", q: "A company guarantees $100,000 of 0% business funding for a 10% fee due at signing. The correct response is:", opts: ["Pay the fee if they promise a refund", "Negotiate the fee to 5%", "Decline; guaranteed approval plus fees before funding is the signature of advance-fee fraud", "Accept if they have a website"], correct: 2, explain: "No legitimate lender can guarantee approval, and fees before funding are the core red flag. Pay any consultant only on funded dollars." }
  ],
  drills: [
    "Write your entity's exact legal name, EIN, business address and business phone on one card and check that the state filing, IRS letter, bank account and any existing vendor account match character for character. Fix any mismatch today.",
    "Request your D-U-N-S number on dnb.com using the free option, and pull both partners' personal credit reports. List every error to dispute and every card above 10% utilization to pay down.",
    "Call the credit departments of five net-30 vendors whose products you would actually buy and ask which business bureaus they report to today and whether there is a minimum first order. Open the three best and place one small real order.",
    "Build a two-column list of business card issuers: those that report full activity to personal bureaus and those that report negative-only, confirming each with the issuer's current policy. Pick the first card you will apply for and the month you will apply.",
    "Write the 0% rehab plan for your first deal: materials budget, card limit you realistically expect, the month the refinance should close, the month the intro period ends, and the payment at the full rate if the refinance slips three months.",
    "Draft your 12-month business credit calendar with one action per month, spacing applications at least 30 days apart and blocking out the 60 days before any planned DSCR refinance."
  ]
});
