BIBLE.register({
  id: "m09",
  part: 4,
  title: "The Tax Code: How Real Estate Investors Keep More",
  icon: "🧾",
  summary: "How rental real estate produces cash in your pocket while showing a loss on paper, which rules let you use that loss, and how to avoid the tax traps that catch new investors.",
  minutes: 95,
  lessons: [
    {
      id: "m09-01",
      title: "Paid in Cash, Taxed on Paper",
      minutes: 9,
      blocks: [
        { h: "Why real estate is tax-favored", p: "Most income is taxed as you earn it. Rental real estate is different because the tax code lets you deduct a slice of the building's cost every year even though you did not spend that money this year. That deduction is called depreciation. It is a real deduction against real income, but it costs you nothing out of pocket. The result is that a rental can put cash in your bank account while the tax return shows little or no taxable income, and sometimes a loss." },
        { h: "What depreciation is", p: "Depreciation is the IRS's way of recognizing that a building wears out. For residential rental property, you deduct the cost of the building (not the land) in equal pieces over 27.5 years using the straight-line method. Land never wears out in the eyes of the tax code, so land is not depreciable. You have to split your purchase price between land and building, usually by using the ratio on the county property appraiser's record or an appraisal. Depreciation starts the month the property is placed in service, meaning ready and available to rent, not the month you close." },
        { formula: "Annual depreciation = (Purchase price − Land value + Capitalized closing and rehab costs) ÷ 27.5" },
        { example: "You buy a rental for $150,000 and spend $30,000 on rehab before renting it. The county says land is 20% of value, so land is $30,000 and the depreciable basis is $150,000 − $30,000 + $30,000 = $150,000. Annual depreciation = $150,000 ÷ 27.5 = $5,455. Say the property clears $3,600 a year in cash flow after all expenses and mortgage payments. Add back the principal portion of the payments (say $2,400, since principal is not deductible) for about $6,000 of taxable income before depreciation. Subtract $5,455 of depreciation and taxable income is about $545. You banked $3,600 and reported $545." },
        { carry: "Residential rental building: 27.5 years straight-line. Land is never depreciated. Depreciation is a deduction you never paid for this year." },
        { trap: "Depreciation is not optional. If you skip it, the IRS still reduces your basis as if you had taken it (this is called allowed or allowable depreciation), so you get taxed on recapture later without ever receiving the deduction. Always claim it. Also, the mortgage principal you pay is not a deduction; only the interest is. Tax rules have exceptions and your facts matter. Confirm everything in this lesson with a CPA who works with rental property investors." },
        { sources: [
          { t: "IRS Publication 527, Residential Rental Property (depreciation, 27.5-year recovery, land not depreciable)", u: "https://www.irs.gov/publications/p527" },
          { t: "IRS Publication 946, How To Depreciate Property", u: "https://www.irs.gov/publications/p946" }
        ] }
      ]
    },
    {
      id: "m09-02",
      title: "Cost Segregation and 100% Bonus Depreciation",
      minutes: 10,
      blocks: [
        { h: "What cost segregation is", p: "A cost segregation study is an engineering-based report that breaks a property into its parts. Instead of treating the whole building as one 27.5-year asset, the study identifies items that the tax code lets you depreciate faster: carpet, appliances, cabinets, and certain fixtures over 5 or 7 years, and land improvements like fences, driveways, and landscaping over 15 years. Only the structure itself stays at 27.5 years. A study on a small single-family rental can be done cheaply with a software-based report; larger properties use a full engineering study." },
        { h: "What bonus depreciation does", p: "Bonus depreciation lets you deduct a large percentage of the cost of qualifying property in the first year instead of spreading it out. Qualifying property is property with a recovery period of 20 years or less, so the 5-, 7-, and 15-year items a cost segregation study finds are exactly what bonus depreciation applies to. The 27.5-year building itself never qualifies. Cost segregation and bonus depreciation work together: the study finds the short-life property, and bonus depreciation lets you write most of it off at once." },
        { h: "The current rule after the 2025 law", p: "The One Big Beautiful Bill Act, signed July 4, 2025, permanently restored 100% bonus depreciation for qualifying property acquired and placed in service after January 19, 2025. Before that law, bonus depreciation had been phasing down: 80% in 2023, 60% in 2024, and 40% in 2025. Property you acquired on or before January 19, 2025 but placed in service later stays on the old phase-down schedule (40% in 2025, 20% in 2026, then zero). For anything you buy from now on, the default is 100%. The 2025 law also raised the Section 179 expensing limit to $2.5 million with a $4 million phase-out, but Section 179 generally does not apply to residential rental property, so bonus depreciation is the tool that matters to you." },
        { example: "You buy a $200,000 rental (building portion $160,000) in 2026. A cost segregation study assigns $25,000 to 5-year property and $15,000 to 15-year land improvements. With 100% bonus depreciation, you deduct the full $40,000 in year one plus regular depreciation on the remaining $120,000 of building, about $4,364. First-year depreciation is about $44,364 instead of about $5,818 without the study (full-year building figures; the mid-month convention trims the building portion in the year you place it in service)." },
        { carry: "100% bonus depreciation is permanent for property acquired and placed in service after January 19, 2025 (OBBBA, signed July 4, 2025). It applies to 5-, 7-, and 15-year property, never to the 27.5-year building." },
        { trap: "A big first-year loss is only useful if you can deduct it. Rental losses are passive, and if your income is too high and you do not qualify as a real estate professional, the loss is suspended and carried forward. Paying for a cost segregation study to create a loss you cannot use this year is wasted money. Read the next two lessons before you order a study. Also remember that accelerated depreciation means more depreciation recapture when you sell, which is one more reason BRRRR investors hold instead of selling. Whether a cost segregation study pays for itself depends on your income, your filing status, and your plans for the property. Confirm with a CPA before you order one." },
        { sources: [
          { t: "BDO: One Big Beautiful Bill Act Expands 100% Depreciation Expensing Opportunities (acquired and placed in service after Jan 19, 2025; transition rules; Section 179 limits)", u: "https://www.bdo.com/insights/tax/one-big-beautiful-bill-act-expands-100-depreciation-expensing-opportunities" },
          { t: "Jones Day: The One Big Beautiful Bill Becomes Law, Key Real Estate Tax Changes", u: "https://www.jonesday.com/en/insights/2025/07/the-one-big-beautiful-bill-becomes-law-real-estate-tax-changes" },
          { t: "IRS Publication 946, How To Depreciate Property (recovery periods, bonus depreciation)", u: "https://www.irs.gov/publications/p946" }
        ] }
      ]
    },
    {
      id: "m09-03",
      title: "Passive Activity Rules: Who Gets to Use the Loss",
      minutes: 10,
      blocks: [
        { h: "Rental losses are passive by default", p: "Internal Revenue Code Section 469 sorts your income into buckets. Wages, business income you actively run, and investment income like interest and dividends are in one group. Rental activity is automatically passive no matter how many hours you spend on it, unless you qualify for an exception. The rule is simple and harsh: passive losses can only offset passive income. A $20,000 rental loss cannot reduce your W-2 wages or your wholesale fees unless an exception applies." },
        { h: "The $25,000 special allowance", p: "The most common exception is the special allowance for rental real estate with active participation. If you actively participate, which means you make management decisions like approving tenants, setting rent, and approving repairs (you can still use a property manager), you may deduct up to $25,000 of rental losses per year against your other income. The allowance phases out as your modified adjusted gross income rises. It is reduced by half of the amount your MAGI exceeds $100,000, so it is fully gone at $150,000 of MAGI. Married couples filing jointly share one $25,000 allowance. If you are married filing separately and lived with your spouse at any time during the year, the allowance is zero.\n\nSuspended losses are not lost. A suspended passive loss carries forward indefinitely. It is released in two ways: when you have passive income in a later year, or when you dispose of your entire interest in the activity in a fully taxable sale to an unrelated person. In that year of sale, all the suspended losses from that property are freed and can offset any income, including wages. This is why a rental that shows losses for ten years is not wasting them; it is banking them." },
        { formula: "Allowance = $25,000 − 0.50 × (MAGI − $100,000), never below zero" },
        { example: "Your MAGI is $120,000 and your rentals lose $18,000. Allowance = $25,000 − 0.50 × $20,000 = $15,000. You deduct $15,000 this year and the other $3,000 is suspended. At $150,000 of MAGI the allowance is zero and the whole $18,000 is suspended." },
        { carry: "Rental losses are passive. Up to $25,000 a year is deductible against other income if you actively participate, reduced by half of MAGI over $100,000, gone at $150,000. Suspended losses carry forward and release on sale." },
        { trap: "People hear that bonus depreciation creates a big loss and assume it wipes out their day-job taxes. If both partners have good W-2 incomes, the $25,000 allowance may already be phased out and the loss just sits there. Model your MAGI before you count on any loss. Note that MAGI for this test is computed with some adjustments, such as adding back IRA deductions and excluded Social Security, so ask your CPA which number applies. Your MAGI, your filing status, and how your activities are grouped all change the answer. Confirm with a CPA before you rely on a rental loss." },
        { sources: [
          { t: "IRS Publication 925, Passive Activity and At-Risk Rules ($25,000 special allowance, active participation, MAGI phase-out, disposition rules)", u: "https://www.irs.gov/pub/irs-pdf/p925.pdf" },
          { t: "26 U.S. Code § 469, Passive activity losses and credits limited", u: "https://www.law.cornell.edu/uscode/text/26/469" }
        ] }
      ]
    },
    {
      id: "m09-04",
      title: "Real Estate Professional Status and the Short-Term Rental Exception",
      minutes: 11,
      blocks: [
        { h: "The two tests", p: "Section 469(c)(7) lets a real estate professional treat rental losses as non-passive, which means they can offset wages and other income with no $25,000 cap. To qualify in a given year you must pass two tests. First, you perform more than 750 hours of services in real property trades or businesses in which you materially participate. Second, more than half of all the personal services you perform in all trades or businesses during the year are in those real property businesses. Real property trades or businesses include development, construction, acquisition, rental, management, leasing, and brokerage." },
        { h: "Why a full-time job usually blocks it", p: "The second test is the killer for W-2 earners. If you work 2,000 hours a year at a job, you would need more than 2,000 hours in real estate to have more than half of your time in real estate. That is almost never true, and the IRS and Tax Court look hard at hour logs that claim it. Hours as an employee only count toward real estate if you own more than 5% of the employer. Separately, each rental must also pass a material participation test, usually more than 500 hours per activity, or 100 hours and more than anyone else. Most investors with several rentals make a one-time election to treat all rentals as a single activity so they pass material participation once." },
        { h: "The spouse rule", p: "On a joint return, one spouse alone must satisfy both the 750-hour test and the more-than-half test. You cannot combine two spouses' hours to reach 750. However, once one spouse qualifies, the hours of both spouses count toward material participation in each rental. This is why a common structure is one partner or spouse working a W-2 job and the other running the real estate full time." },
        { h: "The short-term rental exception", p: "The passive activity regulations say that an activity is not a rental activity at all if the average period of customer use is seven days or less. A second version covers an average stay of thirty days or less when you provide significant personal services like daily cleaning. If your property is not a rental activity under this rule, it is treated like any other business, and you do not need real estate professional status. You still must materially participate (for example, more than 100 hours and more than anyone else, including your cleaner and your manager) for the loss to be non-passive. This is the so-called short-term rental loophole. It is a real rule in the regulations, not a trick, but the hour tracking is strict and a property that averages eight days of stay fails it." },
        { carry: "REPS: more than 750 hours AND more than half of all your working hours in real property businesses, one spouse alone, plus material participation in the rentals. STR exception: average stay 7 days or less is not a rental activity (Reg. 1.469-1T(e)(3)(ii)(A))." },
        { trap: "Keep a contemporaneous log. Reconstructing hours from memory at audit time is the most common way real estate professional claims fail in Tax Court. Log the date, the property, the task, and the time, and do it weekly. Investor education, travel to look at properties you do not own, and reading about real estate generally do not count as participation hours. Real estate professional status is one of the most audited positions in the code. Confirm your eligibility and your log format with a CPA before you claim it." },
        { sources: [
          { t: "26 U.S. Code § 469(c)(7), Special rules for taxpayers in real property business", u: "https://www.law.cornell.edu/uscode/text/26/469" },
          { t: "IRS Publication 925 (real estate professional tests, material participation tests, spouse rule)", u: "https://www.irs.gov/pub/irs-pdf/p925.pdf" },
          { t: "26 CFR 1.469-1T(e)(3)(ii), exceptions to rental activity definition (seven-day and thirty-day rules)", u: "https://www.law.cornell.edu/cfr/text/26/1.469-1T" },
          { t: "The Tax Adviser: Navigating the Real Estate Professional Rules", u: "https://www.thetaxadviser.com/issues/2017/mar/navigating-real-estate-professional-rules/" },
          { t: "Withum: Tax Implications for Short-Term Rental Property Owners", u: "https://www.withum.com/resources/tax-implications-for-short-term-rental-property-owners/" }
        ] }
      ]
    },
    {
      id: "m09-05",
      title: "Selling: Capital Gains, Recapture, and the 1031 Exchange",
      minutes: 11,
      blocks: [
        { h: "What you owe when you sell", p: "When you sell a rental you have held more than one year, your gain is split into two pieces. The part of the gain that comes from depreciation you took (or were allowed to take) is called unrecaptured Section 1250 gain, and it is taxed at your ordinary rate but capped at a maximum of 25%. The rest of the gain is long-term capital gain taxed at 0%, 15%, or 20% depending on your taxable income. For 2026, the 0% rate applies up to $49,450 of taxable income for single filers and $98,900 for married filing jointly; the 20% rate starts above $545,500 single and $613,700 joint. On top of that, the 3.8% net investment income tax applies to rental gains when your modified adjusted gross income exceeds $200,000 single or $250,000 joint. Your state may add its own tax." },
        { example: "You bought a rental for $150,000 (building $120,000), held it eight years, and took $35,000 of depreciation, so your adjusted basis is $115,000. You sell for $220,000 net of selling costs. Total gain is $105,000. The first $35,000 is unrecaptured Section 1250 gain taxed at up to 25%, about $8,750. The remaining $70,000 is long-term capital gain; at 15% that is $10,500. Plus possibly 3.8% NIIT. Total federal tax is roughly $19,000 to $23,000 before state tax." },
        { h: "The 1031 exchange", p: "Section 1031 lets you sell investment real property and buy other investment real property without paying tax now, as long as you follow the rules exactly. Since 2018, only real property qualifies. Like-kind is broad: a rental house for an apartment building, land for a duplex. You must use a qualified intermediary, a neutral third party who holds the sale proceeds; if you touch the cash, the exchange fails. You have 45 days from closing the sale to identify replacement property in writing, and 180 days from the sale (or your tax return due date, if earlier) to close on it. To defer all the tax, you buy property of equal or greater value and reinvest all the equity; any cash or debt relief you keep is called boot and is taxable. The deferred gain and the old depreciation carry over into the new property's basis, so this is a deferral, not forgiveness." },
        { carry: "Depreciation recapture on real estate: up to 25%. Long-term capital gains: 0%, 15%, 20% plus 3.8% NIIT over $200K/$250K MAGI. 1031: 45 days to identify, 180 days to close, qualified intermediary, real property only." },
        { h: "Why BRRRR investors rarely sell", p: "Selling triggers recapture, capital gains, and possibly state tax, and it ends the cash flow. Refinancing lets you pull equity out tax-free (next lesson) and keep the asset, the depreciation, and the tenant paying down the loan. When BRRRR investors do sell, they usually either 1031 into a bigger property or sell in a low-income year to release suspended losses and use the 0% bracket." },
        { trap: "The 45-day clock starts the day you close the sale, not the day you decide to exchange. Investors who sell first and then call an intermediary have already blown the exchange because the proceeds went to them. Line up the qualified intermediary before closing. Sale math depends on your basis records and your bracket for the year. Confirm the numbers with a CPA before you list a property, and involve the qualified intermediary before you sign a contract." },
        { sources: [
          { t: "IRS Publication 544, Sales and Other Dispositions of Assets (Section 1250 property, unrecaptured gain)", u: "https://www.irs.gov/publications/p544" },
          { t: "IRS Topic No. 409, Capital Gains and Losses (0/15/20% rates, 25% maximum on unrecaptured Section 1250 gain)", u: "https://www.irs.gov/taxtopics/tc409" },
          { t: "2026 capital gains thresholds (per Rev. Proc. 2025-32)", u: "https://reedcorp.tax/helpful-guides/2026-capital-gains-tax-brackets/" },
          { t: "IRS Fact Sheet FS-08-18, Like-Kind Exchanges Under IRC Section 1031 (45/180 days, qualified intermediary)", u: "https://www.irs.gov/pub/irs-news/fs-08-18.pdf" },
          { t: "IRS Topic No. 559, Net Investment Income Tax", u: "https://www.irs.gov/taxtopics/tc559" }
        ] }
      ]
    },
    {
      id: "m09-06",
      title: "Refinance Proceeds Are Not Income, and the Step-Up at Death",
      minutes: 7,
      blocks: [
        { h: "Borrowed money is not income", p: "The R in BRRRR is a cash-out refinance. When the bank hands you $60,000 of your equity, you owe no income tax on it, because loan proceeds are not income. You have to pay the money back, so it is not a gain. The interest you pay on that loan stays deductible as a rental expense to the extent the proceeds are used in the rental activity. If you spend refinance cash on personal items, the interest on that portion is not a rental deduction under the interest tracing rules. This is the engine of the whole strategy: you recover your capital tax-free and keep the asset." },
        { h: "Stepped-up basis at death", p: "Section 1014 says that when you die, the people who inherit your property get a new basis equal to its fair market value on the date of death. All the depreciation you took and all the appreciation during your life disappear for income tax purposes. If your heirs sell the next day for that value, there is no capital gain and no recapture. They also start depreciating again from the new, higher basis. For 2026, the federal estate tax exemption is $15 million per person under the 2025 law, so most portfolios owe no estate tax either." },
        { h: "Buy, borrow, die", p: "Put the two rules together and you get the strategy wealthy families have used for generations. Buy appreciating property. Borrow against it tax-free whenever you need cash instead of selling. Die holding it, and the basis steps up so the deferred gain is never taxed. It is legal, it is in the statute, and it rewards holding. It also means your estate plan matters: property held in a revocable living trust still gets the step-up, while property you gift during life carries your old basis to the recipient." },
        { carry: "Cash-out refinance proceeds: not taxable income. At death, basis steps up to fair market value (IRC 1014), erasing deferred gain and recapture. 2026 federal estate exemption: $15 million per person." },
        { trap: "Giving a property to your children during your life to avoid probate hands them your low basis and your recapture bill. Letting them inherit it instead gives them a fresh basis. Talk to an estate attorney before you deed anything to family. Interest tracing and estate planning interact with your personal situation. Confirm with a CPA and an estate planning attorney." },
        { sources: [
          { t: "IRS Publication 525, Taxable and Nontaxable Income (loan proceeds are not income)", u: "https://www.irs.gov/publications/p525" },
          { t: "26 U.S. Code § 1014, Basis of property acquired from a decedent", u: "https://www.law.cornell.edu/uscode/text/26/1014" },
          { t: "IRS Publication 527 (interest tracing and refinance proceeds used for rental activity)", u: "https://www.irs.gov/publications/p527" },
          { t: "ACTEC commentary on the One Big Beautiful Bill ($15 million estate exemption for 2026)", u: "https://www.actec.org/capital-letter/one-big-beautiful-bill-commentary/" }
        ] }
      ]
    },
    {
      id: "m09-07",
      title: "Active Income: Wholesaling, Flipping, S-Corps, and QBI",
      minutes: 11,
      blocks: [
        { h: "Assignment fees and flip profits are ordinary income", p: "When you wholesale a contract for a $10,000 assignment fee or flip a house for a $40,000 profit, that money is not a capital gain and it is not passive. It is ordinary business income, taxed at your regular bracket, and because you are self-employed it is also subject to self-employment tax. Self-employment tax is 15.3%: 12.4% for Social Security on net earnings up to the wage base ($184,500 for 2026) plus 2.9% for Medicare on all of it, with an additional 0.9% Medicare tax above $200,000 single or $250,000 joint. You can deduct half of the self-employment tax when computing income tax, but it still bites." },
        { h: "Dealer versus investor", p: "The IRS does not care what you call yourself; it looks at what you do. If you buy property primarily to resell it, you are a dealer and that property is inventory, so the profit is ordinary income with no depreciation, no installment sale deferral, and no 1031 exchange. If you buy to hold and rent, you are an investor and that property gets capital gain treatment and depreciation. The factors courts weigh include your purpose when you bought, how long you held, how many sales you make, how much you improve and market the property, and whether you have a separate business selling real estate. One person can be a dealer on flips and an investor on rentals, which is exactly why you keep the two activities in separate entities with separate books." },
        { h: "When an S-corporation election helps", p: "An LLC can elect to be taxed as an S-corporation. The owner then pays themselves a salary through payroll, and only the salary is subject to Social Security and Medicare tax; the remaining profit passes through as a distribution free of self-employment tax. The catch is the reasonable compensation rule: the IRS requires that an owner who performs services be paid a reasonable salary for that work before taking distributions, and it can reclassify distributions as wages if the salary is unreasonably low. Payroll, a separate return, and bookkeeping add cost, so the election usually makes sense only once active profit is well above what you would pay yourself anyway. Never put rental property in an S-corp: pulling it out later is a taxable event, and rentals have no self-employment tax to save in the first place." },
        { h: "The qualified business income deduction after 2025", p: "Section 199A lets owners of pass-through businesses deduct up to 20% of qualified business income. The 2025 law made it permanent (it was scheduled to expire after 2025), kept the 20% rate, widened the income ranges over which limitations phase in to $75,000 for single filers and $150,000 for joint filers above the threshold, and added a $400 minimum deduction for taxpayers with at least $1,000 of qualified income from an active business, starting with tax years beginning after December 31, 2025. Wholesale and flip income can qualify. Rental income can qualify if the rental rises to the level of a trade or business; the IRS offers a safe harbor that generally requires 250 or more hours of rental services per year with records." },
        { carry: "Assignment fees and flips: ordinary income plus 15.3% self-employment tax. S-corp saves SE tax only on profit above a reasonable salary. QBI: 20%, now permanent under the 2025 law." },
        { trap: "Mixing a flip into the same LLC that holds your rentals invites the IRS to argue the whole entity is a dealer, which can cost you capital gain treatment and 1031 eligibility on the rentals. Keep active and passive in separate entities, which is the subject of the next module. The S-corp decision and the dealer question are fact-specific. Confirm with a CPA before you elect anything or file your first flip." },
        { sources: [
          { t: "IRS: Self-Employment Tax (Social Security and Medicare Taxes)", u: "https://www.irs.gov/businesses/small-businesses-self-employed/self-employment-tax-social-security-and-medicare-taxes" },
          { t: "2026 Social Security wage base $184,500", u: "https://www.paycor.com/resource-center/articles/social-security-taxable-wage-base/" },
          { t: "IRS: S Corporation Compensation and Medical Insurance Issues (reasonable compensation)", u: "https://irs.gov/businesses/small-businesses-self-employed/s-corporation-compensation-and-medical-insurance-issues" },
          { t: "RSM: Permanent QBI deduction provides some tax planning certainty (OBBBA Section 199A changes)", u: "https://rsmus.com/insights/services/business-tax/obbba-tax-qbi-deduction.html" },
          { t: "IRS: Qualified Business Income Deduction (including rental real estate safe harbor, Rev. Proc. 2019-38)", u: "https://www.irs.gov/newsroom/qualified-business-income-deduction" },
          { t: "IRS Publication 544 (dealer property held primarily for sale is not a capital asset)", u: "https://www.irs.gov/publications/p544" }
        ] }
      ]
    },
    {
      id: "m09-08",
      title: "Everyday Deductions That Add Up",
      minutes: 11,
      blocks: [
        { h: "Mileage", p: "Driving to your rentals, to meet contractors, to the hardware store, and to look at properties you are evaluating in a market where you already operate is deductible. The IRS standard mileage rate for business use in 2026 is 72.5 cents per mile for January 1 through June 30 and 76 cents per mile for July 1 through December 31, after a rare mid-year increase. Keep a log with date, destination, purpose, and miles; an app that tracks drives automatically is the easiest way. Commuting from home to a regular office is never deductible, but trips from a qualifying home office to your properties are." },
        { h: "Home office", p: "If a room or clearly defined area of your home is used regularly and exclusively for your business, you can deduct it. The simplified method is $5 per square foot up to 300 square feet, a maximum of $1,500 per year. The regular method deducts the business percentage of your actual home costs plus depreciation on that portion. Exclusive means exclusive: a desk in the family room does not qualify. For a rental business, the home office deduction is generally only available if the rental activity rises to the level of a trade or business, so ask your CPA which of your businesses it attaches to." },
        { h: "The Augusta rule", p: "Section 280A(g) says that if you rent out your personal residence for fewer than 15 days in a year, the rental income is not included in your gross income and you deduct no rental expenses. Business owners use it by having their own company rent their home for legitimate meetings, up to 14 days a year, at a documented fair market rate. The company deducts the rent and the owner receives it tax-free. It requires a real business purpose, written agreements, minutes or agendas, and a rate you can support with comparable local rentals. It does not work for a sole proprietor renting to themselves, because you cannot pay yourself rent." },
        { h: "Hiring your kids; education, travel, and meals", p: "Wages you pay your children for real work in your business are deductible to the business and taxed to the child, who usually owes little or nothing because of the standard deduction. The payroll tax treatment depends on your entity. If the business is a sole proprietorship or a partnership in which each partner is a parent of the child, wages to a child under 18 are not subject to Social Security and Medicare taxes, and wages to a child under 21 are not subject to federal unemployment tax. If the business is a corporation (including an LLC taxed as an S-corp) or a partnership with a non-parent partner, the child's wages are subject to all payroll taxes regardless of age. The work must be real, age-appropriate, documented with timesheets, and paid at a reasonable rate through a payroll record.\n\nEducation that maintains or improves skills in your existing business is deductible; education that qualifies you for a new business is not, so a course you buy before you own any property is usually a start-up cost rather than a current deduction. Travel to a market where you already do business is deductible when the primary purpose is business; travel to scout a new market before you invest there is generally a start-up or investigation cost, not a current expense. Business meals with a clear business purpose and a real counterparty are 50% deductible. Entertainment is not deductible at all. Keep receipts and write who, what, and why on each one." },
        { carry: "2026 mileage: 72.5 cents (Jan–Jun), 76 cents (Jul–Dec). Home office simplified: $5 per square foot, max 300 square feet. Augusta rule: 14 days or fewer, income excluded. Meals 50%, entertainment 0%." },
        { trap: "Deductions without records are not deductions. The IRS can disallow every mile and every meal you cannot substantiate. Set up one business bank account, one business card, a mileage app, and a photo habit for receipts on day one. Which business a deduction attaches to, and whether a cost is a current expense or a start-up cost, depends on your facts. Confirm with a CPA." },
        { sources: [
          { t: "IRS: Standard mileage rates (2026 rates including July 1 increase)", u: "https://www.irs.gov/tax-professionals/standard-mileage-rates" },
          { t: "IRS news release: 2026 business standard mileage rate 72.5 cents", u: "https://www.irs.gov/newsroom/irs-sets-2026-business-standard-mileage-rate-at-725-cents-per-mile-up-25-cents" },
          { t: "IRS: Simplified option for home office deduction", u: "https://www.irs.gov/businesses/small-businesses-self-employed/simplified-option-for-home-office-deduction" },
          { t: "IRS Publication 587, Business Use of Your Home", u: "https://www.irs.gov/publications/p587" },
          { t: "26 U.S. Code § 280A(g), dwelling unit rented fewer than 15 days", u: "https://www.law.cornell.edu/uscode/text/26/280A" },
          { t: "IRS: Family employees (child employed by parent, payroll tax rules by entity type)", u: "https://www.irs.gov/businesses/small-businesses-self-employed/family-employees" },
          { t: "IRS Publication 463, Travel, Gift, and Car Expenses (50% meals, travel rules)", u: "https://www.irs.gov/publications/p463" },
          { t: "IRS Publication 970, Tax Benefits for Education (work-related education)", u: "https://www.irs.gov/publications/p970" }
        ] }
      ]
    },
    {
      id: "m09-09",
      title: "Retirement Accounts as a Real Estate Investor",
      minutes: 8,
      blocks: [
        { h: "Solo 401(k) and self-directed IRA", p: "Once you have self-employment income from wholesaling or flipping, you can open a Solo 401(k), a retirement plan for a business owner with no employees other than a spouse. For 2026 you can defer $24,500 as the employee (plus $8,000 catch-up at age 50 or older, or $11,250 at ages 60 to 63 if the plan allows), and the business can add a profit-sharing contribution up to 25% of compensation, for a combined cap of $72,000 before catch-ups. A self-directed IRA is an ordinary IRA held by a custodian who allows alternative assets like real estate. Both can own rental property, private notes, or shares of a deal, and the income grows tax-deferred or tax-free in a Roth." },
        { h: "Prohibited transactions: you cannot self-deal", p: "Section 4975 bans any transaction between your retirement account and a disqualified person, which includes you, your spouse, your parents and grandparents, your children and their spouses, and any entity you control 50% or more. Your IRA cannot buy a property from you, sell one to you, rent to your kid, or let you stay in it for a weekend. You cannot personally do the rehab work, lend the IRA money, or personally guarantee its loan. All expenses must be paid from the account and all income must go back into it. The penalty is severe: a prohibited transaction can disqualify the entire IRA as of January 1 of that year, making the whole balance taxable plus penalties." },
        { h: "UBIT and UDFI on leveraged property", p: "Retirement accounts are tax-exempt, but two taxes can still apply. Unrelated business income tax (UBIT) hits an account that runs an active business, such as flipping houses, inside the account. Unrelated debt-financed income (UDFI) is a form of UBIT that applies when an IRA buys property with a loan: the share of the income and gain attributable to the borrowed money is taxable, filed on Form 990-T when gross unrelated income is $1,000 or more. A 401(k) plan has an exception: under Section 514(c)(9), qualified plans are generally exempt from UDFI on acquisition debt for real property. This is a major reason investors who want to use leverage inside a retirement account prefer a Solo 401(k) over an IRA. Loans to a retirement account must be non-recourse, meaning the lender can only take the property, so expect larger down payments and higher rates." },
        { carry: "2026 Solo 401(k): $24,500 employee deferral, $72,000 combined. Section 4975: no transactions with yourself or family. IRA with a loan pays UDFI; a 401(k) is generally exempt on real estate debt." },
        { trap: "The most common prohibited transaction is sweat equity: painting your IRA's rental yourself. It feels harmless and it can blow up the entire account. If the account owns it, hire everything out and pay from the account. Self-directed retirement investing is unforgiving of mistakes. Confirm the structure with a CPA and a custodian or plan provider who specializes in it." },
        { sources: [
          { t: "IRS: One-Participant 401(k) Plans", u: "https://www.irs.gov/retirement-plans/one-participant-401k-plans" },
          { t: "Fidelity: Solo 401(k) contribution limits 2025 and 2026", u: "https://www.fidelity.com/learning-center/smart-money/solo-401k-contribution-limits" },
          { t: "IRS: Retirement Topics, Prohibited Transactions (IRC 4975)", u: "https://www.irs.gov/retirement-plans/plan-participant-employee/retirement-topics-prohibited-transactions" },
          { t: "IRS Publication 598, Tax on Unrelated Business Income of Exempt Organizations (debt-financed income, Form 990-T)", u: "https://www.irs.gov/publications/p598" },
          { t: "26 U.S. Code § 514(c)(9), real property acquired by a qualified organization", u: "https://www.law.cornell.edu/uscode/text/26/514" }
        ] }
      ]
    },
    {
      id: "m09-10",
      title: "Opportunity Zones After 2025 and Property Tax Basics",
      minutes: 8,
      blocks: [
        { h: "Opportunity Zones: the program is now permanent", p: "An Opportunity Zone is a census tract designated as low-income where investors can defer and partly reduce capital gains tax by rolling a gain into a Qualified Opportunity Fund that invests in the zone. The One Big Beautiful Bill Act made the program permanent. Under the original program, deferred gains must be recognized by December 31, 2026, and no new original-program deferrals are available after that date; how long the original 2018 zone map overlaps the new one is a transition detail to verify with a CPA. Starting July 1, 2026, governors select new tracts every ten years, with the first new designations effective January 1, 2027, under a tighter definition of low-income (70% of area or statewide median family income instead of 80%). For gains invested after December 31, 2026, the deferral is a rolling five years from the investment date, the basis step-up is 10% after five years (30% for a new category of Qualified Rural Opportunity Fund), gains on the fund interest are excluded if held at least ten years, and the exclusion is capped at the fair market value at the thirty-year mark. For rural funds, the substantial improvement requirement dropped to 50% of adjusted basis, effective on signing. For a two-partner BRRRR operation, this matters mainly if you are selling appreciated assets with large gains, or if one of your target neighborhoods is a designated zone." },
        { h: "Property tax basics", p: "Property tax is a local tax based on the assessed value of your property times the local millage rate. The assessor (called the property appraiser in Florida and the county auditor in Ohio) sets the value. Here is the trap for investors: the tax bill the seller paid is often not the bill you will pay, because many jurisdictions limit how fast an owner's assessment can rise and then reset it to market value when the property changes hands. Always underwrite with the tax you will pay after purchase, not the seller's bill. Rental property gets no homestead exemption or homestead assessment cap, because those protections are for owner-occupied primary residences. Property tax is a deductible rental expense." },
        { state: {
          fl: "Florida: homestead property is protected by the Save Our Homes cap of 3% per year; non-homestead property (your rentals) has a separate 10% annual assessment cap under Fla. Stat. 193.1554 that does not apply to school levies, and the assessment resets to full market value on a change of ownership or control. Expect your first-year tax bill to jump above what the seller paid.",
          oh: "Ohio: the county auditor reappraises all property every six years (sexennial reappraisal) with a triennial update in year three; values are not reset on sale, but a recent sale price is strong evidence of value at the next update, and school districts have historically been able to challenge values after a sale."
        } },
        { carry: "Opportunity Zones: permanent under the 2025 law; original-program deferred gains recognized December 31, 2026; new zones effective January 1, 2027; post-2026 investments get a rolling 5-year deferral and 10% step-up (30% rural). Underwrite rentals with the post-sale tax bill, not the seller's." },
        { trap: "Using the seller's tax bill in your cash flow analysis can understate expenses by hundreds of dollars a month in a capped-assessment state like Florida. Look up the millage rate and multiply by your purchase price. Opportunity Zone rules are detailed and the transition between the old and new programs is complex. Confirm with a CPA before investing a gain in a fund, and check your county's assessment rules before you underwrite." },
        { sources: [
          { t: "Adams and Reese: Key Changes to the Opportunity Zone Program in the One Big Beautiful Bill Act", u: "https://www.adamsandreese.com/insights/key-changes-to-the-opportunity-zone-program-in-the-one-big-beautiful-bill-act" },
          { t: "Kiplinger: Opportunity Zones, An Expert Guide to the Changes in the One Big Beautiful Bill", u: "https://www.kiplinger.com/real-estate/real-estate-investing/opportunity-zones-changes-in-the-big-beautiful-bill" },
          { t: "IRS: Opportunity Zones", u: "https://www.irs.gov/credits-deductions/businesses/opportunity-zones" },
          { t: "Florida Statutes 193.1554, Assessment of nonhomestead residential property (10% cap)", u: "https://www.leg.state.fl.us/statutes/index.cfm?mode=View+Statutes&SubMenu=1&App_mode=Display_Statute&Search_String=193.1554&URL=0100-0199/0193/Sections/0193.1554.html" },
          { t: "Pinellas County Property Appraiser: Save Our Homes (3% homestead cap)", u: "https://www.pcpao.gov/learn-about/save-our-homes" },
          { t: "Ohio Legislative Service Commission: Property Tax, The Triennial Update", u: "https://www.lsc.ohio.gov/assets/organizations/legislative-service-commission/files/property-tax-the-triennial-update.pdf" }
        ] }
      ]
    }
  ],
  cards: [
    { id: "m09-c01", type: "term", q: "What is depreciation?", a: "A yearly deduction for the wearing out of a building that costs you nothing out of pocket this year. Residential rental buildings depreciate over 27.5 years straight-line." },
    { id: "m09-c02", type: "number", q: "Over how many years is residential rental property depreciated?", a: "27.5 years, straight-line, starting the month the property is placed in service (ready to rent)." },
    { id: "m09-c03", type: "trap", q: "Can you depreciate the land under your rental?", a: "No. Land is never depreciable. Split your purchase price between land and building using the county appraiser ratio or an appraisal, and depreciate only the building and improvements." },
    { id: "m09-c04", type: "formula", q: "How do you compute annual straight-line depreciation on a rental?", a: "(Purchase price − land value + capitalized closing and rehab costs) ÷ 27.5. Example: $137,500 depreciable basis ÷ 27.5 = $5,000 per year." },
    { id: "m09-c05", type: "trap", q: "You decide not to claim depreciation so you have less recapture later. Smart?", a: "No. The IRS reduces your basis by depreciation 'allowed or allowable' whether you claimed it or not, so you get the recapture without the deduction. Always claim it." },
    { id: "m09-c06", type: "trap", q: "Is the principal portion of your mortgage payment deductible?", a: "No. Only mortgage interest is deductible. Principal is a return of borrowed money. This is why taxable income is higher than cash flow before depreciation." },
    { id: "m09-c07", type: "term", q: "What is a cost segregation study?", a: "An engineering-based report that reclassifies parts of a property from 27.5-year to 5-, 7-, and 15-year property (carpet, appliances, fences, driveways), so they can be depreciated faster and qualify for bonus depreciation." },
    { id: "m09-c08", type: "term", q: "What is bonus depreciation?", a: "A first-year deduction of a set percentage of qualifying property with a recovery period of 20 years or less. It never applies to the 27.5-year building itself." },
    { id: "m09-c09", type: "number", q: "What is the bonus depreciation percentage for property acquired and placed in service after January 19, 2025?", a: "100%, made permanent by the One Big Beautiful Bill Act signed July 4, 2025. Property acquired on or before January 19, 2025 stays on the old phase-down (40% in 2025, 20% in 2026)." },
    { id: "m09-c10", type: "scenario", q: "Both partners earn $110,000 W-2 salaries and are considering a $4,000 cost segregation study to create a $40,000 first-year loss. What do you do?", a: "Run the passive loss math first. At that MAGI the $25,000 allowance is mostly or fully phased out, so the loss would be suspended. Skip the study unless you have passive income, qualify for REPS or the STR exception, or plan to sell soon." },
    { id: "m09-c11", type: "number", q: "What recovery periods do cost segregation studies typically assign?", a: "5 years for carpet, appliances, and similar personal property; 7 years for some furniture and equipment; 15 years for land improvements like fences, driveways, and landscaping. The structure stays at 27.5." },
    { id: "m09-c12", type: "trap", q: "What is the hidden cost of accelerated depreciation when you eventually sell?", a: "More depreciation recapture, taxed at up to 25% (unrecaptured Section 1250 gain). Accelerating deductions is a deferral, not a permanent saving, unless you hold until death or 1031 forever." },
    { id: "m09-c13", type: "term", q: "What does it mean that rental income is 'passive' under Section 469?", a: "Rental activity is passive by default regardless of hours worked, so rental losses can only offset passive income unless an exception (the $25,000 allowance, REPS, or the STR rule) applies." },
    { id: "m09-c14", type: "number", q: "What is the special allowance for rental real estate losses and when does it phase out?", a: "Up to $25,000 per year of rental losses against non-passive income if you actively participate. Reduced by 50% of MAGI over $100,000; fully gone at $150,000 MAGI." },
    { id: "m09-c15", type: "formula", q: "Your MAGI is $130,000 and your rentals lose $20,000. How much can you deduct this year under the special allowance?", a: "Allowance = $25,000 − 0.5 × ($130,000 − $100,000) = $10,000. You deduct $10,000 and suspend $10,000." },
    { id: "m09-c16", type: "term", q: "What is 'active participation' for the $25,000 allowance?", a: "Making bona fide management decisions: approving tenants, setting rent terms, approving repairs. You can use a property manager and still actively participate. It is a much lower bar than material participation." },
    { id: "m09-c17", type: "term", q: "What happens to a suspended passive loss?", a: "It carries forward indefinitely. It is released against passive income in later years, or fully released against any income when you dispose of your entire interest in a fully taxable sale to an unrelated party." },
    { id: "m09-c18", type: "scenario", q: "You have $30,000 of suspended losses on a rental and plan to sell it to your brother. Problem?", a: "Yes. Suspended losses are only fully released on a taxable disposition to an unrelated party. A sale to a related party does not free them. Sell to an unrelated buyer or keep holding." },
    { id: "m09-c19", type: "trap", q: "You are married filing separately and lived with your spouse this year. What is your rental loss allowance?", a: "Zero. Married filing separately taxpayers who lived with their spouse at any time during the year get no special allowance." },
    { id: "m09-c20", type: "term", q: "What are the two tests for Real Estate Professional Status?", a: "More than 750 hours in real property trades or businesses in which you materially participate, AND more than half of all your personal service hours for the year in those businesses." },
    { id: "m09-c21", type: "scenario", q: "One partner works 2,000 hours a year at a W-2 job and logs 900 hours on rentals. Does that partner qualify as a real estate professional?", a: "No. 900 hours passes the 750 test but fails the more-than-half test (900 is less than 2,000). A full-time job almost always blocks REPS." },
    { id: "m09-c22", type: "number", q: "Do hours worked as an employee count toward the 750-hour test?", a: "Only if you own more than 5% of the employer. Hours as a regular W-2 employee of someone else's brokerage or construction company do not count." },
    { id: "m09-c23", type: "scenario", q: "A couple files jointly. One spouse works a W-2 job; the other spends 1,200 hours a year running their rentals and nothing else. Can they use rental losses against the W-2 income?", a: "Likely yes. The full-time real estate spouse alone meets both tests, and on a joint return REPS makes the rental losses non-passive against the couple's combined income. Material participation in each rental still must be met (both spouses' hours count there)." },
    { id: "m09-c24", type: "trap", q: "Can two spouses add their hours together to reach 750?", a: "No. One spouse alone must meet the 750-hour and more-than-half tests. Both spouses' hours do count toward material participation in the rentals once one spouse qualifies." },
    { id: "m09-c25", type: "term", q: "What is the grouping election for real estate professionals?", a: "A one-time election to treat all your rental real estate interests as a single activity so you only have to prove material participation once, instead of 500 hours per property." },
    { id: "m09-c26", type: "term", q: "What is the short-term rental exception to the passive loss rules?", a: "Under Reg. 1.469-1T(e)(3)(ii)(A), an activity with an average customer stay of 7 days or less is not a 'rental activity,' so its losses can be non-passive if you materially participate, without needing REPS." },
    { id: "m09-c27", type: "scenario", q: "Your furnished rental averages 9-day stays and you materially participate. Can you use the STR exception?", a: "No. The average stay must be 7 days or less (or 30 days or less with significant personal services). At 9 days it is a rental activity and the passive rules apply." },
    { id: "m09-c28", type: "trap", q: "What is the number one reason REPS and STR loss claims fail at audit?", a: "No contemporaneous hour log. Reconstructed hours are routinely rejected. Log date, property, task, and time weekly. Education and scouting properties you do not own generally do not count." },
    { id: "m09-c29", type: "term", q: "What is unrecaptured Section 1250 gain?", a: "The portion of gain on sale of real estate attributable to straight-line depreciation you took. It is taxed at your ordinary rate but capped at 25%." },
    { id: "m09-c30", type: "number", q: "What are the 2026 long-term capital gains rates and the 0% bracket limits?", a: "0%, 15%, and 20%. For 2026 the 0% rate applies up to $49,450 taxable income single and $98,900 married filing jointly; 20% begins above $545,500 single and $613,700 joint." },
    { id: "m09-c31", type: "number", q: "When does the 3.8% net investment income tax apply to rental gains?", a: "When modified adjusted gross income exceeds $200,000 single or $250,000 married filing jointly. It applies to rental income and gains, not to active business income subject to SE tax." },
    { id: "m09-c32", type: "formula", q: "Adjusted basis $115,000, sold for $220,000 net, $35,000 depreciation taken. How is the gain taxed?", a: "Total gain $105,000. $35,000 is unrecaptured 1250 gain at up to 25%. $70,000 is long-term capital gain at 0/15/20%. Plus 3.8% NIIT if over the MAGI threshold." },
    { id: "m09-c33", type: "number", q: "What are the two deadlines in a 1031 exchange?", a: "45 days from the sale closing to identify replacement property in writing, and 180 days from the sale (or the tax return due date, if earlier) to close. Both clocks start on the sale closing date." },
    { id: "m09-c34", type: "term", q: "What is a qualified intermediary in a 1031 exchange?", a: "A neutral third party who holds your sale proceeds between the sale and the purchase. If you receive the cash, even briefly, the exchange fails. Engage the QI before closing the sale." },
    { id: "m09-c35", type: "term", q: "What is 'boot' in a 1031 exchange?", a: "Cash or debt relief you receive and do not reinvest. Boot is taxable. To defer all gain, buy equal or greater value and reinvest all equity." },
    { id: "m09-c36", type: "scenario", q: "You closed the sale of a rental Tuesday and the title company wired you the proceeds. Wednesday you call about a 1031. What now?", a: "The exchange is dead. You took constructive receipt of the funds. A 1031 requires a qualified intermediary in place before the sale closes. Plan the exchange before you list." },
    { id: "m09-c37", type: "number", q: "Since 2018, what kinds of property qualify for 1031 treatment?", a: "Only real property held for investment or business use. Personal property exchanges were eliminated by the 2017 tax law." },
    { id: "m09-c38", type: "trap", q: "Does a 1031 exchange erase your tax?", a: "No. It defers it. The deferred gain and old depreciation carry into the new property's basis. The gain is only erased if you die holding the property (step-up) or keep exchanging." },
    { id: "m09-c39", type: "term", q: "Why do BRRRR investors rarely sell?", a: "Selling triggers recapture (up to 25%), capital gains, NIIT, and state tax, and ends cash flow. Refinancing pulls out equity tax-free while keeping the asset, depreciation, and tenant-paid principal." },
    { id: "m09-c40", type: "term", q: "Are cash-out refinance proceeds taxable income?", a: "No. Loan proceeds are not income because you owe them back. This is why the 'R' in BRRRR returns your capital tax-free." },
    { id: "m09-c41", type: "trap", q: "You use $20,000 of a rental's cash-out refinance for a family vacation. Is the interest on that portion deductible against the rental?", a: "No. Under the interest tracing rules, interest is deductible based on how the proceeds are used. The portion used personally is not a rental deduction." },
    { id: "m09-c42", type: "term", q: "What is stepped-up basis under IRC 1014?", a: "When you die, your heirs' basis becomes the fair market value at death. Deferred appreciation and depreciation recapture disappear for income tax, and heirs depreciate again from the new basis." },
    { id: "m09-c43", type: "term", q: "What does 'buy, borrow, die' mean?", a: "Buy appreciating property, borrow against it tax-free instead of selling, and hold until death so the basis steps up and the deferred gain is never taxed." },
    { id: "m09-c44", type: "trap", q: "Why not deed your rentals to your kids now to avoid probate?", a: "A lifetime gift carries your low basis and your recapture to them. Letting them inherit gives a stepped-up basis. Use a revocable living trust for probate avoidance and talk to an estate attorney." },
    { id: "m09-c45", type: "number", q: "What is the 2026 federal estate tax exemption?", a: "$15 million per person, set by the 2025 One Big Beautiful Bill Act and indexed for inflation after 2026." },
    { id: "m09-c46", type: "term", q: "How is a wholesale assignment fee taxed?", a: "As ordinary business income at your regular bracket, plus 15.3% self-employment tax. It is not a capital gain and not passive." },
    { id: "m09-c47", type: "number", q: "What is the self-employment tax rate and the 2026 Social Security wage base?", a: "15.3% total: 12.4% Social Security up to $184,500 of net earnings in 2026 plus 2.9% Medicare on all earnings. An extra 0.9% Medicare applies above $200,000 single / $250,000 joint." },
    { id: "m09-c48", type: "term", q: "What is the difference between a dealer and an investor?", a: "A dealer holds property primarily for sale (inventory): ordinary income, no depreciation, no 1031. An investor holds for rent or appreciation: capital gain treatment, depreciation, 1031 available." },
    { id: "m09-c49", type: "scenario", q: "You want to flip one house inside the LLC that holds your three rentals. Risk?", a: "The IRS may argue the entity is a dealer, threatening capital gain and 1031 treatment on the rentals. Keep flips and wholesale in a separate active entity with separate books." },
    { id: "m09-c50", type: "term", q: "How does an S-corp election reduce self-employment tax?", a: "You pay yourself a reasonable W-2 salary (subject to payroll tax) and take the remaining profit as a distribution free of SE tax. Payroll and extra filing costs mean it only pays off above a certain profit level." },
    { id: "m09-c51", type: "trap", q: "What is the 'reasonable compensation' rule for S-corps?", a: "An owner who performs services must be paid a reasonable salary before taking distributions. The IRS can reclassify distributions as wages and assess payroll taxes and penalties if salary is unreasonably low." },
    { id: "m09-c52", type: "trap", q: "Should you hold rental property in an S-corporation?", a: "No. Rentals have no SE tax to save, and distributing appreciated property out of an S-corp is a taxable event. Hold rentals in an LLC taxed as a partnership or disregarded entity." },
    { id: "m09-c53", type: "term", q: "What is the Section 199A qualified business income deduction after the 2025 law?", a: "A deduction of up to 20% of qualified pass-through business income, now permanent. The 2025 law widened the phase-in ranges to $75,000 single / $150,000 joint above the threshold and added a $400 minimum deduction for those with at least $1,000 of active QBI." },
    { id: "m09-c54", type: "number", q: "What is the rental real estate safe harbor for the QBI deduction?", a: "Under Rev. Proc. 2019-38, a rental enterprise generally qualifies as a trade or business if 250 or more hours of rental services are performed per year, with contemporaneous records." },
    { id: "m09-c55", type: "number", q: "What are the 2026 IRS standard mileage rates for business?", a: "72.5 cents per mile for January 1 through June 30, 2026, and 76 cents per mile for July 1 through December 31, 2026, after a mid-year increase." },
    { id: "m09-c56", type: "trap", q: "Is driving from home to your rental deductible?", a: "Yes if you have a qualifying home office as your principal place of business; the trip is business travel. Without a home office, the first trip from home to your regular work location may be nondeductible commuting." },
    { id: "m09-c57", type: "number", q: "What is the simplified home office deduction?", a: "$5 per square foot of space used regularly and exclusively for business, up to 300 square feet, for a maximum of $1,500 per year." },
    { id: "m09-c58", type: "term", q: "What is the Augusta rule?", a: "IRC 280A(g): if you rent your personal residence for fewer than 15 days in a year, the rent is excluded from income. Business owners rent their home to their company for up to 14 days of documented meetings at a fair market rate." },
    { id: "m09-c59", type: "trap", q: "Can a sole proprietor use the Augusta rule by renting their house to themselves?", a: "No. You cannot pay yourself rent. The rule works when a separate entity (an LLC taxed as a partnership or S-corp) rents the home for legitimate business meetings with documentation." },
    { id: "m09-c60", type: "term", q: "When you hire your child, which payroll taxes apply?", a: "Sole proprietorship or parent-only partnership: no Social Security/Medicare under age 18, no FUTA under age 21. Corporation or S-corp or partnership with a non-parent partner: all payroll taxes apply regardless of age." },
    { id: "m09-c61", type: "scenario", q: "You pay your 12-year-old $8,000 a year to 'help' but have no timesheets and no real tasks. Deductible?", a: "Not defensibly. Wages to children must be for real, age-appropriate work at a reasonable rate with payroll records and timesheets. Without that, the IRS disallows the deduction." },
    { id: "m09-c62", type: "number", q: "What percentage of a business meal is deductible? Of entertainment?", a: "Business meals with a documented business purpose: 50%. Entertainment (tickets, golf, clubs): 0%." },
    { id: "m09-c63", type: "trap", q: "You buy a $3,000 investing course before you own any property. Is it a current deduction?", a: "Usually no. Education that qualifies you for a new business is not deductible as a business expense; pre-launch costs are start-up costs under Section 195. Education to improve skills in an existing business is deductible." },
    { id: "m09-c64", type: "scenario", q: "You fly to a city you have never invested in to look at houses. Deductible travel?", a: "Generally not as a current expense. Investigating a new market or business is a start-up or investigation cost. Travel within a market where you already operate, primarily for business, is deductible." },
    { id: "m09-c65", type: "number", q: "What are the 2026 Solo 401(k) contribution limits?", a: "$24,500 employee deferral; $72,000 combined employee plus employer; catch-up $8,000 at 50+, or $11,250 at ages 60 to 63 if the plan allows. Employer share is up to 25% of compensation." },
    { id: "m09-c66", type: "term", q: "What is a disqualified person under Section 4975?", a: "You, your spouse, your ancestors, your lineal descendants and their spouses, your plan's fiduciaries, and entities you control 50% or more. Your retirement account cannot transact with any of them." },
    { id: "m09-c67", type: "scenario", q: "Your self-directed IRA owns a rental and you spend a Saturday painting it to save money. Problem?", a: "Yes, a prohibited transaction. Sweat equity is a contribution of services by a disqualified person and can disqualify the entire IRA, making the whole balance taxable. Hire it out and pay from the IRA." },
    { id: "m09-c68", type: "term", q: "What are UBIT and UDFI?", a: "UBIT is tax on an active business run inside a retirement account. UDFI is UBIT on the debt-financed share of income from leveraged property in an IRA, reported on Form 990-T when gross unrelated income is $1,000 or more." },
    { id: "m09-c69", type: "number", q: "Why do leveraged real estate investors prefer a Solo 401(k) over a self-directed IRA?", a: "Section 514(c)(9) generally exempts qualified plans like 401(k)s from UDFI on acquisition debt for real property. IRAs get no such exemption and pay tax on the leveraged portion." },
    { id: "m09-c70", type: "trap", q: "Can you personally guarantee the mortgage on a property your IRA buys?", a: "No. A personal guarantee is a prohibited extension of credit to the plan. Retirement account loans must be non-recourse, which means larger down payments and higher rates." },
    { id: "m09-c71", type: "number", q: "What happened to Opportunity Zones under the 2025 law?", a: "The program became permanent. Original-program deferred gains are recognized December 31, 2026. New zones are designated every 10 years starting July 1, 2026, effective January 1, 2027, under a 70%-of-median-income test." },
    { id: "m09-c72", type: "number", q: "What benefits apply to gains invested in a Qualified Opportunity Fund after December 31, 2026?", a: "Rolling 5-year deferral; 10% basis step-up after 5 years (30% for a Qualified Rural Opportunity Fund); exclusion of fund gain after a 10-year hold, capped at fair market value at year 30." },
    { id: "m09-c73", type: "trap", q: "Why should you never underwrite a rental using the seller's property tax bill?", a: "Many jurisdictions cap assessment growth and reset to market value on sale, so your bill can jump well above the seller's. Compute your tax from the millage rate times your purchase price." },
    { id: "m09-c74", type: "state", q: "How is a rental's assessed value handled over time?", a: "FL: non-homestead property has a 10% annual assessment cap (Fla. Stat. 193.1554, excludes school levies) that resets to market value on change of ownership; homestead gets the 3% Save Our Homes cap. | OH: county auditor reappraises every 6 years with a triennial update; no automatic reset on sale, but the sale price is strong evidence at the next update." },
    { id: "m09-c75", type: "trap", q: "Does your rental get a homestead exemption?", a: "No. Homestead exemptions and homestead assessment caps are for owner-occupied primary residences only. Rentals pay full non-homestead rates." }
  ],
  quiz: [
    { id: "m09-q01", q: "You buy a rental for $200,000. The county assigns 25% of value to land. You spend $20,000 on rehab before renting. What is your annual depreciation?", opts: ["$7,273", "$6,182", "$8,000", "$5,455"], correct: 1, explain: "Depreciable basis = $200,000 − $50,000 land + $20,000 rehab = $170,000. $170,000 ÷ 27.5 = $6,182." },
    { id: "m09-q02", q: "Which of these is NOT depreciable?", opts: ["A new roof", "Kitchen appliances", "The land", "A fence"], correct: 2, explain: "Land never wears out in the tax code and is never depreciated. Roofs are part of the 27.5-year building; appliances and fences are shorter-life property." },
    { id: "m09-q03", q: "After the One Big Beautiful Bill Act, what bonus depreciation percentage applies to qualifying property acquired and placed in service after January 19, 2025?", opts: ["40%", "60%", "80%", "100%"], correct: 3, explain: "The 2025 law permanently restored 100% bonus depreciation for property acquired and placed in service after January 19, 2025." },
    { id: "m09-q04", q: "Bonus depreciation applies to which part of a residential rental?", opts: ["The entire purchase price", "Only property with a recovery period of 20 years or less, like 5-, 7-, and 15-year items", "The land", "The 27.5-year building structure"], correct: 1, explain: "Bonus depreciation is limited to property with a recovery period of 20 years or less. The building structure (27.5 years) and land never qualify." },
    { id: "m09-q05", q: "Your MAGI is $140,000. You actively participate in your rentals, which lose $12,000 this year. How much can you deduct against your wages under the special allowance?", opts: ["$12,000", "$0", "$5,000", "$25,000"], correct: 2, explain: "Allowance = $25,000 − 0.5 × ($140,000 − $100,000) = $5,000. The other $7,000 is suspended and carried forward." },
    { id: "m09-q06", q: "At what MAGI is the $25,000 rental loss allowance completely phased out?", opts: ["$100,000", "$125,000", "$150,000", "$200,000"], correct: 2, explain: "The allowance is reduced by 50% of MAGI over $100,000, so it hits zero at $150,000." },
    { id: "m09-q07", q: "What happens to suspended passive losses when you sell the property in a fully taxable sale to an unrelated buyer?", opts: ["They are lost forever", "They are released and can offset any income, including wages", "They can only offset the gain on that sale", "They convert to capital losses"], correct: 1, explain: "A full taxable disposition to an unrelated party releases all suspended losses from that activity against income of any type." },
    { id: "m09-q08", q: "Which statement about Real Estate Professional Status is correct?", opts: ["Spouses can combine hours to reach 750", "You need more than 750 hours AND more than half of all your working hours in real property businesses", "Any licensed real estate agent automatically qualifies", "500 hours in rentals is enough"], correct: 1, explain: "Section 469(c)(7) requires both tests, met by one spouse alone. A license is irrelevant; it is about hours." },
    { id: "m09-q09", q: "A partner works 1,900 hours at a full-time job and 1,000 hours on rentals. Does she qualify as a real estate professional?", opts: ["Yes, because 1,000 exceeds 750", "No, because 1,000 is not more than half of her 2,900 total hours", "Yes, if she owns more than 10 properties", "Only if she has a real estate license"], correct: 1, explain: "She passes the 750-hour test but fails the more-than-half test. A full-time job almost always blocks REPS." },
    { id: "m09-q10", q: "Under the passive activity regulations, a furnished rental with an average guest stay of what length is NOT treated as a rental activity?", opts: ["30 days or less, always", "14 days or less", "7 days or less", "90 days or less"], correct: 2, explain: "Reg. 1.469-1T(e)(3)(ii)(A): average period of customer use of 7 days or less. A 30-day version exists only with significant personal services." },
    { id: "m09-q11", q: "Depreciation you took on a rental is taxed on sale as unrecaptured Section 1250 gain at a maximum rate of:", opts: ["15%", "20%", "25%", "37%"], correct: 2, explain: "Unrecaptured Section 1250 gain is taxed at ordinary rates capped at 25%. The rest of the gain gets the 0/15/20% capital gains rates." },
    { id: "m09-q12", q: "In a 1031 exchange, how many days do you have to identify replacement property, and how many to close?", opts: ["30 and 120", "45 and 180", "60 and 180", "45 and 365"], correct: 1, explain: "45 days to identify in writing and 180 days to close, both counted from the closing of the sale." },
    { id: "m09-q13", q: "Which action kills a 1031 exchange?", opts: ["Buying a duplex to replace a single-family rental", "Using a qualified intermediary", "Receiving the sale proceeds in your own bank account", "Identifying three potential replacement properties"], correct: 2, explain: "Taking receipt of the cash, even briefly, disqualifies the exchange. The qualified intermediary must hold the funds." },
    { id: "m09-q14", q: "You refinance a rental and pull out $75,000 in cash. How much of that is taxable income?", opts: ["$75,000", "Only the amount above your original purchase price", "$0", "The amount above your adjusted basis"], correct: 2, explain: "Loan proceeds are not income because you owe them back. Cash-out refinance money is tax-free." },
    { id: "m09-q15", q: "Under IRC Section 1014, what basis do your heirs receive in a rental you held until death?", opts: ["Your original purchase price", "Your adjusted basis after depreciation", "Fair market value at your date of death", "Zero"], correct: 2, explain: "Basis steps up to fair market value at death, erasing deferred gain and recapture for income tax purposes." },
    { id: "m09-q16", q: "A $12,000 wholesale assignment fee is taxed as:", opts: ["Long-term capital gain", "Passive income", "Ordinary income subject to self-employment tax", "Tax-free loan proceeds"], correct: 2, explain: "Assignment fees are active business income: ordinary rates plus 15.3% self-employment tax." },
    { id: "m09-q17", q: "What is the 2026 Social Security wage base for the 12.4% portion of self-employment tax?", opts: ["$160,200", "$168,600", "$176,100", "$184,500"], correct: 3, explain: "For 2026 the Social Security wage base is $184,500. The 2.9% Medicare portion has no cap." },
    { id: "m09-q18", q: "Why is an S-corp election a bad fit for holding rental property?", opts: ["Rentals have no self-employment tax to save, and distributing appreciated property out of an S-corp is taxable", "S-corps cannot own real estate", "Rentals in an S-corp lose depreciation", "S-corps pay a flat 21% tax"], correct: 0, explain: "The S-corp's benefit is avoiding SE tax, which rentals do not owe. Getting property out later triggers gain. Use an LLC taxed as a partnership or disregarded entity." },
    { id: "m09-q19", q: "What did the 2025 One Big Beautiful Bill Act do to the Section 199A QBI deduction?", opts: ["Repealed it", "Reduced it to 15%", "Made it permanent at 20% and widened the phase-in ranges", "Limited it to C-corporations"], correct: 2, explain: "199A was set to expire after 2025. The law made it permanent, kept 20%, widened phase-in ranges to $75,000/$150,000, and added a $400 minimum deduction." },
    { id: "m09-q20", q: "What is the IRS business standard mileage rate for driving done in September 2026?", opts: ["67 cents", "70 cents", "72.5 cents", "76 cents"], correct: 3, explain: "The rate was 72.5 cents for January through June 2026 and rose to 76 cents effective July 1, 2026." },
    { id: "m09-q21", q: "Your two-member LLC taxed as a partnership rents your home for 12 days of documented strategy meetings at a fair market rate under Section 280A(g). How is the rent taxed to you?", opts: ["As ordinary income", "As passive rental income", "It is excluded from your income because the home was rented fewer than 15 days", "As a capital gain"], correct: 2, explain: "Section 280A(g) excludes rental income from a personal residence rented fewer than 15 days per year. The LLC deducts the rent as a business expense." },
    { id: "m09-q22", q: "Your wholesale business is a sole proprietorship. You hire your 15-year-old for real filing and marketing work. Which payroll taxes apply to the child's wages?", opts: ["All of them: Social Security, Medicare, and FUTA", "None of Social Security, Medicare, or FUTA", "Social Security and Medicare but not FUTA", "FUTA only"], correct: 1, explain: "For a parent's sole proprietorship, a child under 18 is exempt from Social Security and Medicare and a child under 21 is exempt from FUTA. In a corporation or S-corp, all apply." },
    { id: "m09-q23", q: "What is the maximum employee deferral to a Solo 401(k) for 2026 for someone under age 50?", opts: ["$23,000", "$23,500", "$24,500", "$72,000"], correct: 2, explain: "The 2026 employee deferral limit is $24,500. $72,000 is the combined employee-plus-employer cap." },
    { id: "m09-q24", q: "Your self-directed IRA buys a rental with a 50% non-recourse loan. What tax issue arises?", opts: ["None; IRAs are fully tax-exempt", "UDFI: the debt-financed share of income and gain is taxable, reported on Form 990-T", "The loan is a prohibited transaction", "The IRA loses its tax-exempt status automatically"], correct: 1, explain: "Leveraged real estate in an IRA produces unrelated debt-financed income. A Solo 401(k) is generally exempt from UDFI on real estate acquisition debt under Section 514(c)(9)." },
    { id: "m09-q25", q: "Under the original Opportunity Zone program, by what date must gains deferred into a fund be recognized?", opts: ["July 4, 2025", "December 31, 2026", "January 1, 2027", "December 31, 2028"], correct: 1, explain: "Original-program deferrals end December 31, 2026, when the deferred gain is recognized. New zones designated starting July 1, 2026 take effect January 1, 2027, with a rolling 5-year deferral for new investments." }
  ],
  drills: [
    "Pull last month's bank and card statements and list every expense that could be deductible for your real estate business (mileage, software, supplies, meals with a business purpose, education, phone, home office). Mark which ones you have a receipt for and which you do not.",
    "Install a mileage tracking app today and log every business drive this week with date, destination, and purpose. At the end of the week, multiply the miles by the current IRS rate (76 cents for the second half of 2026) to see what you would have lost without the log.",
    "Write down your expected modified adjusted gross income for this year and compute your $25,000 special allowance using the formula: $25,000 minus half of the amount over $100,000. Decide whether a rental loss this year would actually be usable for you.",
    "Write five questions to ask a CPA at your first meeting: Should our active and passive activities be in separate entities? At what profit level does an S-corp election pay off for us? Does either partner or spouse have a realistic path to real estate professional status? Would a cost segregation study help us this year given our incomes? What records do you want from us monthly?",
    "For one property you are analyzing, split the price into land and building using the county appraiser's ratio, compute first-year depreciation at 27.5 years, and then estimate the first-year deduction if a cost segregation study moved 20% of the building cost into 5- and 15-year property with 100% bonus depreciation.",
    "Look up the millage rate for the county where you plan to buy and compute the property tax on a hypothetical $180,000 purchase. Compare it to the current owner's tax bill on a real listing in that county and note the difference you would need to underwrite."
  ]
});
