BIBLE.register({
  id: "m10",
  part: 4,
  title: "Entities & Asset Protection",
  icon: "🛡️",
  summary: "How to structure a two-partner rental business so one lawsuit, one bad tenant, or one partner's divorce does not take down everything you have built, and what an LLC actually does and does not protect.",
  minutes: 75,
  lessons: [
    {
      id: "m10-01",
      title: "What an LLC Does and Does Not Protect",
      minutes: 9,
      blocks: [
        { h: "The basic idea", p: "A limited liability company, or LLC, is a legal entity separate from its owners, who are called members. When the LLC owns a rental and a tenant sues over an injury at the property, the tenant is suing the LLC. If the LLC follows the rules, the tenant can reach the LLC's assets but not your personal house, car, or savings. That wall between the business's debts and your personal assets is the entire point. Asset protection does not mean you never get sued. It means a judgment is limited to the pot of assets inside the entity that got sued." },
        { h: "Inside liability versus outside liability", p: "Lawyers split the risk into two directions. Inside liability is a claim that starts inside the LLC, such as a slip and fall at a property the LLC owns. The LLC protects your personal assets from that claim. Outside liability is a claim against you personally, such as a car accident on your way to the grocery store, where the creditor then tries to reach your LLC membership interest to get at the rental. Protection against outside liability depends on state law and is where the charging order, discussed in the next lesson, comes in." },
        { h: "What an LLC does not do", p: "An LLC does not protect you from your own negligence. If you personally cause the harm, for example you do the electrical work yourself and it starts a fire, you can be sued personally alongside the LLC. An LLC does not protect you from loans you personally guaranteed, and nearly every loan a new investor gets will carry a personal guarantee. An LLC does not reduce your taxes by itself; a single-member LLC is ignored for income tax and a multi-member LLC is taxed as a partnership, so your tax bill is identical to owning the property in your own name. And an LLC protects nothing if you treat it like a personal piggy bank, which is the piercing-the-veil problem covered later." },
        { h: "LLCs and insurance work together", p: "Insurance is your first line of defense and the LLC is your second. Insurance pays the claim and the legal defense up to the policy limit; the LLC contains anything that exceeds the limit or that insurance excludes. Investors who skip insurance because they have an LLC have it backwards. Carry a landlord policy and an umbrella on every property, then put the property in the LLC." },
        { carry: "An LLC walls off inside liability (claims arising at the property) from your personal assets. It does not shield you from your own negligence, your personal guarantees, or your taxes. Insurance first, entity second." },
        { trap: "Forming an LLC and then leaving the property deeded in your personal name gives you nothing. The entity only protects assets it actually owns. Title, lease, bank account, and insurance must all be in the LLC's name. Entity law is state law and the details matter. Confirm your structure with a local real estate attorney." },
        { sources: [
          { t: "IRS: Limited Liability Company (LLC) tax classification (disregarded entity vs partnership)", u: "https://www.irs.gov/businesses/small-businesses-self-employed/limited-liability-company-llc" },
          { t: "Florida Revised Limited Liability Company Act, Chapter 605, Florida Statutes", u: "https://www.leg.state.fl.us/statutes/index.cfm?App_mode=Display_Statute&URL=0600-0699/0605/0605.html" },
          { t: "Ohio Revised Limited Liability Company Act, ORC Chapter 1706", u: "https://codes.ohio.gov/ohio-revised-code/chapter-1706" }
        ] }
      ]
    },
    {
      id: "m10-02",
      title: "Single-Member vs Multi-Member and the Charging Order",
      minutes: 9,
      blocks: [
        { h: "The charging order", p: "When a creditor wins a judgment against you personally and wants your LLC interest, most states limit the creditor to a charging order. A charging order is a court order that directs the LLC to pay the creditor any distributions that would otherwise go to you. The creditor does not become a member, cannot vote, cannot force a sale of the property, and cannot make the LLC distribute anything. If the LLC simply does not distribute, the creditor waits. That is a strong incentive for the creditor to settle." },
        { h: "Why the number of members matters", p: "Courts and legislatures created the charging order to protect the other members of an LLC from having a stranger forced into their business. When there is only one member, there is no innocent partner to protect, and some states let the creditor go further and foreclose on the single member's interest, taking over the whole LLC. This is why a two-partner LLC is often better protected than two single-member LLCs, and why the choice of state matters." },
        { state: {
          fl: "Florida: under Fla. Stat. 605.0503, a charging order is the exclusive remedy against a member of a multi-member LLC. For a single-member LLC, after the 2010 Olmstead v. FTC decision and the 2011 statute change, a creditor who shows a charging order will not satisfy the judgment in a reasonable time can foreclose on the membership interest and take control of the LLC. Florida single-member LLCs offer weak outside-liability protection.",
          oh: "Ohio: under ORC 1706.342 (Revised LLC Act, effective February 11, 2022), a charging order is the sole and exclusive remedy for a judgment creditor of a member, foreclosure is prohibited, and the statute does not distinguish single-member from multi-member LLCs."
        } },
        { h: "Tax treatment follows the member count", p: "A single-member LLC is a disregarded entity by default: the IRS ignores it and the rental goes on Schedule E of the owner's personal return. A multi-member LLC is a partnership by default and files Form 1065, issuing each member a Schedule K-1. Two business partners who each own 50% of an LLC have a partnership, with the extra cost of a partnership return but the benefit of multi-member charging order protection. Spouses who co-own an LLC in a non-community-property state are also a multi-member LLC for tax purposes." },
        { carry: "Charging order: creditor gets your distributions, not your vote or the property. Multi-member LLCs get the strongest protection; a single-member LLC can be foreclosed in Florida but not in Ohio." },
        { trap: "Adding a 1% member just to call the LLC multi-member can be attacked as a sham if that member has no real economic stake or role. If you want multi-member protection, make the second member genuine, with a real contribution and real rights in the operating agreement. Charging order law changes and varies by state. Confirm with a local real estate attorney." },
        { sources: [
          { t: "Fla. Stat. 605.0503, Charging order (multi-member exclusive remedy; single-member foreclosure)", u: "https://www.leg.state.fl.us/statutes/index.cfm?App_mode=Display_Statute&URL=0600-0699/0605/Sections/0605.0503.html" },
          { t: "Alper Law: Charging Order Protection for Florida LLCs, How 605.0503 Works", u: "https://www.alperlaw.com/florida-asset-protection/llc/charging-order-protection/" },
          { t: "Alper Law: Olmstead v. FTC and Single-Member LLCs in Florida", u: "https://www.alperlaw.com/florida-asset-protection/case-law/olmstead-v-ftc/" },
          { t: "ORC 1706.342, Charging order as exclusive remedy (Ohio)", u: "https://codes.ohio.gov/ohio-revised-code/section-1706.342" },
          { t: "IRS: Single Member Limited Liability Companies", u: "https://www.irs.gov/businesses/small-businesses-self-employed/single-member-limited-liability-companies" }
        ] }
      ]
    },
    {
      id: "m10-03",
      title: "The Operating Agreement: The Document That Saves the Partnership",
      minutes: 11,
      blocks: [
        { h: "Why you need one even if the state does not require it", p: "The operating agreement is the private contract between the members that says who owns what, who decides what, and what happens when something goes wrong. Neither Florida nor Ohio requires you to file it, and many two-person LLCs never sign one. Then one partner wants out, or dies, or gets divorced, and the state's default rules decide the outcome, often badly. Write the agreement while you still like each other. For two equal partners it should answer the questions below in plain language." },
        { h: "Capital and splits", p: "State what each member contributes: cash, a property, credit, or labor, and what each contribution is worth. Say whether future capital calls are required, what happens if one partner cannot fund a call (dilution, a loan from the other partner at a stated rate, or both), and how profits, losses, and cash distributions are split. Profit split does not have to match ownership percentage, but the tax allocation has to have substantial economic effect, so have the CPA review anything other than straight pro rata." },
        { h: "Decision rights and deadlock", p: "A 50-50 LLC has a built-in problem: every disagreement is a tie. List which decisions need both signatures (buying or selling a property, borrowing, signing a lease over a certain length, admitting a new member, hiring a relative) and which either partner can make alone up to a dollar limit. Then write a deadlock clause: mediation first, then a buy-sell mechanism such as one partner naming a price and the other choosing to buy or sell at that price. Without a deadlock clause the only remedy is a judicial dissolution, which means a judge and a forced sale." },
        { h: "Buyout, death, divorce, and disability", p: "Decide now how a departing member's interest is valued (appraisal, formula, or agreed value updated annually) and paid (lump sum or installments over a stated term at a stated rate). Restrict transfers so neither partner can sell to an outsider without the other's consent. Add a death clause giving the surviving partner the right to buy the deceased partner's interest from the estate, and consider funding it with life insurance on each partner. Add a divorce clause so a former spouse who is awarded part of a membership interest receives only an economic interest (the right to distributions) and never voting rights, with the remaining partner holding an option to buy that interest. Add a disability clause with the same mechanics. These four events end more partnerships than bad deals do." },
        { carry: "A two-partner operating agreement must cover: contributions and capital calls, profit and distribution split, major-decision list, deadlock buy-sell, transfer restrictions, and buyout terms on death, divorce, and disability." },
        { trap: "Downloading a free single-member template and changing the names to two partners leaves out every clause that matters: capital calls, deadlock, and the death and divorce provisions. Pay an attorney to draft a real two-member agreement. It is the cheapest insurance you will buy. Have a local real estate or business attorney draft or review your operating agreement before the first property closes." },
        { sources: [
          { t: "Fla. Stat. 605.0105 and 605.0106, Operating agreement scope and limitations (Florida)", u: "https://www.leg.state.fl.us/statutes/index.cfm?App_mode=Display_Statute&URL=0600-0699/0605/0605.html" },
          { t: "Taft Law: The Ohio Revised LLC Act, What You Need to Know (operating agreement flexibility, default rules)", u: "https://www.taftlaw.com/news-events/law-bulletins/the-ohio-revised-llc-act-what-you-need-to-know/" },
          { t: "IRS Publication 541, Partnerships (allocations, substantial economic effect)", u: "https://www.irs.gov/publications/p541" }
        ] }
      ]
    },
    {
      id: "m10-04",
      title: "Structure: Holding Companies, Operating Companies, and the S-Corp",
      minutes: 9,
      blocks: [
        { h: "Separate what is risky from what is valuable", p: "The core design rule is to keep activities that generate lawsuits away from assets that are worth protecting. Rentals are valuable and generate inside liability from tenants and guests. Wholesaling and flipping are active businesses that generate different risks: contract disputes, contractor claims, and buyers who feel misled. If all of it sits in one LLC, a flip gone wrong exposes the rentals. The standard answer is at least two entities: an operating company for the active business and one or more holding companies for the rentals." },
        { h: "The holding company pattern", p: "Many investors put each rental, or each small group of rentals, in its own LLC so a judgment at one property cannot reach the others. Those property LLCs can be owned directly by the partners or by a parent holding LLC that the partners own. The parent gives you one place to hold the bank account, sign property management agreements, and own the subsidiaries, and it can be formed in the state with the strongest charging order law. The trade-off is cost and bookkeeping: each LLC needs its own bank account, its own books, and its own state filings. Start with one holding LLC for the first property or two and add entities as equity grows and the cost becomes worth it. Ohio allows a series LLC, where one filing creates separate protected series; Florida does not have a series LLC statute, and a series formed elsewhere may not be respected by Florida courts, so ask counsel before relying on one across state lines." },
        { h: "The operating company and the S-corp election", p: "The wholesale and flip business belongs in a separate LLC. Because that income is subject to self-employment tax, this is the entity that may benefit from an S-corporation election once profits justify it. The S-corp pays each working partner a reasonable salary through payroll and distributes the remaining profit free of self-employment tax. Rentals should never go into the S-corp, for the reasons covered in the tax module: there is no self-employment tax on rents to save, and moving appreciated property out of an S-corp is taxable. Keep the structure simple to explain: active in the S-corp, passive in the LLCs." },
        { h: "Lenders and the structure", p: "Conventional lenders generally lend to people, not LLCs, so your first loans may need to close in your personal names and the property deeded to the LLC afterward (see the due-on-sale lesson). DSCR lenders and commercial lenders routinely lend directly to an LLC, with the members signing personal guarantees. Either way, the rental lease and insurance should name the LLC that holds title." },
        { carry: "Active business (wholesale, flips) in an operating LLC, possibly taxed as an S-corp. Rentals in holding LLCs taxed as a partnership or disregarded. Never mix the two." },
        { trap: "Over-structuring on day one is as common as under-structuring. Six LLCs with no properties cost filing fees, registered agent fees, and accounting hours for nothing. Match the number of entities to the equity at risk and grow it. The right number of entities depends on your equity, your lenders, and your states. Confirm with a local real estate attorney and your CPA together." },
        { sources: [
          { t: "IRS: S Corporations (election, reasonable compensation)", u: "https://www.irs.gov/businesses/small-businesses-self-employed/s-corporations" },
          { t: "Taft Law: The Ohio Revised LLC Act (series LLCs under ORC 1706.76)", u: "https://www.taftlaw.com/news-events/law-bulletins/the-ohio-revised-llc-act-what-you-need-to-know/" },
          { t: "Florida Division of Corporations (Sunbiz): Florida Limited Liability Company forms (no series LLC filing exists)", u: "https://dos.fl.gov/sunbiz/start-business/efile/fl-llc/" }
        ] }
      ]
    },
    {
      id: "m10-05",
      title: "Deeding a Financed Property Into an LLC: The Due-on-Sale Issue",
      minutes: 10,
      blocks: [
        { h: "What the due-on-sale clause says", p: "Almost every mortgage contains a due-on-sale clause: if you transfer the property without the lender's consent, the lender may declare the entire loan due immediately. Deeding your rental from your personal name to your LLC is a transfer. In practice lenders rarely call performing loans, but the right exists, and a lender that wants to get out of a low-rate loan has a reason to use it. Know the rules before you record a deed." },
        { h: "The Garn-St Germain exceptions", p: "The federal Garn-St Germain Act, at 12 U.S.C. 1701j-3(d), lists transfers a lender may not treat as a due-on-sale trigger on residential property with fewer than five dwelling units. The list includes a transfer to a relative on the borrower's death, a transfer where the borrower's spouse or children become an owner, a transfer resulting from a divorce decree or separation agreement, a lease of three years or less without an option to buy, and a transfer into an inter vivos (living) trust in which the borrower is and remains a beneficiary. Transfers to an LLC are not on the list. The living trust exception is why some investors deed into a land trust first; see the land trust lesson for what that does and does not accomplish." },
        { h: "The Fannie Mae and Freddie Mac exception", p: "For loans owned or securitized by Fannie Mae on or after June 1, 2016, the Fannie Mae Servicing Guide (section D1-4.1-02) treats a transfer to a limited liability company as an exempt transaction, meaning the servicer may not call the loan, provided the LLC is controlled by the original borrower or the original borrower owns a majority interest, and the loan continues to be paid. Freddie Mac has a parallel provision. This covers many conventional investor loans, but not all: portfolio loans, hard money, DSCR loans, and FHA or VA loans have their own rules, so read your note and ask the servicer in writing. Keep the lender's written response in the property file.\n\nDeeding to an LLC can also affect your title insurance, which generally covers the named insured and may not automatically extend to the LLC without an endorsement. Your homeowner or landlord policy must be rewritten in the LLC's name. And in some states the transfer itself is taxed." },
        { state: {
          fl: "Florida: documentary stamp tax on deeds is 70 cents per $100 of consideration, and consideration includes the balance of any mortgage on the property. Deeding a rental with a $150,000 mortgage into your LLC can trigger about $1,050 of doc stamps even though no money changed hands (Fla. Stat. 201.02; Crescent Miami Center v. Department of Revenue, 2005, exempted only unencumbered transfers to a wholly owned entity, and the 2009 conduit-entity rule taxes a sale of the entity within three years).",
          oh: "Ohio: counties charge a real property conveyance fee on deeds; some transfers to an entity the grantor controls may qualify for an exemption on the county's conveyance fee statement, so confirm with the county auditor before recording."
        } },
        { carry: "Due-on-sale: an LLC transfer is not a Garn-St Germain exception, but Fannie Mae and Freddie Mac treat a transfer to an LLC the borrower controls as exempt for loans they bought on or after June 1, 2016. Get the servicer's answer in writing, update title insurance and the hazard policy, and check transfer tax." },
        { trap: "Recording a quitclaim deed to your LLC without telling anyone can void your title insurance coverage for the LLC, leave the insurance policy in the wrong name so a claim is denied, and in Florida trigger doc stamps on the mortgage balance. Do it deliberately, with the servicer's letter, a warranty deed, a title endorsement, and a new policy. Whether to deed a financed property into an LLC, and how, depends on your lender and your state's transfer tax. Confirm with a local real estate attorney before recording anything." },
        { sources: [
          { t: "12 U.S. Code § 1701j-3, Preemption of due-on-sale prohibitions (subsection (d) exemptions)", u: "https://www.law.cornell.edu/uscode/text/12/1701j-3" },
          { t: "Fannie Mae Servicing Guide D1-4.1-02, Allowable Exemptions Due to the Type of Transfer (transfer to LLC)", u: "https://servicing-guide.fanniemae.com/svc/d1-4.1-02/allowable-exemptions-due-type-transfer" },
          { t: "Florida Bar Journal: Documentary Stamp Tax, The Legislature Strikes Back (Crescent Miami Center; mortgage as consideration; 70 cents per $100)", u: "https://www.floridabar.org/the-florida-bar-journal/documentary-stamp-tax-the-legislature-strikes-back/" },
          { t: "Florida Department of Revenue: Documentary Stamp Tax", u: "https://floridarevenue.com/taxes/taxesfees/Pages/doc_stamp.aspx" }
        ] }
      ]
    },
    {
      id: "m10-06",
      title: "Insurance: Landlord Policies, Umbrellas, and Renters Insurance",
      minutes: 8,
      blocks: [
        { h: "A homeowner policy does not cover a rental", p: "A standard homeowner policy is written for an owner who lives in the house. Once a tenant moves in, the insurer can deny a claim because the use changed. You need a landlord policy, often called a dwelling fire policy or DP-3. It covers the structure, your liability as owner, and usually loss of rent if the property becomes uninhabitable after a covered loss. Choose replacement cost coverage over actual cash value so a claim pays to rebuild rather than paying depreciated value. During a rehab, before a tenant is in place, you need a vacant or builder's risk policy; a landlord policy on a vacant house is also a denied-claim risk." },
        { h: "Umbrella policies", p: "An umbrella policy sits on top of your landlord and auto liability limits and adds another layer, typically sold in million-dollar increments, for a comparatively small premium. It responds when a judgment exceeds the underlying policy. Because an injury claim can exceed a typical landlord liability limit, an umbrella is the cheapest way to cover the gap between what the LLC owns and what a bad judgment could be. If the LLC owns the property, the LLC should be the named insured and the members should be covered as additional insureds, or the LLC should carry its own commercial umbrella. Ask the agent to confirm in writing who is covered." },
        { h: "Require renters insurance", p: "Your landlord policy covers your building, not your tenant's belongings and not the tenant's own liability. Require renters insurance in the lease and require proof before move-in. It protects the tenant's property, pays the tenant's liability if the tenant starts a fire that damages your building, and reduces the chance a tenant sues you for losses that are really theirs. Many property managers will not place a tenant without it." },
        { carry: "Landlord (DP-3) policy with replacement cost and loss of rent; vacant or builder's risk during rehab; umbrella above it; renters insurance required in every lease." },
        { trap: "Keeping the old homeowner policy on a house you converted to a rental saves a few dollars a month and can cost you the entire building when a claim is denied for misrepresentation of occupancy. Rewrite the policy the day the tenant signs. Lease clauses requiring renters insurance must comply with your state's landlord-tenant law. Confirm with a local real estate attorney and an insurance agent who writes investor policies." },
        { sources: [
          { t: "Insurance Information Institute: Coverage for renting out your home", u: "https://www.iii.org/article/coverage-for-renting-out-your-home" },
          { t: "Insurance Information Institute: What is an umbrella liability policy?", u: "https://www.iii.org/article/what-umbrella-liability-policy" },
          { t: "Insurance Information Institute: Renters insurance", u: "https://www.iii.org/article/what-renters-insurance" }
        ] }
      ]
    },
    {
      id: "m10-07",
      title: "Land Trusts: Privacy, Not Protection",
      minutes: 7,
      blocks: [
        { h: "What a land trust is", p: "A land trust is a revocable trust that holds title to a single piece of real estate. A trustee's name appears on the deed, while the beneficiary, who has all the practical rights to the property, is named only in a private trust agreement. The beneficial interest is treated as personal property, which can make transferring it simpler than recording a new deed." },
        { h: "What it does", p: "A land trust gives privacy: someone searching the county records sees the trustee, not you. It can simplify transfer and estate planning for a single property. Because it is an inter vivos trust in which the borrower remains a beneficiary, deeding a financed house into a land trust falls within the Garn-St Germain exception, so the lender may not treat that transfer as a due-on-sale trigger on residential property of fewer than five units. Some investors then assign the beneficial interest to an LLC; whether that second step is protected from the lender is a separate question that depends on the loan documents, and you should not assume it is." },
        { h: "What it does not do", p: "A land trust by itself provides no liability protection. The beneficiary is still the owner for liability purposes, and a plaintiff's attorney can obtain the trust agreement in discovery. Privacy slows down a casual search; it does not stop a lawsuit. If you want protection, the beneficiary of the land trust should be an LLC, and the LLC should be the entity that is actually run like a business. The land trust is a wrapper, not a shield." },
        { state: {
          fl: "Florida has a dedicated land trust statute, Fla. Stat. 689.071 (the Florida Land Trust Act), which recognizes the trustee's full power to deal with the property and treats the beneficial interest as personal property when the trust instrument so provides.",
          oh: "Ohio has no equivalent statute dedicated to land trusts; Ohio land trusts are created under general trust law, and the trustee's authority is typically shown by recording a memorandum of trust. Have an Ohio attorney draft the trust and the memorandum."
        } },
        { carry: "A land trust provides privacy and fits the Garn-St Germain living-trust exception. It provides no liability protection on its own; name an LLC as beneficiary if protection is the goal." },
        { trap: "Paying for a land trust and believing you are now protected is the most common asset-protection misunderstanding. Privacy is not protection. Insurance plus a properly run LLC is protection. Land trust law is state-specific and the interaction with your lender depends on your loan documents. Confirm with a local real estate attorney." },
        { sources: [
          { t: "Fla. Stat. 689.071, Florida Land Trust Act", u: "https://m.flsenate.gov/Statutes/689.071" },
          { t: "Alper Law: Florida Land Trusts for Asset Protection and Privacy (what they do and do not protect)", u: "https://www.alperlaw.com/florida-asset-protection/florida-land-trust/" },
          { t: "12 U.S. Code § 1701j-3(d)(8), transfer into an inter vivos trust in which the borrower remains a beneficiary", u: "https://www.law.cornell.edu/uscode/text/12/1701j-3" }
        ] }
      ]
    },
    {
      id: "m10-08",
      title: "Piercing the Veil: How Investors Lose Their Protection",
      minutes: 8,
      blocks: [
        { h: "What piercing means", p: "Piercing the corporate veil is what a court does when it decides your LLC is not really a separate business but just you wearing a costume. If the veil is pierced, the plaintiff can reach your personal assets as though the LLC did not exist. The LLC paperwork does not protect you; your behavior does. Courts look at whether the entity was operated as a genuine separate business and whether honoring the separation would be unfair to the person who was harmed." },
        { h: "The three classic failures", p: "The first is commingling: paying personal bills from the LLC account, depositing rent into your personal account, or moving money back and forth without documenting it as a contribution, a distribution, or a loan. The second is undercapitalization: an LLC that owns a property but has no money and no insurance to cover foreseeable claims looks like a shell designed to dodge creditors. The third is ignoring formalities: no operating agreement, no separate books, leases and contracts signed in your own name instead of the LLC's, and letting the state administratively dissolve the entity for failing to file the annual report. Fraud, such as moving assets out of the LLC after an injury, is the fourth and is fatal." },
        { h: "How to keep the veil intact", p: "Open a dedicated bank account for each LLC before it owns anything. Run every dollar of rent in and every expense out through that account. Sign every lease, contract, and vendor agreement as a member or manager of the LLC, with the LLC's name on the signature line. Keep the operating agreement signed and current, record major decisions in a short written consent, keep adequate insurance, and file the state annual report on time. When you need money from the LLC, take it as a documented distribution. When you put money in, document it as a capital contribution or a loan with terms." },
        { carry: "Veil-piercing factors: commingling, undercapitalization, ignored formalities, fraud. Defense: separate bank account, LLC signs everything, written consents, adequate insurance, annual filings on time." },
        { trap: "Signing a lease as yourself because you did not have the LLC's name handy is a small act that can be used to argue the LLC was never real. Build a signature block that reads: [Your Company] LLC, by [Your Name], Manager, and use it every single time. Veil-piercing standards vary by state and court. Confirm your operating practices with a local real estate attorney." },
        { sources: [
          { t: "Cornell Legal Information Institute: Piercing the corporate veil", u: "https://www.law.cornell.edu/wex/piercing_the_corporate_veil" },
          { t: "Fla. Stat. 605.0304, Liability of members and managers", u: "https://www.leg.state.fl.us/statutes/index.cfm?App_mode=Display_Statute&URL=0600-0699/0605/Sections/0605.0304.html" },
          { t: "ORC 1706.26, Liability of members and managers (Ohio)", u: "https://codes.ohio.gov/ohio-revised-code/section-1706.26" }
        ] }
      ]
    },
    {
      id: "m10-09",
      title: "Registered Agents, Annual Filings, and Separate Books",
      minutes: 8,
      blocks: [
        { h: "Registered agent", p: "Every LLC must name a registered agent (Ohio calls it a statutory agent): a person or company with a physical address in the state that accepts legal papers and official mail on behalf of the LLC during business hours. You can be your own agent if you have an in-state street address and are reliably there, but a commercial registered agent keeps your home address off the public record and guarantees someone receives a lawsuit on time. Missing a served complaint because nobody was home can lead to a default judgment." },
        { h: "Formation and annual filings", p: "Forming an LLC means filing Articles of Organization with the state and paying a fee. Most states then require a periodic report to keep the entity in good standing, and letting it lapse can lead to administrative dissolution, which is a veil-piercing factor and can cloud title to property the LLC owns. Put every deadline on a shared calendar with a reminder two weeks ahead. Separately, the federal beneficial ownership information (BOI) reporting requirement that took effect in 2024 was narrowed in March 2025 so that domestic companies and their U.S. owners are no longer required to report; check FinCEN's current guidance before assuming anything, since this area has changed repeatedly." },
        { state: {
          fl: "Florida: Articles of Organization cost $125 ($100 filing fee plus $25 registered agent designation) through Sunbiz. An annual report is due each year between January 1 and May 1 and costs $138.75; filing after May 1 adds a $400 late fee for a total of $538.75, and continued failure leads to administrative dissolution in the fall.",
          oh: "Ohio: Articles of Organization (Form 610) cost $99 through the Secretary of State's Ohio Business Central. Ohio does not require an annual or biennial report for LLCs, so the main ongoing duties are keeping the statutory agent current and filing any amendments."
        } },
        { h: "Keep it real with separate books", p: "Each entity needs its own bank account, its own bookkeeping file, and its own set of financial statements, even if one person does all the work. Use accounting software with a separate company file per entity, categorize transactions monthly, and reconcile to the bank statement. Keep a digital property file for each asset: deed, title policy, insurance declarations, loan documents, leases, inspection reports, and the servicer's letter about the LLC transfer. Clean books make the tax return cheaper, make lenders comfortable, and are the single best evidence that the LLC is a real business if the veil is ever challenged." },
        { carry: "FL: $125 to form, $138.75 annual report due by May 1, $538.75 if late. OH: $99 to form, no annual report. Both: registered or statutory agent, separate bank account and books per entity." },
        { trap: "Letting the LLC be administratively dissolved for a missed annual report while it still holds title to a rental means the entity that owns your property technically no longer exists. Reinstatement is possible but costs more than the report, and the gap can be used against you in litigation. Filing fees and deadlines change. Verify them on the state's website before you file, and confirm your compliance calendar with a local real estate attorney." },
        { sources: [
          { t: "Florida Division of Corporations: Fees (LLC filing $125; annual report $138.75; late $538.75)", u: "https://dos.fl.gov/sunbiz/forms/fees/" },
          { t: "Florida Division of Corporations: Annual Report instructions", u: "https://dos.fl.gov/sunbiz/manage-business/efile/annual-report/" },
          { t: "Ohio Secretary of State: Filing Forms and Fee Schedule (Form 610 Articles of Organization $99)", u: "https://www.ohiosos.gov/businesses/filing-forms--fee-schedule/" },
          { t: "FinCEN: Beneficial Ownership Information Reporting (March 2025 interim final rule exempting domestic companies)", u: "https://www.fincen.gov/boi" }
        ] }
      ]
    }
  ],
  cards: [
    { id: "m10-c01", type: "term", q: "What is an LLC?", a: "A limited liability company: a state-law entity separate from its owners (members). Claims against the LLC generally reach only the LLC's assets, not the members' personal assets, if the LLC is run properly." },
    { id: "m10-c02", type: "term", q: "What is the difference between inside and outside liability?", a: "Inside: a claim arising at the property (tenant injury) against the LLC; the LLC shields your personal assets. Outside: a personal claim against you (car accident) where the creditor tries to reach your LLC interest; the charging order is the defense." },
    { id: "m10-c03", type: "trap", q: "Does an LLC protect you if you personally did the faulty wiring that caused a fire?", a: "No. An LLC never shields you from your own negligence. You can be sued personally alongside the LLC. Hire licensed trades and carry insurance." },
    { id: "m10-c04", type: "trap", q: "Does putting a property in an LLC lower your income tax?", a: "No. A single-member LLC is disregarded and a multi-member LLC is a partnership; either way the rental income is taxed exactly as if you owned it personally." },
    { id: "m10-c05", type: "trap", q: "Does an LLC protect you from a loan you personally guaranteed?", a: "No. A personal guarantee is your personal promise. The lender can pursue you directly regardless of the LLC. Nearly all new-investor loans carry one." },
    { id: "m10-c06", type: "scenario", q: "You formed an LLC last year but the rental is still deeded in your personal name. A tenant is injured. Are you protected?", a: "No. The LLC only protects assets it owns. The property, lease, bank account, and insurance must all be in the LLC's name for the wall to exist." },
    { id: "m10-c07", type: "term", q: "What is a charging order?", a: "A court order directing an LLC to pay a member's creditor any distributions that would have gone to that member. The creditor gets no vote, no management rights, and cannot force a sale." },
    { id: "m10-c08", type: "state", q: "Can a creditor foreclose on a single-member LLC interest?", a: "FL: yes, under Fla. Stat. 605.0503 after Olmstead v. FTC (2010), if a charging order alone will not satisfy the judgment in a reasonable time. | OH: no, ORC 1706.342 makes the charging order the exclusive remedy and bars foreclosure for all LLCs regardless of member count." },
    { id: "m10-c09", type: "term", q: "Why do multi-member LLCs get stronger charging order protection?", a: "The remedy exists to protect innocent co-members from a forced stranger. A single-member LLC has no co-member to protect, so some states (including Florida) let creditors foreclose." },
    { id: "m10-c10", type: "trap", q: "Can you add a 1% member just to get multi-member protection?", a: "Risky. A nominal member with no real contribution or role can be attacked as a sham. Make the second member genuine with real capital and rights in the operating agreement." },
    { id: "m10-c11", type: "term", q: "How is a two-member LLC taxed by default?", a: "As a partnership. It files Form 1065 and issues each member a Schedule K-1. A single-member LLC is disregarded and reports on the owner's Schedule E." },
    { id: "m10-c12", type: "term", q: "What is an operating agreement?", a: "The private contract among LLC members covering ownership, contributions, profit splits, decision rights, transfers, and exit events. Not filed with the state; not legally required in Florida or Ohio; essential anyway." },
    { id: "m10-c13", type: "scenario", q: "Your partner cannot fund a $10,000 capital call for a roof. Your operating agreement is silent. What happens?", a: "State default rules decide, usually badly. A good agreement would specify dilution, a member loan at a stated rate, or both. Write the capital call clause before you need it." },
    { id: "m10-c14", type: "term", q: "What is a deadlock clause?", a: "A provision for resolving 50-50 ties: typically mediation, then a buy-sell mechanism (one partner names a price, the other chooses to buy or sell at it). Without it, the remedy is judicial dissolution." },
    { id: "m10-c15", type: "scenario", q: "Your partner gets divorced and the court awards the ex-spouse half of your partner's LLC interest. What should the operating agreement have done?", a: "Limited any transferee by divorce to an economic interest (distributions only, no vote) and given the remaining partner an option to buy that interest at a formula price." },
    { id: "m10-c16", type: "scenario", q: "Your partner dies. The estate's attorney calls about their 50%. What should already be in place?", a: "A death clause giving the surviving partner the right (or obligation) to buy the interest from the estate at a set valuation method and payment terms, ideally funded by life insurance on each partner." },
    { id: "m10-c17", type: "term", q: "What is a transfer restriction in an operating agreement?", a: "A clause barring a member from selling or assigning their interest to an outsider without the other members' consent, often with a right of first refusal." },
    { id: "m10-c18", type: "trap", q: "What is wrong with using a free single-member template for a two-partner LLC?", a: "It omits everything that matters for two owners: capital calls, deadlock, transfer restrictions, and death, divorce, and disability buyouts. Pay an attorney to draft a real multi-member agreement." },
    { id: "m10-c19", type: "term", q: "What is the holding company / operating company structure?", a: "Rentals (valuable, passive) sit in holding LLCs; the active wholesale and flip business sits in a separate operating LLC. A lawsuit from the active business cannot reach the rentals." },
    { id: "m10-c20", type: "trap", q: "Why not run flips and rentals in the same LLC?", a: "Flip liabilities (contractor, buyer, contract disputes) expose the rentals, and dealer activity in the entity can threaten capital gain and 1031 treatment on the rentals. Separate them." },
    { id: "m10-c21", type: "term", q: "What is a series LLC?", a: "One LLC filing with internally separated series, each with its own assets and liabilities shielded from the others. Ohio permits them under ORC 1706.76; Florida has no series LLC statute." },
    { id: "m10-c22", type: "trap", q: "You form a series LLC in a state that allows it and buy Florida rentals in different series. Safe?", a: "Uncertain. Florida has no series LLC statute, and a Florida court may not respect the internal liability shields. Ask a Florida attorney before relying on a series across state lines." },
    { id: "m10-c23", type: "term", q: "Which entity should hold the S-corp election?", a: "Only the active operating company (wholesale, flips) with self-employment income to save. Never the rental holding LLCs." },
    { id: "m10-c24", type: "trap", q: "What is the cost of over-structuring on day one?", a: "Multiple LLCs with no properties still cost filing fees, registered agent fees, bank accounts, and accounting time. Match the number of entities to the equity at risk and grow it over time." },
    { id: "m10-c25", type: "term", q: "What is a due-on-sale clause?", a: "A mortgage provision letting the lender declare the full loan due if the property is transferred without consent. Deeding to your LLC is a transfer." },
    { id: "m10-c26", type: "number", q: "Which transfers does the Garn-St Germain Act (12 U.S.C. 1701j-3(d)) protect from due-on-sale enforcement?", a: "On residential property under five units: transfer on death to a relative, to a spouse or children, under a divorce decree, a lease of 3 years or less without a purchase option, and into a living trust where the borrower remains a beneficiary. Transfers to an LLC are not listed." },
    { id: "m10-c27", type: "number", q: "What does Fannie Mae's Servicing Guide say about transferring a mortgaged property to an LLC?", a: "For loans Fannie Mae purchased or securitized on or after June 1, 2016, a transfer to an LLC controlled by, or majority-owned by, the original borrower is an exempt transaction the servicer may not call (D1-4.1-02)." },
    { id: "m10-c28", type: "scenario", q: "You want to deed a conventionally financed rental to your LLC. What is the right sequence?", a: "Ask the servicer in writing whether the Fannie/Freddie LLC exemption applies and keep the reply; get a title endorsement extending coverage to the LLC; rewrite the insurance in the LLC's name; check state transfer tax; then record a warranty deed." },
    { id: "m10-c29", type: "state", q: "Does deeding a mortgaged rental into your own LLC trigger transfer tax?", a: "FL: yes, doc stamps at 70 cents per $100 of consideration, and the mortgage balance counts as consideration (Fla. Stat. 201.02; Crescent Miami Center 2005 exempts only unencumbered transfers). | OH: a county conveyance fee applies to deeds; some controlled-entity transfers may be exempt on the conveyance fee statement, so confirm with the county auditor." },
    { id: "m10-c30", type: "formula", q: "Florida doc stamps on deeding a rental with a $200,000 mortgage balance into your LLC?", a: "$200,000 ÷ $100 × $0.70 = $1,400, even though no cash changed hands, because the mortgage is consideration." },
    { id: "m10-c31", type: "trap", q: "What happens to your title insurance when you quitclaim to an LLC without telling anyone?", a: "The policy insures the named insured, not the LLC, so coverage may not follow the transfer. Get an endorsement or new policy naming the LLC." },
    { id: "m10-c32", type: "trap", q: "Why should you not use a quitclaim deed to move property into your LLC?", a: "A quitclaim gives no warranties and can break the chain of title coverage. Use a warranty deed with a title endorsement so the LLC receives insured title." },
    { id: "m10-c33", type: "term", q: "What is a landlord (DP-3) policy?", a: "A dwelling policy for a non-owner-occupied rental covering the structure, owner liability, and usually loss of rent. A standard homeowner policy does not cover a tenant-occupied house." },
    { id: "m10-c34", type: "trap", q: "You keep your homeowner policy after renting the house out. Risk?", a: "Claim denial for misrepresentation of occupancy, potentially losing the whole building. Rewrite to a landlord policy the day the lease is signed." },
    { id: "m10-c35", type: "term", q: "What is the difference between replacement cost and actual cash value coverage?", a: "Replacement cost pays to rebuild or replace at today's prices. Actual cash value pays depreciated value, leaving you short after a major loss. Choose replacement cost." },
    { id: "m10-c36", type: "trap", q: "What policy do you need during the rehab phase, before a tenant moves in?", a: "A vacant property or builder's risk policy. A standard landlord policy on a vacant house under renovation is a denied-claim risk." },
    { id: "m10-c37", type: "term", q: "What is an umbrella policy?", a: "Extra liability coverage, usually sold in $1 million increments, that pays above your landlord and auto liability limits. It is the cheapest way to cover a judgment that exceeds the underlying policy." },
    { id: "m10-c38", type: "scenario", q: "Your LLC owns the rental but your personal umbrella names only you. A tenant sues the LLC for more than the landlord policy limit. Covered?", a: "Possibly not; a personal umbrella may not cover an entity. Have the LLC named as insured or carry a commercial umbrella, and get the agent's confirmation in writing." },
    { id: "m10-c39", type: "term", q: "Why require renters insurance in every lease?", a: "It covers the tenant's belongings and liability (including a fire the tenant causes), which your landlord policy does not, and reduces the chance the tenant sues you for their own losses." },
    { id: "m10-c40", type: "term", q: "What is a land trust?", a: "A revocable trust holding title to one property. The trustee appears on the deed; the beneficiary (the real owner) is named only in a private trust agreement. It provides privacy, not liability protection." },
    { id: "m10-c41", type: "trap", q: "Does a land trust protect you from a tenant lawsuit?", a: "No. The beneficiary is still the owner for liability, and the trust agreement is discoverable. For protection, make an LLC the beneficiary and run the LLC properly." },
    { id: "m10-c42", type: "term", q: "How does a land trust interact with the due-on-sale clause?", a: "A transfer into a living trust where the borrower remains a beneficiary is a Garn-St Germain exception on residential property under five units. A later assignment of the beneficial interest to an LLC is not clearly protected; check the loan documents." },
    { id: "m10-c43", type: "state", q: "Do Florida and Ohio have land trust statutes?", a: "FL: yes, the Florida Land Trust Act, Fla. Stat. 689.071. | OH: no dedicated land trust statute; land trusts rely on general trust law and a recorded memorandum of trust, so use an Ohio attorney." },
    { id: "m10-c44", type: "term", q: "What is piercing the corporate veil?", a: "A court disregarding the LLC and holding members personally liable because the entity was not operated as a genuine separate business. The paperwork does not protect you; your conduct does." },
    { id: "m10-c45", type: "trap", q: "What is commingling and why does it matter?", a: "Mixing personal and LLC money: paying personal bills from the LLC account or depositing rent personally. It is the number one veil-piercing factor. One account per entity, every dollar through it." },
    { id: "m10-c46", type: "term", q: "What is undercapitalization?", a: "An LLC with no cash reserves and no insurance to meet foreseeable claims. Courts treat it as a shell designed to dodge creditors. Keep reserves and adequate insurance in the entity." },
    { id: "m10-c47", type: "scenario", q: "You sign a new lease as 'Jane Smith' instead of in the LLC's name because the template did not have a signature block. Problem?", a: "Yes. Contracts signed personally are evidence the LLC is not real and can make you personally liable on the lease. Use: [Your Company] LLC, by [Your Name], Manager, every time." },
    { id: "m10-c48", type: "scenario", q: "A tenant is injured and you quickly move the LLC's cash to your personal account to keep it safe. Consequence?", a: "That is a fraudulent transfer and the strongest possible veil-piercing fact. It exposes your personal assets and can add penalties. Never move assets after a claim arises." },
    { id: "m10-c49", type: "term", q: "What is a registered agent (statutory agent in Ohio)?", a: "A person or company with a physical in-state address who accepts lawsuits and official mail for the LLC during business hours. Missing service can lead to a default judgment." },
    { id: "m10-c50", type: "state", q: "What does it cost to form an LLC and keep it in good standing?", a: "FL: $125 to file Articles of Organization; annual report $138.75 due January 1 to May 1; $538.75 if late, then administrative dissolution. | OH: $99 to file Articles of Organization (Form 610); no annual or biennial report required." },
    { id: "m10-c51", type: "number", q: "When is the Florida LLC annual report due and what is the late penalty?", a: "Due by May 1 each year. After May 1 a $400 late fee applies, making the total $538.75 instead of $138.75; continued failure leads to administrative dissolution." },
    { id: "m10-c52", type: "trap", q: "Your LLC was administratively dissolved for a missed annual report while it holds title to a rental. Why is that dangerous?", a: "The owner of record technically no longer exists in good standing, which can cloud title, complicate a sale or refinance, and is a veil-piercing factor. Reinstate immediately and calendar the deadline." },
    { id: "m10-c53", type: "number", q: "What is the status of federal beneficial ownership information (BOI) reporting for domestic LLCs?", a: "FinCEN's March 2025 interim final rule exempted domestic companies and their U.S. owners from BOI reporting. This area has changed repeatedly; check fincen.gov/boi before relying on it." },
    { id: "m10-c54", type: "trap", q: "Why keep a separate accounting file and bank account for each LLC even if one person does all the work?", a: "Separate books prove the entity is a real business (anti-piercing), make the tax return cheaper, satisfy lenders, and let you see each property's true performance." },
    { id: "m10-c55", type: "scenario", q: "You need $5,000 from the holding LLC for a personal emergency. How do you take it without weakening the veil?", a: "Record it as a member distribution, approved per the operating agreement, paid by transfer from the LLC account to your personal account, and noted in the books. Never pay the personal bill directly from the LLC." }
  ],
  quiz: [
    { id: "m10-q01", q: "Which of these does an LLC NOT protect you from?", opts: ["A tenant's slip-and-fall claim at a property the LLC owns", "A loan you personally guaranteed", "A contractor's claim against the LLC for unpaid work", "A guest injured by a loose handrail at the LLC's rental"], correct: 1, explain: "A personal guarantee is your personal promise; the lender can pursue you directly. The LLC shields inside liability, not your own guarantees or your own negligence." },
    { id: "m10-q02", q: "What is a charging order?", opts: ["An order forcing the LLC to sell its property", "An order making the creditor a voting member", "An order directing the LLC to pay the debtor-member's distributions to the creditor", "A lien on the member's personal residence"], correct: 2, explain: "The creditor receives distributions if and when they are made, but gets no vote, no management rights, and cannot force a sale." },
    { id: "m10-q03", q: "In Florida, what can a judgment creditor do against a single-member LLC that it cannot do against a multi-member LLC?", opts: ["Nothing; the rules are identical", "Foreclose on the membership interest if a charging order will not satisfy the judgment in a reasonable time", "Seize the LLC's real estate directly", "Dissolve the LLC without a court order"], correct: 1, explain: "Fla. Stat. 605.0503, after Olmstead v. FTC (2010), permits foreclosure of a single-member interest; for multi-member LLCs the charging order is exclusive." },
    { id: "m10-q04", q: "Under Ohio's ORC 1706.342, a judgment creditor of an LLC member may:", opts: ["Foreclose on a single-member LLC interest", "Only obtain a charging order, with foreclosure prohibited regardless of member count", "Take possession of LLC property", "Force a distribution"], correct: 1, explain: "Ohio's Revised LLC Act makes the charging order the sole and exclusive remedy and does not distinguish single-member from multi-member LLCs." },
    { id: "m10-q05", q: "How is a two-member LLC taxed by default?", opts: ["As a C-corporation", "As a disregarded entity on one member's Schedule E", "As a partnership filing Form 1065 with K-1s", "As an S-corporation"], correct: 2, explain: "Multi-member LLCs default to partnership taxation. Single-member LLCs are disregarded. An S-corp requires an election." },
    { id: "m10-q06", q: "Which clause resolves a 50-50 tie between two partners without going to court?", opts: ["A capital call clause", "A deadlock buy-sell clause", "A transfer restriction", "An indemnification clause"], correct: 1, explain: "A deadlock clause provides mediation and then a buy-sell mechanism. Without it, the only remedy is judicial dissolution." },
    { id: "m10-q07", q: "A partner's ex-spouse is awarded part of the partner's LLC interest in a divorce. A well-drafted operating agreement would:", opts: ["Make the ex-spouse a full voting member", "Dissolve the LLC automatically", "Give the ex-spouse only an economic interest and give the other partner an option to buy it", "Require the LLC to sell all property"], correct: 2, explain: "Divorce clauses limit transferees to distribution rights with no vote and give the remaining partner a purchase option at a formula price." },
    { id: "m10-q08", q: "Where should the wholesale and flip business sit relative to the rentals?", opts: ["In the same LLC to save on fees", "In a separate operating LLC, possibly taxed as an S-corp, with rentals in separate holding LLCs", "Inside the rental holding LLC but with a separate bank account", "In the partners' personal names"], correct: 1, explain: "Active business risks and dealer status should be isolated from the valuable, passive rental assets. Never put rentals in the S-corp." },
    { id: "m10-q09", q: "Which state permits series LLCs by statute?", opts: ["Florida only", "Ohio only", "Both Florida and Ohio", "Neither"], correct: 1, explain: "Ohio's Revised LLC Act (ORC 1706.76, effective February 11, 2022) permits series LLCs. Florida has no series LLC statute." },
    { id: "m10-q10", q: "Which transfer is NOT a Garn-St Germain due-on-sale exception?", opts: ["Transfer into a living trust where the borrower remains a beneficiary", "Transfer to the borrower's children", "Transfer to the borrower's wholly owned LLC", "Transfer under a divorce decree"], correct: 2, explain: "12 U.S.C. 1701j-3(d) lists trusts, spouses and children, death, divorce, and short leases. LLCs are not on the list; Fannie Mae and Freddie Mac have their own LLC exemption." },
    { id: "m10-q11", q: "Under the Fannie Mae Servicing Guide, a transfer of a mortgaged property to an LLC is exempt from due-on-sale enforcement when:", opts: ["The loan is at least 12 months old", "The loan was purchased or securitized by Fannie Mae on or after June 1, 2016 and the original borrower controls or majority-owns the LLC", "The LLC has at least two members", "The property is a primary residence"], correct: 1, explain: "D1-4.1-02 keys on the June 1, 2016 purchase or securitization date and borrower control or majority ownership of the LLC." },
    { id: "m10-q12", q: "You deed a Florida rental with a $150,000 mortgage balance into your wholly owned LLC for no cash. Documentary stamp tax owed on the deed?", opts: ["$0, because no money changed hands", "$1,050", "$525", "$150"], correct: 1, explain: "Florida treats the mortgage balance as consideration. $150,000 ÷ $100 × $0.70 = $1,050. Only unencumbered transfers to a wholly owned entity escape doc stamps under Crescent Miami Center." },
    { id: "m10-q13", q: "What policy should insure a tenant-occupied rental?", opts: ["A standard homeowner (HO-3) policy", "A landlord or dwelling fire (DP-3) policy with replacement cost and loss of rent", "Renters insurance", "A builder's risk policy"], correct: 1, explain: "Homeowner policies assume owner occupancy and can deny claims on a rental. Builder's risk is for the rehab phase; renters insurance covers the tenant." },
    { id: "m10-q14", q: "What does an umbrella policy do?", opts: ["Replaces the landlord policy", "Covers the tenant's belongings", "Adds liability coverage above the limits of your landlord and auto policies", "Covers flood damage"], correct: 2, explain: "An umbrella responds when a judgment exceeds the underlying policy limits, typically in $1 million increments." },
    { id: "m10-q15", q: "What does a land trust provide on its own?", opts: ["Liability protection equal to an LLC", "Privacy of ownership and a Garn-St Germain living-trust exception, but no liability protection", "Tax deferral", "Exemption from property tax"], correct: 1, explain: "The beneficiary remains the owner for liability purposes and the trust agreement is discoverable. Name an LLC as beneficiary for protection." },
    { id: "m10-q16", q: "Which behavior is the most common veil-piercing factor?", opts: ["Hiring a property manager", "Carrying too much insurance", "Commingling personal and LLC funds", "Filing the annual report early"], correct: 2, explain: "Paying personal bills from the LLC account or depositing rent personally is the classic evidence that the LLC is not a separate business." },
    { id: "m10-q17", q: "After a tenant is injured, you transfer the LLC's cash to your personal account to protect it. This is:", opts: ["Smart asset protection", "A fraudulent transfer that invites veil piercing and penalties", "Permitted if documented as a distribution", "Required by most operating agreements"], correct: 1, explain: "Moving assets out after a claim arises is fraud on creditors and the strongest possible argument for holding you personally liable." },
    { id: "m10-q18", q: "What does it cost to form an LLC in Florida through Sunbiz, and what is the annual report fee?", opts: ["$99 and no annual report", "$125 and $138.75", "$138.75 and $400", "$100 and $50"], correct: 1, explain: "Florida: $125 to file Articles of Organization ($100 plus $25 registered agent fee); $138.75 annual report due by May 1, $538.75 if late." },
    { id: "m10-q19", q: "What does Ohio charge to file LLC Articles of Organization, and what is its annual report requirement?", opts: ["$125 and an annual report due May 1", "$99 and no annual or biennial report", "$50 and a biennial report", "$150 and an annual report due April 15"], correct: 1, explain: "Ohio charges $99 for Form 610 and does not require periodic LLC reports; keep the statutory agent current." },
    { id: "m10-q20", q: "How should you sign a lease on behalf of your LLC?", opts: ["Your personal name only", "The LLC's name only, with no individual signature", "[Your Company] LLC, by [Your Name], Manager", "The property manager's name"], correct: 2, explain: "Signing in a representative capacity shows the LLC is the contracting party and protects you from personal liability on the contract." }
  ],
  drills: [
    "Write a one-page outline of your two-partner operating agreement: each partner's contribution, profit split, the list of decisions that need both signatures, your deadlock mechanism, and what happens on death, divorce, and disability. Bring it to an attorney rather than asking the attorney to start from scratch.",
    "Look up the actual LLC filing fee and annual report deadline on your state's business filing website today (sunbiz.org for Florida, ohiosos.gov for Ohio) and put the deadline on a shared calendar with a two-week reminder.",
    "Call an insurance agent who writes investor policies and get quotes for a landlord (DP-3) policy with replacement cost and loss of rent, a vacant or builder's risk policy for the rehab period, and a $1 million umbrella. Ask in writing whether the umbrella will cover an LLC-owned property.",
    "Draft your standard signature block ([Your Company] LLC, by [Your Name], Manager) and add it to your lease template, your contractor agreement template, and your email signature for business correspondence.",
    "Open a separate business checking account for your first LLC and set up a bookkeeping file for it. Write a one-paragraph rule for yourself and your partner: every dollar in and out goes through this account, and money moving to a personal account is recorded as a distribution.",
    "If you already own a financed rental in your personal name, read the due-on-sale clause in your mortgage, then email your loan servicer asking in writing whether a transfer to an LLC you control is an exempt transaction under the Fannie Mae or Freddie Mac servicing guide. File the reply in the property folder."
  ]
});
