BIBLE.register({
  id: "m11",
  part: 5,
  title: "Marketing From Scratch",
  icon: "📣",
  summary: "How to build a motivated-seller marketing machine from zero: who to target, how to reach them legally, what it costs, and how to track every dollar so you know what is working by day ninety.",
  minutes: 95,
  lessons: [
    {
      id: "m11-01",
      title: "Who You Are Marketing To",
      minutes: 10,
      blocks: [
        { h: "Marketing is a targeting problem first", p: "Before you spend a dollar on letters, ads, or phone lists, you need to know exactly who you are trying to reach. In this business you have two audiences. The first is the motivated seller: an owner who has a reason to sell quickly, quietly, or without fixing anything, and who values speed and certainty over squeezing out the last dollar. The second is the cash buyer: an investor who will buy the deals you find, either from you as an assignment or as the end buyer on a property you flip. Everything you do in marketing is a message to one of these two people." },
        { h: "The seven motivated-seller avatars", p: "An avatar is a short description of a type of person and the situation they are in. The avatars that produce most off-market deals are these. Absentee owners: people who own a property they do not live in, often a rental or an inherited house in another city, and the distance makes ownership a hassle. Probate and inherited property: heirs who received a house after a death and may live far away, disagree with siblings, or simply want it gone. Pre-foreclosure: owners behind on the mortgage who have received a notice of default or a lis pendens, which is a public filing that a foreclosure lawsuit has started. Tax delinquent: owners behind on property taxes, which is public record and a strong sign of financial stress or neglect. Tired landlords: owners of rentals with bad tenants, deferred repairs, or evictions who are done being a landlord. Code violations: owners cited by the city for an unsafe or neglected property, which creates fines and pressure. Vacant properties: houses with no one living in them, which cost money every month and signal an owner who has emotionally checked out." },
        { h: "Stacking signals", p: "One signal is a lead. Two or three signals on the same property is a hot lead. An absentee owner whose rental is vacant and tax delinquent is far more likely to sell at a discount than an absentee owner with a paying tenant. When you build lists later in this module, you will look for properties that appear on more than one list. Investors call this list stacking, and it is the single biggest lever for improving response rates without spending more money." },
        { h: "The cash-buyer avatar", p: "Your buyer is usually a local fix-and-flip investor or a buy-and-hold landlord, often using hard money or private money, who buys several properties a year and can close in two to three weeks. They care about three things: a real discount to after-repair value, an honest repair estimate, and a clean, assignable contract. You find them at closings, at meetups, through title companies, and by watching who buys distressed properties for cash in the county records." },
        { carry: "Seven seller avatars: absentee, probate, pre-foreclosure, tax delinquent, tired landlord, code violation, vacant. Two or more signals on one property is a hot lead." },
        { trap: "Beginners market to everyone in a zip code because the list is cheap. You end up paying to reach thousands of people with no reason to sell. Narrow the list until every name on it has a motivation signal." }
      ]
    },
    {
      id: "m11-02",
      title: "Your Offer and Positioning",
      minutes: 9,
      blocks: [
        { h: "What you are actually selling", p: "You are not selling a house. You are selling a solution to a problem: a fast, certain, as-is sale with no repairs, no showings, no agent commission, and a closing date the seller picks. Your marketing should say that in plain words. The seller's problem might be a tenant, an inheritance, a tax bill, or just exhaustion. Your offer is relief from that problem in exchange for a price below retail. Both halves of that trade must be clear in your message." },
        { h: "Do not look like a bandit sign", p: "A bandit sign is a handwritten-looking yard sign that says something like we buy houses cash with a phone number. Sellers have seen thousands of them, and the look signals low effort and high pressure. You want to position as a small, local, professional buyer: a real company name, a real website, a real phone number that a human answers, a photo of the people behind the business, and a clear explanation of how the process works. Professional positioning raises your response rate and, more importantly, raises the quality of the sellers who respond." },
        { h: "A one-sentence positioning statement", p: "Write a single sentence that says who you help, what you do, and how you do it differently. For example: [Your Company] buys houses in [Your County] as-is for cash and closes on the seller's schedule, so owners who need a simple exit can skip repairs, showings, and commissions. Every letter, postcard, web page, and voicemail should be a version of this sentence. If you cannot say it in one breath, you are not ready to mail." },
        { h: "Credibility you can build in week one", p: "You do not need a track record to look credible. You need consistency. Use the same company name, logo, colors, and phone number everywhere. Put a short about page on your site with your names and why you do this. Add a simple how it works page with three steps. Set up a Google Business Profile so your company appears on a map. Ask the first few people you help, even if the deal did not close, for a short written review. These cost almost nothing and remove the biggest objection a seller has: is this real?" },
        { carry: "Position as a local, professional, as-is cash buyer who closes on the seller's timeline. Same name, same number, same look everywhere." },
        { trap: "Promising a specific price or a specific closing date in the marketing itself. You cannot know either until you see the house and check title. Promise the process, not the number." }
      ]
    },
    {
      id: "m11-03",
      title: "List Building",
      minutes: 11,
      blocks: [
        { h: "Where the data comes from", p: "Almost every motivated-seller list starts with public records. The county property appraiser or auditor publishes who owns each parcel and the mailing address, which is how you find absentee owners: the mailing address does not match the property address. The clerk of court publishes probate case filings and foreclosure filings. The tax collector publishes delinquent tax rolls. The city code enforcement office publishes violations, often searchable online or available by public records request. Utility shutoffs and vacancy data are harder to get directly but show up in paid tools. You can pull all of this yourself for free if you are willing to spend time, and that is exactly how to start when money is tight." },
        { h: "Paid list tools, described generically", p: "There is a category of software that aggregates county data nationwide and lets you filter it: owner type, equity, years owned, vacancy flags, pre-foreclosure status, tax delinquency, and more. These tools typically charge a monthly subscription, as of late 2026 usually somewhere in the range of a few dozen to a couple hundred dollars a month depending on features, and some charge extra to export records or to skip trace, which means finding the owner's phone number and email. A second category is driving-for-dollars apps, which let you tag a distressed property from your phone while you drive and then look up and mail the owner. The tool matters far less than the filters you choose and the follow-up you do." },
        { h: "Driving for dollars", p: "Driving for dollars means driving or walking target neighborhoods and writing down addresses of properties that look neglected: tall grass, boarded windows, tarps on the roof, piled mail, code notices on the door, full gutters, cars that have not moved. These are vacant and distressed properties that no list can fully capture, and the owners often get far less mail than people on purchased lists. You then look up the owner in the appraiser's records and mail or call. Done consistently, a few hours a week produces a small, high-quality list that competitors are not touching." },
        { h: "Cleaning and stacking your list", p: "Before you mail, remove duplicates, remove owners who are the same entity under multiple spellings, remove government and bank-owned parcels, and remove anyone who has told you to stop contacting them. Then stack: mark which records appear on two or more of your lists. Mail the stacked records first and most often. Keep every list in one spreadsheet with columns for source, date pulled, owner name, property address, mailing address, signals, and contact history. This spreadsheet becomes your CRM, which stands for customer relationship management system, until you outgrow it." },
        { carry: "Free sources: property appraiser (absentee), clerk of court (probate, foreclosure), tax collector (delinquent), code enforcement (violations), your own eyes (vacant). Stack lists and mail the overlaps first." },
        { trap: "Buying a huge list and mailing it once. A single touch to ten thousand names almost always loses to five touches to one thousand well-chosen names." }
      ]
    },
    {
      id: "m11-04",
      title: "Direct Mail",
      minutes: 12,
      blocks: [
        { h: "Why mail still works", p: "Direct mail is the most reliable channel for a brand-new investor because it is permission-free, it reaches owners whose phone numbers you cannot find, it does not require a license or consent, and it scales with your budget in a predictable way. The downside is that it is slow: most responses come in the second, third, and fourth mailing, not the first." },
        { h: "Letters versus postcards", p: "A postcard is cheap, fast, and gets read because there is nothing to open, but it is also obviously marketing. A letter in a plain envelope, especially one with a handwritten or handwriting-style address, gets opened at a higher rate and feels personal, but costs more per piece and takes longer to produce. A common approach is to send letters to your highest-value stacked records and probate leads, and postcards to larger, lower-signal lists. Whatever you send, keep it short, name the property address, explain in two sentences what you offer, and give one clear way to respond: a phone number and a website." },
        { h: "Frequency and response rates", p: "Industry guides for investor direct mail commonly report response rates in roughly the one to five percent range, with higher results from stacked lists, handwritten pieces, and repeated touches. Treat that as an approximate range, not a promise. A response is a call or a web form, not a deal: many responses are people asking you to stop or asking for a retail price. Plan to mail the same list every four to six weeks for at least five to seven touches before you judge it. Sellers rarely act on the first piece; they act when their situation changes and your name is the one on the fridge." },
        { h: "What it costs", p: "As of mid-2025 the United States Postal Service raised a Forever stamp to seventy-eight cents and a domestic postcard stamp to sixty-one cents. Printed and mailed through a mail house, postcards commonly run in the range of roughly thirty to seventy cents each all-in with bulk postage, and letters more. Say you mail one thousand postcards at fifty cents, which is five hundred dollars. At a two percent response rate you get twenty responses. If a quarter of those are real conversations, you have five leads at one hundred dollars per lead. If it takes twenty leads to get a deal, your cost per deal from mail is around two thousand dollars. Run this math on your own numbers every month." },
        { formula: "Cost per lead = total mail spend ÷ qualified responses. Cost per deal = total mail spend ÷ closed deals." },
        { example: "1,000 postcards × $0.50 = $500. 2% response = 20 responses. 5 qualified leads → $100 per lead. One deal per 20 leads → about $2,000 per deal." },
        { carry: "Mail the same list every 4–6 weeks for 5–7 touches. Response rate roughly 1–5% (approximate); a response is a conversation, not a deal." },
        { trap: "Judging a list after one mailing. The first touch almost always looks like a failure. Budget for the full sequence before you send the first piece." },
        { sources: [
          { t: "REsimpli, Direct Mail Marketing for Real Estate Investors guide (response rates, postcard costs)", u: "https://resimpli.com/blog/direct-mail-marketing-for-real-estate-investors-the-ultimate-guide/" },
          { t: "USPS, New Prices for July 2025 (Forever stamp 78¢, postcard 61¢)", u: "https://about.usps.com/newsroom/national-releases/2025/0409-usps-recommends-new-prices-for-july-2025.htm" }
        ] }
      ]
    },
    {
      id: "m11-05",
      title: "Cold Calling and Texting: The Compliance Layer",
      minutes: 14,
      blocks: [
        { h: "Why this lesson matters more than the script", p: "Calling and texting owners directly is fast and cheap, which is why so many investors do it, and it is also where new investors get sued. The rules below are not optional and they are not the same in every state. Read this lesson twice. Then confirm your specific plan with a local attorney before you dial." },
        { h: "The TCPA", p: "The Telephone Consumer Protection Act, a federal law found at Title 47, United States Code, Section 227, restricts calls and texts made with an automatic telephone dialing system, an artificial or prerecorded voice, and telephone solicitations to residential numbers. Texts are treated as calls. The FCC's rules under the TCPA prohibit telephone solicitations before eight in the morning or after nine at night in the called party's local time, require you to honor the National Do Not Call Registry, and require you to keep your own internal do-not-call list and honor a request within ten business days. The penalty structure is what makes this dangerous: the statute allows a private lawsuit for five hundred dollars per violation, and up to three times that amount if the court finds the violation willful or knowing. A thousand texts to the wrong list can be a seven-figure exposure." },
        { h: "The National Do Not Call Registry", p: "The Federal Trade Commission runs the National Do Not Call Registry. Before you make telephone solicitations, you scrub your list against it, which means removing every number that is registered, and you re-scrub at least every thirty-one days. Telemarketers must subscribe to access the registry. As of the fiscal year beginning October 1, 2025, the first five area codes are free and each additional area code costs eighty-two dollars per year, with a nationwide cap of twenty-two thousand six hundred twenty-six dollars. Most beginners only need a handful of area codes, so this costs very little. Do not skip it." },
        { h: "AI voices and the one-to-one consent rule", p: "Two recent developments matter. First, on February 8, 2024, the FCC issued a Declaratory Ruling that AI-generated voices count as artificial voices under the TCPA, so using an AI voice to call someone without their prior express consent is treated the same as an illegal robocall, effective immediately. If you use any AI calling or voicemail-drop tool, you need the same consent you would need for a prerecorded message. Second, the FCC had adopted a one-to-one consent rule that would have required consent to name a single specific seller; in January 2025 the Eleventh Circuit Court of Appeals vacated that rule in Insurance Marketing Coalition v. FCC, holding the FCC exceeded its authority, so the prior consent standard applies. Practically, this means lead-generation websites can still gather consent for multiple buyers, but you still need clear prior express consent before any autodialed or prerecorded contact, and the rules can change again. Check for updates before you launch a texting campaign." },
        { h: "State laws stack on top", p: "Many states have their own telemarketing laws that are stricter than the federal rules, and both of the states this curriculum focuses on do. Florida's Telephone Solicitation Act requires prior express written consent before any autodialed call or text, limits solicitation calls to between eight in the morning and eight at night, caps attempts at three per twenty-four hours on the same subject, and provides its own five hundred dollar per violation private lawsuit with up to triple damages. Ohio's Telephone Solicitation Sales Act requires certain telephone solicitors to register with the Ohio Attorney General and post a bond before soliciting Ohio consumers, and requires you to state your real name, company, and purpose within the first sixty seconds. Read the Florida and Ohio guides in this curriculum before you call anyone in either state, and confirm with a local real estate attorney." },
        { h: "A practical compliance checklist", p: "Call manually, one number at a time, from a real phone, using a real human voice. Scrub against the federal registry and any state registry at least monthly and keep the receipts. Keep an internal do-not-call list and add anyone who asks to stop, immediately. Call and text only between the narrowest allowed window, which in Florida is eight in the morning to eight at night. Get written consent before any automated or AI contact. Identify yourself and your company in the first sentence. Keep a log of every call and text. If any of this feels like too much, stick to mail until you can afford a compliance-focused calling platform and an attorney review." },
        { carry: "TCPA: $500 per violation, up to 3× if willful. Scrub the DNC registry every 31 days. No autodialer, no AI voice, no prerecorded message without prior express consent. Florida: written consent, 8am–8pm, 3 attempts per 24 hours." },
        { state: { fl: "Florida Statute 501.059 requires prior express written consent for autodialed calls and texts; 501.616 limits calls to 8am–8pm and three attempts per 24 hours; private action $500 per violation, up to triple for willful violations.", oh: "Ohio Revised Code Chapter 4719 requires certain telephone solicitors to register with the Attorney General and post a bond; disclose name, company, and purpose within 60 seconds. Review the exemptions in 4719.01 with an attorney." } },
        { trap: "Buying a skip-traced list and loading it into a mass-texting tool on day one. Texts are calls under the TCPA, and a texting platform does not make you compliant. Confirm with a local real estate attorney before you send the first automated message." },
        { sources: [
          { t: "47 U.S.C. § 227 (TCPA), statutory damages", u: "https://www.law.cornell.edu/uscode/text/47/227" },
          { t: "47 CFR 64.1200 (calling hours, DNC registry, internal DNC list)", u: "https://www.ecfr.gov/current/title-47/chapter-I/subchapter-B/part-64/subpart-L/section-64.1200" },
          { t: "FTC press release, DNC Registry telemarketer fees for FY2026", u: "https://www.ftc.gov/news-events/news/press-releases/2025/08/telemarketer-fees-access-ftcs-national-do-not-call-registry-increase-2026" },
          { t: "FCC Declaratory Ruling, AI-generated voices are artificial under the TCPA (Feb 8, 2024)", u: "https://docs.fcc.gov/public/attachments/DOC-400393A1.pdf" },
          { t: "Morrison Foerster, Eleventh Circuit vacates FCC one-to-one consent rule (Jan 2025)", u: "https://www.mofo.com/resources/insights/250130-eleventh-circuit-vacates-fcc-s-tcpa-one-to-one-consent-rule" },
          { t: "Florida Statute 501.059, Telephone solicitation", u: "http://www.leg.state.fl.us/statutes/index.cfm?App_mode=Display_Statute&URL=0500-0599/0501/Sections/0501.059.html" },
          { t: "Nolo, Florida Telemarketing Law (501.616 hours and three-call limit)", u: "https://www.nolo.com/legal-encyclopedia/florida-restrictions-telemarketers.html" },
          { t: "Ohio Attorney General, Telemarketing and Do Not Call Registry (ORC Chapter 4719)", u: "https://www.ohioattorneygeneral.gov/Business/Services-for-Business/Business-Guide/Telemarketing-and-Do-Not-Call-Registry" }
        ] }
      ]
    },
    {
      id: "m11-06",
      title: "Online: Website, Search, Social, Video",
      minutes: 11,
      blocks: [
        { h: "The website is the hub", p: "Every other channel sends people somewhere, and that somewhere should be a simple website you control. It needs five things: your positioning sentence above the fold, a short form that asks for name, phone, and property address, a how it works section with three steps, an about page with real names and a photo, and a phone number that rings a human. Load fast on a phone. Nothing else matters at the start. Many investor website platforms exist and cost a modest monthly fee; a basic site builder works too." },
        { h: "Google pay-per-click", p: "Pay-per-click, or PPC, means you pay Google each time someone clicks your ad after searching a phrase like sell my house fast or we buy houses plus your city. These are high-intent searchers who are actively looking for a buyer, so PPC leads tend to be warmer than mail leads and convert at a higher rate; one long-running investor marketing guide describes closing roughly one in ten to one in fifteen PPC leads as a strong result. The cost is the catch: competitive real estate keywords are expensive per click, and you need enough budget to get a statistically meaningful number of clicks before you can judge anything. A good rule from that same guide is to budget your test as one hundred clicks times your estimated cost per click. For a five hundred dollar a month start, PPC is usually not the first channel. For two thousand a month, a focused campaign on a handful of exact-match keywords in your county can work." },
        { h: "SEO", p: "Search engine optimization, or SEO, is earning free search traffic by publishing useful pages. For an investor that means a page for each city you buy in, honest articles about how to sell an inherited house, what happens in a foreclosure, how to sell a house with a bad tenant, and so on. SEO takes months to produce leads, so start it in month one and expect nothing until month six or later. It is the channel that gets cheaper over time while every other channel gets more expensive." },
        { h: "Facebook, Instagram, and YouTube", p: "Social content does two jobs. It makes you look real when a seller checks you out after getting your letter, and it builds your cash-buyer list because investors follow investors. Post short, honest updates: a property you walked, a lesson you learned, a before and after. Avoid hype and never promise returns. YouTube is the long game: a plain video answering one seller question per week, cut into short clips for other platforms, compounds for years. None of this needs to be polished. It needs to be consistent and true. Paid social ads to sellers are possible but tend to produce lower-intent leads than search; treat them as a test, not a foundation." },
        { carry: "Website first: positioning sentence, short form, how it works, about page, phone. PPC is high intent but needs budget; SEO is slow but compounds; social proves you are real and builds your buyer list." },
        { trap: "Spending the first month designing a beautiful website and logo instead of mailing. A one-page site built in a weekend is enough. Marketing that reaches sellers beats marketing that impresses you." },
        { sources: [
          { t: "Carrot, Ultimate Guide to Google Ads for Real Estate Investors (test budget formula, conversion range)", u: "https://carrot.com/blog/adwords-for-real-estate-investors/" }
        ] }
      ]
    },
    {
      id: "m11-07",
      title: "Networking and Your Cash Buyers List",
      minutes: 10,
      blocks: [
        { h: "Agents", p: "Real estate agents see distressed listings, expired listings, and sellers whose homes will not pass a lender's inspection. Find investor-friendly agents by asking at meetups and by watching who lists the beat-up houses in your target zips. Offer them two things: a fast, clean cash closing for their problem listings, and the chance to represent you on the buy side so they earn a commission. Be reliable the first time and they will call you first the second time." },
        { h: "Other wholesalers", p: "Other wholesalers are not just competitors. A wholesaler with a deal and no buyer will often split the fee with someone who brings the buyer, which investors call a joint venture or JV. A wholesaler who finds a deal outside their buy box will send it to you if you have sent them one. Build a short list of five to ten active wholesalers, learn exactly what each one buys, and trade honestly." },
        { h: "Title companies and attorneys", p: "An investor-friendly title company or closing attorney sees every cash sale in the county. They know who the active cash buyers are, they can tell you whether an assignment or a double close is routine in your market, and they will often introduce you to lenders and other investors. Pick one early, bring them coffee, and ask how they prefer to receive contracts. You will learn more about the local market in that conversation than in a month of videos." },
        { h: "Meetups and building the buyers list", p: "Go to every local real estate investor meetup for the first ninety days. Your goal is not to pitch; it is to collect the names of people who actually buy. Ask each one: what do you buy, where, at what discount, how fast can you close, and how do you want to receive deals. Put the answers in a spreadsheet with name, phone, email, areas, property types, max price, funding type, and proof of funds on file. Add buyers from county records by searching recent cash sales of distressed properties and mailing those buyers. Add buyers who respond to a simple online listing of a property you have under contract. A list of twenty real, verified buyers beats a list of five hundred names from a Facebook group." },
        { carry: "Buyers list columns: name, phone, email, areas, property types, max price, funding, proof of funds, last contact. Twenty verified buyers beats five hundred names." },
        { trap: "Treating anyone who says they are a cash buyer as one. Ask for a recent closing statement or proof of funds before you send them a contract. Tire-kickers waste the inspection period you negotiated with the seller." }
      ]
    },
    {
      id: "m11-08",
      title: "Tracking: Cost Per Lead, Appointment, and Deal",
      minutes: 9,
      blocks: [
        { h: "You cannot improve what you do not measure", p: "Marketing feels random until you track it, and then it becomes a machine with dials. Every channel you run needs its own phone number or tracking code so you know where each lead came from. Several call-tracking services sell local numbers for a few dollars a month each; put a different number on your postcards, your letters, your website, and your signs. Every lead goes into one spreadsheet with the source filled in. No exceptions." },
        { h: "The four numbers", p: "Cost per lead is what you spent on a channel divided by the number of real conversations with a decision-maker it produced. Cost per appointment is spend divided by the number of in-person or video walk-throughs it produced. Cost per contract is spend divided by signed purchase agreements. Cost per deal is spend divided by closed deals. Track all four by channel by month. The ratios between them tell you where the problem is: lots of leads but few appointments means your phone skills need work; lots of appointments but few contracts means your offers or your rapport need work; lots of contracts but few closings means your deals are not real or your buyers list is weak." },
        { formula: "CPL = spend ÷ leads. CPA = spend ÷ appointments. CPC = spend ÷ contracts. CPD = spend ÷ closed deals." },
        { example: "Month: $1,200 on mail → 12 leads ($100 CPL) → 4 appointments ($300 CPA) → 1 contract ($1,200 per contract) → 1 closed deal with a $12,000 assignment fee. Return: 10 to 1." },
        { h: "A simple KPI sheet", p: "A key performance indicator, or KPI, is a number you watch every week. Build one sheet with a row per week and these columns: mail pieces sent, calls made, texts sent, website visits, leads, appointments, offers made, contracts signed, deals closed, total marketing spend, and revenue. At the bottom of each month compute the four costs per channel. Review the sheet with your partner every Monday for fifteen minutes. The habit matters more than the format." },
        { carry: "Separate tracking number per channel. Track CPL, CPA, CPC, CPD monthly by channel. Review the KPI sheet with your partner every week." },
        { trap: "Using one phone number for everything. Six months later you have no idea which channel produced your deals, so you cannot cut the losers or double the winners." }
      ]
    },
    {
      id: "m11-09",
      title: "Budgets and the 90-Day Launch Plan",
      minutes: 9,
      blocks: [
        { h: "A $500 a month start", p: "With five hundred dollars a month you cannot afford PPC or paid tools that bite into the budget, so you buy time with effort. Spend about three hundred and fifty dollars on roughly seven hundred postcards or three hundred letters to a stacked list you pulled yourself from county records. Spend about fifty dollars on a basic website and domain. Spend about fifty dollars on a call-tracking number and a simple CRM or spreadsheet tool. Keep fifty dollars for gas and printing while you drive for dollars four hours a week. Call your list manually, compliantly, during allowed hours. Attend two meetups a month for free. This budget wins on consistency: the same seven hundred names, mailed every five weeks, called in between." },
        { h: "A $2,000 a month start", p: "With two thousand dollars a month you add reach and speed. Spend about one thousand dollars on mail to a larger stacked list, perhaps two thousand postcards or a mix of letters and postcards. Spend about one hundred fifty dollars on a list and skip-tracing tool. Spend about five hundred dollars on a tightly targeted Google PPC test in your county, or on a part-time virtual assistant who makes compliant manual calls under your supervision. Spend about two hundred dollars on website, tracking numbers, CRM, and DNC registry access. Keep one hundred fifty dollars for driving, printing, meetup costs, and a thank-you gift for the title company that sends you your first buyer. These dollar figures are illustrative splits, not quotes; prices change, so get current pricing before you commit." },
        { h: "The 90-day plan, week by week", p: "Weeks one and two: write your positioning sentence, set up the company name, phone number, website, and spreadsheet; pull your first lists from county records; scrub against the DNC registry; attend your first meetup; set up the KPI sheet. Weeks three and four: send mailing one; start driving for dollars four hours a week; begin manual compliant calling two hours a day on allowed days; interview two title companies. Weeks five and six: answer every call within five minutes; set your first appointments; send mailing two; publish three website pages for SEO; add every buyer you meet to the buyers list. Weeks seven and eight: make your first written offers; send mailing three; review the KPI sheet with your partner and cut any channel with zero leads after two full touches. Weeks nine and ten: sign your first contract or diagnose why not; send mailing four; get proof of funds from your top ten buyers. Weeks eleven and twelve: send mailing five; market your contract to buyers; close or assign; compute cost per lead, appointment, contract, and deal for the quarter; decide what to double for the next ninety days." },
        { carry: "Ninety days: set up in weeks 1–2, mail every 5 weeks, call daily, drive weekly, meetup monthly, review KPIs weekly, first offer by week 7, first contract by week 10." },
        { trap: "Changing channels every two weeks because nothing has happened yet. Marketing compounds. Pick two channels, run them for the full ninety days, and only then judge." }
      ]
    }
  ],
  cards: [
    { id: "m11-c01", type: "term", q: "What is a motivated seller?", a: "An owner with a real reason to sell quickly or as-is who values speed and certainty over top price. Example: an out-of-state heir with a vacant inherited house and a tax bill." },
    { id: "m11-c02", type: "term", q: "What is an absentee owner?", a: "An owner whose mailing address differs from the property address, meaning they do not live there. Usually a landlord or an heir. Found in county property appraiser records." },
    { id: "m11-c03", type: "term", q: "What is a lis pendens?", a: "A public court filing that a lawsuit affecting the property, usually a foreclosure, has begun. It is a pre-foreclosure signal you can pull from the clerk of court." },
    { id: "m11-c04", type: "term", q: "What is list stacking?", a: "Finding properties that appear on two or more motivation lists, such as absentee plus tax delinquent plus vacant, and marketing to those first and most often." },
    { id: "m11-c05", type: "term", q: "What is driving for dollars?", a: "Driving or walking target neighborhoods to record addresses of visibly distressed or vacant properties, then looking up and contacting the owners." },
    { id: "m11-c06", type: "term", q: "What is skip tracing?", a: "Finding an owner's current phone number and email from their name and address, usually through a paid data tool, so you can call or text instead of only mail." },
    { id: "m11-c07", type: "term", q: "What is a bandit sign and why avoid the look?", a: "A cheap handwritten-style yard sign that says we buy houses with a phone number. Sellers associate it with low effort and high pressure; professional positioning gets better-quality responses." },
    { id: "m11-c08", type: "term", q: "What is a positioning statement?", a: "One sentence saying who you help, what you do, and how you are different, used consistently across every channel. Example: [Your Company] buys houses as-is for cash and closes on the seller's schedule." },
    { id: "m11-c09", type: "term", q: "What is the TCPA?", a: "The Telephone Consumer Protection Act, 47 U.S.C. 227, the federal law restricting autodialed calls, artificial or prerecorded voices, and telephone solicitations. Texts count as calls." },
    { id: "m11-c10", type: "term", q: "What is the National Do Not Call Registry?", a: "The FTC's list of phone numbers that have opted out of telemarketing. You must scrub your calling list against it and re-scrub at least every 31 days." },
    { id: "m11-c11", type: "term", q: "What is an internal do-not-call list?", a: "Your own list of people who asked you to stop contacting them. Federal rules require you to honor the request within ten business days; do it immediately." },
    { id: "m11-c12", type: "term", q: "What is PPC?", a: "Pay-per-click advertising, where you pay each time someone clicks your ad after searching a phrase like sell my house fast. High intent, high cost per click." },
    { id: "m11-c13", type: "term", q: "What is SEO?", a: "Search engine optimization: earning free search traffic by publishing useful pages, such as a guide to selling an inherited house in your county. Slow to start, compounds over time." },
    { id: "m11-c14", type: "term", q: "What is a KPI?", a: "A key performance indicator, a number you watch every week. For marketing: pieces sent, calls made, leads, appointments, offers, contracts, closings, spend." },
    { id: "m11-c15", type: "term", q: "What is a cash buyers list?", a: "Your verified roster of investors who buy with cash or hard money, with their areas, property types, max price, funding type, and proof of funds on file." },
    { id: "m11-c16", type: "term", q: "What is a JV in wholesaling?", a: "A joint venture: one wholesaler has the contract, another brings the buyer, and they split the assignment fee by written agreement." },
    { id: "m11-c17", type: "formula", q: "How do you compute cost per lead?", a: "CPL = channel spend ÷ qualified leads from that channel. Example: $600 on mail producing 6 real conversations = $100 per lead." },
    { id: "m11-c18", type: "formula", q: "How do you compute cost per deal?", a: "CPD = total channel spend ÷ closed deals. Example: $3,600 over three months of mail producing 2 closings = $1,800 per deal." },
    { id: "m11-c19", type: "formula", q: "How do you compute cost per appointment?", a: "CPA = channel spend ÷ walk-through appointments set. Example: $1,200 and 4 appointments = $300 per appointment." },
    { id: "m11-c20", type: "formula", q: "How do you size a PPC test budget?", a: "Test budget ≈ 100 clicks × estimated cost per click. If a click costs $15, a meaningful first test is about $1,500, which is why PPC is not a $500-a-month channel." },
    { id: "m11-c21", type: "formula", q: "How do you estimate mail responses before you send?", a: "Expected responses = pieces × response rate. 1,000 postcards at 2% = 20 responses; only a fraction are real leads." },
    { id: "m11-c22", type: "number", q: "What are TCPA statutory damages per violation?", a: "$500 per violation, and the court may increase it up to three times that amount for willful or knowing violations." },
    { id: "m11-c23", type: "number", q: "What hours does federal law allow telephone solicitations?", a: "8 a.m. to 9 p.m. in the called party's local time, under 47 CFR 64.1200(c). States can be stricter; Florida is 8 a.m. to 8 p.m." },
    { id: "m11-c24", type: "number", q: "How often must you re-scrub against the DNC registry?", a: "At least every 31 days; the registry version you use must be no more than 31 days old when you call." },
    { id: "m11-c25", type: "number", q: "What does DNC registry access cost for FY2026?", a: "First five area codes free, then $82 per area code per year, capped at $22,626 for all area codes, effective October 1, 2025." },
    { id: "m11-c26", type: "number", q: "When did the FCC rule that AI voices are artificial under the TCPA?", a: "February 8, 2024, by Declaratory Ruling, effective immediately. AI-voice calls need the same prior express consent as prerecorded robocalls." },
    { id: "m11-c27", type: "number", q: "What happened to the FCC one-to-one consent rule?", a: "The Eleventh Circuit vacated it in January 2025 in Insurance Marketing Coalition v. FCC, so the prior consent standard applies. Watch for further changes." },
    { id: "m11-c28", type: "number", q: "What did USPS charge for a Forever stamp and a postcard stamp after July 2025?", a: "Forever stamp 78 cents; domestic postcard 61 cents. Mail-house bulk postage is lower." },
    { id: "m11-c29", type: "number", q: "What is a typical investor direct-mail response rate?", a: "Roughly 1–5% according to industry guides, approximate and list-dependent. A response is a call, not a deal." },
    { id: "m11-c30", type: "number", q: "How many touches should a mail list get before you judge it?", a: "Five to seven touches, roughly every four to six weeks. Most responses come after the first mailing, not from it." },
    { id: "m11-c31", type: "number", q: "How long should you give SEO before expecting leads?", a: "Six months or more. Start in month one so it is producing when your paid channels get expensive." },
    { id: "m11-c32", type: "number", q: "How fast should you return a seller's call?", a: "Within five minutes when you can. Speed to lead is the cheapest conversion improvement you will ever make." },
    { id: "m11-c33", type: "state", q: "What are the key telemarketing restrictions in Florida versus Ohio?", a: "FL: prior express written consent for autodialed calls and texts (501.059), calls 8am–8pm, max three attempts per 24 hours (501.616), $500 per violation up to triple. | OH: certain solicitors must register with the Attorney General and post a bond (ORC 4719); disclose name, company, and purpose within 60 seconds." },
    { id: "m11-c34", type: "state", q: "Which state's call window is narrower, and what is it?", a: "FL: 8am–8pm, narrower than the federal 8am–9pm. | OH: follows the federal 8am–9pm window; review ORC 4719 for registration duties." },
    { id: "m11-c35", type: "state", q: "Where does each state publish its telemarketing rules?", a: "FL: Florida Statutes 501.059 and 501.616, enforced by the Department of Agriculture and Consumer Services. | OH: Ohio Revised Code Chapter 4719, enforced by the Ohio Attorney General." },
    { id: "m11-c36", type: "scenario", q: "You have $500 a month and one weekend. What is the first marketing move?", a: "Pull a stacked list from free county records, mail about 700 postcards or 300 letters to it, set up a one-page site and a tracking number, and schedule the second mailing before the first goes out." },
    { id: "m11-c37", type: "scenario", q: "A tool offers to text 5,000 skip-traced owners for $200. What do you do?", a: "Decline until you have written consent or an attorney-approved manual process. Texts are calls under the TCPA; 5,000 unconsented texts could mean $2.5 million in exposure." },
    { id: "m11-c38", type: "scenario", q: "A seller calls from your postcard and says take me off your list. What do you do?", a: "Add them to your internal do-not-call and do-not-mail list immediately, confirm politely, and never contact them again. Federal rules require honoring it within ten business days." },
    { id: "m11-c39", type: "scenario", q: "Your first mailing of 1,000 postcards produced three calls, all asking for retail price. Quit the list?", a: "No. One touch tells you nothing. Send touches two through five on schedule, track responses per touch, and judge the list after the full sequence." },
    { id: "m11-c40", type: "scenario", q: "You want to use an AI voice agent to call your list after hours. Is that allowed?", a: "Not without prior express consent. Since the FCC's February 2024 ruling, AI voices are artificial voices under the TCPA, and after-hours solicitation calls violate the 8am–9pm rule anyway." },
    { id: "m11-c41", type: "scenario", q: "An absentee owner's rental shows up on the vacant list and the tax-delinquent list. How do you treat it?", a: "It is a stacked, hot lead. Send a personal letter first, follow with a compliant manual call, and keep it at the top of your follow-up list." },
    { id: "m11-c42", type: "scenario", q: "You have 12 leads this month but only one appointment. Which part of the funnel is broken?", a: "Lead-to-appointment conversion, which is your phone skills and qualifying. Record your calls, review them with your partner, and tighten the first-call structure before spending more on leads." },
    { id: "m11-c43", type: "scenario", q: "You have 6 appointments but zero contracts after two months. What do you fix?", a: "Appointment-to-contract: your offer presentation, rapport, or your numbers. Practice presenting the math and the options, and check whether your offers are realistic for the market." },
    { id: "m11-c44", type: "scenario", q: "A Facebook group member says they are a cash buyer and wants your contract. What do you ask for?", a: "Proof of funds or a recent closing statement, their buy box, and how fast they close. No proof, no contract. Protect your inspection period." },
    { id: "m11-c45", type: "scenario", q: "You are deciding between PPC and mail with a $2,000 budget. How do you split it?", a: "Mail is the foundation; put roughly half into a stacked-list mail sequence, test PPC with a tight exact-match campaign only if you can fund about 100 clicks, and keep the rest for tools, tracking, and DNC access." },
    { id: "m11-c46", type: "scenario", q: "You meet an investor-friendly agent at a meetup. What do you offer?", a: "A reliable cash close for their problem listings and the buy-side commission when they represent you. Then close your first one cleanly so they call you first next time." },
    { id: "m11-c47", type: "scenario", q: "A title company asks how you plan to close your wholesale deals. Why does the answer matter?", a: "They see every cash sale in the county and know which buyers are real and whether assignments are routine locally. Ask how they want contracts delivered and who the active cash buyers are." },
    { id: "m11-c48", type: "scenario", q: "You are about to call a Florida owner at 8:30 p.m. Is it allowed?", a: "No. Florida limits solicitation calls to 8 a.m. to 8 p.m. even though federal law allows until 9 p.m. Wait until the next morning." },
    { id: "m11-c49", type: "scenario", q: "You have called a Florida owner three times today with no answer. Can you try once more tonight?", a: "No. Florida caps attempts at three per 24 hours on the same subject. Log it and try tomorrow during allowed hours." },
    { id: "m11-c50", type: "scenario", q: "Day 60 of your 90-day plan and no contract yet. What does the plan say to do?", a: "Diagnose, not quit: review CPL, CPA, and offers made; cut any channel with zero leads after two full touches; keep mailing on schedule; get proof of funds from your top buyers." },
    { id: "m11-c51", type: "trap", q: "Mailing one huge list once.", a: "Costs the same as five touches to a fifth of the list and almost always produces fewer deals. Shrink the list, increase the frequency." },
    { id: "m11-c52", type: "trap", q: "One phone number on everything.", a: "You lose the ability to compute cost per lead by channel. Use a separate tracking number per channel from day one; they cost a few dollars a month." },
    { id: "m11-c53", type: "trap", q: "Promising a price or closing date in the marketing.", a: "You cannot know either before the walk-through and title search. Promise the process: as-is, cash, no commissions, your timeline." },
    { id: "m11-c54", type: "trap", q: "Skipping the DNC scrub because you are only calling a few hundred people.", a: "A single registered number is a violation worth $500 to $1,500. Access to five area codes is free. Scrub every list, every month." },
    { id: "m11-c55", type: "trap", q: "Switching channels every two weeks.", a: "Marketing compounds; nothing works in two weeks. Choose two channels and run them for the full ninety days before judging." },
    { id: "m11-c56", type: "trap", q: "Spending month one on a logo and a perfect website.", a: "A one-page site built in a weekend is enough. Sellers respond to clear offers and fast callbacks, not design." },
    { id: "m11-c57", type: "trap", q: "Assuming a texting platform makes you compliant.", a: "The platform sends the message; you own the consent, the scrub, the hours, and the liability. Get written consent or stick to manual, compliant calls." },
    { id: "m11-c58", type: "trap", q: "Treating mail responses as deals.", a: "Many responses are opt-outs and retail-price seekers. Count qualified conversations as leads and track them separately." },
    { id: "m11-c59", type: "trap", q: "Building a buyers list of names without verifying funds.", a: "Unverified buyers tie up your contract and burn your inspection period. Require proof of funds before sending any contract." },
    { id: "m11-c60", type: "trap", q: "Starting SEO only after paid channels get expensive.", a: "SEO needs six-plus months to produce. Publish your first pages in month one so it carries weight when you need it." },
    { id: "m11-c61", type: "term", q: "What is a Google Business Profile and why set one up?", a: "A free listing that puts your company on Google Maps and search with hours, phone, and reviews. It is the fastest free credibility signal for a new company." },
    { id: "m11-c62", type: "term", q: "What is an established business relationship under the TCPA rules?", a: "A relationship from a purchase within the prior 18 months or an inquiry within the prior 3 months. It affects DNC treatment but does not replace consent for autodialed or prerecorded contact." },
    { id: "m11-c63", type: "number", q: "How many hours a week of driving for dollars does the $500 plan assume?", a: "About four hours a week, producing a small list of vacant and distressed properties that competitors are not mailing." },
    { id: "m11-c64", type: "scenario", q: "Your partner wants to skip the weekly KPI review because nothing has changed. What do you say?", a: "The habit is the point. Fifteen minutes every Monday, same sheet, same columns. The week nothing changes is the week you spot that calls dropped to zero." },
    { id: "m11-c65", type: "term", q: "What is a mail house?", a: "A printing and mailing vendor that prints your pieces, applies bulk postage, and mails them, usually at a lower all-in cost per piece than doing it yourself at scale." }
  ],
  quiz: [
    { id: "m11-q01", q: "Which of these is the strongest single lead?", opts: ["An owner-occupant in a nice neighborhood", "An absentee owner whose rental is vacant and tax delinquent", "Any address in a zip code you like", "A homeowner who just refinanced"], correct: 1, explain: "Three stacked motivation signals on one property make it far more likely to sell at a discount than any unstacked record." },
    { id: "m11-q02", q: "What are TCPA statutory damages per violation?", opts: ["$100, up to $300 if willful","$1,000 flat","$50 per text","$500, up to $1,500 if willful"], correct: 3, explain: "47 U.S.C. 227 provides $500 per violation and allows courts to increase the award up to three times that for willful or knowing violations." },
    { id: "m11-q03", q: "How often must a calling list be re-scrubbed against the National Do Not Call Registry?", opts: ["Once a year", "Every 90 days", "At least every 31 days", "Only when you buy a new list"], correct: 2, explain: "47 CFR 64.1200 requires using a registry version obtained no more than 31 days before the call." },
    { id: "m11-q04", q: "What did the FCC's February 8, 2024 Declaratory Ruling establish?", opts: ["AI-generated voices are artificial voices under the TCPA","Texts are not calls under the TCPA","Calling hours extended to 10 p.m.","The DNC registry was abolished"], correct: 0, explain: "The FCC ruled AI-generated voices count as artificial, so AI-voice calls need the same prior express consent as prerecorded robocalls." },
    { id: "m11-q05", q: "What happened to the FCC's one-to-one consent rule?", opts: ["It took effect nationwide in 2025", "The Supreme Court upheld it", "The Eleventh Circuit vacated it in January 2025", "Congress repealed it in 2026"], correct: 2, explain: "In Insurance Marketing Coalition v. FCC the Eleventh Circuit held the FCC exceeded its authority, restoring the prior consent standard." },
    { id: "m11-q06", q: "Federal rules allow telephone solicitations during which hours?", opts: ["7 a.m. to 10 p.m.", "8 a.m. to 9 p.m. local time of the called party", "9 a.m. to 5 p.m.", "Any time on weekdays"], correct: 1, explain: "47 CFR 64.1200(c)(1) sets 8 a.m. to 9 p.m. at the called party's location; some states, like Florida, are narrower." },
    { id: "m11-q07", q: "Florida's call window and attempt cap for solicitation calls are:", opts: ["8am–9pm, unlimited attempts","9am–6pm, one attempt per day","8am–8pm, max three attempts per 24 hours on the same subject","No state rule; federal only"], correct: 2, explain: "Florida Statute 501.616 limits calls to 8 a.m. to 8 p.m. and three attempts per 24-hour period on the same subject matter." },
    { id: "m11-q08", q: "What does Ohio's Telephone Solicitation Sales Act (ORC 4719) require of certain telephone solicitors?", opts: ["A real estate license","A $500 annual fee to the FCC","Nothing; Ohio has no state rule","Registration with the Attorney General and a bond"], correct: 3, explain: "Ohio requires covered solicitors to register with the Attorney General and post a bond, and to disclose name, company, and purpose within 60 seconds. Check exemptions with an attorney." },
    { id: "m11-q09", q: "You mail 1,000 postcards at $0.50 each and get 20 responses, 5 of which are qualified. Cost per lead?", opts: ["$25", "$50", "$100", "$500"], correct: 2, explain: "Spend is $500; 5 qualified leads; $500 ÷ 5 = $100 per lead. Responses are not leads." },
    { id: "m11-q10", q: "Industry guides commonly report investor direct-mail response rates of roughly:", opts: ["1 to 5 percent","0.01 to 0.1 percent","10 to 20 percent","25 percent or more"], correct: 0, explain: "Guides report roughly 1–5 percent, higher with stacked lists and repeat touches. Treat it as approximate and measure your own." },
    { id: "m11-q11", q: "How many touches should a mail list receive before you judge it?", opts: ["One", "Two", "Five to seven", "Twenty"], correct: 2, explain: "Most responses arrive on later touches. Plan and budget for five to seven mailings roughly every four to six weeks." },
    { id: "m11-q12", q: "Which free public source reveals absentee owners?", opts: ["The MLS","Zillow saved searches","The DNC registry","County property appraiser records where mailing address differs from property address"], correct: 3, explain: "The appraiser or auditor publishes owner and mailing address; a mismatch means the owner does not live there." },
    { id: "m11-q13", q: "The DNC registry fee for FY2026 is:", opts: ["Free for all area codes","$500 flat","$10 per area code","First five area codes free, then $82 each, capped at $22,626"], correct: 3, explain: "The FTC set FY2026 fees at $82 per area code after five free ones, with a nationwide cap of $22,626, effective October 1, 2025." },
    { id: "m11-q14", q: "What is the main purpose of a separate tracking phone number per channel?", opts: ["To compute cost per lead and cost per deal by channel","To look bigger","To avoid the TCPA","To get cheaper postage"], correct: 0, explain: "Without channel attribution you cannot cut losing channels or double winning ones." },
    { id: "m11-q15", q: "A month shows 12 leads, 1 appointment, 0 contracts. Where is the funnel breaking?", opts: ["Lead generation", "Lead-to-appointment conversion", "Title work", "The buyers list"], correct: 1, explain: "Plenty of leads but almost no appointments points to phone skills and qualifying, not marketing volume." },
    { id: "m11-q16", q: "Which online channel produces the highest-intent seller leads?", opts: ["Facebook page posts","YouTube shorts","Instagram reels","Google PPC on phrases like sell my house fast"], correct: 3, explain: "Someone searching for a fast sale is actively looking for a buyer; PPC leads convert at higher rates but cost more per click." },
    { id: "m11-q17", q: "A reasonable PPC test budget rule from investor marketing guides is:", opts: ["$50 total", "100 clicks times estimated cost per click", "One day of spend", "Whatever is left after mail"], correct: 1, explain: "You need enough clicks to judge; 100 clicks at the going rate per click sizes a meaningful first test." },
    { id: "m11-q18", q: "What should you require before sending a contract to a new cash buyer?", opts: ["A handshake","A Facebook profile","Proof of funds or a recent closing statement","Nothing; speed matters most"], correct: 2, explain: "Unverified buyers tie up your contract and burn the inspection period you negotiated." },
    { id: "m11-q19", q: "In the $500-a-month plan, the largest share goes to:", opts: ["Mail to a stacked list you pulled yourself","PPC","Paid list software","A logo designer"], correct: 0, explain: "Roughly $350 of $500 goes to postcards or letters; effort replaces money everywhere else." },
    { id: "m11-q20", q: "By which week does the 90-day plan expect the first written offer?", opts: ["Week 1", "Week 3", "Week 7", "Week 12"], correct: 2, explain: "Weeks seven and eight are for first written offers after two mailings and several weeks of calling and appointments." },
    { id: "m11-q21", q: "A seller asks you to stop contacting them. Federal rules require you to honor that within:", opts: ["Ten business days", "Six months", "One year", "There is no requirement"], correct: 0, explain: "47 CFR 64.1200(d) requires honoring a company-specific do-not-call request within a reasonable time not to exceed ten business days. Do it immediately." },
    { id: "m11-q22", q: "What should every marketing piece promise?", opts: ["A specific price", "A specific closing date", "The process: as-is, cash, no commissions, seller's timeline", "Above-market value"], correct: 2, explain: "You cannot know price or date before the walk-through and title. Promise what you control." },
    { id: "m11-q23", q: "What are the SEO pages most worth publishing in month one?", opts: ["Your biography","Stock photos of houses","A list of competitors","One page per city you buy in plus honest guides to common seller situations"], correct: 3, explain: "Pages that answer real seller questions in your market compound over six-plus months into free leads." },
    { id: "m11-q24", q: "An established business relationship under the TCPA rules comes from a purchase within how many months?", opts: ["3", "6", "18", "36"], correct: 2, explain: "A purchase within the prior 18 months, or an inquiry within the prior 3 months, under 47 CFR 64.1200(f)(5). It does not substitute for consent to autodialed or prerecorded contact." }
  ],
  drills: [
    "Write your one-sentence positioning statement using [Your Company] and [Your County], read it aloud, and cut every word that is not needed.",
    "Pull 200 absentee-owner records from the county property appraiser today, then cross-check 50 of them against the tax collector's delinquent list and mark the overlaps.",
    "Set up free access to the National Do Not Call Registry for your five target area codes and scrub your first list.",
    "Price one mailing: get a quote from a mail house for 500 postcards and 250 letters, and build the cost-per-lead math for both at a 1 percent and a 3 percent response.",
    "Build the KPI sheet with one row per week and the columns from lesson eight, then schedule a recurring 15-minute Monday review with your partner.",
    "Drive one target neighborhood for two hours, record at least 15 distressed addresses, and look up the owner of each in county records.",
    "Read the Florida or Ohio telemarketing guide in this curriculum, write your calling rules on an index card, and tape it next to your phone."
  ]
});
