BIBLE.register({
  id: "m12",
  part: 5,
  title: "Sales & Negotiation",
  icon: "🤝",
  summary: "How to turn a seller lead into a signed contract: understanding motivation, running the first call, building honest rapport, presenting a cash offer with the math, handling the twelve objections you will hear most, and following up until the deal closes or dies.",
  minutes: 100,
  lessons: [
    {
      id: "m12-01",
      title: "Seller Psychology and the Four Pillars",
      minutes: 9,
      blocks: [
        { h: "Nobody sells a house at a discount for no reason", p: "A seller who accepts a cash offer well below retail value is not confused about what the house is worth. They are trading price for something they want more: speed, certainty, privacy, relief from a burden, or the end of a conflict. Your job in every conversation is to find out what that something is. When you understand what the seller actually wants, the price conversation gets easier, because you can show how your offer delivers the thing they care about most." },
        { h: "The four pillars", p: "Experienced investors evaluate every lead on four pillars. Motivation: why are they selling, and how badly do they want it done? Timeline: when do they need to be out or paid? Condition: what is wrong with the house, and does the seller have the money, energy, or desire to fix it? Price: what do they think it is worth, and what do they actually need to walk away with? You need a real answer on all four before you make an offer. A seller with high motivation, a short timeline, a rough house, and a realistic price is a deal. A seller with low motivation, no timeline, a clean house, and a retail price is a conversation to put on a long follow-up cycle, not a deal to chase." },
        { h: "Motivation is a story, not a label", p: "The list you pulled says probate or tax delinquent, but the seller does not think of themselves that way. They think: my mother died and my brother will not return my calls. Or: the tenant stopped paying in March and I am tired of driving two hours to deal with it. Get the story. The story tells you the timeline, the condition, and the real price floor far more accurately than any list label." },
        { h: "What sellers fear", p: "Sellers who talk to investors are usually afraid of three things: being lowballed and insulted, being scammed by someone who is not real, and being pressured into a decision they will regret. Every technique in this module is designed to address those fears honestly. You address lowballing by showing your math. You address scams by being transparent about who you are and how the process works. You address pressure by giving them options and time. Sales done right is removing fear, not adding it." },
        { carry: "Four pillars: motivation, timeline, condition, price. Get a real answer on all four before you offer. High motivation plus short timeline is where deals live." },
        { trap: "Leading with price. Asking what do you want for it in the first two minutes anchors the seller to a retail number before you have learned anything. Price is the last pillar, not the first." }
      ]
    },
    {
      id: "m12-02",
      title: "The First Call Structure",
      minutes: 10,
      blocks: [
        { h: "You have about ninety seconds to earn the next ten minutes", p: "Whether the seller called you from a postcard or you are calling them, the first call has one goal: earn enough trust to ask real questions, and gather enough information to decide whether to set an appointment. It is not the place to make an offer. A simple structure keeps you from rambling: open, permission, discovery, summary, next step." },
        { h: "Open and permission", p: "Open with your name, your company, and the reason for the call in one breath, then ask for permission to continue. For an inbound call: Thanks for calling [Your Company], this is [Your Name]. Which property are you calling about? For an outbound call: Hi, this is [Your Name] with [Your Company]. I am a local buyer and I am reaching out about the property on [Street Name]. Is that something you would ever consider selling? If the answer is no, thank them, ask if you can check back in a few months, and note the date. If the answer is maybe or yes, ask: do you have a few minutes for me to ask some questions so I can see whether I can even help?" },
        { h: "Discovery", p: "Discovery is where you work through the four pillars with open questions, which are questions that cannot be answered with yes or no. Start with condition because it is the least threatening: tell me about the house. Move to the situation: what has you thinking about selling? Then timeline: if everything lined up, when would you want this done? Price last: do you have a number in mind? Listen more than you talk. Write everything down. The next lesson gives you the full question list." },
        { h: "Summary and next step", p: "Before you end the call, repeat back what you heard in a few sentences: so the house needs a roof and the kitchen is original, the tenant moved out in June, you would like to be done by the end of the year, and you were hoping for somewhere around two hundred thousand. Did I get that right? This proves you listened and catches misunderstandings. Then propose a specific next step: I would like to walk the property so I can give you a real number instead of a guess. Would Tuesday at four or Wednesday at ten work better? Always offer two times." },
        { carry: "First call: open, permission, discovery (condition, situation, timeline, price), summary, next step. No offer on the first call. Always propose two appointment times." },
        { trap: "Making an offer over the phone before seeing the house. You either offer too high and have to retrade, which destroys trust, or too low and lose a seller you could have won in person." }
      ]
    },
    {
      id: "m12-03",
      title: "Qualifying Questions",
      minutes: 11,
      blocks: [
        { h: "Why a question list", p: "You will forget to ask something important when you are nervous, so keep this list in front of you on every call. You do not have to ask every question in order. Use it as a checklist to make sure you leave the call with the four pillars filled in. The questions are grouped by pillar." },
        { h: "Condition questions", p: "One: Tell me about the house, what would I see if I walked in today? Two: How old is the roof, and are there any leaks you know of? Three: How are the heating and air, electrical, and plumbing? Four: When were the kitchen and bathrooms last updated? Five: Is anyone living in the property right now? Six: Are there any repairs you have been putting off? Seven: Have you had any insurance claims, code letters, or permit issues on the property?" },
        { h: "Motivation and situation questions", p: "Eight: What has you thinking about selling now? Nine: How long have you owned the property, and how did you come to own it? Ten: Have you talked to anyone else about buying it, or thought about listing it with an agent? Eleven: If the house did not sell, what would you do instead? Twelve: What would a good outcome look like for you here, beyond the money?" },
        { h: "Timeline questions", p: "Thirteen: If everything lined up, when would you ideally want this done? Fourteen: Is there a date that matters, like a court date, a tax deadline, a move, or a loan payment? Fifteen: Is there anyone else who needs to be part of this decision, such as a spouse, a sibling, or an attorney?" },
        { h: "Price and financial questions", p: "Sixteen: Do you have a number in mind? Seventeen: How did you arrive at that number? Eighteen: Is there a mortgage on the property, and roughly what is owed? Nineteen: Are the property taxes and any association dues current? Twenty: If I could close on your timeline, take the house exactly as it is, and cover the normal closing costs, is there a price that would make that worth it to you?" },
        { carry: "Twenty questions across four pillars. Condition first, price last. Question twenty is the soft price question: as-is, your timeline, I cover closing costs, what number makes that worth it?" },
        { trap: "Asking the questions like an interrogation. Space them out, respond to the answers, share a little about yourself, and let the seller talk. Rapport is built in the gaps between the questions." }
      ]
    },
    {
      id: "m12-04",
      title: "Rapport and Tactical Empathy",
      minutes: 12,
      blocks: [
        { h: "Rapport without being fake", p: "Rapport is the sense that you understand the other person and are on their side. It cannot be faked for long, and sellers in hard situations have good radar for fakes. Real rapport comes from three habits: being genuinely curious about their situation, slowing down to match their pace, and being honest even when honesty costs you a little. If the house is not a fit, tell them and point them toward an agent. The seller you helped for free this year refers you a deal next year." },
        { h: "Ideas from Never Split the Difference", p: "Former FBI negotiator Chris Voss wrote a widely read negotiation book called Never Split the Difference, and several of its core ideas translate directly to seller conversations. The overall concept he calls tactical empathy is understanding the other side's feelings and mindset and demonstrating that understanding out loud, so the other person feels heard and becomes more open. What follows is a paraphrase of four techniques from the book, not quotations." },
        { h: "Labeling and mirroring", p: "Labeling means naming the emotion you observe in a neutral way, usually starting with it seems like or it sounds like: it sounds like dealing with this tenant has been exhausting. You then stop talking and let the seller respond. The label shows you understand without arguing or agreeing. Mirroring means repeating the last few important words the person said, with a slight upward tone, and then pausing: so your brother wants to keep it? The seller will almost always expand on what they meant, and you learn what you would otherwise have had to guess." },
        { h: "Calibrated questions and the accusation audit", p: "Calibrated questions are open how and what questions that invite the other side to solve the problem with you instead of saying no: how am I supposed to make that number work with a roof and a kitchen? What would need to happen for this to make sense for you? They keep the conversation moving without confrontation. The accusation audit means saying the negative things the seller is probably thinking about you before they do: you are probably thinking this is another investor who is going to lowball me and waste my time. Saying it first takes the sting out and lets the seller correct you or relax. Use all four lightly; one label is powerful, five in a row is a technique the seller can hear." },
        { carry: "Tactical empathy: label the emotion (it sounds like...), mirror the key words, ask calibrated how and what questions, and audit the accusation before they make it. Use lightly." },
        { trap: "Learning techniques and using them to manipulate. Sellers feel it, and the deal that closes under pressure is the deal that gets cancelled, disputed, or badmouthed. The techniques work because they help you understand, not because they trick anyone." }
      ]
    },
    {
      id: "m12-05",
      title: "Presenting the Cash Offer",
      minutes: 12,
      blocks: [
        { h: "Show the math", p: "The single best way to present a low offer is to show the seller exactly how you got there. Start from what the house would sell for fixed up, which earlier modules call the after-repair value or ARV. Subtract the repairs, with the big items listed. Subtract your holding, closing, and selling costs. Subtract a profit margin and say plainly that you need to make money or you cannot do this. What is left is your offer. When sellers see the math they may not love the number, but they stop feeling insulted by it, because it is no longer an opinion about their house; it is arithmetic." },
        { formula: "Offer = ARV − repairs − holding and closing costs − profit. Many investors shortcut this as Offer = (ARV × 0.70) − repairs." },
        { example: "ARV $220,000. Repairs $45,000 (roof, HVAC, kitchen, baths, paint, floors). Holding and closing $15,000. Profit $25,000. Offer about $135,000. The 70 percent shortcut gives $154,000 − $45,000 = $109,000; the detailed version is more defensible in the room." },
        { h: "Anchoring", p: "An anchor is the first number said out loud; everything after it is compared to it. If the seller anchors at a retail number, you should not respond with your maximum. Present a range or a first number that leaves room to move, while staying honest: based on the repairs we walked through, I am seeing a number in the range of one twenty-five to one thirty-five. Never present an anchor you cannot explain with the math, and never present a number you would not actually close at if they said yes immediately." },
        { h: "Options: cash versus terms", p: "Giving a seller two or three options moves the conversation from yes or no to which one. The simplest pair is a lower cash price with a fast close, and a higher price with terms, such as seller financing, a longer closing, or the seller staying in the house for a period after closing. For example: I can do one hundred thirty thousand cash and close in three weeks, or I can do one hundred fifty thousand if you carry the financing for five years with monthly payments. Only offer terms you have actually run the numbers on and that your attorney has reviewed. Many sellers who would never take the cash number say yes to terms, and many who need cash now realize the lower number is the one that solves their problem." },
        { h: "Then stop talking", p: "After you present the number and the options, be quiet. The silence will feel long. The seller is thinking. If you fill the silence you will usually raise your own offer against yourself. Let them respond, then handle whatever comes next with the objection framework in the next lesson." },
        { carry: "Present the math out loud: ARV, repairs, costs, profit, offer. Anchor with a defensible range. Offer cash versus terms. Then stop talking." },
        { trap: "Negotiating against yourself in the silence. The seller pauses, you panic, and you add ten thousand dollars before they have said a word. Count to ten in your head." }
      ]
    },
    {
      id: "m12-06",
      title: "The Twelve Objections",
      minutes: 14,
      blocks: [
        { h: "Objections are information", p: "An objection is not a rejection. It is the seller telling you what they need to hear before they can say yes. The framework for every objection is the same: acknowledge it without arguing, ask a question to understand what is behind it, and then respond to the real concern. The twelve objections below cover almost everything you will hear. Each is followed by the response approach, not a script to recite." },
        { h: "Objections one through four", p: "One, that is too low: acknowledge, then walk the math again slowly and ask which part they disagree with, the ARV, the repairs, or the costs. Often they disagree with the repairs, so offer to walk the house together with a contractor. Two, I will just list it with an agent: agree that listing may get a higher price, then lay out the honest comparison: commission, repairs, inspections, financing fall-through, showings, and time. Ask how much the extra money is worth against the extra months. Three, I need to think about it: of course, then ask what specifically they want to think through, so you can address it now or know what to follow up about. Set a specific follow-up date. Four, another investor offered more: ask whether that offer is in writing, with proof of funds, and when it closes. Many are not. Explain that you will not match a number you cannot close at, and that you will be here if the other buyer disappears." },
        { h: "Objections five through eight", p: "Five, what is your fee or how do you make money: tell the truth. You buy below retail, you either fix and resell or rent, or you may assign your contract to another investor for a fee, and your profit comes from the gap, not from charging the seller anything. Transparency here is also a legal requirement in some states; see the ethics lesson. Six, I need to talk to my spouse or family: respect it and ask to include them in the next conversation so everyone hears the same information. Seven, the house is worth more than that; the neighbor sold for X: ask about the neighbor's house condition and when it sold, and show how your ARV already assumes a fully renovated house. Eight, I am not in a hurry: acknowledge, lower the pressure completely, ask whether there is any price at which speed would matter, and move them to a long follow-up cycle." },
        { h: "Objections nine through twelve", p: "Nine, I do not trust investors: run the accusation audit, then show them who you are: website, reviews, the title company you use, references. Offer to let their attorney review the contract. Ten, can you do better: ask what number would make them sign today, and only move if the math supports it; if you move, move once and get the signature. Eleven, I want to wait for the market to improve: ask what happens to their situation while they wait, taxes, vacancy, repairs, and compare that carrying cost to the price difference they hope for. Twelve, I will sell it myself: respect it, explain what a buyer's lender inspection and appraisal will do to an as-is house, and ask to be their backup if it does not go as planned." },
        { carry: "Acknowledge, ask what is behind it, respond to the real concern. Too low → which part of the math? List it → honest comparison. Think about it → think about what, and when do we talk?" },
        { trap: "Arguing with an objection. The moment you say you are wrong about your house's value, you have lost. Ask questions until the seller argues your side for you." }
      ]
    },
    {
      id: "m12-07",
      title: "Follow-Up and Negotiating With Agents",
      minutes: 10,
      blocks: [
        { h: "Most deals close on follow-up", p: "Most experienced investors report that the majority of their contracts come from leads they followed up with for weeks or months, not from first-call yeses. Sellers move when their situation changes, and your job is to be the name they already trust when it does. A simple cadence: after an appointment with no contract, follow up at two days, one week, two weeks, thirty days, and then monthly. Rotate the method: call, text if you have consent and it is legal in your state, handwritten note, email. Every touch should add something small, a market update, a question about the tenant, a reminder that your offer still stands, rather than just checking in." },
        { h: "Keep the file alive", p: "Every lead gets a record with the four pillars, the offer made, the objections heard, and the next follow-up date. Review the follow-up list weekly with your partner. A lead goes dead only when the seller says stop, the property sells to someone else, or twelve months pass with no change. Dead leads still get mailed as part of your regular list unless they asked you to stop." },
        { h: "Negotiating with agents on listed properties", p: "Listed properties are a real deal source, especially stale listings and homes that keep falling out of contract. The listing agent works for the seller, so your approach is different. Be fast, be clear, and make their job easy. Submit a clean written offer with proof of funds, a short inspection period, and a realistic closing date. Explain in the cover note why your price is where it is, and offer to show your repair estimate. Ask the agent what matters most to their seller; sometimes it is the closing date or the ability to leave belongings behind, not the price. Never ask an agent to misrepresent anything to their client, and never try to go around the agent to the seller on a listed property." },
        { h: "Assignability on listed deals", p: "Many listing agents and sellers push back on and/or assigns language because they worry you are not a real buyer. Be ready to explain who will actually close and consider a double close instead of an assignment on listed properties. The contracts module covers both methods in detail." },
        { carry: "Follow-up cadence: 2 days, 1 week, 2 weeks, 30 days, then monthly, rotating methods, adding something each touch. With agents: clean written offer, proof of funds, explain your math, ask what the seller values most." },
        { trap: "Following up by just checking in. It trains the seller to ignore you. Bring something: a question, a comp, a reminder of the specific problem your offer solves." }
      ]
    },
    {
      id: "m12-08",
      title: "The Walk-Through and Closing the Appointment",
      minutes: 10,
      blocks: [
        { h: "Before you arrive", p: "Pull the comparable sales and have a working ARV. Pull the county record for owner name, taxes, and any liens you can see. Bring a flashlight, a tape measure, a notepad, your contract, a pen, and a one-page explanation of how the process works. Arrive exactly on time. Dress like a professional who is about to crawl into an attic: clean, plain, practical." },
        { h: "The walk itself", p: "Let the seller lead the tour and keep asking questions. You are doing two things at once: estimating repairs room by room, and learning the story. Point at problems gently and ask about them rather than announcing them: how long has that stain been there? Take photos with permission. Check the roof from the ground, the water heater and furnace labels for age, the panel for brand and capacity, under sinks for leaks, and the foundation for cracks. The repair estimation module covers the numbers; this lesson is about doing it without making the seller defensive." },
        { h: "Sitting down", p: "After the walk, ask to sit at the kitchen table. Summarize what you saw. Walk through the math out loud as the offer lesson describes, write the number down, and present the options. Then be quiet. Handle objections with questions. If the seller says yes or close to yes, move to the paperwork right then; a seller who sleeps on it faces a night of friends and family telling them to list it." },
        { h: "Getting the signature", p: "Walk through the contract page by page in plain language: price, earnest money, inspection period, closing date, and what happens if either side backs out. Explain who the title company is and what happens next, including that you may bring a partner or assign the contract if that is your plan, and that your earnest money will be deposited with the title company. Point out where to sign. Give them a copy. Ask whether they have any questions. Then confirm the next three steps with dates: you will send the contract to title tomorrow, title will reach out within a few days, and you will check in on a specific day. A clear next step is what makes the signature feel safe." },
        { carry: "Walk, ask, estimate, sit down, show the math, present options, be quiet, handle objections with questions, sign at the table, confirm the next three steps with dates." },
        { trap: "Leaving without a decision because you did not bring the contract or did not ask. If you have the numbers and the seller is ready, ask for the signature at the kitchen table. Tomorrow is another investor's appointment." }
      ]
    },
    {
      id: "m12-09",
      title: "Ethics and Disclosure",
      minutes: 7,
      blocks: [
        { h: "The line you do not cross", p: "You will be tempted, especially early, to shade the truth: to imply you will live in the house, to hide that you plan to assign the contract, to overstate repairs, or to say another buyer exists when none does. Do not. Beyond being wrong, misrepresentation can void the contract, expose you to fraud and consumer-protection claims, and in some states violate real estate licensing or wholesaler disclosure laws. The reputation you build in a small market follows you to every title company and every agent." },
        { h: "Disclose your intent", p: "Tell sellers in plain words how you make money and that you may assign the contract or bring in a partner. Several states now require written disclosure of assignment intent before the contract is binding. Ohio's wholesaler disclosure statute, Ohio Revised Code 5301.95, effective March 2, 2026, requires a separate, conspicuous written disclosure signed before the contract binds, and lets the owner cancel before closing if it was not given. Florida has no wholesaler-specific disclosure statute as of late 2026, but it regulates unlicensed real estate activity strictly under Chapter 475, and acting as an unlicensed broker is a felony there, so your contract and your conduct must make clear you are a principal buyer, not an agent for the seller. The contracts module covers both in detail. Confirm with a local real estate attorney." },
        { h: "Never mislead on value or condition", p: "You can present your math and your opinion of repairs. You cannot tell a seller their house is worth less than you believe it is, invent code problems, or claim the market is crashing to lower the price. Honest hard numbers persuade better than dishonest ones anyway, and they survive the seller's attorney reading the file." },
        { carry: "Never mislead. Disclose that you may assign or bring a partner, in writing where required. Ohio: ORC 5301.95 written disclosure (effective March 2, 2026). Florida: Chapter 475, act only as a principal. Confirm with a local real estate attorney." },
        { state: { fl: "No wholesaler-specific disclosure statute as of late 2026; Chapter 475 licensing law applies and unlicensed brokerage is a third-degree felony under 475.42, so contract and conduct must show you are a principal buyer.", oh: "ORC 5301.95 (effective March 2, 2026) requires a separate, conspicuous, bold, twelve-point written disclosure that you may assign for profit and that the price may be below market value, signed by both parties before the contract is binding; owner may cancel before closing if not provided." } },
        { sources: [
          { t: "Ohio Revised Code 5301.95, Residential real estate wholesaler disclosure", u: "https://codes.ohio.gov/ohio-revised-code/section-5301.95" },
          { t: "Florida Statutes Chapter 475, Real Estate Brokers (see 475.011 exemptions and 475.42 violations)", u: "http://www.leg.state.fl.us/statutes/index.cfm?App_mode=Display_Statute&URL=0400-0499/0475/0475.html" }
        ] }
      ]
    }
  ],
  cards: [
    { id: "m12-c01", type: "term", q: "What are the four pillars of seller qualification?", a: "Motivation, timeline, condition, and price. Get a real answer on all four before making an offer; high motivation plus a short timeline is where deals live." },
    { id: "m12-c02", type: "term", q: "What is an open question?", a: "A question that cannot be answered with yes or no, such as tell me about the house or what has you thinking about selling. Discovery runs on open questions." },
    { id: "m12-c03", type: "term", q: "What is tactical empathy?", a: "Chris Voss's concept of understanding the other side's feelings and mindset and demonstrating that understanding out loud so they feel heard and become more open." },
    { id: "m12-c04", type: "term", q: "What is labeling?", a: "Naming the emotion you observe neutrally, usually starting with it sounds like or it seems like, then pausing. Example: it sounds like this tenant has worn you out." },
    { id: "m12-c05", type: "term", q: "What is mirroring?", a: "Repeating the last few important words the seller said with a slight upward tone, then pausing so they expand. Example: so your brother wants to keep it?" },
    { id: "m12-c06", type: "term", q: "What is a calibrated question?", a: "An open how or what question that invites the other side to solve the problem with you. Example: how am I supposed to make that number work with a new roof?" },
    { id: "m12-c07", type: "term", q: "What is an accusation audit?", a: "Saying the negative things the seller is probably thinking about you before they do, so the sting is gone. Example: you are probably expecting a lowball from another investor." },
    { id: "m12-c08", type: "term", q: "What is an anchor in negotiation?", a: "The first number spoken; everything after is judged against it. Present a defensible range you can explain with math and would actually close at." },
    { id: "m12-c09", type: "term", q: "What is a terms offer?", a: "A higher price in exchange for seller financing, a longer close, or post-closing occupancy, offered alongside a lower cash price so the seller chooses between options instead of yes or no." },
    { id: "m12-c10", type: "term", q: "What is a follow-up cadence?", a: "A planned schedule of touches after an appointment: 2 days, 1 week, 2 weeks, 30 days, then monthly, rotating method and adding something each time." },
    { id: "m12-c11", type: "term", q: "What is the and/or assigns clause?", a: "Contract language letting the buyer assign the contract to another party. Listing agents often push back on it; be ready to explain or double close instead." },
    { id: "m12-c12", type: "term", q: "What does principal buyer mean and why does it matter?", a: "You are buying for yourself, not representing the seller. Florida's Chapter 475 regulates unlicensed brokerage, so your contract and conduct must show you are a principal." },
    { id: "m12-c13", type: "formula", q: "What is the detailed offer formula?", a: "Offer = ARV − repairs − holding and closing costs − profit. ARV $220,000 − $45,000 − $15,000 − $25,000 = $135,000." },
    { id: "m12-c14", type: "formula", q: "What is the 70 percent shortcut and when do you use it?", a: "Offer = (ARV × 0.70) − repairs. $220,000 × 0.70 = $154,000 − $45,000 = $109,000. Use it to screen quickly; use the detailed version at the kitchen table." },
    { id: "m12-c15", type: "formula", q: "How do you turn a seller's number into a question?", a: "Ask how they arrived at it, then compare: their number minus your ARV-based offer equals the gap to explain with repairs, costs, and profit." },
    { id: "m12-c16", type: "number", q: "How many qualifying questions are on the list, and which comes last?", a: "Twenty, grouped by pillar. Price questions come last, ending with the soft price question: as-is, your timeline, I cover closing costs, what number makes that worth it?" },
    { id: "m12-c17", type: "number", q: "What is the follow-up cadence after an appointment with no contract?", a: "Two days, one week, two weeks, thirty days, then monthly until the seller says stop, the property sells, or twelve months pass." },
    { id: "m12-c18", type: "number", q: "How many appointment times should you offer?", a: "Two specific options, such as Tuesday at four or Wednesday at ten. It moves the seller from whether to which." },
    { id: "m12-c19", type: "number", q: "When did Ohio's wholesaler disclosure law take effect and what font size does it require?", a: "March 2, 2026; the disclosure must be conspicuous, boldface, and at least twelve-point, separate from the contract, signed before the contract binds." },
    { id: "m12-c20", type: "number", q: "How long after the walk-through should you present the offer?", a: "Immediately, at the kitchen table, with the math. A seller who sleeps on it hears from friends and family all night." },
    { id: "m12-c21", type: "state", q: "What does each state require you to disclose as a wholesaler?", a: "FL: no wholesaler-specific disclosure statute as of late 2026; Chapter 475 governs and unlicensed brokerage is a felony, so act and contract only as a principal. | OH: ORC 5301.95 written disclosure of assignment intent and below-market price, signed before the contract binds (effective March 2, 2026)." },
    { id: "m12-c22", type: "state", q: "What happens if a wholesaler skips the disclosure in each state?", a: "FL: no specific statute, but misrepresentation and unlicensed-activity risk under Chapter 475. | OH: the owner may cancel any time before closing without penalty and earnest money must be returned within 30 days; it is also a deceptive practice under consumer law." },
    { id: "m12-c23", type: "scenario", q: "Seller's first words: what will you give me for it? What do you say?", a: "I would be guessing without seeing it, and I do not want to insult you with a guess. Can I ask a few questions about the house first? Then run discovery." },
    { id: "m12-c24", type: "scenario", q: "Seller says: that is too low. Response approach?", a: "Acknowledge, then ask which part of the math they disagree with: ARV, repairs, or costs. Offer to walk the house with a contractor if it is the repairs." },
    { id: "m12-c25", type: "scenario", q: "Seller says: I will just list it with an agent. Response approach?", a: "Agree listing may bring a higher price, then compare honestly: commission, repairs, inspections, financing fall-through, showings, months. Ask what the extra money is worth against the time." },
    { id: "m12-c26", type: "scenario", q: "Seller says: I need to think about it. Response approach?", a: "Of course. Ask what specifically they want to think through so you can address it now, then set a specific follow-up date and time." },
    { id: "m12-c27", type: "scenario", q: "Seller says: another investor offered me more. Response approach?", a: "Ask if it is in writing with proof of funds and a closing date. Explain you will not match a number you cannot close at, and you will be here if the other buyer disappears." },
    { id: "m12-c28", type: "scenario", q: "Seller asks: what is your fee, how do you make money? Response approach?", a: "Tell the truth: you buy below retail and profit from fixing and reselling, renting, or assigning your contract to another investor for a fee. The seller pays you nothing directly." },
    { id: "m12-c29", type: "scenario", q: "Seller says: I need to talk to my spouse. Response approach?", a: "Respect it and ask to include the spouse in the next conversation so everyone hears the same math at the same time. Set the date." },
    { id: "m12-c30", type: "scenario", q: "Seller says: the neighbor sold for a lot more. Response approach?", a: "Ask about the neighbor's condition and sale date, then show that your ARV already assumes a fully renovated house; the gap is the renovation." },
    { id: "m12-c31", type: "scenario", q: "Seller says: I am not in a hurry. Response approach?", a: "Drop all pressure, ask whether any price would make speed matter, and move them to a long follow-up cycle with a monthly touch." },
    { id: "m12-c32", type: "scenario", q: "Seller says: I do not trust investors. Response approach?", a: "Run the accusation audit, then show proof: website, reviews, your title company, references, and offer to have their attorney review the contract." },
    { id: "m12-c33", type: "scenario", q: "Seller says: can you do any better? Response approach?", a: "Ask what number gets a signature today. Move only if the math supports it, move once, and get the signature at the same time." },
    { id: "m12-c34", type: "scenario", q: "Seller says: I will wait for the market to improve. Response approach?", a: "Ask what happens to their situation while they wait: taxes, vacancy, repairs, risk. Compare that carrying cost to the price gain they hope for." },
    { id: "m12-c35", type: "scenario", q: "Seller says: I will sell it myself. Response approach?", a: "Respect it, explain what a retail buyer's inspection, appraisal, and lender will do with an as-is house, and ask to be the backup plan." },
    { id: "m12-c36", type: "scenario", q: "You present the number and the seller goes silent for twenty seconds. What do you do?", a: "Nothing. Stay quiet and let them think. Filling the silence usually means raising your own offer before they have said a word." },
    { id: "m12-c37", type: "scenario", q: "After the walk the seller is nodding along to your math. What is the next move?", a: "Ask to sit at the kitchen table, write the number down, present the options, and move to the contract right then. Do not leave for them to sleep on it." },
    { id: "m12-c38", type: "scenario", q: "A listing agent says their seller will not accept and/or assigns. What do you do?", a: "Explain who will close and why, or offer to remove the assignment language and plan a double close. Never go around the agent to the seller." },
    { id: "m12-c39", type: "scenario", q: "You are about to sign an Ohio seller. What must happen before the contract binds?", a: "Both of you sign and date a separate, conspicuous, bold, twelve-point written disclosure that you may assign the contract for profit and the price may be below market, per ORC 5301.95." },
    { id: "m12-c40", type: "scenario", q: "A seller asks whether you are going to live in the house. You plan to assign. What do you say?", a: "The truth: you are an investor, you may renovate and resell, rent, or assign the contract to another investor, and you will put that in writing. Misleading them risks the contract and legal exposure." },
    { id: "m12-c41", type: "scenario", q: "Your partner wants to tell a seller the market is crashing to get a lower price. Your call?", a: "No. You can present honest math and your repair opinion; you cannot misrepresent value or market conditions. Honest hard numbers persuade and survive the seller's attorney." },
    { id: "m12-c42", type: "scenario", q: "A probate lead says their sibling will not return calls. How do you use the four pillars?", a: "Motivation is high but decision authority is split. Ask who has legal authority to sell, offer to meet both, and build your timeline around the court process." },
    { id: "m12-c43", type: "scenario", q: "Seller wants $200,000; your detailed math says $135,000. How do you present it?", a: "Ask how they got to $200,000, then walk ARV, repairs, costs, and profit out loud, land on your range, and offer a terms option at a higher price if the numbers support it." },
    { id: "m12-c44", type: "trap", q: "Leading with price on the first call.", a: "It anchors the seller to a retail number before you learn anything. Condition first, situation, timeline, then price." },
    { id: "m12-c45", type: "trap", q: "Making an offer over the phone sight unseen.", a: "Too high means a retrade that destroys trust; too low loses a seller you could have won in person. Offer at the kitchen table." },
    { id: "m12-c46", type: "trap", q: "Running the question list like an interrogation.", a: "Space the questions, react to answers, share a little about yourself. Rapport is built in the gaps." },
    { id: "m12-c47", type: "trap", q: "Stacking five empathy techniques in a row.", a: "The seller hears a technique instead of a person. One good label, then listen." },
    { id: "m12-c48", type: "trap", q: "Negotiating against yourself in the silence.", a: "Present the number, stop talking, count to ten. Let the seller respond first." },
    { id: "m12-c49", type: "trap", q: "Arguing with an objection.", a: "Saying you are wrong about your house ends the deal. Acknowledge, ask what is behind it, respond to the real concern." },
    { id: "m12-c50", type: "trap", q: "Following up with just checking in.", a: "It trains sellers to ignore you. Bring a comp, a question, a reminder of the problem your offer solves." },
    { id: "m12-c51", type: "trap", q: "Leaving the appointment without asking for the signature.", a: "If you have the numbers and the seller is ready, ask at the table. Bring the contract to every appointment." },
    { id: "m12-c52", type: "trap", q: "Hiding your plan to assign the contract.", a: "In Ohio it is a statutory violation that lets the seller cancel; everywhere it is misrepresentation that can void the deal and your reputation." },
    { id: "m12-c53", type: "trap", q: "Presenting an anchor you cannot explain or would not close at.", a: "If the seller says yes to your anchor and you cannot perform, you have lied. Every number you say must be backed by math and your ability to close." },
    { id: "m12-c54", type: "trap", q: "Going around a listing agent to the seller.", a: "It damages the agent relationship you need for future deals and can breach the listing terms. Work through the agent and make their job easy." },
    { id: "m12-c55", type: "term", q: "What is a retrade?", a: "Lowering your price after the contract is signed, usually citing inspection findings. Occasionally legitimate for real surprises, but habitual retrading destroys your reputation with sellers, agents, and title companies." },
    { id: "m12-c56", type: "term", q: "What is the summary step on the first call?", a: "Repeating back the four pillars in a few sentences and asking did I get that right. It proves you listened and catches misunderstandings before the appointment." },
    { id: "m12-c57", type: "scenario", q: "The seller's number is close to yours but not quite. Do you split the difference?", a: "Not automatically. Ask what number gets a signature today, check the math, and if you move, move once and sign. Splitting by habit teaches sellers to start high." },
    { id: "m12-c58", type: "number", q: "What should you check for age during the walk-through?", a: "Roof from the ground, water heater and furnace labels, electrical panel brand and capacity, under sinks for leaks, foundation for cracks." },
    { id: "m12-c59", type: "scenario", q: "A tired landlord says the tenant has not paid since March. How do you use labeling?", a: "It sounds like this has been draining for months. Then pause. Let the seller tell the rest of the story; it gives you timeline and price floor." },
    { id: "m12-c60", type: "term", q: "What makes a signature feel safe to a seller?", a: "Walking the contract page by page in plain language, naming the title company, and confirming the next three steps with dates before you leave." },
    { id: "m12-c61", type: "scenario", q: "A seller on a listed property cares most about leaving furniture behind, not price. How do you use that?", a: "Write the offer to accept the property with all contents as-is and highlight it in the cover note. Non-price terms often win listed deals." },
    { id: "m12-c62", type: "trap", q: "Letting a lead go dead after one no.", a: "Most contracts come from follow-up as situations change. A lead is dead only when the seller says stop, the property sells, or twelve months pass." },
    { id: "m12-c63", type: "number", q: "In the worked offer example, what were ARV, repairs, costs, profit, and offer?", a: "ARV $220,000, repairs $45,000, holding and closing $15,000, profit $25,000, offer about $135,000." },
    { id: "m12-c64", type: "term", q: "What is the and/or assigns alternative on listed deals?", a: "A double close: you buy and resell in two transactions, so the seller's contract does not need assignment language. Covered in the contracts module." }
  ],
  quiz: [
    { id: "m12-q01", q: "Which pillar should you ask about last on a first call?", opts: ["Condition", "Motivation", "Timeline", "Price"], correct: 3, explain: "Asking price first anchors the seller to a retail number before you have learned anything. Condition is the least threatening opener." },
    { id: "m12-q02", q: "What is the goal of the first call?", opts: ["Make an offer","Get a signed contract","Give a repair estimate","Earn trust, gather the four pillars, and set an appointment"], correct: 3, explain: "No offer on the first call. Open, permission, discovery, summary, and a specific next step with two time options." },
    { id: "m12-q03", q: "A seller says: my brother wants to keep it. You respond: so your brother wants to keep it? This is:", opts: ["An accusation audit", "A calibrated question", "Mirroring", "Anchoring"], correct: 2, explain: "Mirroring repeats the last key words with a slight upward tone and a pause so the seller expands." },
    { id: "m12-q04", q: "Saying you are probably thinking this is another investor who will lowball you, before the seller says it, is:", opts: ["An accusation audit", "Labeling", "A retrade", "Mirroring"], correct: 0, explain: "The accusation audit names the negatives the other side is already thinking so they lose their sting." },
    { id: "m12-q05", q: "ARV $220,000, repairs $45,000, holding and closing $15,000, profit $25,000. Detailed offer?", opts: ["$175,000", "$160,000", "$135,000", "$109,000"], correct: 2, explain: "220,000 − 45,000 − 15,000 − 25,000 = 135,000. The 70 percent shortcut would give 109,000." },
    { id: "m12-q06", q: "ARV $220,000 and repairs $45,000. The 70 percent shortcut offer is:", opts: ["$109,000", "$154,000", "$135,000", "$175,000"], correct: 0, explain: "220,000 × 0.70 = 154,000; minus 45,000 = 109,000." },
    { id: "m12-q07", q: "After presenting the offer, the seller is silent. You should:", opts: ["Stay quiet and let them think","Raise the offer to break the tension","Restate the ARV","Pack up and leave"], correct: 0, explain: "Filling the silence usually means negotiating against yourself. Count to ten." },
    { id: "m12-q08", q: "Why offer a cash option and a terms option together?", opts: ["To confuse the seller","Because terms are always better for you","To avoid disclosing your profit","To move the decision from yes or no to which one"], correct: 3, explain: "Options let sellers pick what solves their problem; some choose a higher price with terms, others the lower fast cash." },
    { id: "m12-q09", q: "Seller says that is too low. Best first move?", opts: ["Raise the offer", "Explain you have other deals", "Ask which part of the math they disagree with", "End the call"], correct: 2, explain: "Acknowledge, then locate the disagreement: ARV, repairs, or costs. Often it is repairs, which you can walk together." },
    { id: "m12-q10", q: "Seller says another investor offered more. You should:", opts: ["Ask if it is written, with proof of funds and a closing date","Match it immediately","Tell them the other investor is lying","Walk away permanently"], correct: 0, explain: "Many competing offers are verbal and unfunded. Do not match a number you cannot close at; stay available." },
    { id: "m12-q11", q: "Seller asks how you make money. The right answer is:", opts: ["Change the subject", "Say you charge no fee and leave it there", "Explain you buy below retail and profit by renovating, renting, or assigning the contract", "Say you are buying it to live in"], correct: 2, explain: "Transparency builds trust and, in some states like Ohio, assignment intent must be disclosed in writing." },
    { id: "m12-q12", q: "What is the recommended follow-up cadence after an appointment with no contract?", opts: ["Daily for a month","Once after 90 days","Never; move on","2 days, 1 week, 2 weeks, 30 days, then monthly"], correct: 3, explain: "Most experienced investors report most contracts come from follow-up as situations change. Rotate methods and add value each touch." },
    { id: "m12-q13", q: "When does a lead go dead?", opts: ["After the first no", "After two weeks of silence", "When the seller says stop, the property sells, or twelve months pass", "When another investor calls them"], correct: 2, explain: "Situations change; keep the file alive and keep mailing unless they asked you to stop." },
    { id: "m12-q14", q: "A listing agent resists and/or assigns. Best approach?", opts: ["Contact the seller directly","Threaten to withdraw","Explain who will close or plan a double close","Hide the assignment in the fine print"], correct: 2, explain: "Work through the agent, be transparent, and use a double close when assignment language is a problem." },
    { id: "m12-q15", q: "Where should you present the offer after the walk-through?", opts: ["By email the next day","Over the phone a week later","Through the seller's neighbor","At the kitchen table, immediately, with the math"], correct: 3, explain: "A seller who sleeps on it faces a night of friends telling them to list it. Present, be quiet, handle objections, sign." },
    { id: "m12-q16", q: "Ohio's wholesaler disclosure statute is:", opts: ["ORC 4719.01", "ORC 5301.95, effective March 2, 2026", "ORC 319.54", "Ohio has none"], correct: 1, explain: "ORC 5301.95 requires a separate, conspicuous, bold, twelve-point written disclosure signed before the contract binds." },
    { id: "m12-q17", q: "If an Ohio wholesaler fails to give the required disclosure, the owner may:", opts: ["Cancel any time before closing without penalty","Do nothing; the contract stands","Only sue after closing","Demand double the price"], correct: 0, explain: "ORC 5301.95 allows cancellation before closing, requires return of earnest money within 30 days, and treats the violation as a deceptive practice." },
    { id: "m12-q18", q: "In Florida, wholesaler conduct is governed mainly by:", opts: ["A wholesaler disclosure statute","The TCPA","Chapter 201 doc stamp law","Chapter 475 real estate licensing law"], correct: 3, explain: "Florida has no wholesaler-specific disclosure statute as of late 2026; Chapter 475 regulates unlicensed brokerage, and 475.42 makes it a felony, so you must act as a principal." },
    { id: "m12-q19", q: "Which is an acceptable negotiation tactic?", opts: ["Telling the seller the market is crashing when it is not", "Inventing a competing buyer", "Showing your ARV, repair, cost, and profit math", "Implying you will live in the house when you plan to assign"], correct: 2, explain: "Honest math persuades and survives attorney review. The other three are misrepresentation." },
    { id: "m12-q20", q: "The twenty-question list ends with which question?", opts: ["What is the square footage?", "If I close on your timeline, take it as-is, and cover normal closing costs, what price makes that worth it?", "Who is your agent?", "What color is the roof?"], correct: 1, explain: "The soft price question ties your value, speed, as-is, no costs, to the seller's number." },
    { id: "m12-q21", q: "How many appointment times should you propose at the end of the first call?", opts: ["Two","One","Five","Let them pick any time"], correct: 0, explain: "Two specific options move the seller from whether to which." },
    { id: "m12-q22", q: "Which best describes real rapport?", opts: ["Agreeing with everything the seller says", "Genuine curiosity, matching their pace, and honesty even when it costs you", "Using five empathy techniques per call", "Complimenting the house"], correct: 1, explain: "Sellers in hard situations detect fakes. Honesty, including telling them when the house is not a fit, builds the reputation that brings referrals." },
    { id: "m12-q23", q: "Seller says: I will sell it myself. Best response approach?", opts: ["Tell them they will fail","Lower your offer","Respect it, explain what a retail buyer's inspection and lender will do with an as-is house, and ask to be the backup","Stop following up"], correct: 2, explain: "Respect plus honest information plus a backup position keeps you first in line when the retail sale stalls." }
  ],
  drills: [
    "Role-play all twelve objections out loud with your partner, switching roles, until each response approach comes out in your own words without notes.",
    "Record yourself running the first-call structure on a practice lead, then listen back and count how many closed questions you asked; redo it with open questions only.",
    "Write the twenty qualifying questions on a single card in your own words and keep it by your phone for every call this week.",
    "Take one real or practice property and present the offer math out loud: ARV, repairs, holding and closing, profit, offer, plus a cash option and a terms option.",
    "Practice three labels and three mirrors in ordinary conversations today and notice how much more people say when you pause.",
    "Build your follow-up tracker with columns for the four pillars, offer made, objections heard, and next touch date, and load every open lead into it.",
    "Read Ohio Revised Code 5301.95 and Florida Chapter 475 sections 475.011 and 475.42, then write in one paragraph what you will say to every seller about how you make money."
  ]
});
