BIBLE.register({
  id: "m13",
  part: 5,
  title: "Contracts & Closing",
  icon: "📝",
  summary: "How a purchase contract works, how to get paid through an assignment, double close, or novation, how title clears, what happens on closing day, and the dozen things that kill deals at the table, with the Florida and Ohio rules you must know.",
  minutes: 85,
  lessons: [
    {
      id: "m13-01",
      title: "Anatomy of a Purchase Contract",
      minutes: 11,
      blocks: [
        { h: "What a contract actually does", p: "A purchase and sale agreement is a written promise: the seller agrees to deliver clear title to a specific property on a specific date, and the buyer agrees to pay a specific price, subject to conditions both sides accept. Once both sign, the buyer holds what is called equitable interest, a legal interest in the property that the buyer can, in most cases, transfer to someone else. That transferable interest is the entire basis of wholesaling. Learn every part of the document, because every part is negotiable and every part can kill the deal." },
        { h: "The core terms", p: "Parties: the legal names of the seller, exactly as they appear on the deed, and the buyer, which is usually your company, often followed by and/or assigns. Property: the street address plus the legal description or parcel number from the county. Price: the total purchase price in words and numbers. Earnest money: the deposit you put down to show you are serious, who holds it, when it is due, and when it becomes nonrefundable. Closing date: the day title transfers and money moves, often written as on or before a date, with a provision for extensions. Possession: when the seller must be out, which is usually at closing but can be later by agreement." },
        { h: "Contingencies and the inspection period", p: "A contingency is a condition that must be satisfied or the buyer can cancel and get the deposit back. The most important for an investor is the inspection period, also called the due diligence period: a set number of days, often seven to fifteen, during which you can inspect, run numbers, line up your buyer or your money, and walk away for any reason. Other common contingencies are financing, appraisal, clear title, and sale of another property. Cash investors usually waive financing and appraisal contingencies to make the offer stronger, and rely on the inspection period and the title contingency instead." },
        { h: "And/or assigns", p: "Writing the buyer as [Your Company], and/or assigns means the contract can be assigned to another buyer who steps into your shoes. Without that language, many contracts still allow assignment unless they say otherwise, but some forms specifically prohibit it, and some sellers and agents object to it. Know what your form says. The clause is routine with off-market sellers and frequently resisted on listed properties." },
        { carry: "Contract parts: parties, property, price, earnest money, inspection period, closing date, possession, contingencies, and/or assigns. Equitable interest is what you assign." },
        { trap: "Using a contract you downloaded without reading it. Standard forms often include clauses that prohibit assignment, make earnest money nonrefundable at signing, or shorten the inspection period. Read every line, then confirm with a local real estate attorney." }
      ]
    },
    {
      id: "m13-02",
      title: "Investor-Friendly Clauses and Earnest Money",
      minutes: 10,
      blocks: [
        { h: "Clauses that protect you", p: "Investors add a handful of clauses to protect their position. An inspection period long enough to do real work, with the right to cancel for any reason and a full refund. A clause making the contract contingent on the buyer's partner or lender approval, which is a soft exit. An access clause allowing you to bring contractors, partners, and buyers through the property before closing. Marketing permission letting you advertise the property before closing. A clause that earnest money is the seller's sole remedy if you default, which caps your downside at the deposit. A clause that the seller will sign any documents the title company needs. And a closing-date extension right, often for a small additional deposit." },
        { h: "What sellers' agents push back on", p: "On listed properties, agents routinely object to: assignment language, because they fear you are not a real buyer; long inspection periods, because the house is off the market while you decide; tiny earnest money, because it costs you nothing to walk; partner-approval clauses, which they read as a free option; and marketing before closing, which looks like you are flipping the contract. Be ready to trade. Offer a shorter inspection period for a larger deposit, remove the assignment clause and plan a double close, or show proof of funds to earn back the terms you need." },
        { h: "Earnest money norms", p: "Earnest money is negotiable and varies by market and by how the property was found. With off-market sellers, investors often put down a small, symbolic deposit, commonly in the hundreds of dollars to about a thousand, and sellers rarely object because the deposit is not what they care about. On listed properties, agents usually expect a deposit closer to one percent of the price or more. The key questions are not just how much but who holds it, which should always be the title company or closing attorney, never the seller; when it is due, usually within a few days of signing; and when it goes hard, meaning nonrefundable, which should be after your inspection period ends, not at signing. These are customary practices, not rules; confirm what is normal with your title company and attorney." },
        { carry: "Deposit held by title or attorney, never the seller. Refundable until the inspection period ends. Off-market: often a few hundred dollars; listed: expect around one percent or more. Earnest money as the seller's sole remedy caps your risk." },
        { trap: "Letting the deposit go hard at signing. If you cannot find a buyer and the money is nonrefundable from day one, you have just paid the seller to learn a lesson. Tie nonrefundability to the end of the inspection period." }
      ]
    },
    {
      id: "m13-03",
      title: "Assignment, Double Close, and Novation",
      minutes: 13,
      blocks: [
        { h: "Three ways to get paid", p: "You have a property under contract at one price and a buyer willing to pay more. There are three common ways to capture the difference. Assignment: you sell your contract to the end buyer, who closes directly with the seller, and you are paid an assignment fee at closing. Double close: you actually buy the property from the seller and then immediately sell it to the end buyer in a second transaction, often the same day, keeping the spread. Novation: by agreement with the seller, you replace the original contract with a new one in which the end buyer becomes the purchaser, usually used when the end buyer is a retail buyer using a mortgage and the property is listed or marketed at a higher retail price. Each has different costs, disclosure, and risk." },
        { h: "Assignment", p: "Assignment is the cheapest and simplest. One closing, one set of closing costs, and your fee appears on the settlement statement for everyone to see, including the seller. That transparency is the main objection: a seller who sees you earned twenty thousand dollars for signing papers can get upset, and some will try to back out. Assignment is also impossible when the contract prohibits it and difficult when the end buyer is using a conventional lender, because many lenders will not fund an assigned contract. Use assignment when the seller is comfortable with investors, the fee is modest relative to the price, and the end buyer pays cash or hard money." },
        { h: "Double close", p: "A double close keeps your fee private because there are two separate transactions with two separate settlement statements. It costs more: two sets of closing costs, two transfer taxes in most cases, and you must bring funds to the first closing, either your own, a hard money loan, or a short-term transactional lender who funds for a day in exchange for a fee. Some title companies will not use the end buyer's funds to pay the seller, so ask in advance. Use a double close when the spread is large, when the seller or the agent objects to assignment, or when the contract is not assignable." },
        { h: "Novation", p: "In a novation, the seller agrees to release you from the original contract and sign a new one directly with the end buyer at a higher price, and you are paid the difference as a fee or through a separate agreement at closing. Novation lets you market a property to retail buyers, including those using mortgages, which usually means a higher sale price. It requires the seller's written cooperation, a very clear fee agreement, and careful handling of how the property is advertised, because marketing a property you do not own to retail buyers can look like unlicensed brokerage. Novation is the method most likely to raise licensing questions, so do not attempt it without an attorney who has reviewed your documents and your marketing." },
        { h: "Disclosure differences", p: "Whatever method you use, the seller should know you may assign or resell for a profit, in writing where the law requires it. Ohio now requires a specific written disclosure before the contract binds, covered in the state lesson. Florida regulates your conduct through licensing law, so your paperwork must show you are a principal in the transaction and never represent yourself as acting on the seller's behalf. Your end buyer should also receive full disclosure that they are purchasing contract rights and what your fee is. Confirm with a local real estate attorney." },
        { carry: "Assignment: one closing, fee visible, cheapest. Double close: two closings, fee private, two sets of costs, needs funding. Novation: new contract with end buyer, retail price, highest licensing risk. Disclose in every case." },
        { trap: "Planning an assignment to a buyer using a conventional mortgage. Many lenders will not fund an assigned contract. Know how your buyer is paying before you choose the method." }
      ]
    },
    {
      id: "m13-04",
      title: "The Assignment Agreement and the Buyer's Deposit",
      minutes: 9,
      blocks: [
        { h: "What the assignment agreement says", p: "The assignment agreement is a short separate contract between you, the assignor, and your end buyer, the assignee. It identifies the original purchase contract by date and parties, states that you are transferring all your rights and obligations under it, states the assignment fee and when it is paid, usually at closing from the buyer's funds, and states the nonrefundable deposit the buyer pays you now to lock the deal. It should say the buyer takes the property as-is, has reviewed the original contract and any inspections, and is responsible for closing on the original terms and date. Attach the original contract as an exhibit." },
        { h: "The buyer's deposit", p: "Your end buyer should put down a nonrefundable deposit when they sign the assignment, held by the title company and credited toward their purchase at closing. The deposit is what keeps a buyer from tying up your deal and vanishing; without it, you have given away your contract for free. Many investors ask for a deposit at least equal to the earnest money you have at risk with the seller, and often several thousand dollars, so that a buyer who walks covers your deposit and your time. State clearly when it is forfeited: if the buyer fails to close on time for any reason other than the seller's default or a title defect." },
        { h: "Who talks to whom", p: "Send the signed assignment and the original contract to the title company together, and introduce your buyer to the closer. From this point the title company coordinates with the buyer on funds and documents, but you stay involved until the deal records. Keep the seller informed too: a seller who is surprised at closing by a new buyer's name and a fee line is a seller who may refuse to sign." },
        { carry: "Assignment agreement: identifies the original contract, transfers rights and duties, states the fee, states the buyer's nonrefundable deposit held at title, buyer takes it as-is on the original terms. No deposit, no assignment." },
        { trap: "Giving a buyer the contract without a nonrefundable deposit. They shop it, tie up your inspection period, and disappear three days before closing. Collect the deposit before you send the signed assignment." }
      ]
    },
    {
      id: "m13-05",
      title: "Title: Search, Insurance, Liens, and Clear to Close",
      minutes: 11,
      blocks: [
        { h: "What title is", p: "Title is the legal right to own and transfer the property. A title search is an examination of public records to confirm the seller actually owns the property and to find anything attached to it: mortgages, judgments, tax liens, code enforcement liens, association liens, mechanics liens from unpaid contractors, easements, and open permits. The search produces a title commitment, which lists what must be cleared before the title company will insure the buyer. The time it takes varies, but allow at least one to two weeks and start the search the day the contract is signed." },
        { h: "Title insurance", p: "Title insurance is a one-time premium policy that protects against defects the search missed or that were hidden, such as a forged deed in the chain of title or an unknown heir. There are two policies: the owner's policy protects the buyer, and the lender's policy protects the mortgage lender. Who pays for the owner's policy and who chooses the title company is set by local custom and the contract, not by state law, and it differs between the two states this curriculum covers; see the state lesson. Cash buyers do not need a lender's policy but should always buy the owner's policy." },
        { h: "Liens and payoffs", p: "Every lien must be paid or released at or before closing for the buyer to receive clear title. The title company orders a payoff letter from each lender showing the exact balance to a specific date. The seller's net proceeds are what remains after all payoffs, prorated taxes, and the seller's closing costs. This is where deals die quietly: if the mortgage payoff plus liens exceeds the price, the seller is underwater and cannot close without bringing money or a short sale approval from the lender. Ask about the mortgage balance and any liens in your first conversation so you are not surprised by the title commitment." },
        { h: "Clear to close", p: "Clear to close means every item on the title commitment is satisfied, payoffs are confirmed, the deed and closing documents are prepared, and funds are scheduled. The closer will send a settlement statement showing every dollar in and out for both sides. Read it line by line before closing day. Check the purchase price, your fee or your spread, the earnest money credit, prorations, and every fee you did not expect." },
        { carry: "Title search finds the seller's ownership and every lien. The commitment lists what must clear. Payoffs come from the lenders. Clear to close means all cleared, documents ready, funds scheduled. Always buy the owner's policy." },
        { trap: "Waiting to order title until you have a buyer. Title problems take weeks to fix, and your inspection period is ticking. Open title the day you sign with the seller." }
      ]
    },
    {
      id: "m13-06",
      title: "The Closing Process and Wire Fraud",
      minutes: 10,
      blocks: [
        { h: "The timeline", p: "Day one: contract signed, earnest money delivered to title, title search ordered. Days one through seven: inspections, contractor walk-throughs, buyer walk-throughs, offer to your buyers list. Days seven through fifteen: inspection period ends, deposit goes hard, assignment agreement signed with the end buyer and their deposit collected. Days ten through twenty-one: title commitment issued, liens identified, payoffs ordered, any title problems worked. Days twenty-one through thirty: settlement statement reviewed, final walk-through, closing documents signed, funds wired, deed recorded. Cash deals can close faster; a thirty-day window gives room for title surprises." },
        { h: "Closing day", p: "At closing the seller signs the deed and affidavits, the buyer signs the settlement statement and any loan documents, the title company collects funds, pays off liens, pays each party, and records the deed with the county. In many markets the parties sign separately, sometimes with a mobile notary, and the deal funds when all documents and funds are in. The deal is done when the deed records and the title company confirms disbursement, not when you sign. Your assignment fee or your spread is wired to you from the title company, usually the same day or the next business day." },
        { h: "Wire fraud: the biggest single risk on closing day", p: "Real estate closings are a prime target for wire fraud, in which criminals compromise an email account of someone in the transaction and send fake wiring instructions that look real. The FBI's Internet Crime Complaint Center reported that in 2024 business email compromise produced 21,442 complaints and about 2.77 billion dollars in losses, and real-estate-related fraud complaints totaled 9,359 with about 173.6 million dollars in losses. Once a wire lands in the criminal's account it is often gone within hours. The protection is simple and must be absolute: never wire money based on instructions received by email alone. Call the title company at a phone number you already know, from their website or your prior calls, not from the email, and verbally confirm the account and routing numbers before sending. Tell your sellers and buyers to do the same, in writing, at the start of every deal." },
        { carry: "Deal is done when the deed records and funds disburse. Never wire on email instructions alone: call title at a number you already know and confirm account and routing numbers by voice." },
        { trap: "Trusting a last-minute email saying wiring instructions have changed. That is the fraud. Instructions almost never change; a change is a stop sign, not an update. Call the known number." },
        { sources: [
          { t: "FBI Internet Crime Complaint Center, 2024 Internet Crime Report", u: "https://www.ic3.gov/AnnualReport/Reports/2024_IC3Report.pdf" }
        ] }
      ]
    },
    {
      id: "m13-07",
      title: "What Kills Deals at the Table",
      minutes: 10,
      blocks: [
        { h: "Twelve deal killers", p: "The deals that die in the last week usually die from something that was knowable in the first week. Here are the twelve most common, each with the fix." },
        { h: "One through four", p: "One, the seller is not the only owner: a spouse, a sibling heir, or an ex on the deed must sign too; pull the deed before you write the contract. Two, probate is not complete: an heir cannot sell until the court gives authority; ask for the letters of administration or the court order. Three, the payoff exceeds the price: the seller is underwater; get mortgage and lien balances in the first call. Four, unknown liens: code enforcement, utility, association, or judgment liens show up on title; order title day one and budget time to negotiate releases." },
        { h: "Five through eight", p: "Five, the end buyer cannot fund: hard money fell through or the proof of funds was fake; verify funds and collect a real nonrefundable deposit. Six, the buyer retrades after inspection: they want ten thousand off the day before closing; set expectations that the price is as-is and the deposit is forfeited for failure to close. Seven, the seller gets cold feet after seeing the assignment fee: disclose early, in writing, and consider a double close for large spreads. Eight, the contract was not assignable or the lender will not fund an assignment: read the form and know your buyer's financing before choosing the exit method." },
        { h: "Nine through twelve", p: "Nine, the property has an open permit, unpermitted addition, or active code case: pull the municipal records during the inspection period and price the fix. Ten, occupancy problems: a tenant refuses access or the seller will not be out by closing; include an access clause, verify occupancy, and use a possession agreement with a holdback if the seller stays. Eleven, missed deadlines: the inspection period lapsed, the deposit went hard, or the closing date passed without an extension; calendar every date the day you sign. Twelve, wire fraud or a funding delay: funds did not arrive, or worse, went to a criminal; confirm instructions by phone and schedule wires a day early." },
        { carry: "Deal killers are knowable in week one: who is on the deed, is probate done, what is owed, what liens exist, is the buyer real, is the contract assignable, are permits open, who is living there, what are the dates." },
        { trap: "Treating the title company as the people who find problems. They will, but by then the clock has run out. You find the problems in week one; title confirms them." }
      ]
    },
    {
      id: "m13-08",
      title: "Investor-Friendly Title, Attorneys, Taxes, and State Rules",
      minutes: 11,
      blocks: [
        { h: "Choosing a title company or attorney", p: "Some states close with title companies, some with attorneys, and in both Florida and Ohio title companies and attorneys both handle closings. What you need is one that is investor-friendly, which means: they have closed assignments and double closes before and can explain how they handle each, they will hold earnest money and buyer deposits, they will explain their stance on using the end buyer's funds in a double close, they communicate fast, and they can close in two to three weeks when title is clean. Interview two or three before your first deal. Ask directly: how many assignment closings did you do last year?" },
        { h: "Transfer taxes and who pays", p: "Both states tax the transfer of real estate at closing, and the rates and customs differ. In Florida, the documentary stamp tax on deeds is seventy cents per one hundred dollars of consideration statewide, with a different structure in Miami-Dade County, and the seller customarily pays it, though the contract controls. In Ohio, the state real property conveyance fee is one dollar per one thousand dollars of value, and counties may add a permissive fee of up to three dollars per one thousand, so the total is up to four dollars per one thousand; it is customarily paid by the seller and negotiable. In a double close, you are the seller on the second transaction, so budget the transfer tax on the resale price as your cost." },
        { example: "Double close in Florida at $140,000 then $165,000: seller pays doc stamps of $980 on the first deed; you pay $1,155 on the second. Ohio at the same prices in a 4-mill county: $560 on the first, $660 on the second." },
        { h: "Who chooses and pays for title", p: "In Florida, the party who pays for the owner's title policy customarily chooses the title agent; in most counties that is the seller, while in several counties including Miami-Dade, Broward, Sarasota, and Collier the buyer customarily pays and chooses. This is county custom, not law, and the contract controls. In Ohio, custom also varies by region: the owner's policy is often split between buyer and seller in the northeast and paid by the seller in central Ohio. Ask your title company what is customary in the county and write it into the contract rather than assuming." },
        { h: "The wholesaler disclosure statutes", p: "Ohio enacted a wholesaler disclosure statute, Ohio Revised Code 5301.95, effective March 2, 2026. Before a contract to buy residential property becomes binding, a wholesaler who intends to assign must give a separate, conspicuous written disclosure in boldface at least twelve-point type stating that the wholesaler may assign the contract for profit without the owner's consent and that the agreed price may be below market value, signed and dated by both parties. If it is not given, the owner may cancel any time before closing without penalty, earnest money must be returned within thirty days, and the violation is an unfair or deceptive act under Ohio consumer law. Florida has no wholesaler-specific statute as of late 2026; it relies on Chapter 475, the real estate licensing law. Under 475.011 an owner selling its own property is exempt from licensing, and a buyer under contract transferring its own contract rights is generally treated as a principal, but under 475.42 performing brokerage services for another without a license is a third-degree felony. The practical rule in Florida is to always be a party to the contract, never market a property you do not have under contract, and never act for the seller. Confirm with a local real estate attorney." },
        { h: "Tax reminder", p: "Assignment fees and double-close spreads are ordinary business income, reported on Schedule C if you operate as a sole proprietor or through your entity's return, and subject to self-employment tax, not capital gains. Confirm with a CPA." },
        { carry: "FL: doc stamps $0.70 per $100 on the deed, seller customarily pays; Chapter 475 governs wholesalers. OH: conveyance fee $1 per $1,000 state plus up to $3 per $1,000 county, seller customarily pays; ORC 5301.95 disclosure effective March 2, 2026. Assignment fees are ordinary income." },
        { state: { fl: "Deed doc stamps $0.70 per $100 of consideration statewide (Miami-Dade differs), customarily seller-paid. Owner's title policy and choice of title agent follow county custom: seller in most counties, buyer in Miami-Dade, Broward, Sarasota, Collier. No wholesaler statute; Chapter 475 licensing law applies, 475.42 makes unlicensed brokerage a felony.", oh: "Conveyance fee $1 per $1,000 state plus permissive county fee up to $3 per $1,000, customarily seller-paid and negotiable. Owner's policy often split in northeast Ohio, seller-paid in central Ohio. ORC 5301.95 wholesaler disclosure required before contract binds, effective March 2, 2026." } },
        { sources: [
          { t: "Ohio Revised Code 5301.95, Residential real estate wholesaler disclosure (effective March 2, 2026)", u: "https://codes.ohio.gov/ohio-revised-code/section-5301.95" },
          { t: "Ohio Department of Taxation, Real Property Conveyance Fee (1 mill state, up to 3 mills county; ORC 319.54, 322.01–322.07)", u: "https://dam.assets.ohio.gov/image/upload/tax.ohio.gov/communications/publications/brief_summaries/new%20internet%20feb_7_2012/real_property_conveyance_fee_2_8.pdf" },
          { t: "Ohio Real Title, Closing Costs in Ohio: owner's policy and conveyance fee customs", u: "https://ohiorealtitle.com/2026/01/closing-costs-in-ohio-what-buyers-and-sellers-need-to-know/" },
          { t: "Florida Department of Revenue, Documentary Stamp Tax (Chapter 201, F.S.)", u: "https://floridarevenue.com/taxes/taxesfees/Pages/doc_stamp.aspx" },
          { t: "Oldham Law, Florida Documentary Stamp Tax guide ($0.70 per $100 on deeds, Miami-Dade exception, seller customarily pays)", u: "https://oldfllaw.com/florida-documentary-stamp-tax/" },
          { t: "Barnes Walker, Who Pays for Title Insurance in Florida (county customs)", u: "https://barneswalker.com/who-pays-for-title-insurance-in-florida/" },
          { t: "Florida Statutes 475.011, Exemptions from licensing", u: "http://www.leg.state.fl.us/statutes/index.cfm?App_mode=Display_Statute&URL=0400-0499/0475/Sections/0475.011.html" },
          { t: "Florida Statutes Chapter 475 (see 475.42 violations and penalties)", u: "http://www.leg.state.fl.us/statutes/index.cfm?App_mode=Display_Statute&URL=0400-0499/0475/0475.html" },
          { t: "IRS, Instructions for Schedule C (Profit or Loss From Business)", u: "https://www.irs.gov/instructions/i1040sc" },
          { t: "Blue Cloud CPA, Is My Assignment Fee Ordinary Income? (IRC 1221, 1402)", u: "https://bluecloudcpa.com/guides/real-estate-wholesaling-tax-assignment-fee" }
        ] }
      ]
    }
  ],
  cards: [
    { id: "m13-c01", type: "term", q: "What is equitable interest?", a: "The legal interest a buyer holds in a property once a purchase contract is signed, before closing. It is what you transfer in an assignment." },
    { id: "m13-c02", type: "term", q: "What is earnest money?", a: "The buyer's deposit showing good faith, held by the title company or attorney, refundable until the inspection period ends and then applied to the price at closing." },
    { id: "m13-c03", type: "term", q: "What is an inspection or due diligence period?", a: "A set number of days, often 7–15, during which the buyer can inspect, run numbers, line up a buyer or funding, and cancel for any reason with a full deposit refund." },
    { id: "m13-c04", type: "term", q: "What is a contingency?", a: "A condition that must be met or the buyer may cancel and recover the deposit. Common ones: inspection, financing, appraisal, clear title. Cash investors usually keep inspection and title only." },
    { id: "m13-c05", type: "term", q: "What does and/or assigns mean?", a: "Buyer language allowing the contract to be assigned to another party who steps into the buyer's position. Routine off-market, often resisted on listed properties." },
    { id: "m13-c06", type: "term", q: "What is an assignment?", a: "Selling your contract rights to an end buyer who closes directly with the seller; you are paid an assignment fee at closing. One closing, fee visible on the settlement statement." },
    { id: "m13-c07", type: "term", q: "What is a double close?", a: "Two back-to-back transactions: you buy from the seller, then sell to your end buyer, keeping the spread. Fee stays private; two sets of closing costs and transfer taxes; needs funding." },
    { id: "m13-c08", type: "term", q: "What is a novation?", a: "Replacing the original contract with a new one between the seller and the end buyer, with the seller's written agreement, so you can sell at retail to a mortgage buyer. Highest licensing risk; attorney required." },
    { id: "m13-c09", type: "term", q: "What is transactional funding?", a: "A very short-term loan, often one day, used to fund the first leg of a double close, repaid from the second closing in exchange for a fee." },
    { id: "m13-c10", type: "term", q: "What is a title commitment?", a: "The title company's report after the search listing what must be cleared, such as liens and payoffs, before it will issue a title policy to the buyer." },
    { id: "m13-c11", type: "term", q: "What is an owner's title policy?", a: "One-time premium insurance protecting the buyer against hidden title defects like a forged deed or unknown heir. Cash buyers do not need a lender's policy but should always buy the owner's policy." },
    { id: "m13-c12", type: "term", q: "What is a payoff letter?", a: "A lender's statement of the exact balance owed on a lien to a specific date, ordered by the title company so the lien can be paid and released at closing." },
    { id: "m13-c13", type: "term", q: "What does clear to close mean?", a: "Every title commitment item is satisfied, payoffs are confirmed, documents are prepared, and funds are scheduled. Read the settlement statement line by line at this point." },
    { id: "m13-c14", type: "term", q: "What is a settlement statement?", a: "The closing document listing every dollar in and out for both sides: price, deposits, payoffs, prorations, fees, and your assignment fee or spread." },
    { id: "m13-c15", type: "term", q: "What is business email compromise?", a: "Fraud where a criminal takes over or spoofs an email account in the transaction and sends fake wiring instructions. Defeated by confirming instructions by phone at a known number." },
    { id: "m13-c16", type: "term", q: "What is a mechanics lien?", a: "A lien filed by an unpaid contractor or supplier against the property. It must be paid or released before clear title can transfer." },
    { id: "m13-c17", type: "formula", q: "How do you compute Florida deed doc stamps?", a: "Price ÷ 100 × $0.70. A $165,000 deed = 1,650 × 0.70 = $1,155. Seller customarily pays; contract controls." },
    { id: "m13-c18", type: "formula", q: "How do you compute the Ohio conveyance fee in a 4-mill county?", a: "Price ÷ 1,000 × ($1 state + up to $3 county). $165,000 × 4 ÷ 1,000 = $660. Seller customarily pays; negotiable." },
    { id: "m13-c19", type: "formula", q: "How do you compute the seller's net proceeds?", a: "Price − mortgage payoff − other liens − prorated taxes − seller closing costs. If payoffs exceed price, the seller is underwater and cannot close without cash or a short sale." },
    { id: "m13-c20", type: "formula", q: "How do you size the end buyer's deposit?", a: "At least your earnest money at risk with the seller, often several thousand dollars, nonrefundable and held at title. Buyer deposit ≥ your deposit + your time." },
    { id: "m13-c21", type: "number", q: "What is a typical inspection period for an investor contract?", a: "Often seven to fifteen days, negotiated. Long enough to inspect, run numbers, and find your buyer or funding." },
    { id: "m13-c22", type: "number", q: "What is the Florida deed documentary stamp tax rate?", a: "$0.70 per $100 of consideration statewide; Miami-Dade uses a different structure. Customarily seller-paid." },
    { id: "m13-c23", type: "number", q: "What is the Ohio real property conveyance fee?", a: "$1 per $1,000 state (1 mill) plus a permissive county fee of up to $3 per $1,000, so up to $4 per $1,000 total. Customarily seller-paid." },
    { id: "m13-c24", type: "number", q: "When did Ohio's wholesaler disclosure statute take effect?", a: "March 2, 2026, Ohio Revised Code 5301.95. Disclosure must be given and signed before the contract becomes binding." },
    { id: "m13-c25", type: "number", q: "What font and format does the Ohio disclosure require?", a: "Conspicuous, boldface, at least twelve-point type, on a document separate from the purchase contract, signed and dated by both wholesaler and owner." },
    { id: "m13-c26", type: "number", q: "How fast must earnest money be returned if an Ohio wholesaler failed to disclose and the owner cancels?", a: "Within thirty days, by the escrow or closing agent, under ORC 5301.95." },
    { id: "m13-c27", type: "number", q: "What did the FBI IC3 report for 2024 business email compromise?", a: "21,442 complaints and about $2.77 billion in losses; real estate fraud added 9,359 complaints and about $173.6 million in losses." },
    { id: "m13-c28", type: "number", q: "How long should you allow for a title search?", a: "At least one to two weeks; order it the day the contract is signed because title fixes take longer than inspection periods." },
    { id: "m13-c29", type: "number", q: "What is the penalty level for unlicensed brokerage in Florida?", a: "A third-degree felony under Florida Statute 475.42. Always be a party to the contract and never act for the seller." },
    { id: "m13-c30", type: "state", q: "Who customarily pays the deed transfer tax and what is the rate?", a: "FL: seller customarily pays doc stamps of $0.70 per $100 (Miami-Dade differs). | OH: seller customarily pays the conveyance fee of $1 per $1,000 state plus up to $3 per $1,000 county; negotiable." },
    { id: "m13-c31", type: "state", q: "Who customarily pays for and chooses the owner's title policy?", a: "FL: the party paying chooses; seller in most counties, buyer in Miami-Dade, Broward, Sarasota, Collier. | OH: varies by region, often split in northeast Ohio and seller-paid in central Ohio; ask the title company and write it into the contract." },
    { id: "m13-c32", type: "state", q: "What wholesaler-specific law applies?", a: "FL: none as of late 2026; Chapter 475 licensing law governs, with 475.011 exemptions and 475.42 felony penalties. | OH: ORC 5301.95 written disclosure before the contract binds, effective March 2, 2026." },
    { id: "m13-c33", type: "state", q: "What happens if the assignment-intent disclosure is skipped?", a: "FL: no specific statute, but misrepresentation and unlicensed-activity risk under Chapter 475. | OH: owner may cancel before closing without penalty, earnest money returned within 30 days, and it is a deceptive act under consumer law." },
    { id: "m13-c34", type: "scenario", q: "The deed shows the seller and an ex-spouse. The seller says the ex is out of the picture. What now?", a: "Both owners must sign. Get the ex's contact and consent before writing the contract, or confirm with a title company and attorney how title was divided in the divorce." },
    { id: "m13-c35", type: "scenario", q: "An heir wants to sell a parent's house; probate has not been opened. Can you contract?", a: "You can sign a contract contingent on the heir obtaining court authority, but the sale cannot close until letters of administration or a court order exist. Build the timeline around the court." },
    { id: "m13-c36", type: "scenario", q: "Title finds a $12,000 code enforcement lien you did not know about. What do you do?", a: "Negotiate: ask the municipality about lien reduction, ask the seller to reduce the price or pay it from proceeds, or cancel inside your inspection period if the numbers no longer work." },
    { id: "m13-c37", type: "scenario", q: "Your end buyer is using a conventional mortgage and you planned to assign. Problem?", a: "Yes. Many lenders will not fund an assigned contract. Switch to a double close with transactional funding, or find a cash or hard-money buyer." },
    { id: "m13-c38", type: "scenario", q: "The seller sees a $25,000 assignment fee on the settlement statement and refuses to sign. How could this have been avoided?", a: "Disclose early and in writing that you may assign for a profit, and use a double close when the spread is large relative to the price." },
    { id: "m13-c39", type: "scenario", q: "A buyer wants your contract but will not put down a deposit. Do you send the assignment?", a: "No. Without a nonrefundable deposit held at title, the buyer can shop your deal and vanish. No deposit, no assignment." },
    { id: "m13-c40", type: "scenario", q: "You get an email from the title company the morning of closing saying the wiring instructions changed. What do you do?", a: "Do not wire. Call the title company at the number you already have, not the one in the email, and confirm by voice. Changed instructions are the fraud signal." },
    { id: "m13-c41", type: "scenario", q: "Day 14 of a 15-day inspection period and you have no buyer. Options?", a: "Negotiate an extension in writing before day 15, often for a small additional deposit; or cancel and get your deposit back. Letting it lapse makes the deposit nonrefundable." },
    { id: "m13-c42", type: "scenario", q: "Seller wants to stay in the house two weeks after closing. How do you protect the buyer?", a: "Use a written possession or occupancy agreement with a daily rate and a holdback from seller proceeds at title until the seller is out and the house is inspected." },
    { id: "m13-c43", type: "scenario", q: "A listing agent objects to and/or assigns and a 15-day inspection. What trade do you offer?", a: "Remove the assignment clause and plan a double close, shorten inspection to 7–10 days, and increase earnest money with proof of funds to show you are real." },
    { id: "m13-c44", type: "scenario", q: "You are signing an Ohio seller on Monday. What must be done first?", a: "Both sign and date the separate, conspicuous, bold, twelve-point ORC 5301.95 disclosure that you may assign for profit and the price may be below market, before the contract binds." },
    { id: "m13-c45", type: "scenario", q: "You want to list a Florida property you have under contract on the MLS at a higher price before closing. Is that safe?", a: "Not without an attorney. Marketing a property you do not own to retail buyers can look like unlicensed brokerage under Chapter 475, a felony in Florida. Novation requires careful legal structuring." },
    { id: "m13-c46", type: "scenario", q: "Mortgage payoff is $150,000 and your contract price is $135,000. Can this close?", a: "Not as written. The seller is underwater and must bring $15,000 plus costs or get the lender to approve a short sale. Ask about balances on the first call to avoid this." },
    { id: "m13-c47", type: "trap", q: "Letting earnest money go nonrefundable at signing.", a: "If you cannot find a buyer you lose the deposit. Tie nonrefundability to the end of the inspection period." },
    { id: "m13-c48", type: "trap", q: "Letting the seller hold the earnest money.", a: "You may never see it again. Deposits go to the title company or closing attorney, always." },
    { id: "m13-c49", type: "trap", q: "Ordering title only after you find a buyer.", a: "Title problems take weeks; your inspection period does not. Open title the day the seller signs." },
    { id: "m13-c50", type: "trap", q: "Not calendaring the contract dates.", a: "A missed inspection deadline makes your deposit hard; a missed closing date can void the deal. Enter every date the day you sign." },
    { id: "m13-c51", type: "trap", q: "Wiring funds from email instructions.", a: "Business email compromise cost victims about $2.77 billion in 2024 per the FBI. Call the known number and confirm account and routing by voice, every time." },
    { id: "m13-c52", type: "trap", q: "Choosing the exit method before knowing how the buyer pays.", a: "Mortgage buyers often cannot close an assignment. Verify funding type first, then choose assignment, double close, or novation." },
    { id: "m13-c53", type: "trap", q: "Assuming who pays title and transfer tax.", a: "Both are set by local custom and the contract, and they differ by state and even by county. Ask your title company and write it in." },
    { id: "m13-c54", type: "trap", q: "Treating assignment income as capital gain.", a: "Assignment fees and double-close spreads are ordinary business income subject to self-employment tax. Confirm with a CPA." },
    { id: "m13-c55", type: "term", q: "What is an investor-friendly title company?", a: "One that has closed assignments and double closes, holds deposits, explains its policy on using end-buyer funds, communicates fast, and can close in two to three weeks on clean title." }
  ],
  quiz: [
    { id: "m13-q01", q: "What interest does a buyer hold after signing a purchase contract and before closing?", opts: ["Equitable interest","Fee simple title","A lien","A lease"], correct: 0, explain: "Equitable interest is the transferable contract interest that makes assignment possible; legal title transfers at closing." },
    { id: "m13-q02", q: "When should earnest money become nonrefundable?", opts: ["At signing", "When title is ordered", "After the inspection period ends", "Never"], correct: 2, explain: "Tying nonrefundability to the end of due diligence lets you cancel with a full refund if the deal does not work." },
    { id: "m13-q03", q: "Who should hold the earnest money?", opts: ["The seller","You","Your end buyer","The title company or closing attorney"], correct: 3, explain: "A neutral third party protects both sides; a seller holding the deposit can simply keep it." },
    { id: "m13-q04", q: "Which exit method keeps your fee off the seller's settlement statement?", opts: ["Assignment","Both equally","Neither","Double close"], correct: 3, explain: "A double close has two transactions and two statements; an assignment fee appears on the single closing statement." },
    { id: "m13-q05", q: "Your end buyer is using a conventional mortgage. The safest method is usually:", opts: ["Double close or novation with attorney review","Assignment","Bandit sign","Verbal agreement"], correct: 0, explain: "Many lenders will not fund assigned contracts; a double close or carefully structured novation avoids that problem." },
    { id: "m13-q06", q: "Which method carries the highest unlicensed-brokerage risk?", opts: ["Assignment", "Double close", "Novation", "Cash purchase"], correct: 2, explain: "Novation involves marketing a property you do not own to retail buyers, which can look like brokerage without a license." },
    { id: "m13-q07", q: "Ohio's wholesaler disclosure statute ORC 5301.95 took effect on:", opts: ["January 1, 2024", "March 2, 2026", "July 4, 2025", "It has not taken effect"], correct: 1, explain: "The statute requires a separate, conspicuous, bold, twelve-point disclosure signed before the contract binds." },
    { id: "m13-q08", q: "If an Ohio wholesaler fails to give the disclosure, the owner may:", opts: ["Do nothing","Sue only after closing","Keep the wholesaler's buyer deposit","Cancel before closing without penalty and get earnest money back within 30 days"], correct: 3, explain: "ORC 5301.95 also makes the failure an unfair or deceptive act under Ohio consumer law." },
    { id: "m13-q09", q: "Florida's deed documentary stamp tax rate statewide is:", opts: ["$0.35 per $100", "$0.70 per $100", "$1.05 per $100", "$1 per $1,000"], correct: 1, explain: "Seventy cents per hundred dollars of consideration; Miami-Dade uses a different structure. Seller customarily pays." },
    { id: "m13-q10", q: "Ohio's conveyance fee is:", opts: ["$1 per $1,000 state plus up to $3 per $1,000 county","$0.70 per $100","$5 per $1,000 flat","There is none"], correct: 0, explain: "One mill mandatory plus up to three permissive mills, so up to four dollars per thousand, customarily seller-paid." },
    { id: "m13-q11", q: "Doc stamps on a $165,000 Florida deed are:", opts: ["$660", "$980", "$1,155", "$1,650"], correct: 2, explain: "165,000 ÷ 100 = 1,650 × $0.70 = $1,155." },
    { id: "m13-q12", q: "Ohio conveyance fee on $165,000 in a 4-mill county is:", opts: ["$165", "$495", "$660", "$1,155"], correct: 2, explain: "165,000 ÷ 1,000 × $4 = $660." },
    { id: "m13-q13", q: "In most Florida counties, who customarily pays for and chooses the owner's title policy?", opts: ["Buyer","Title company","The county","Seller"], correct: 3, explain: "Seller in most counties; buyer in Miami-Dade, Broward, Sarasota, and Collier. County custom, contract controls." },
    { id: "m13-q14", q: "Florida wholesalers are governed primarily by:", opts: ["Chapter 475 real estate licensing law","A wholesaler disclosure statute","Chapter 4719","The TCPA"], correct: 0, explain: "Florida has no wholesaler statute as of late 2026; 475.42 makes unlicensed brokerage a third-degree felony, so act only as a principal." },
    { id: "m13-q15", q: "An email says wiring instructions changed the morning of closing. You should:", opts: ["Wire to the new account quickly", "Reply to confirm", "Call the title company at a number you already know and verify by voice", "Text the sender"], correct: 2, explain: "Changed instructions are the classic business email compromise signal. Never wire on email alone." },
    { id: "m13-q16", q: "The FBI IC3 reported 2024 business email compromise losses of about:", opts: ["$27 million", "$277 million", "$2.77 billion", "$27.7 billion"], correct: 2, explain: "21,442 complaints and about $2.77 billion in losses; real estate fraud added about $173.6 million." },
    { id: "m13-q17", q: "When should you order the title search?", opts: ["After finding a buyer","The week of closing","Only if the seller asks","The day the contract is signed"], correct: 3, explain: "Title problems take weeks to fix and the inspection period is short. Open title day one." },
    { id: "m13-q18", q: "Mortgage payoff $150,000, contract price $135,000. The seller is:", opts: ["Fine", "Underwater and cannot close without cash or short sale approval", "Entitled to a bonus", "Required to lower the price"], correct: 1, explain: "Payoffs exceeding price mean no net proceeds; ask about balances on the first call to avoid this." },
    { id: "m13-q19", q: "What should you collect from your end buyer when they sign the assignment?", opts: ["A nonrefundable deposit held at title","Nothing","A verbal promise","A copy of their driver's license only"], correct: 0, explain: "The deposit prevents the buyer from shopping your deal and disappearing; no deposit, no assignment." },
    { id: "m13-q20", q: "Assignment fees are taxed as:", opts: ["Ordinary business income subject to self-employment tax","Long-term capital gains","Tax-free","Rental income"], correct: 0, explain: "The contract was held for sale, so the fee is ordinary income reported on Schedule C or your entity return. Confirm with a CPA." },
    { id: "m13-q21", q: "Which is a typical investor-friendly clause?", opts: ["Earnest money nonrefundable at signing", "No inspection period", "Earnest money as the seller's sole remedy if buyer defaults", "Seller holds the deposit"], correct: 2, explain: "Sole-remedy language caps your downside at the deposit if you cannot close." },
    { id: "m13-q22", q: "The deed shows two owners and only one signed your contract. The contract is:", opts: ["Fully enforceable","Enforceable if you pay more","Automatically assigned","Not enforceable against the non-signing owner; both must sign"], correct: 3, explain: "Every owner on the deed must sign. Pull the deed before writing the contract." }
  ],
  drills: [
    "Get a copy of the purchase contract your title company or attorney recommends, read every line, and highlight the inspection period, earnest money terms, closing date, and any assignment language.",
    "Interview two title companies or closing attorneys: ask how many assignments and double closes they closed last year, how they handle end-buyer funds, and what is customary in your county for title and transfer tax.",
    "Draft your one-page assignment agreement with [Your Company] as assignor, including the fee, the buyer's nonrefundable deposit, and as-is language, and have an attorney review it.",
    "Compute doc stamps or conveyance fees for a double close at $140,000 and $165,000 in your state and county, and add the result to your deal calculator as a cost line.",
    "Write your wire-fraud rule on a card, including the title company's phone number from their website, and send it to your partner, your first seller, and your first buyer.",
    "Read Ohio Revised Code 5301.95 or Florida Statutes 475.011 and 475.42 in full and write a one-paragraph plain-English version you can say to a seller."
  ]
});
