BIBLE.register({
  id: "m14",
  part: 5,
  title: "AI in Your Business",
  icon: "🤖",
  summary: "How to use AI assistants as a tireless junior analyst, writer, and sparring partner for your real estate business, without letting them make the calls, break the law, or feed you numbers you never checked.",
  minutes: 95,
  lessons: [
    {
      id: "m14-01",
      title: "What AI Is Good At, and What It Is Not",
      minutes: 8,
      blocks: [
        { h: "A fast junior analyst who sounds confident about everything", p: "An AI assistant is a large language model: software trained on a huge amount of text that predicts what words should come next. That makes it very good at anything that is mostly language. It can draft a letter in seconds, summarize a forty-page inspection report, turn your messy voice notes into a clean checklist, and play the part of a grumpy seller so you can practice. It works at two in the morning after your shift and it never gets tired of your questions. The catch is that it produces fluent, confident text whether or not that text is true. It does not know what it does not know, and it will not warn you when it is guessing." },
        { h: "Four things it does well", p: "First, drafting. Give it the facts and it writes the first version of anything: a follow-up email, a contractor scope, a social post. Second, summarizing. Paste in a long document and ask for the five things that matter. Third, role-play. Tell it to be a skeptical seller, a picky lender, or a tough buyer, and rehearse. Fourth, structuring. Hand it a pile of unorganized notes and ask for a table, a timeline, or a decision list. In every one of these jobs, you supply the facts and the AI supplies the shape." },
        { h: "Three things it does badly", p: "First, current facts. Unless the tool is actively searching the web and showing you its sources, it is working from training data that may be a year or more old. Rates, statutes, and local rules change. Second, math without a tool. Models can make arithmetic slips, especially in long chains of numbers, and they state the wrong answer with the same confidence as the right one. Always redo deal math yourself or in a spreadsheet. Third, invented specifics. Ask for a statute number, a court case, a comparable sale, or a quote from a famous investor, and it may produce one that does not exist. This is called a hallucination, and it is the single biggest way AI costs investors money." },
        { h: "The rule that keeps you safe", p: "Treat every AI output as a draft from a smart intern who has never seen your market and sometimes makes things up. You read it, you check the numbers, you verify any fact that matters, and you sign your own name to it. AI speeds up the eighty percent of a task that is shaping language. The twenty percent that is judgment, verification, and responsibility stays with you." },
        { carry: "AI is great at drafting, summarizing, role-play, and structuring. It is bad at current facts, unchecked math, and invented specifics. You verify, you decide, you sign." },
        { trap: "Pasting AI output into a contract, an offer, or a marketing piece without reading it. The intern wrote it; you are the one who gets sued or loses the deal." }
      ]
    },
    {
      id: "m14-02",
      title: "The Prompt Pattern: Role, Context, Task, Format, Examples",
      minutes: 10,
      blocks: [
        { h: "Why vague prompts give vague answers", p: "If you type 'write a seller letter' you get a generic letter that sounds like every other investor. If you tell the AI who it is, what situation it is in, exactly what you want, how you want it laid out, and show it one example you like, you get something you can actually use. Think of a prompt as a work order to a new hire. The more specific the order, the less rework." },
        { h: "The five parts", p: "Role: who the AI should act as, such as an experienced real estate acquisitions manager or a plain-spoken copywriter. Context: the facts of the situation, including your market type, the seller's circumstances, and your constraints. Task: the one thing you want done, stated as a verb. Format: how the output should look, such as a numbered list, under one hundred words, or a table with three columns. Examples: one or two samples of what good looks like, or what you want to avoid. You do not need all five every time, but the more that is at stake, the more of them you use." },
        { formula: "ROLE + CONTEXT + TASK + FORMAT + EXAMPLES = usable first draft" },
        { h: "Prompt one: deal screener", p: "Copy this and fill in the brackets. 'You are an experienced buy-and-hold real estate analyst. I am a beginner investor using the BRRRR method, which means buy, rehab, rent, refinance, repeat. Here are the facts on a property: address type [single family, three bed two bath], asking price [X], estimated after-repair value [X] based on these comps [paste], estimated rehab [X] based on these notes [paste], expected rent [X], and my lender refinances at seventy-five percent of appraised value. Task: lay out the deal in a structured summary with purchase, rehab, all-in cost, refinance loan amount, cash left in the deal, and monthly cash flow after a payment at [rate] percent, taxes [X], insurance [X], and ten percent for vacancy and maintenance. Show every calculation step so I can check it. Then list the three biggest risks you see. Format: short headings, one line per number.'" },
        { h: "Prompt two: follow-up message", p: "'You are a calm, respectful real estate investor who buys houses directly from homeowners. Context: I spoke with a homeowner four days ago about buying their house as-is. They said they needed to talk to their sister first. They were friendly but not in a hurry. Task: write a short text message checking in, with no pressure, that reminds them who I am and offers to answer questions. Format: under forty words, no exclamation points, no emojis, end with a simple question. Write three versions with slightly different tones so I can pick one.'" },
        { h: "Prompt three: contractor scope", p: "'You are a general contractor who writes clear scopes of work for investor rehabs. Context: here are my walk-through notes and photos descriptions for a nineteen-seventies ranch house [paste notes]. Task: turn these into a room-by-room scope of work I can hand to three contractors for apples-to-apples bids. Format: one section per room, each item as a short line starting with a verb, materials grade noted as basic rental grade, and a final section listing anything I should get inspected before bidding.'" },
        { carry: "Every serious prompt names the role, gives the context, states one task, specifies the format, and shows an example. Save your best prompts in a note and reuse them." },
        { trap: "Asking for ten things in one prompt. You get ten shallow answers. One task per prompt, then follow up." }
      ]
    },
    {
      id: "m14-03",
      title: "Analyzing a Deal with AI (Then Checking Every Number)",
      minutes: 10,
      blocks: [
        { h: "What AI adds to deal analysis", p: "The value is not that the AI knows your market. It does not. The value is speed and structure. You paste in raw material, such as a list of comparable sales, your rehab walk-through notes, and the listing description, and ask for a structured summary. In thirty seconds you get a clean layout: the comps sorted by similarity, a rehab estimate organized by trade, the risks listed, and the questions you still need to answer. That turns a scattered pile of information into something you can reason about." },
        { h: "The workflow", p: "Step one, gather the facts yourself: comps from your data source, rent estimates from at least two sources, rehab notes from your own walk-through, and the lender's refinance terms. Step two, paste them in with the deal screener prompt from the last lesson and ask the AI to show every calculation. Step three, rebuild the math in your own spreadsheet or calculator. Do not skip this. Step four, ask the AI to argue against the deal: 'Give me the five strongest reasons this is a bad buy.' Step five, decide. The AI organized; you analyzed." },
        { example: "You paste five comps and ask for an ARV, which means after-repair value. The AI averages all five and says $215,000. You check and see two comps are a mile away and one has a pool. You drop those, average the remaining three at $198,000, and your maximum offer falls by about $12,000. That is the check that matters." },
        { h: "Where it goes wrong", p: "AI will happily invent a comparable sale if you ask it to 'find comps' without giving it data, because it has no live access to your MLS or county records unless the specific tool is connected to one. It can also silently mix up numbers you pasted, such as swapping asking price and ARV, or apply a formula from one market to another. And it will not know that a particular street floods, that the roof is original, or that the neighborhood is split by a highway. Everything local, physical, and current comes from you." },
        { carry: "AI structures the deal; you supply the comps and rehab numbers, and you rebuild the math yourself before you make an offer." },
        { trap: "Asking an AI to 'pull comps' for an address. Unless it is connected to a real data source and shows you the records, the comps it produces may be fiction." }
      ]
    },
    {
      id: "m14-04",
      title: "Seller Follow-Up Texts and Emails",
      minutes: 9,
      blocks: [
        { h: "The job AI is best at in your business", p: "Most deals come from follow-up, and most investors are bad at follow-up because writing twenty thoughtful messages is tedious. AI removes the tedium. Give it the notes from your last conversation and it drafts a message that references what the seller actually said, in a tone you choose. You still read it, fix anything wrong, and hit send yourself." },
        { h: "Tone rules worth writing into every prompt", p: "Plain language, no hype, no urgency tricks, no fake deadlines. Short sentences. One question at the end so the seller has an easy way to reply. Reference a real detail from the last conversation so it does not read like a template. Sign with your real name and company. Tell the AI to avoid words that sound like a sales script, and give it two or three examples of messages you have sent that got replies." },
        { formula: "Prompt: 'Rewrite this draft so it sounds like a neighbor, not a salesperson. Keep it under 50 words. Remove urgency language. End with one easy question.'" },
        { h: "Compliance: a human must review and a human must send", p: "Two reasons. First, accuracy. The AI does not know whether the number you quoted last week was $140,000 or $145,000, and a wrong number in writing is a problem. Second, the law. Marketing text messages sent with automated systems require prior express written consent under the federal Telephone Consumer Protection Act, known as the TCPA, and the FCC treats text messages as calls under that law. Drafting with AI is fine. Letting an AI system blast texts to a list on its own is not, and the next lessons explain why. Keep a human in the loop on every outbound message to a homeowner." },
        { carry: "AI drafts the follow-up from your call notes; you check the facts, fix the tone, and send it yourself, one person to one person." },
        { trap: "Letting a tool auto-send AI-written texts to a list of homeowners who never agreed to receive marketing texts. That is an automated marketing message without consent, and the penalties are per message." },
        { sources: [
          { t: "Telephone Consumer Protection Act of 1991, overview (statutory damages and consent)", u: "https://en.wikipedia.org/wiki/Telephone_Consumer_Protection_Act_of_1991" },
          { t: "47 CFR 64.1200, Delivery restrictions (FCC TCPA rules)", u: "https://www.law.cornell.edu/cfr/text/47/64.1200" }
        ] }
      ]
    },
    {
      id: "m14-05",
      title: "Role-Play: Practice Objections with a Skeptical Seller",
      minutes: 9,
      blocks: [
        { h: "Why role-play works", p: "The first time you hear 'that offer is insulting' should not be on a real call. Role-play lets you hear objections a hundred times in a safe room until your response is calm and automatic. AI is a patient sparring partner. It will play the same seller as many times as you want, change personalities on request, and critique you afterward." },
        { h: "The role-play prompt", p: "Copy this. 'You are playing a homeowner named Pat. Pat inherited a house that needs work, is tired of dealing with it, but is suspicious of investors and thinks the house is worth more than it is. Pat is not rude but is skeptical and asks hard questions. I am the investor calling Pat. Stay in character as Pat no matter what. Do not help me or break character unless I type STOP. When I type STOP, give me honest feedback on three things I did well and three things I should fix, and then score my call from one to ten. Start the call: I have just said hello and introduced myself.'" },
        { formula: "Role + personality + goal + 'stay in character until STOP' + feedback request = a repeatable practice partner" },
        { h: "Vary the seller", p: "Change one variable each session. Make Pat angry about a low offer. Make Pat an elderly owner who talks slowly and changes subjects. Make Pat a landlord who knows the numbers and wants to negotiate the assignment fee. Make Pat insist on talking to a lawyer first. Ask for the top five objections investors hear in pre-foreclosure situations and drill them one at a time. The goal is not to win the fake call. The goal is to notice where you freeze, rush, or over-talk." },
        { h: "What to listen for in the feedback", p: "Did you ask about the seller's situation before talking about price? Did you acknowledge the objection before answering it? Did you give a reason for your number? Did you leave the door open at the end? Ask the AI to grade you on those four things specifically, because generic praise is useless." },
        { carry: "Run one AI role-play a day. Same scenario until you score an eight, then change one variable." },
        { trap: "Treating the AI seller's reaction as proof your script works. Real sellers are less predictable. Role-play builds calm, not certainty." }
      ]
    },
    {
      id: "m14-06",
      title: "Content Production Without Losing Your Voice",
      minutes: 9,
      blocks: [
        { h: "What AI does for content", p: "Video scripts, social posts, newsletters, blog articles, and email sequences are all language work, which is exactly where AI shines. You can turn one recorded ten-minute video into a transcript, then into a newsletter, three short posts, and a list of clip ideas, in a few minutes. The bottleneck shifts from writing to deciding what you want to say and showing up on camera." },
        { h: "The voice problem", p: "Default AI writing has a recognizable flavor: tidy, upbeat, full of three-item lists and phrases like 'unlock' and 'game-changer.' Readers tune it out. Fix it by feeding the AI your own voice. Paste in five things you have written or said that sound like you. Tell it what you never say. Tell it your reading level, sentence length, and whether you use humor. Then ask it to write in that voice and to flag any sentence that sounds like marketing copy." },
        { formula: "Prompt: 'Here are five samples of how I write. Learn the voice. Rewrite the draft below in that voice. Short sentences. No hype words. Flag anything that sounds like an ad.'" },
        { h: "The production line", p: "Record first, in your own words, even if it is rough. Transcribe. Ask the AI to pull out the three strongest ideas and the one story. Have it draft the newsletter from the transcript, not from scratch, so the ideas stay yours. Edit by hand for ten minutes. Then ask for the short posts, each built around one idea, each with a hook in the first line. Finally ask for a list of anything in the piece that is a factual claim, and check each one before publishing." },
        { h: "Compliance in content", p: "If you are a licensed agent, your brokerage and state have advertising rules about names, disclosures, and claims. AI does not know your rules. Add them to the prompt and check the output against them. Never let AI invent testimonials, results, or statistics for marketing. Invented results in advertising are a consumer-protection problem, and the Federal Trade Commission has brought enforcement actions over deceptive AI-related claims since 2024." },
        { carry: "Record in your own words first, then let AI reshape the transcript. Feed it your voice samples and ban hype words. Check every claim before publishing." },
        { trap: "Publishing AI-generated statistics or testimonials. If you cannot point to the source, it does not go in the post." },
        { sources: [
          { t: "FTC Operation AI Comply enforcement sweep (Sept 2024), summarized by Mintz", u: "https://www.mintz.com/insights-center/viewpoints/54731/2024-10-03-ftc-launches-operation-ai-comply-five-enforcement" }
        ] }
      ]
    },
    {
      id: "m14-07",
      title: "AI Inside Your CRM",
      minutes: 8,
      blocks: [
        { h: "What a CRM is and why AI belongs in it", p: "A CRM, or customer relationship management system, is the database where every lead, call, note, and next step lives. Most modern CRMs now include AI features, and the useful ones fall into three buckets: automations, lead scoring, and summaries. You do not need to build these yourself. You need to know what they do so you can turn on the right ones and ignore the rest." },
        { h: "Automations", p: "An automation is a rule: when this happens, do that. When a new lead comes in from a website form, create a task to call within ten minutes. When a lead has not been touched in fourteen days, flag it. When a deal moves to under contract, generate the checklist for closing. AI adds flexibility, such as reading an inbound email and sorting it into the right pipeline stage, or drafting the reply for you to approve. The rule stays the same: AI can draft and suggest, but a person approves anything that goes out to a homeowner." },
        { h: "Lead scoring", p: "Lead scoring ranks your leads by how likely they are to turn into a deal, based on signals such as motivation keywords in notes, how fast they replied, equity position, and how many times you have spoken. It helps you call the right ten people first on a day when you only have an hour. Treat the score as a suggestion. A score is only as good as the notes you typed in, and a seller the model rates low may be the one who calls you back in month six." },
        { h: "Summaries", p: "Before a call, an AI summary of the lead's history saves you reading six months of notes. After a call, a recorded call can be transcribed and summarized into the CRM automatically, with the next action pulled out. This is the single feature most likely to fix your follow-up, because the note gets written even on the days you are exhausted. Check your state's rules on recording calls and tell the other party when you record." },
        { carry: "Three CRM AI features worth turning on: automations with human approval, lead scoring as a suggestion, and call summaries that set the next action." },
        { trap: "Letting an automation send messages without a review step. Every outbound homeowner message passes through a person." }
      ]
    },
    {
      id: "m14-08",
      title: "AI Voice Agents, Texting, and the Law",
      minutes: 12,
      blocks: [
        { h: "The temptation", p: "Vendors now sell AI voice agents that will call a list of homeowners, hold a conversation in a human-sounding voice, and book appointments while you sleep. For a beginner with no time, this sounds like the answer. It is a legal trap, and this lesson explains exactly why." },
        { h: "The FCC ruling of February 2024", p: "On February 8, 2024, the Federal Communications Commission issued a declaratory ruling that calls made with AI-generated or cloned voices count as 'artificial' voices under the Telephone Consumer Protection Act. The TCPA already restricted calls using an artificial or prerecorded voice. The ruling removed any doubt that AI voices are covered. The practical result is that a marketing call made by an AI voice agent requires prior express written consent from the person called, the same as any robocall, and state attorneys general can go after the use of the AI voice itself." },
        { h: "What consent means and what the penalties are", p: "Prior express written consent is a signed written agreement, which can be electronic, in which the person clearly agrees to receive marketing calls or texts from you using automated technology at a specific number. A homeowner on a purchased skip-traced list has given you nothing of the kind. Under the TCPA, a person can sue for up to five hundred dollars per violation, and up to fifteen hundred dollars per violation if the violation was willful. Each call or text is a violation. One campaign of a thousand AI texts to a cold list can be a seven-figure exposure. The FCC and courts treat text messages as calls for this purpose." },
        { h: "What changed in 2025", p: "In December 2023 the FCC adopted a stricter 'one-to-one consent' rule for lead generators. In January 2025 the Eleventh Circuit Court of Appeals vacated that rule in Insurance Marketing Coalition v. FCC, and the FCC later deleted it. That does not loosen anything for you. The underlying requirement of prior express written consent for automated marketing calls and texts still stands. Separately, federal rules prohibit telephone solicitations before eight in the morning or after nine at night in the called party's local time, and the national Do Not Call Registry must be honored." },
        { state: {
          fl: "Florida's Telephone Solicitation Act, section 501.059, requires prior express written consent for sales calls or texts made with an automated system, and section 501.616 bans commercial solicitation calls before eight a.m. or after eight p.m. local time and more than three calls on the same subject to one person in twenty-four hours. Florida also keeps its own do-not-call list. Confirm with a local real estate attorney.",
          oh: "Ohio's Telephone Solicitation Sales Act, Revised Code chapter 4719, requires certain telephone solicitors to register with the Attorney General and post a bond, to identify themselves and the purpose of the call within the first sixty seconds, and not to block caller ID. Check the exemptions in section 4719.01 and confirm with a local real estate attorney."
        } },
        { h: "What you can safely do", p: "Use AI to draft messages a human sends one at a time. Use AI to transcribe and summarize calls you make yourself. Use an AI voice agent only for inbound calls, where the homeowner called you, and even then tell them it is an automated assistant. If a homeowner has filled out a form on your website that clearly discloses they agree to receive automated calls and texts from your company, keep that record forever. If you ever consider an outbound AI calling or texting campaign, have a telecom compliance attorney review it first. Most beginners should simply not do it." },
        { carry: "AI voices are 'artificial' under the TCPA as of the FCC's February 8, 2024 ruling. Marketing robocalls and autotexts need prior express written consent. Penalties are up to $500 per call, $1,500 if willful. Do not let AI cold-call." },
        { trap: "Buying an 'AI cold caller' because the vendor says it is compliant. The liability is yours, not the vendor's. Confirm with a local real estate attorney." },
        { sources: [
          { t: "FCC news release, Feb 8, 2024: AI-generated voices in robocalls are illegal under TCPA", u: "https://docs.fcc.gov/public/attachments/DOC-400393A1.pdf" },
          { t: "Wilson Sonsini: FCC rules AI-generated voices are artificial under the TCPA", u: "https://www.wsgr.com/en/insights/fcc-rules-ai-generated-voices-are-artificial-under-the-tcpa.html" },
          { t: "TCPA statutory damages ($500 / $1,500 per violation)", u: "https://en.wikipedia.org/wiki/Telephone_Consumer_Protection_Act_of_1991" },
          { t: "Womble Bond Dickinson: FCC repeals one-to-one consent rule after Eleventh Circuit decision (2025)", u: "https://www.womblebonddickinson.com/us/insights/blogs/fcc-repeals-one-one-consent-rule-following-eleventh-circuit-decision" },
          { t: "47 CFR 64.1200 (calling hours, Do Not Call, consent)", u: "https://www.law.cornell.edu/cfr/text/47/64.1200" },
          { t: "Florida Statutes 501.059 (2025)", u: "https://flsenate.gov/Laws/Statutes/2025/501.059" },
          { t: "Florida Statutes 501.616 (calling hours, three-call limit)", u: "https://www.leg.state.fl.us/statutes/index.cfm?App_mode=Display_Statute&URL=0500-0599%2F0501%2FSections%2F0501.616.html" },
          { t: "Ohio Attorney General: Telemarketing and Do Not Call Registry (ORC 4719)", u: "https://www.ohioattorneygeneral.gov/Business/Services-for-Business/Business-Guide/Telemarketing-and-Do-Not-Call-Registry" }
        ] }
      ]
    },
    {
      id: "m14-09",
      title: "Data Privacy: What Never Goes into the Chat Box",
      minutes: 8,
      blocks: [
        { h: "Where your pasted text goes", p: "When you paste something into an AI tool, it leaves your computer and goes to the company's servers. Depending on the product and your settings, it may be stored, reviewed, or used to train future models. For example, OpenAI's help documentation states that for its consumer products it may use your content to train its models unless you turn that off in settings, while its business and API products do not train on your data by default. Other vendors have their own rules. The point is not which vendor is better. The point is that you must read the terms and set the privacy controls before you paste anything about a real person." },
        { h: "The never-paste list", p: "Social Security numbers. Dates of birth paired with names. Bank account or card numbers. Driver's license numbers. Loan account numbers. Full credit reports. Anything from a tenant application. Medical or hardship details a seller shared with you in confidence. Signed contracts with all parties' personal details still in them. If you need help with a document that contains these, strip or black out the identifiers first, or describe the situation without the specifics." },
        { h: "Why this matters legally and practically", p: "Sellers and tenants hand you sensitive information because they trust you. State privacy and data-breach laws can apply to a small business that collects personal data, and a leak traced to your account is your problem. Practically, a seller who finds out you pasted their divorce details into a chatbot will never do business with you, and will tell people. Protecting their data is also protecting your reputation." },
        { h: "A simple setup", p: "Use a business or team tier of whatever tool you choose, because those tiers typically do not train on your data by default and offer admin controls. Turn off chat history or training where the option exists. Keep a short written data policy for your company: what may be pasted, what may not, and who checks. Use placeholders like Seller A and Property One in prompts. Review the vendor's terms once a year, because they change." },
        { carry: "Never paste SSNs, account numbers, birth dates with names, credit reports, or tenant applications into an AI tool. Use placeholders. Read the terms and turn off training where you can." },
        { trap: "Uploading a signed purchase agreement to 'summarize it.' It carries the seller's full legal name, address, and sometimes bank details. Redact first." },
        { sources: [
          { t: "OpenAI Help: How your data is used to improve model performance", u: "https://help.openai.com/en/articles/5722486-how-your-data-is-used-to-improve-model-performance" },
          { t: "OpenAI Help: Data controls in ChatGPT", u: "https://help.openai.com/en/articles/7730893-data-controls-in-chatgpt" }
        ] }
      ]
    },
    {
      id: "m14-10",
      title: "The Daily AI Stack and the Honest Limits",
      minutes: 10,
      blocks: [
        { h: "A thirty-minute daily routine", p: "Minutes one to five: paste yesterday's call notes and ask for a summary, a list of next actions, and any follow-ups due today. Minutes five to fifteen: draft today's follow-up texts and emails from those notes, then edit and send them yourself. Minutes fifteen to twenty-two: run one deal through the screener prompt and rebuild the math by hand. Minutes twenty-two to twenty-eight: one role-play, one objection. Minutes twenty-eight to thirty: ask the AI to write tomorrow's top three tasks into your task list in plain language. That is the whole stack. It fits before a shift or after one." },
        { h: "The tools you actually need", p: "One general AI assistant you pay for, on a business tier if you can. One transcription tool for calls and videos, which may be built into your phone or CRM. One spreadsheet for the math, because the AI's arithmetic is not your source of truth. A saved note of your ten best prompts. That is it. More tools means more subscriptions, more passwords, and more places your data lives." },
        { h: "Hallucinated statutes and comps", p: "The best-known example of AI invention is Mata v. Avianca, a 2023 federal case in New York in which lawyers filed a brief containing court cases that ChatGPT had made up, complete with fake quotations. The judge fined them five thousand dollars. The same thing happens with real estate: an AI will produce a plausible statute section about wholesaling disclosure, a plausible Fannie Mae guideline, or a plausible comparable sale on a street that exists, none of which are real. If a fact has consequences, you find the primary source yourself: the statute on the state legislature's website, the guideline on the lender's site, the comp in the county record." },
        { h: "Over-reliance", p: "The quieter risk is that AI makes you feel productive without making you better. If you never write a seller message yourself, you never learn the words that work. If you never rebuild the math, you never develop the instinct that tells you a deal is off before you run the numbers. Use AI to speed up work you already understand. For skills you are still building, do the first version yourself, then ask the AI to critique it." },
        { h: "A confirmation habit", p: "End every important AI session with the same question: 'List every factual claim, number, or citation in your answer that I should verify, and tell me where to verify each one.' Then do it. This one habit catches most of the damage." },
        { carry: "Thirty minutes a day: summarize, draft, screen one deal, one role-play, plan tomorrow. Verify every statute, guideline, and comp at the primary source. Do first drafts yourself for skills you are still learning." },
        { trap: "Citing an AI-supplied statute or case to a seller, an attorney, or a lender. Mata v. Avianca ended in sanctions. Find the primary source or do not cite it." },
        { sources: [
          { t: "Mata v. Avianca, Inc. (S.D.N.Y. 2023), sanctions for fabricated AI citations", u: "https://en.wikipedia.org/wiki/Mata_v._Avianca,_Inc." }
        ] }
      ]
    }
  ],
  cards: [
    { id: "m14-c01", type: "term", q: "What is a large language model?", a: "Software trained on huge amounts of text to predict the next words. It produces fluent language whether or not the content is true. Example: it can draft a seller letter in seconds but may invent a statute number." },
    { id: "m14-c02", type: "term", q: "What is an AI hallucination?", a: "A confident, plausible-sounding output that is false, such as a fake court case, a fake comparable sale, or a quote nobody said. It is the main way AI costs investors money." },
    { id: "m14-c03", type: "number", q: "Name the four things AI assistants do well.", a: "Drafting, summarizing, role-play, and structuring messy information. In each, you supply the facts and the AI supplies the shape." },
    { id: "m14-c04", type: "number", q: "Name the three things AI assistants do badly.", a: "Current facts (training data goes stale), math without a tool (arithmetic slips stated confidently), and invented specifics (statutes, comps, quotes)." },
    { id: "m14-c05", type: "term", q: "What are the five parts of a strong prompt?", a: "Role, context, task, format, examples. Example: 'You are an acquisitions manager (role); the seller said X (context); write a check-in text (task); under 40 words (format); here is one I liked (example).'" },
    { id: "m14-c06", type: "trap", q: "You ask the AI for ten things in one prompt. What happens?", a: "You get ten shallow answers. One task per prompt, then follow up with the next task." },
    { id: "m14-c07", type: "scenario", q: "You ask an AI to 'pull comps' for an address and it lists five sales. What do you do?", a: "Treat them as fiction unless the tool is connected to a real data source and shows the records. Pull comps yourself, then paste them in and ask the AI to organize them." },
    { id: "m14-c08", type: "scenario", q: "The AI averages five comps to an ARV of $215,000. Two comps are a mile away and one has a pool. What now?", a: "Drop the three bad comps, average the rest yourself, and lower your maximum offer accordingly. The AI organizes; you judge comparability." },
    { id: "m14-c09", type: "formula", q: "What is the deal-analysis workflow with AI?", a: "Gather facts yourself, paste them in with a screener prompt that shows every calculation, rebuild the math in your spreadsheet, ask the AI to argue against the deal, then decide." },
    { id: "m14-c10", type: "trap", q: "Why can't you trust the AI's deal math?", a: "Models make arithmetic slips in long chains and state wrong answers with full confidence. Always rebuild the numbers in a spreadsheet or calculator before offering." },
    { id: "m14-c11", type: "scenario", q: "You want the AI to stress-test a deal you like. What do you ask?", a: "'Give me the five strongest reasons this is a bad buy.' Forcing the opposite case surfaces risks your excitement hid." },
    { id: "m14-c12", type: "term", q: "What tone rules belong in every seller follow-up prompt?", a: "Plain language, no hype or fake urgency, short sentences, reference a real detail from the last call, end with one easy question, sign with your real name." },
    { id: "m14-c13", type: "trap", q: "A tool offers to auto-send AI-written texts to your skip-traced list. Why is that a problem?", a: "Automated marketing texts need prior express written consent under the TCPA, and a purchased list has none. Each text is a separate violation." },
    { id: "m14-c14", type: "number", q: "What are TCPA statutory damages per violation?", a: "Up to $500 per call or text, and up to $1,500 per violation if willful. A thousand-message campaign can be seven-figure exposure." },
    { id: "m14-c15", type: "number", q: "What did the FCC rule on February 8, 2024?", a: "That AI-generated or cloned voices are 'artificial' voices under the TCPA, so AI voice robocalls need the same prior express written consent as any robocall." },
    { id: "m14-c16", type: "term", q: "What is prior express written consent?", a: "A signed written agreement (electronic counts) in which a person clearly agrees to receive marketing calls or texts from you using automated technology at a specific number." },
    { id: "m14-c17", type: "scenario", q: "A vendor says its AI cold-caller is 'fully TCPA compliant.' Do you buy it?", a: "No. The liability is yours, not the vendor's. Cold outbound AI calls to homeowners who never consented are the exact conduct the 2024 FCC ruling targets. Confirm with a local real estate attorney." },
    { id: "m14-c18", type: "number", q: "What happened to the FCC's one-to-one consent rule?", a: "The Eleventh Circuit vacated it in January 2025 (Insurance Marketing Coalition v. FCC) and the FCC deleted it. The underlying prior-express-written-consent requirement still stands." },
    { id: "m14-c19", type: "number", q: "What are the federal telemarketing quiet hours?", a: "No telephone solicitations before 8 a.m. or after 9 p.m. in the called party's local time, under 47 CFR 64.1200. Some states are stricter." },
    { id: "m14-c20", type: "state", q: "What are the state calling-hour and frequency rules for sales calls?", a: "FL: no commercial solicitation calls before 8 a.m. or after 8 p.m., and no more than three calls on the same subject to one person in 24 hours (s. 501.616). | OH: no state-specific hour rule in ORC 4719; federal 8 a.m. to 9 p.m. applies, plus registration and bond for non-exempt solicitors." },
    { id: "m14-c21", type: "state", q: "What do the states require for automated sales calls and texts?", a: "FL: prior express written consent under s. 501.059, plus Florida's own do-not-call list. | OH: registration with the Attorney General and a bond for non-exempt solicitors under ORC 4719, identify yourself within 60 seconds, never block caller ID." },
    { id: "m14-c22", type: "scenario", q: "A homeowner called your number and an AI assistant answered and booked the appointment. Is that okay?", a: "Inbound is far safer than outbound, since the homeowner initiated. Still disclose that it is an automated assistant and keep a human reviewing the booking." },
    { id: "m14-c23", type: "term", q: "What is AI role-play and why use it?", a: "Prompting the AI to act as a skeptical seller so you can rehearse objections. It builds calm responses before you hear the objection on a real call." },
    { id: "m14-c24", type: "formula", q: "What are the parts of a good role-play prompt?", a: "Character with a name and personality, their goal and suspicion level, 'stay in character until I type STOP,' then a request for three strengths, three fixes, and a score." },
    { id: "m14-c25", type: "scenario", q: "You scored an 8 on the same role-play three times in a row. What next?", a: "Change one variable: make the seller angry, elderly, a numbers-savvy landlord, or someone who wants a lawyer first. Keep one variable changing at a time." },
    { id: "m14-c26", type: "trap", q: "What is the danger of winning the fake call?", a: "Believing your script is proven. Real sellers are less predictable. Role-play builds composure, not certainty." },
    { id: "m14-c27", type: "number", q: "What four things should the AI grade you on after a practice call?", a: "Did you ask about the situation before price, acknowledge the objection before answering, give a reason for your number, and leave the door open." },
    { id: "m14-c28", type: "term", q: "What is the 'voice problem' with AI content?", a: "Default AI writing is tidy, upbeat, and full of hype words and three-item lists; readers tune it out. Fix it by feeding your own writing samples and banning hype words." },
    { id: "m14-c29", type: "formula", q: "What is the content production line with AI?", a: "Record in your own words, transcribe, have AI pull the three strongest ideas, draft the newsletter from the transcript, hand-edit ten minutes, spin out short posts, then verify every factual claim." },
    { id: "m14-c30", type: "trap", q: "The AI wrote a post saying 'investors in your area saw 14% returns last year.' Can you publish it?", a: "No. You cannot source it. Invented statistics and testimonials in advertising are a consumer-protection problem; the FTC has pursued deceptive AI-related claims since 2024." },
    { id: "m14-c31", type: "scenario", q: "You are a licensed agent and AI drafted a social post. What extra check applies?", a: "Your state and brokerage advertising rules on names, disclosures, and claims. AI does not know them; add them to the prompt and check the output against them." },
    { id: "m14-c32", type: "term", q: "What is a CRM?", a: "Customer relationship management software: the database holding every lead, call, note, and next action. Example: a seller lead with six calls logged and a follow-up due Friday." },
    { id: "m14-c33", type: "term", q: "What is a CRM automation?", a: "A rule: when this happens, do that. Example: a new web lead triggers a call-within-ten-minutes task; fourteen days of silence triggers a flag." },
    { id: "m14-c34", type: "term", q: "What is lead scoring?", a: "An AI or rules-based rank of leads by likelihood to close, using signals like motivation keywords, reply speed, and equity. Treat it as a suggestion for who to call first, not a verdict." },
    { id: "m14-c35", type: "trap", q: "What is the problem with trusting a low lead score?", a: "The score is only as good as the notes you typed. The seller the model rated low may be the one who calls back in month six. Keep following up." },
    { id: "m14-c36", type: "scenario", q: "You are exhausted after a shift and skip writing call notes. What CRM AI feature fixes this?", a: "Call recording with automatic transcription and summary that writes the note and sets the next action. Disclose recording and follow your state's call-recording rules." },
    { id: "m14-c37", type: "trap", q: "What is the one rule for every CRM automation that touches a homeowner?", a: "A human approves anything that goes out. AI drafts and suggests; a person sends." },
    { id: "m14-c38", type: "number", q: "List the never-paste items for AI tools.", a: "Social Security numbers, birth dates with names, bank or card numbers, driver's license numbers, loan account numbers, credit reports, tenant applications, and confidential hardship details." },
    { id: "m14-c39", type: "scenario", q: "You want help summarizing a signed purchase agreement. What do you do first?", a: "Redact names, addresses, account numbers, and signatures, or describe the terms using placeholders like Seller A and Property One." },
    { id: "m14-c40", type: "trap", q: "Why does a consumer AI account differ from a business tier for privacy?", a: "Consumer tiers may use your content to train models by default unless you opt out; business and API tiers at major vendors typically do not. Read the terms and set the controls." },
    { id: "m14-c41", type: "term", q: "What is a placeholder prompt?", a: "Describing a situation with stand-ins such as Seller A and Property One instead of real identifiers, so the AI helps without receiving personal data." },
    { id: "m14-c42", type: "number", q: "Describe the thirty-minute daily AI routine.", a: "Five minutes summarizing yesterday's notes, ten drafting follow-ups, seven screening one deal and rebuilding the math, six on one role-play, two planning tomorrow's top three." },
    { id: "m14-c43", type: "number", q: "What tools make up a minimal AI stack?", a: "One paid general assistant on a business tier, one transcription tool, one spreadsheet for math, and a saved note of your ten best prompts." },
    { id: "m14-c44", type: "number", q: "What was Mata v. Avianca?", a: "A 2023 federal case in New York where lawyers filed a brief citing cases ChatGPT invented, with fake quotes. The judge fined them $5,000. Verify every citation at the source." },
    { id: "m14-c45", type: "scenario", q: "The AI cites 'Section 475.XX' as your state's wholesaling disclosure rule. What do you do?", a: "Look it up on the state legislature's website yourself. If it is not there, it does not exist. Never repeat an AI-supplied statute to a seller, lender, or attorney." },
    { id: "m14-c46", type: "trap", q: "What is over-reliance and how do you avoid it?", a: "Feeling productive without getting better. Do first drafts yourself for skills you are still learning, then have the AI critique. Use AI to speed up work you already understand." },
    { id: "m14-c47", type: "formula", q: "What is the confirmation habit at the end of an AI session?", a: "Ask: 'List every factual claim, number, or citation I should verify, and where to verify each.' Then check each one." },
    { id: "m14-c48", type: "scenario", q: "A seller shared her divorce and medical details on a call. You want AI help drafting a compassionate follow-up. What do you paste?", a: "Only the business facts and the tone you want, using a placeholder for her name. Leave the confidential details out of the chat box entirely." },
    { id: "m14-c49", type: "term", q: "What is a deal screener prompt?", a: "A saved prompt that gives the AI your deal facts and refinance terms and asks for a structured summary showing every calculation step plus the three biggest risks." },
    { id: "m14-c50", type: "scenario", q: "You have one hour and forty leads. How does CRM AI help?", a: "Use lead scoring to pick the top ten to call, read AI summaries of each before dialing, and let call transcription write the notes and next actions afterward." },
    { id: "m14-c51", type: "trap", q: "Why should you write three versions of a follow-up text instead of one?", a: "The first AI draft is often generic. Three tones give you a real choice and make it easier to spot the one that sounds like you." },
    { id: "m14-c52", type: "number", q: "How often should you re-read your AI vendor's terms?", a: "At least once a year, and whenever you get a terms-update notice. Training and retention policies change." },
    { id: "m14-c53", type: "scenario", q: "A homeowner filled out your website form agreeing to automated texts. A year later you want to text them. What matters?", a: "That you kept the consent record, including the exact disclosure language, date, and number. Keep it forever. Without it you cannot prove consent." },
    { id: "m14-c54", type: "term", q: "What does 'artificial voice' mean under the TCPA after 2024?", a: "Any non-human voice on a call, now explicitly including AI-generated and cloned voices, per the FCC's February 2024 declaratory ruling." }
  ],
  quiz: [
    { id: "m14-q01", q: "Which task is an AI assistant LEAST reliable at without extra tools?", opts: ["Summarizing a long inspection report", "Drafting a follow-up email", "Stating this month's refinance rates", "Playing a skeptical seller"], correct: 2, explain: "Current facts like rates come from training data that may be stale. Drafting, summarizing, and role-play are language tasks AI handles well." },
    { id: "m14-q02", q: "What are the five parts of a strong prompt?", opts: ["Greeting, question, thanks, signature, date", "Role, context, task, format, examples", "Price, ARV, rehab, rent, rate", "Who, what, when, where, why"], correct: 1, explain: "Role, context, task, format, and examples turn a vague request into a work order the AI can execute." },
    { id: "m14-q03", q: "An AI returns five comps for an address you typed in. Which statement is true?", opts: ["They are reliable if the addresses exist", "They can be used as your ARV basis", "They may be invented unless the tool is connected to real data and shows records", "They are more accurate than MLS data"], correct: 2, explain: "Models have no live market access unless connected to a data source. Pull comps yourself and have the AI organize them." },
    { id: "m14-q04", q: "After the AI lays out a deal with all calculations shown, what must you do before offering?", opts: ["Rebuild the math in your own spreadsheet", "Ask the AI to double-check itself", "Send the summary to the seller", "Nothing, the steps were shown"], correct: 0, explain: "Showing steps helps you audit, but AI arithmetic slips are common. Your spreadsheet is the source of truth." },
    { id: "m14-q05", q: "On what date did the FCC rule that AI-generated voices are 'artificial' under the TCPA?", opts: ["January 15, 2025", "February 8, 2024", "October 1, 2023", "June 22, 2023"], correct: 1, explain: "The FCC's declaratory ruling was issued February 8, 2024. June 22, 2023 was the Mata v. Avianca sanctions decision." },
    { id: "m14-q06", q: "What are TCPA statutory damages per violation, and the willful amount?", opts: ["$100 and $300", "$250 and $750", "$500 and $1,500", "$1,000 and $5,000"], correct: 2, explain: "Up to $500 per violation, trebled to up to $1,500 if willful. Each call or text counts separately." },
    { id: "m14-q07", q: "What consent does a marketing call made by an AI voice agent require?", opts: ["No consent if the number is public","Verbal consent during the call","Consent from the list vendor","Prior express written consent"], correct: 3, explain: "Because AI voices are 'artificial' under the TCPA, marketing calls using them require prior express written consent from the person called." },
    { id: "m14-q08", q: "What happened to the FCC's one-to-one consent rule in 2025?", opts: ["It took effect and expanded to texts","Congress codified it","It was replaced by a two-to-one rule","The Eleventh Circuit vacated it and the FCC deleted it"], correct: 3, explain: "Insurance Marketing Coalition v. FCC vacated the rule in January 2025. The baseline prior-express-written-consent requirement still applies." },
    { id: "m14-q09", q: "Under federal rules, telephone solicitations are prohibited during which hours in the called party's local time?", opts: ["Before 9 a.m. or after 8 p.m.", "Before 8 a.m. or after 9 p.m.", "Before 7 a.m. or after 10 p.m.", "Before 10 a.m. or after 6 p.m."], correct: 1, explain: "47 CFR 64.1200 bars solicitations before 8 a.m. and after 9 p.m. local time. Florida is stricter at 8 p.m." },
    { id: "m14-q10", q: "Florida's section 501.616 limits commercial solicitation calls on the same subject to how many per person in 24 hours?", opts: ["One", "Two", "Three", "Five"], correct: 2, explain: "Florida caps it at three calls on the same subject matter in a 24-hour period, regardless of which number you call from." },
    { id: "m14-q11", q: "Ohio's Telephone Solicitation Sales Act (ORC 4719) requires non-exempt solicitors to do what?", opts: ["Register with the Attorney General and post a bond", "Obtain a real estate license", "Call only on weekdays", "Use a local area code"], correct: 0, explain: "Ohio requires registration and a bond for non-exempt telephone solicitors, plus identification within 60 seconds and no caller-ID blocking." },
    { id: "m14-q12", q: "What is the safest use of an AI voice agent for a beginner?", opts: ["Outbound calls to skip-traced lists", "Outbound calls to expired listings", "Inbound calls where the homeowner called you, with disclosure", "Leaving ringless voicemails"], correct: 2, explain: "Inbound avoids the unsolicited-call problem because the homeowner initiated. Still disclose it is automated and keep a human reviewing." },
    { id: "m14-q13", q: "Which item should NEVER be pasted into an AI tool?", opts: ["A list of neighborhood comps","Your own draft newsletter","Your contractor's scope of work","A seller's Social Security number"], correct: 3, explain: "SSNs, account numbers, birth dates with names, credit reports, and tenant applications stay out. Use placeholders instead." },
    { id: "m14-q14", q: "According to OpenAI's help documentation, which is true by default?", opts: ["Consumer and business data are both used for training", "Neither consumer nor business data is ever used", "Consumer content may be used for training unless you opt out; business and API data are not", "Only business data is used for training"], correct: 2, explain: "OpenAI states consumer products may train on content unless the user disables it, while business, enterprise, and API data are not used by default. Other vendors differ; read the terms." },
    { id: "m14-q15", q: "What was the outcome of Mata v. Avianca (2023)?", opts: ["The lawyers won on appeal", "The lawyers were fined $5,000 for citing fabricated AI-generated cases", "ChatGPT was banned from courts", "The case was dismissed without penalty"], correct: 1, explain: "The judge sanctioned the attorneys $5,000 for submitting fake cases with fake quotes generated by ChatGPT." },
    { id: "m14-q16", q: "What is the correct rule for CRM automations that send messages to homeowners?", opts: ["A human reviews and approves before anything goes out","Let them run unattended to save time","Only send on weekends","Use them only for buyers"], correct: 0, explain: "AI drafts and suggests. A person approves every outbound homeowner message, for accuracy and for compliance." },
    { id: "m14-q17", q: "How should you treat an AI lead score?", opts: ["As a final verdict on the lead","As proof of motivation","As a reason to delete low scores","As a suggestion for who to call first"], correct: 3, explain: "Scores reflect the notes you typed and can miss the seller who calls back in month six. Use them to prioritize, not to prune." },
    { id: "m14-q18", q: "What is the best fix for AI content that 'sounds like AI'?", opts: ["Ask for more exclamation points","Add more bullet lists","Make it longer","Feed it samples of your own writing and ban hype words"], correct: 3, explain: "Give the model your voice samples, your banned words, and your sentence style, then have it flag anything that reads like an ad." },
    { id: "m14-q19", q: "In the role-play prompt, why do you include 'stay in character until I type STOP'?", opts: ["To make the AI friendlier", "To prevent it from coaching you mid-call and breaking the practice", "To shorten the session", "To comply with the TCPA"], correct: 1, explain: "Without that instruction the model tends to drop character and help, which defeats the purpose of pressure practice." },
    { id: "m14-q20", q: "What should you ask at the end of every important AI session?", opts: ["'List every factual claim, number, or citation I should verify and where'","'Are you sure?'","'Make it sound more professional'","'Summarize in one word'"], correct: 0, explain: "Asking for a verification list surfaces every checkable claim so you can confirm them at primary sources." },
    { id: "m14-q21", q: "In the thirty-minute routine, how much time goes to screening one deal and rebuilding the math?", opts: ["About two minutes", "About seven minutes", "About fifteen minutes", "The full thirty"], correct: 1, explain: "Minutes fifteen to twenty-two: paste the facts, get the structured summary, and redo the numbers yourself." },
    { id: "m14-q22", q: "Which is the best description of AI's proper role in your business?", opts: ["Decision maker", "Compliance officer", "Fast junior analyst whose work you verify and sign", "Replacement for a CRM"], correct: 2, explain: "AI shapes language and structure quickly. Judgment, verification, and responsibility stay with you." }
  ],
  drills: [
    "Run one AI role-play cold call today using the skeptical-seller prompt. Type STOP, get your score, and write down the one thing to fix tomorrow.",
    "Save the three copy-ready prompts from lesson two into a note on your phone, with your own blanks filled in.",
    "Take one real or practice deal, run it through the deal screener prompt, then rebuild every number in a spreadsheet. Circle any place the two disagree.",
    "Paste yesterday's call notes into your AI tool and have it draft three follow-up texts in different tones. Edit one by hand and send it yourself.",
    "Open the settings of every AI tool you use and turn off training or chat history where the option exists. Write down which tier you are on.",
    "Write your company's one-paragraph never-paste policy and share it with your partner.",
    "Ask your AI tool to list the top five objections sellers raise in pre-foreclosure, then drill one of them in role-play until you score an eight."
  ]
});
