BIBLE.register({
  id: "m15",
  part: 5,
  title: "The Daily Operator",
  icon: "⏱️",
  summary: "The daily and weekly habits that turn knowledge into a pipeline: the five numbers to track, how to block time around a full-time job, CRM discipline, drills, energy, mindset for slow months, how to pick mentors, and the twelve books worth reading.",
  minutes: 95,
  lessons: [
    {
      id: "m15-01",
      title: "The Five Daily KPIs That Build a Pipeline",
      minutes: 9,
      blocks: [
        { h: "Activity beats study", p: "You can read every module in this app and still have zero deals, because deals come from activity, not knowledge. A KPI is a key performance indicator: a number you track because moving it moves the business. Most beginners track the wrong thing, which is deals closed. Closed deals are a result that lags your effort by weeks or months. If you only watch results, you will quit during the lag. You need to watch the inputs you control today." },
        { h: "The five numbers", p: "One: new leads. How many new potential sellers entered your system today, from any source. Two: conversations. How many real two-way exchanges you had with a decision maker, by phone, text, or in person. A voicemail does not count. Three: appointments. How many times you set a specific date and time to see a property or walk through numbers with a seller. Four: offers. How many written or verbal offers you made. Five: deals analyzed. How many properties you ran through your analysis, even ones you passed on. These five are the whole pipeline. Everything else is a result." },
        { formula: "Leads → Conversations → Appointments → Offers → (Deals). Track the first four daily; count analyzed deals as your practice reps." },
        { h: "Why these five", p: "They are leading indicators, meaning they move before revenue does, and they are fully inside your control. You cannot force a seller to sign, but you can decide to have ten conversations today. Over a few months, your own ratios appear: how many conversations become appointments, how many appointments become offers, how many offers become contracts. Once you know your ratios you can work backward from a goal. If you need one contract a month and one in ten offers gets accepted, you need ten offers, and if one in three appointments produces an offer, you need thirty appointments, and so on." },
        { example: "Your log after sixty days: 400 conversations, 40 appointments, 14 offers, 1 contract. Ratios: ten percent of conversations become appointments, about a third of appointments become offers, one in fourteen offers closes. To get two contracts a month you now know you need roughly 28 offers, 80 appointments, and 800 conversations. That is a plan, not a hope." },
        { carry: "Five daily KPIs: new leads, conversations, appointments, offers, deals analyzed. Log them every day. Your ratios will tell you what to do tomorrow." },
        { trap: "Counting study time as progress. Reading is preparation. Only the five KPIs build a pipeline." }
      ]
    },
    {
      id: "m15-02",
      title: "Time Blocking Around a Full-Time Job",
      minutes: 11,
      blocks: [
        { h: "Why blocking beats to-do lists", p: "A to-do list tells you what to do. A time block tells you when, and protects the slot from everything else. When you are building a business around a job, the job will eat every unprotected hour. Blocking means you decide in advance that six to seven in the morning is prospecting, and nothing short of an emergency moves it. The block is the appointment with your future business." },
        { h: "The core blocks you need each week", p: "Prospecting: live conversations with sellers, which must land when sellers answer phones, usually late morning, late afternoon, and early evening on weekdays, plus Saturday mornings. Follow-up and CRM: writing notes, sending messages, setting next actions, which can happen at any hour. Deal analysis: running numbers, which can happen at any hour. Appointments and property walks: daylight, usually evenings and weekends when you work days. Learning: one module or one chapter, in the dead hours. Weekly review: one hour, same time every week." },
        { h: "Sample plan one: the nine-to-five worker", p: "Monday through Friday, six to six forty-five in the morning: CRM follow-up and deal analysis, because sellers are not awake but your notes and spreadsheets are. Lunch, twelve fifteen to twelve forty-five: prospecting calls from your car or a quiet room, three days a week. Five thirty to seven in the evening: prospecting calls two days a week, property appointments the other days. Eight thirty to nine at night: ten minutes logging KPIs and planning tomorrow, then one lesson. Saturday, nine to one: appointments, property walks, and a prospecting block. Sunday afternoon: one-hour weekly review, then rest. That is roughly twelve to fifteen hours a week, which is enough to build a pipeline if the blocks are real." },
        { h: "Sample plan two: the four-on, four-off rotation", p: "Many shift workers work four long days then have four days off. Treat the two halves of the rotation differently. On work days, aim for the minimum: fifteen minutes of CRM follow-up and KPI logging before or after shift, and one lesson if you have energy. Do not schedule seller calls on twelve-hour days; you will sound tired and you will skip them. On off days, run a full business day: nine to eleven prospecting, eleven to twelve follow-up and analysis, afternoon appointments and property walks, a second prospecting block from four to six, then KPIs and planning. Four off days run this way give you four full business days every eight, which is more focused selling time than most nine-to-five side hustlers get. Put the weekly review on the last off day. Protect the first off day's morning for sleep if you worked nights; a rested caller beats an early one." },
        { h: "Working with a partner", p: "If one of you has daytime hours and the other has off-day blocks, split by clock, not by role. The daytime partner takes callbacks and lender or title conversations during business hours; the shift partner runs long prospecting blocks and property walks on off days. Keep one shared calendar and one shared CRM so no lead falls between you. Agree on one weekly meeting that never moves." },
        { carry: "Block prospecting when sellers answer, follow-up and analysis in dead hours, appointments in daylight, and one fixed weekly review. Twelve to fifteen protected hours a week builds a pipeline." },
        { trap: "Scheduling seller calls on your longest work days. You will skip them and feel guilty. Move calls to off days and do only follow-up on shift days." }
      ]
    },
    {
      id: "m15-03",
      title: "The Morning Routine and the Evening Shutdown",
      minutes: 8,
      blocks: [
        { h: "Keep the morning short", p: "A good morning routine for a business you run on the side is not two hours of journaling. It is a short ritual that puts you in motion. Ten to twenty minutes is plenty. Review the three tasks you wrote last night. Open the CRM and look at today's due follow-ups. Read one card from this app. Say your opening script out loud once. Then do the first real task before you check email or social media. The point is to start the day with a move on the business, not with other people's requests." },
        { h: "The evening shutdown", p: "The evening shutdown is the more important of the two, because it is where the business actually gets managed. Five steps, ten minutes. One: log the five KPIs for today in your tracker. Two: make sure every conversation from today has a note and a next action in the CRM. Three: write tomorrow's top three tasks on paper or in your task app, with the single most important one first. Four: look at tomorrow's blocks and confirm they are still protected. Five: close the laptop and stop. The shutdown lets your brain stop carrying the business overnight, which is why you will be able to keep doing this for years." },
        { formula: "Shutdown: log KPIs → note + next action on every lead touched → top 3 for tomorrow → confirm blocks → stop." },
        { h: "Why top three and not ten", p: "A list of ten guarantees you end the day feeling behind. Three forces you to decide what matters. The first item should be a KPI-moving activity, usually prospecting or offers, because that is the work you are most tempted to avoid. If you only finish one thing tomorrow, it should be that." },
        { carry: "Morning: review top three, check due follow-ups, one card, say your script, do the first real task. Evening: log KPIs, note and next action on every lead, top three for tomorrow, confirm blocks, stop." },
        { trap: "Ending the day without logging KPIs because 'nothing happened.' Zeros are data. A week of zeros tells you exactly what to fix." }
      ]
    },
    {
      id: "m15-04",
      title: "CRM Discipline: Every Lead, Every Call, Every Note",
      minutes: 9,
      blocks: [
        { h: "The CRM is the business", p: "Your CRM, or customer relationship management system, is the only place your pipeline exists. If a lead is not in it, the lead does not exist. If a call is not logged, it did not happen as far as the business is concerned, because in three weeks you will not remember it. Deals in this business close on the fifth, eighth, or twelfth contact, often months after the first call. A CRM is how a tired person with a job keeps two hundred conversations alive without dropping any." },
        { h: "The four non-negotiables", p: "Every lead goes in the same day it arrives, with source, property address, owner name, phone, and the reason they might sell. Every call, text, and email gets logged, including unanswered attempts, because attempt counts tell you when to stop. Every conversation gets a note in the seller's own words: what they said about timeline, price, condition, and motivation. Every lead has a next action with a date, always, even if that date is six months away. A lead with no next action is a lead you have silently given up on." },
        { formula: "Lead in same day + every touch logged + notes in the seller's words + next action always set" },
        { h: "Writing notes that help future you", p: "Bad note: 'Talked to seller, not ready.' Good note: 'Spoke with owner, inherited from mother in March, two siblings must agree, wants to list with an agent first, said call back in October after the estate is settled, mentioned roof is from the nineties.' The second note lets you open the next call with something that proves you listened. Record facts and the seller's exact phrases, not your opinions." },
        { h: "Pipeline stages", p: "Keep your stages simple: new, contacted, conversation, appointment set, offer made, under contract, closed, dead, and long-term follow-up. Move every lead to the stage that reflects reality during the shutdown. Dead means the property sold to someone else or the owner said never again. Not ready is not dead; not ready is long-term follow-up with a next action date." },
        { carry: "If it is not in the CRM, it does not exist. Every lead in same day, every touch logged, notes in the seller's words, and a dated next action on every single lead." },
        { trap: "Marking a lead dead because the seller said no once. No today is often yes in month six. Set a next action and keep it in long-term follow-up." }
      ]
    },
    {
      id: "m15-05",
      title: "The Weekly Review",
      minutes: 8,
      blocks: [
        { h: "One hour that steers the week", p: "The weekly review is the one meeting your business cannot skip. Same day, same time, one hour, with your partner if you have one. It has three parts: pipeline, numbers, and cuts. Done every week, it keeps you from drifting for a month before noticing that nothing is moving." },
        { h: "Part one: pipeline", p: "Walk every lead in the appointment, offer, and under-contract stages one at a time. For each: what is the next action, who owns it, and when. Then scan the long-term follow-up list for anything due this week. Then check that no lead anywhere in the system is missing a next action. This takes twenty to thirty minutes and it is where deals get rescued." },
        { h: "Part two: numbers", p: "Add up the week's five KPIs and compare them with last week and with your target. Compute your running ratios: conversations to appointments, appointments to offers, offers to contracts. Ask one question: which number is the bottleneck? If conversations are low, your problem is prospecting time or lead sources. If conversations are high but appointments are low, your problem is your script. If appointments are high but offers are low, you are not making offers, which is usually fear. If offers are high but nothing is accepted, your offers may be too low or you are talking to unmotivated sellers." },
        { h: "Part three: what to cut", p: "Ask what you did this week that moved no KPI. Hours on a logo, a website rebuild, a new tool, or a fourth podcast are the usual answers. Cut one of them next week and give the hour to the bottleneck. Then write next week's three targets and lock the blocks on the calendar." },
        { carry: "Weekly review, one hour, same time: walk the pipeline, total the KPIs and find the bottleneck, cut one thing that moved nothing." },
        { trap: "Skipping the review because the week went badly. A bad week is exactly when the review matters most." }
      ]
    },
    {
      id: "m15-06",
      title: "Skills to Drill Every Day",
      minutes: 8,
      blocks: [
        { h: "Why daily reps", p: "The skills that make money in this business are physical skills as much as mental ones: saying the right words smoothly, running numbers fast enough to answer a seller on the phone, hearing an objection without flinching. Those come from repetition, not reading. Four short drills, ten to fifteen minutes total, keep the edge sharp between real calls." },
        { h: "Drill one: the sixty-second deal analysis", p: "Pull any listing or any lead. Set a timer for one minute. Estimate the after-repair value from what you know, estimate rehab by condition category, apply your maximum allowable offer formula, and state the offer out loud. Then check the real numbers at your leisure. The goal is a fast first pass, not a perfect one. Speed on the phone comes from a thousand of these." },
        { formula: "MAO = (ARV × 0.70) − Rehab (adjust the percentage to your own market and exit)" },
        { h: "Drill two: the two-minute script run", p: "Say your opening, your three discovery questions, and your close out loud, standing up, with a timer. Record it on your phone once a week and listen. You will hear filler words, speed, and places you sound unsure. Fix one per week." },
        { h: "Drill three: one objection", p: "Pick one objection per day: your offer is too low, I want to list with an agent, I need to talk to my spouse, I am not in a hurry, how do I know you are legitimate. Say your response out loud three times. Then run it once in AI role-play if you have time. Rotate through your list so each objection comes up weekly." },
        { h: "Drill four: one new term", p: "Open one card in this app and read it aloud, then explain it in your own words as if to a seller. Terms you can explain plainly are terms you understand. One a day is three hundred and sixty-five a year." },
        { carry: "Daily drills, fifteen minutes: one sixty-second deal analysis, one two-minute script run, one objection out loud three times, one term explained plainly." },
        { trap: "Drilling only when you feel ready. The drill is what makes you ready. Do it before the real calls, not instead of them." }
      ]
    },
    {
      id: "m15-07",
      title: "Energy, Sleep, and Health as Business Inputs",
      minutes: 7,
      blocks: [
        { h: "You are the main asset", p: "In a two-person business built around a day job, the limiting resource is not money or leads. It is your attention and your energy after the job has taken its share. That makes sleep, food, movement, and recovery business decisions, not personal ones. This lesson is practical, not medical. Talk to a doctor about anything health-related. Here, the question is only how to protect the energy that makes the calls." },
        { h: "Practical rules that operators use", p: "Protect sleep like a time block, because a tired caller sounds tired and sellers hear it. If you work nights or rotating shifts, give yourself a real recovery window after a run of shifts before scheduling calls; a half day of sleep buys a full day of good work. Eat before prospecting blocks so hunger does not shorten them. Move your body a little before calls; a ten-minute walk is enough to change how you sound. Keep water on the desk. Drink less caffeine late in the day if it is costing you sleep. None of this is a program; it is removing the things that quietly steal your blocks." },
        { h: "Match tasks to energy", p: "Do the hardest thing, usually prospecting or offers, in your best energy window, and do follow-up logging and lesson reading in your worst. For most people the best window is within a few hours of waking after a full sleep. For a night-shift worker that may be two in the afternoon. The clock does not matter. The energy does." },
        { h: "Recovery is part of the plan", p: "Schedule one full day off each week with no business tasks. Burnout in year one is the most common way this business ends, and it rarely comes from working too hard for a week. It comes from never stopping. The weekly off day and the evening shutdown are what let you run for the years this takes." },
        { carry: "Sleep is a time block. Do prospecting in your best energy window, logging and reading in your worst. One full day off every week. Confirm anything health-related with a doctor." },
        { trap: "Grinding through a run of night shifts and then making seller calls on no sleep. You burn the lead and your confidence. Sleep first, call second." }
      ]
    },
    {
      id: "m15-08",
      title: "Doubt, Slow Months, and the Month-Eight Dip",
      minutes: 8,
      blocks: [
        { h: "What slow months are", p: "Every pipeline business has stretches where activity is high and results are zero. You make forty offers and none land. Three deals fall out of contract in a row. A partner gets busy at work. These months are not a sign the business is broken. They are the lag between inputs and results, and they are when most people quit." },
        { h: "The month-eight dip", p: "Operators often describe a pattern: months one through three run on excitement, months four through six produce the first small wins, and then somewhere around month seven to nine the novelty is gone, the first wins have been spent, the pace of learning slows, and nothing seems to move. Call it the month-eight dip. It is not a statistic; it is a pattern worth expecting so it does not surprise you. The people who come out the other side are almost always the ones who kept logging KPIs through it." },
        { h: "What to do in a dip", p: "First, go back to the numbers. If your five KPIs are still at target, the dip is a lag and the fix is patience. If the KPIs have slipped, which is common because discouragement quietly shrinks your blocks, the fix is to rebuild the blocks, not to change strategy. Second, shrink the goal to the next action: one call, one offer, one analysis. Third, talk to someone who is further along; a ten-minute conversation with a working investor resets perspective faster than anything. Fourth, do not buy a new course or switch strategies in a dip. Changing strategy restarts the clock on your ratios." },
        { h: "Doubt is information, not a verdict", p: "When you doubt yourself, ask what specifically you doubt. If it is a skill, drill it. If it is a number, go check your ratios. If it is whether the strategy works at all, read the module on deal math again and run one more analysis. Vague doubt is paralyzing; specific doubt is a to-do list." },
        { carry: "Expect a dip around months seven to nine. In a dip: check the KPIs, rebuild the blocks, shrink to the next action, talk to someone further along, and do not switch strategies." },
        { trap: "Buying a new course or chasing a new strategy in month eight. It feels like progress and it resets your ratios to zero." }
      ]
    },
    {
      id: "m15-09",
      title: "Mentors, Communities, and How Not to Get Fleeced",
      minutes: 9,
      blocks: [
        { h: "Why you need people", p: "You cannot see your own blind spots, and a book cannot look at your specific deal. A mentor, a coach, or a working community compresses years into months by telling you which of your worries matter. The trouble is that real estate education is a huge industry that sells hope, and a beginner cannot easily tell a real operator from a performer." },
        { h: "What good looks like", p: "A worthwhile mentor or program still does deals today, in a market like yours, and will show you specifics when asked: a settlement statement, an actual rehab budget, a real lease. The teaching is about process and numbers more than about lifestyle. The price is clear up front and it is a price you could recover with one deal. The community has members who are a year ahead of you, talking about problems, not just wins. You are encouraged to take action between sessions and to report your KPIs. Free local meetups and investor associations are a good first community and cost nothing." },
        { h: "Red flags", p: "A free webinar that ends in a countdown timer and a price that drops if you buy right now. A story about the mentor's results with no documents. Pressure to put tuition on a credit card or to borrow against your home. Prices that jump from a few hundred to tens of thousands with 'inner circle' tiers. Claims of guaranteed deals or returns. Students who only talk about the mentor, not about their own deals. Any program that discourages you from asking an attorney or an accountant. Testimonials you cannot verify. Teaching that is mostly mindset with little math." },
        { h: "How to choose", p: "Before paying anyone, go to a free local investor meetup three times and ask working investors what they actually used. Ask any paid program for the name of a current student in a market like yours and call them. Read the refund terms before the sales call. Set a ceiling for education spending in year one and do not cross it; a reasonable rule is to spend less on courses than you have set aside for earnest money and inspections. Spend the difference on marketing that produces leads. Deals teach faster than courses." },
        { carry: "Pick mentors who still do deals, show documents, teach process and math, price clearly, and have students a year ahead of you. Red flags: countdown timers, guaranteed returns, credit-card tuition, no documents." },
        { trap: "Paying for the fourth course before you have made your fortieth offer. Education is not the bottleneck. Offers are." }
      ]
    },
    {
      id: "m15-10",
      title: "The Reading List and the Mentor Frameworks",
      minutes: 12,
      blocks: [
        { h: "Twelve books, one takeaway each", p: "One: Rich Dad Poor Dad, by Robert Kiyosaki. Take the distinction between assets that pay you and liabilities that cost you; buy things that put money in your pocket. Two: Buy, Rehab, Rent, Refinance, Repeat, by David M. Greene. The clearest full walkthrough of the BRRRR method and why buying below value and forcing appreciation lets you recycle the same capital. Three: The Book on Rental Property Investing, by Brandon Turner. Take the discipline of analyzing rentals on cash flow and the habit of running the numbers on everything. Four: The Book on Investing in Real Estate with No (and Low) Money Down, by Brandon Turner. Take the menu of creative structures, partnerships, and private money, and the warning that low money down means higher risk. Five: The Book on Estimating Rehab Costs, by J Scott. Take the method of walking a house system by system and building a line-item budget before you offer. Six: The Millionaire Real Estate Investor, by Gary Keller with Dave Jenks and Jay Papasan. Take the models: criteria for what you buy, terms for how you buy, and a network of people who feed you deals." },
        { h: "Books seven through twelve", p: "Seven: Never Split the Difference, by Chris Voss with Tahl Raz. Take tactical empathy, labeling what the other person feels, and calibrated questions that start with how or what. Eight: Atomic Habits, by James Clear. Take the idea that systems beat goals and that tiny daily habits compound; your KPI log is exactly this. Nine: Wealth without Cash, by Pace Morby. Take the mechanics of subject-to and seller-financing deals and the idea that a seller's problem, not their equity, defines the deal. Ten: Long-Distance Real Estate Investing, by David M. Greene. Take the core team concept and the systems that let you buy where the numbers work rather than where you live. Eleven: The E-Myth Revisited, by Michael E. Gerber. Take the shift from working in the business to working on it, and the habit of writing down every process. Twelve: Who Not How, by Dan Sullivan with Benjamin Hardy. Take the question to ask when stuck: not how do I do this, but who can do this, which is the mindset that lets a two-person business grow." },
        { h: "Mentor frameworks in plain words", p: "These are ideas as this curriculum understands them, not quotations. Kiyosaki's core idea is that financial education, not income, separates the rich from everyone else, and that the goal is cash-flowing assets that work while you sleep; his Cashflow Quadrant sorts people into employee, self-employed, business owner, and investor, and argues for moving right. Pace Morby's core idea is creative finance: many sellers have problems that cash cannot solve but terms can, so learn subject-to, seller financing, and novations and lead with the seller's situation. Brandon Turner's core idea is that ordinary people build wealth one rental at a time by running conservative numbers and buying consistently, and that the number of doors you own can grow in stages as skills and capital compound." },
        { h: "Two more frameworks", p: "Ryan Pineda's core idea, as laid out in his book Flip Your Future, is that flipping can replace a job income quickly if you treat it as a business with marketing, systems, and a team, and that a first business funds the next ones. David Greene's core idea is that BRRRR lets you recycle the same capital repeatedly, that you should build a core team of agent, lender, contractor, and property manager, and that where you invest should be decided by the numbers, not by where you happen to live. Notice the overlap: every one of these frameworks says run the numbers, build systems, build a team, and keep buying. The disagreements are about which vehicle, not about the discipline." },
        { h: "How to read as an operator", p: "One book a month is enough. Read with a pen and write three actions, not twenty highlights. Apply one action within a week or the book was entertainment. Do not read a second book on the same topic until you have made offers using the first. And remember the hierarchy: offers beat reading, reading beats scrolling." },
        { carry: "Twelve books: Kiyosaki, Greene (two), Turner (two), J Scott, Keller, Voss, Clear, Morby, Gerber, Sullivan. One a month, three actions each. Every mentor framework agrees: run the numbers, build systems, build a team, keep buying." },
        { trap: "Collecting books and gurus instead of making offers. If you have read five investing books and made zero offers, stop reading for thirty days." },
        { sources: [
          { t: "Buy, Rehab, Rent, Refinance, Repeat, David M. Greene (BiggerPockets Publishing)", u: "https://www.amazon.com/Buy-Rehab-Rent-Refinance-Repeat/dp/1947200089" },
          { t: "The Book on Rental Property Investing, Brandon Turner", u: "https://www.amazon.com/Book-Rental-Property-Investing-Intelligent/dp/099071179X" },
          { t: "The Book on Investing in Real Estate with No (and Low) Money Down, Brandon Turner", u: "https://www.amazon.com/Book-Investing-Real-Estate-Money/dp/B00PL16ASY" },
          { t: "The Book on Estimating Rehab Costs, J Scott", u: "https://store.biggerpockets.com/products/the-book-on-estimating-rehab-costs" },
          { t: "The Millionaire Real Estate Investor, Gary Keller, Dave Jenks, Jay Papasan", u: "https://www.amazon.com/Millionaire-Real-Estate-Investor/dp/0071446370" },
          { t: "Never Split the Difference, Chris Voss and Tahl Raz", u: "https://www.amazon.com/Never-Split-Difference-Negotiating-Depended/dp/0062407805" },
          { t: "Wealth without Cash, Pace Morby", u: "https://www.amazon.com/Wealth-without-Cash-Supercharge-Subject/dp/1947200887" },
          { t: "Long-Distance Real Estate Investing, David Greene", u: "https://www.amazon.com/Long-Distance-Real-Estate-Investing-State/dp/0997584750" },
          { t: "Flip Your Future, Ryan Pineda", u: "https://www.amazon.com/Flip-Your-Future-Figures-Flipping/dp/1543932460" },
          { t: "Who Not How, Dan Sullivan with Benjamin Hardy", u: "https://www.amazon.com/Who-Not-How-Accelerating-Teamwork/dp/1401962327" },
          { t: "Traction and related business-systems reading, Gino Wickman (optional)", u: "https://www.amazon.com/Traction-Get-Grip-Your-Business-ebook/dp/B007QWLLV2" },
          { t: "Rich Dad's Cashflow Quadrant, Robert Kiyosaki", u: "https://www.goodreads.com/book/show/81922.Rich_Dad_s_Cashflow_Quadrant" }
        ] }
      ]
    }
  ],
  cards: [
    { id: "m15-c01", type: "term", q: "What is a KPI?", a: "A key performance indicator: a number you track because moving it moves the business. Example: conversations per day, not deals closed." },
    { id: "m15-c02", type: "number", q: "What are the five daily KPIs?", a: "New leads, conversations, appointments, offers, and deals analyzed. The first four are the pipeline; the fifth is your practice reps." },
    { id: "m15-c03", type: "term", q: "What is a leading indicator versus a lagging one?", a: "A leading indicator moves before revenue and is in your control, like offers made. A lagging indicator is a result, like deals closed. Track leading indicators daily." },
    { id: "m15-c04", type: "term", q: "What counts as a conversation?", a: "A real two-way exchange with a decision maker by phone, text, or in person. A voicemail or an unanswered text does not count." },
    { id: "m15-c05", type: "formula", q: "How do you work backward from a deal goal using ratios?", a: "Goal ÷ offer-to-contract ratio = offers needed; offers ÷ appointment-to-offer ratio = appointments; appointments ÷ conversation-to-appointment ratio = conversations. Example: 1 deal at 1-in-10 offers, 1-in-3 appointments, 1-in-10 conversations needs 10 offers, 30 appointments, 300 conversations." },
    { id: "m15-c06", type: "scenario", q: "After 60 days you have 400 conversations, 40 appointments, 14 offers, 1 contract. What do you learn?", a: "Your ratios: 10% conversations to appointments, about a third appointments to offers, 1 in 14 offers close. For two contracts a month you need roughly 28 offers, 80 appointments, 800 conversations." },
    { id: "m15-c07", type: "trap", q: "Why is tracking only closed deals a mistake?", a: "Deals lag effort by weeks or months. Watching only results means you quit during the lag. Track the inputs you control today." },
    { id: "m15-c08", type: "term", q: "What is time blocking?", a: "Deciding in advance when a task happens and protecting that slot. Example: six to seven a.m. is CRM follow-up, and nothing short of an emergency moves it." },
    { id: "m15-c09", type: "number", q: "When should prospecting blocks land?", a: "When sellers answer: late morning, late afternoon, and early evening on weekdays, plus Saturday mornings. Follow-up and analysis can happen at any hour." },
    { id: "m15-c10", type: "scenario", q: "You work nine to five. Where do your prospecting blocks go?", a: "Lunch calls three days a week, two evening blocks from about five thirty to seven, and Saturday morning. Mornings before work go to CRM follow-up and analysis." },
    { id: "m15-c11", type: "scenario", q: "You work four twelve-hour shifts then have four days off. How do you split the business?", a: "Shift days: fifteen minutes of follow-up and KPI logging only. Off days: full business days with two prospecting blocks, appointments, and analysis. Weekly review on the last off day." },
    { id: "m15-c12", type: "trap", q: "What is the mistake shift workers make with seller calls?", a: "Scheduling them on twelve-hour work days. You sound tired and you skip them. Put calls on off days." },
    { id: "m15-c13", type: "number", q: "How many protected hours a week can build a pipeline alongside a job?", a: "Roughly twelve to fifteen, if the blocks are real and most of them are live conversations, not study." },
    { id: "m15-c14", type: "scenario", q: "One partner has daytime hours, the other has off-day blocks. How do you split work?", a: "By clock, not by role: the daytime partner handles callbacks, lenders, and title during business hours; the shift partner runs long prospecting blocks and property walks on off days. One shared CRM, one shared calendar, one fixed weekly meeting." },
    { id: "m15-c15", type: "number", q: "How long should the morning routine be?", a: "Ten to twenty minutes: review top three, check due follow-ups, one card, say your script aloud, do the first real task before email." },
    { id: "m15-c16", type: "formula", q: "What are the five steps of the evening shutdown?", a: "Log the five KPIs, confirm a note and next action on every lead touched, write tomorrow's top three, confirm tomorrow's blocks, stop." },
    { id: "m15-c17", type: "trap", q: "Why write a top three instead of a top ten?", a: "Ten guarantees you end the day behind. Three forces a decision, and the first should be the KPI-moving task you are most tempted to avoid." },
    { id: "m15-c18", type: "trap", q: "Nothing happened today, so you skip logging KPIs. Why is that wrong?", a: "Zeros are data. A week of zeros points at the exact block that collapsed. Log every day." },
    { id: "m15-c19", type: "term", q: "What is the CRM's role in a part-time business?", a: "It is the only place the pipeline exists. It keeps two hundred conversations alive for a tired person with a job. If it is not in the CRM, it does not exist." },
    { id: "m15-c20", type: "number", q: "What are the four CRM non-negotiables?", a: "Lead entered the same day, every touch logged including no-answers, notes in the seller's own words, and a dated next action on every lead." },
    { id: "m15-c21", type: "scenario", q: "Rewrite this note: 'Talked to seller, not ready.'", a: "'Inherited from mother in March, two siblings must agree, wants to try an agent first, call back in October after estate settles, roof from the nineties.' Facts and the seller's phrases, not opinions." },
    { id: "m15-c22", type: "trap", q: "A seller says no. You mark the lead dead. What went wrong?", a: "No today is often yes in month six. Dead means sold or never again. Not ready goes to long-term follow-up with a next action date." },
    { id: "m15-c23", type: "number", q: "Name a simple set of pipeline stages.", a: "New, contacted, conversation, appointment set, offer made, under contract, closed, dead, long-term follow-up." },
    { id: "m15-c24", type: "number", q: "How long is the weekly review and what are its three parts?", a: "One hour, same time each week: walk the pipeline, total the KPIs and find the bottleneck, decide what to cut." },
    { id: "m15-c25", type: "scenario", q: "Conversations are high but appointments are low. What is the bottleneck?", a: "Your script or discovery questions. You are talking to people but not converting the talk into a reason to meet." },
    { id: "m15-c26", type: "scenario", q: "Appointments are high but offers are low. What is the bottleneck?", a: "You are not making offers, which is usually fear of a low number. Commit to leaving every appointment with an offer, even a verbal range." },
    { id: "m15-c27", type: "scenario", q: "Offers are high but none are accepted. What do you check?", a: "Whether you are talking to motivated sellers at all, and whether your offers are so low they never start a negotiation. Review the last ten offers against seller motivation notes." },
    { id: "m15-c28", type: "trap", q: "What is the usual answer to 'what did I do this week that moved no KPI'?", a: "Logo, website rebuild, new tool, another podcast. Cut one next week and give the hour to the bottleneck." },
    { id: "m15-c29", type: "number", q: "What are the four daily drills and how long do they take?", a: "Sixty-second deal analysis, two-minute script run, one objection said aloud three times, one term explained plainly. About fifteen minutes total." },
    { id: "m15-c30", type: "formula", q: "What is the sixty-second deal analysis?", a: "Estimate ARV, estimate rehab by condition category, apply MAO = (ARV × 0.70) − rehab adjusted to your market, state the offer aloud. Check real numbers afterward. Speed first, precision later." },
    { id: "m15-c31", type: "term", q: "What is the two-minute script run?", a: "Saying your opening, three discovery questions, and close out loud with a timer, standing. Record weekly and fix one flaw per week." },
    { id: "m15-c32", type: "number", q: "List five objections to rotate through daily drills.", a: "Your offer is too low; I want to list with an agent; I need to talk to my spouse; I am not in a hurry; how do I know you are legitimate." },
    { id: "m15-c33", type: "trap", q: "Why not wait to drill until you feel ready?", a: "The drill is what makes you ready. Drill before the real calls, never instead of them." },
    { id: "m15-c34", type: "term", q: "Why are sleep and energy business inputs?", a: "In a side business the limiting resource is your attention after the job. A tired caller sounds tired and sellers hear it. Protect sleep like a time block." },
    { id: "m15-c35", type: "scenario", q: "You just finished a run of night shifts. When do you make seller calls?", a: "After a real recovery window. A half day of sleep buys a full day of good calls. Sleep first, call second." },
    { id: "m15-c36", type: "number", q: "How do you match tasks to energy?", a: "Hardest task, usually prospecting or offers, in your best energy window; logging and reading in your worst. Clock does not matter, energy does." },
    { id: "m15-c37", type: "trap", q: "What is the most common way a year-one business ends?", a: "Burnout from never stopping, not from one hard week. Schedule one full day off every week and keep the evening shutdown." },
    { id: "m15-c38", type: "term", q: "What is the month-eight dip?", a: "A commonly described pattern, not a statistic: around months seven to nine the excitement is gone, early wins are spent, and nothing seems to move. Expect it so it does not surprise you." },
    { id: "m15-c39", type: "scenario", q: "You are in a dip and your KPIs are still at target. What is the fix?", a: "Patience. The dip is the lag between inputs and results. Keep logging and keep the blocks." },
    { id: "m15-c40", type: "scenario", q: "You are in a dip and your KPIs have slipped. What is the fix?", a: "Rebuild the blocks, not the strategy. Discouragement quietly shrinks prospecting time. Shrink the goal to the next action and talk to someone further along." },
    { id: "m15-c41", type: "trap", q: "Why not switch strategies in month eight?", a: "Changing vehicles resets your ratios to zero and restarts the clock. Buying a new course in a dip feels like progress and is not." },
    { id: "m15-c42", type: "term", q: "What is the difference between vague doubt and specific doubt?", a: "Vague doubt paralyzes. Specific doubt is a to-do list: doubt a skill, drill it; doubt a number, check your ratios; doubt the strategy, rerun the deal math." },
    { id: "m15-c43", type: "number", q: "What does a worthwhile mentor or program look like?", a: "Still does deals in a market like yours, shows documents when asked, teaches process and math, prices clearly at a level one deal recovers, and has students a year ahead of you talking about problems." },
    { id: "m15-c44", type: "trap", q: "Name five red flags in a real estate education sale.", a: "Countdown-timer pricing, results with no documents, credit-card or home-equity tuition pressure, guaranteed returns, and tiers that jump to tens of thousands." },
    { id: "m15-c45", type: "scenario", q: "A webinar ends with a price that drops if you buy in the next ten minutes. What do you do?", a: "Close the tab. Urgency pricing is a sales tactic, not a sign of value. Go to three free local meetups first and ask working investors what they actually used." },
    { id: "m15-c46", type: "number", q: "What is a reasonable ceiling for education spending in year one?", a: "Less than you have set aside for earnest money and inspections. Spend the difference on marketing that produces leads. Deals teach faster than courses." },
    { id: "m15-c47", type: "scenario", q: "A program will not give you the name of a current student to call. What does that tell you?", a: "Enough to walk away. Verifiable students a year ahead of you are the minimum proof a program is real." },
    { id: "m15-c48", type: "term", q: "What is the one-line takeaway from Rich Dad Poor Dad?", a: "Assets put money in your pocket; liabilities take it out. Buy assets. Kiyosaki's Cashflow Quadrant adds: move from employee and self-employed toward business owner and investor." },
    { id: "m15-c49", type: "term", q: "What is the takeaway from Buy, Rehab, Rent, Refinance, Repeat by David M. Greene?", a: "Buying below value and forcing appreciation through rehab lets you refinance and recycle the same capital into the next property." },
    { id: "m15-c50", type: "term", q: "What are the takeaways from Brandon Turner's two books?", a: "Rental Property Investing: analyze on cash flow and run numbers on everything. No and Low Money Down: a menu of partnerships, private money, and creative structures, with the warning that less money down means more risk." },
    { id: "m15-c51", type: "term", q: "What is the takeaway from The Book on Estimating Rehab Costs by J Scott?", a: "Walk the house system by system and build a line-item budget before you make an offer." },
    { id: "m15-c52", type: "term", q: "What is the takeaway from The Millionaire Real Estate Investor by Gary Keller?", a: "Build models: criteria for what you buy, terms for how you buy, and a network of people who bring you deals." },
    { id: "m15-c53", type: "term", q: "What is the takeaway from Never Split the Difference by Chris Voss?", a: "Tactical empathy: label what the other side feels, and ask calibrated questions starting with how or what instead of arguing." },
    { id: "m15-c54", type: "term", q: "What is the takeaway from Atomic Habits by James Clear?", a: "Systems beat goals and tiny daily habits compound. Your daily KPI log is this idea in practice." },
    { id: "m15-c55", type: "term", q: "What is Pace Morby's core idea in Wealth without Cash?", a: "Creative finance: many sellers have problems cash cannot solve but terms can. Learn subject-to and seller financing and lead with the seller's situation." },
    { id: "m15-c56", type: "term", q: "What are the takeaways from The E-Myth Revisited and Who Not How?", a: "Gerber: work on the business, not just in it, and write down every process. Sullivan and Hardy: when stuck ask who can do this, not how do I do this." },
    { id: "m15-c57", type: "number", q: "What do all the mentor frameworks agree on?", a: "Run the numbers, build systems, build a team, keep buying. They disagree about the vehicle, not the discipline." },
    { id: "m15-c58", type: "trap", q: "You have read five investing books and made zero offers. What now?", a: "Stop reading for thirty days and make offers. Education is not your bottleneck." }
  ],
  quiz: [
    { id: "m15-q01", q: "Which of these is one of the five daily KPIs?", opts: ["Deals closed", "Hours studied", "Conversations with decision makers", "Social media followers"], correct: 2, explain: "The five are new leads, conversations, appointments, offers, and deals analyzed. Deals closed is a lagging result." },
    { id: "m15-q02", q: "Why track leading indicators instead of closed deals?", opts: ["Closed deals are hard to count","Closed deals are not important","Lenders require it","Leading indicators are in your control and move before revenue"], correct: 3, explain: "Results lag effort by months. Inputs you control today keep you working through the lag." },
    { id: "m15-q03", q: "Your ratios: 1 in 10 offers closes, 1 in 3 appointments yields an offer, 1 in 10 conversations yields an appointment. For 2 contracts a month, how many conversations do you need?", opts: ["60", "200", "600", "2,000"], correct: 2, explain: "2 contracts × 10 = 20 offers; 20 × 3 = 60 appointments; 60 × 10 = 600 conversations." },
    { id: "m15-q04", q: "When should prospecting blocks be scheduled?", opts: ["Whenever you have free time","When sellers answer: late morning, late afternoon, early evening, Saturday mornings","Early mornings before 7 a.m.","Late at night after work"], correct: 1, explain: "Prospecting must land when sellers pick up. Follow-up and analysis can fill the odd hours." },
    { id: "m15-q05", q: "On a four-on, four-off rotation, what should business work on shift days be limited to?", opts: ["Fifteen minutes of follow-up and KPI logging","Full prospecting blocks","Property walks","Nothing at all"], correct: 0, explain: "Calls on twelve-hour days get skipped and sound tired. Keep the pipeline alive with brief follow-up and do the heavy work on off days." },
    { id: "m15-q06", q: "Which is NOT one of the five evening shutdown steps?", opts: ["Log the five KPIs", "Set a next action on every lead touched", "Read three new lessons", "Write tomorrow's top three"], correct: 2, explain: "The shutdown is: log KPIs, note and next action on every lead, top three, confirm blocks, stop. Learning happens in its own block." },
    { id: "m15-q07", q: "A lead has no next action set in the CRM. What does that mean?", opts: ["The lead is closed","Nothing; it is fine","The lead is high priority","You have silently given up on it"], correct: 3, explain: "Every lead needs a dated next action, even six months out. No next action means no follow-up will happen." },
    { id: "m15-q08", q: "Which note is written correctly?", opts: ["'Not interested, dead.'", "'Seller seemed nice, maybe later.'", "'Inherited in March, siblings must agree, trying an agent first, call back October, roof from the nineties.'", "'Lowball offer, they hated it.'"], correct: 2, explain: "Good notes record facts and the seller's phrases so the next call proves you listened." },
    { id: "m15-q09", q: "In the weekly review, conversations are high but appointments are low. Where is the bottleneck?", opts: ["Your script and discovery questions","Lead sources","Offer pricing","The CRM software"], correct: 0, explain: "You are reaching people but not converting the talk into a reason to meet. Fix the script." },
    { id: "m15-q10", q: "What is the sixty-second deal analysis for?", opts: ["Replacing a full analysis before closing", "Building speed for a fast first pass on the phone", "Impressing lenders", "Calculating taxes"], correct: 1, explain: "It trains quick estimates so you can respond to a seller in real time. Full numbers come afterward." },
    { id: "m15-q11", q: "Which drill should be recorded weekly and reviewed?", opts: ["The two-minute script run", "The one new term", "The KPI log", "The reading list"], correct: 0, explain: "Recording your script run exposes filler words, pace, and uncertainty so you can fix one thing a week." },
    { id: "m15-q12", q: "You just finished a run of night shifts. What is the right move for seller calls?", opts: ["Call immediately while motivated","Text instead of call","Skip calls for the week","Sleep first, then call in your best energy window"], correct: 3, explain: "A rested caller beats an early one. A half day of sleep buys a full day of good work." },
    { id: "m15-q13", q: "What is the month-eight dip?", opts: ["A commonly described pattern where motivation and results sag around months seven to nine","A documented statistic about failure rates","A tax deadline","A seasonal drop in home prices"], correct: 0, explain: "It is a pattern operators describe, not a statistic. Expecting it keeps it from surprising you." },
    { id: "m15-q14", q: "You are in a dip and your KPIs have slipped. What is the correct fix?", opts: ["Switch to a new strategy", "Buy a new course", "Rebuild your time blocks and shrink to the next action", "Take three months off"], correct: 2, explain: "Discouragement shrinks blocks. Restore the activity rather than restart your ratios with a new vehicle." },
    { id: "m15-q15", q: "Which is a red flag in a real estate education program?", opts: ["Shows settlement statements and real rehab budgets", "Has students a year ahead of you discussing problems", "Pressures you to put tuition on a credit card before a countdown ends", "Encourages you to consult an attorney"], correct: 2, explain: "Urgency pricing and debt-funded tuition are classic warning signs. The other three are marks of a legitimate program." },
    { id: "m15-q16", q: "Who wrote Buy, Rehab, Rent, Refinance, Repeat?", opts: ["Brandon Turner", "David M. Greene", "Gary Keller", "Pace Morby"], correct: 1, explain: "David M. Greene's book is the full walkthrough of the BRRRR method. Brandon Turner wrote The Book on Rental Property Investing." },
    { id: "m15-q17", q: "Which book is the source of 'tactical empathy' and calibrated how/what questions?", opts: ["Atomic Habits", "The E-Myth Revisited", "Who Not How", "Never Split the Difference"], correct: 3, explain: "Chris Voss, with Tahl Raz, teaches labeling emotions and asking calibrated questions in Never Split the Difference." },
    { id: "m15-q18", q: "What is Pace Morby's core idea as summarized in this module?", opts: ["Buy only with cash","Invest only out of state","Flip ten houses a year","Creative finance: solve the seller's problem with terms such as subject-to and seller financing"], correct: 3, explain: "Wealth without Cash centers on subject-to, seller financing, and leading with the seller's situation rather than their equity." },
    { id: "m15-q19", q: "What do Kiyosaki, Morby, Turner, Pineda, and Greene all agree on?", opts: ["Flipping is better than renting", "Never use debt", "Run the numbers, build systems, build a team, keep buying", "Only invest where you live"], correct: 2, explain: "The frameworks differ on vehicle, not on discipline." },
    { id: "m15-q20", q: "You have read five investing books and made zero offers. What does the module recommend?", opts: ["Read five more", "Hire a coach immediately", "Stop reading for thirty days and make offers", "Build a website"], correct: 2, explain: "Education is not the bottleneck at that point. Offers are." }
  ],
  drills: [
    "Create a KPI tracker today with five columns: leads, conversations, appointments, offers, deals analyzed. Log today's numbers even if they are all zero.",
    "Open your calendar and block next week: prospecting when sellers answer, follow-up and analysis in dead hours, one weekly review. Share it with your partner.",
    "Do tonight's evening shutdown: log KPIs, confirm every lead touched has a note and next action, write tomorrow's top three, confirm blocks, stop.",
    "Audit your CRM for leads with no next action. Set a dated next action on every one before you stop today.",
    "Run the four daily drills right now: one sixty-second analysis, one two-minute script run recorded on your phone, one objection aloud three times, one card explained in your own words.",
    "Find one free local real estate investor meetup and put the next meeting on your calendar.",
    "Pick one book from the list, order or borrow it, and write the date you will finish it. Decide the three actions before you start reading."
  ]
});
