BIBLE.register({
  id: "m16",
  part: 6,
  title: "Scaling to a Million",
  icon: "🚀",
  summary: "The road from one deal to a real portfolio: what changes at each stage, how capital actually recycles across ten BRRRRs, when to move from DSCR loans to bank portfolio and commercial debt, 1031 trade-ups, who to hire and in what order, the income-replacement math, and why a million in net worth arrives long before a million in cash flow.",
  minutes: 90,
  lessons: [
    {
      id: "m16-01",
      title: "The Roadmap by Stage",
      minutes: 9,
      blocks: [
        { h: "Scaling is a sequence, not a leap", p: "Nobody goes from zero to thirty doors by trying harder. The business changes shape at predictable points, and the mistake at each point is to keep doing what worked at the last one. This lesson gives you the map so you can tell which stage you are in and what the next stage asks of you." },
        { h: "Deal one: learn", p: "The first deal exists to teach you, not to make you rich. You will overpay for something, the rehab will run over, the refinance will take longer than planned, and you will learn more in those months than in a year of reading. The goal is to finish it without losing money and to write down every mistake. Do not scale anything yet. Do not hire anyone. Do the whole thing yourself so you understand each job before you hand it off." },
        { h: "Deals two through five: systems", p: "Now you have done each task once. Turn each into a written checklist: how you find deals, how you analyze, how you make offers, the rehab scope template, the lender packet, the lease-up process. Every deal in this stage should be done by following the checklist and improving it. Your capital is still the constraint, so this is also where you learn the recycling math in the next lesson and where you may bring in a first private lender. You are still doing most of the work yourself, but by deal five, you should be able to hand any one task to someone else with a document." },
        { h: "Deals six through fifteen: team", p: "Your time becomes the constraint. You cannot cold-call, walk properties, manage three rehabs, and refinance two houses in the same week while holding a job. This is where the hiring order in lesson five begins, starting with a virtual assistant and a property manager. Your job shifts from doing to checking: reviewing the KPIs, approving offers, and talking to lenders. Loan limits also start to bind in this stage, which is what lesson three is about." },
        { h: "Deals sixteen through thirty: portfolio and financing shift", p: "You stop thinking about houses and start thinking about a portfolio. Financing moves from one loan per house to portfolio or commercial loans across several properties. You may trade several houses for a small apartment building using a 1031 exchange. You have a bookkeeper, a property manager, and probably an acquisitions person. Your weekly review looks at occupancy, cash reserves, debt coverage, and refinance dates rather than individual leads. This is the stage where income starts to replace a salary, and it is usually years in." },
        { carry: "Deal 1: learn. Deals 2–5: write the systems. Deals 6–15: build the team. Deals 16–30: think portfolio and shift financing." },
        { trap: "Hiring in the learning stage, or still doing everything yourself in the team stage. Each stage has one constraint. Solve that one." }
      ]
    },
    {
      id: "m16-02",
      title: "Capital Recycling Math Across Ten BRRRRs",
      minutes: 12,
      blocks: [
        { h: "The idea", p: "BRRRR means buy, rehab, rent, refinance, repeat. The whole strategy rests on one move: you buy and fix a property for less than it is worth, refinance based on its new value, and pull your cash back out to do it again. If you get all your cash back, one pot of money can buy an unlimited number of houses, in theory. In practice you leave some cash in each deal, and the lender's rules control how fast you can repeat. Here is the math on one realistic deal, then across ten." },
        { h: "One deal, worked", p: "Assume a house you buy for $100,000 that needs $30,000 of rehab, with $10,000 of closing, holding, and carrying costs, so your all-in cost is $140,000. After the rehab it appraises at $185,000. Your refinance lender will lend seventy-five percent of the appraised value, which is $138,750. Subtract about $4,000 of refinance closing costs and you net $134,750 back. Your cash left in the deal is $140,000 minus $134,750, which is $5,250. Rent is $1,650 a month and after the new payment, taxes, insurance, management, and reserves you clear about $200 a month. The numbers in this example are illustrative, not a forecast of any market." },
        { formula: "Cash left in = All-in cost − (Appraised value × refinance LTV − refinance costs)" },
        { example: "$140,000 − ($185,000 × 0.75 − $4,000) = $140,000 − $134,750 = $5,250 left in the deal. Equity created: $185,000 − $138,750 loan = $46,250." },
        { h: "Ten deals, in prose", p: "Start with $60,000 of your own cash. Each deal needs roughly $45,000 of cash up front for the hard-money down payment, part of the rehab, and holding costs, and returns about $39,750 at refinance, so each deal consumes about $5,250 of your pot. After deal one you have $54,750 left. After deal two, $49,500. After deal three, $44,250. After deal four, $39,000. After deal five, $33,750. After deal six, $28,500. After deal seven, $23,250. After deal eight, $18,000. After deal nine, $12,750. After deal ten, $7,500. Ten houses later you have spent $52,500 of cash and you own ten properties worth $1,850,000 with $1,387,500 of debt, which is $462,500 of equity, plus about $2,000 a month in cash flow. Your original $60,000 became roughly $462,500 of equity. That is the engine." },
        { h: "What slows the engine", p: "Seasoning. Lenders usually will not refinance on the new appraised value until you have owned the property for a period. Since February 2023 Fannie Mae has required that a first mortgage being paid off in a cash-out refinance be at least twelve months old, with limited exceptions. DSCR lenders, which are non-agency lenders who qualify the loan on the property's rent rather than your income, often allow shorter seasoning, commonly a few months, but it varies by lender and must be confirmed in writing before you buy. If each cycle takes six to nine months, one pot of money does one to two deals a year, so ten deals is five to ten years with one pot. Two pots, or a private lender who funds the next purchase while the last one seasons, doubles the pace. Appraisals also come in low sometimes, which means more cash left in. Build a cushion: if your plan only works at $5,000 left in, a $15,000 appraisal miss breaks it." },
        { carry: "Cash left in = all-in − (appraisal × LTV − refi costs). Illustrative deal: $5,250 left in, $46,250 equity created. Ten deals from a $60,000 pot: about $462,500 of equity, if seasoning and appraisals cooperate." },
        { trap: "Planning on a perfect BRRRR where every dollar comes back. Budget for cash left in, a low appraisal, and the seasoning wait, or the second deal stalls for lack of cash." },
        { sources: [
          { t: "Fannie Mae 12-month seasoning for cash-out refinances (SEL-2023-01), summarized by Black, Mann & Graham", u: "https://bmandg.com/fannie-mae-announces-new-12-month-seasoning-requirement-for-cash-out-refinances/" },
          { t: "DSCR vs portfolio bank loan comparison, 2026 (LTV and rate ranges)", u: "https://dscrauthority.com/compare/dscr-vs-portfolio-bank-loan/" }
        ] }
      ]
    },
    {
      id: "m16-03",
      title: "From DSCR to Portfolio and Commercial Loans",
      minutes: 11,
      blocks: [
        { h: "Three kinds of debt", p: "Conventional or agency loans are the thirty-year fixed mortgages sold to Fannie Mae and Freddie Mac; they have the best rates but qualify you on your personal income and cap how many you can have. DSCR loans, which stands for debt service coverage ratio, qualify the loan on the property's rent divided by its payment, ignore your personal income, and are the workhorse for investors with a day job. Portfolio and commercial loans come from banks that keep the loan on their own books, which lets them cover many properties with one loan and make their own rules." },
        { h: "Where agency loans stop", p: "Fannie Mae's Selling Guide limits a borrower with a second-home or investment-property loan to ten financed properties. Many lenders stop earlier in practice. Each conventional loan also requires full income documentation, which gets harder as your tax returns show more depreciation. For most investors with a job, agency loans run out somewhere between four and ten doors." },
        { h: "What DSCR loans give and cost", p: "DSCR lenders typically want a ratio of at least one point zero, meaning rent covers the payment, and price better above one point two. As of mid 2026 one industry comparison put typical DSCR rates around six and one eighth to seven and three eighths percent, purchase loan-to-value of seventy-five to eighty percent, cash-out refinance loan-to-value of seventy to seventy-five percent, thirty-year fixed terms, and three-to-five-year step-down prepayment penalties. There is no hard cap on property count. The cost is a higher rate than agency debt and a prepayment penalty that punishes you for refinancing early. Rates change constantly; verify before you plan." },
        { h: "When to shift to a bank", p: "The signal is either property count or property type. On count, somewhere around ten doors, managing ten separate loans with ten payment dates and ten escrow accounts becomes a job in itself, and a blanket loan, which is one loan secured by several properties, simplifies it. On type, any residential building with five or more units is commercial property and is financed with commercial multifamily debt, not a residential DSCR loan. Commercial lenders underwrite the building's whole income statement and typically want a debt service coverage ratio of about one point two to one point two five." },
        { h: "What community banks want", p: "A community bank is a local bank that keeps your loan on its books. It will want your full financial picture: tax returns, a personal financial statement listing everything you own and owe, and a global cash flow analysis of all your properties together. It will want your deposit accounts, because your operating balances are part of why it lends to you. It will want personal recourse, meaning you personally guarantee the loan. Typical structures as of 2026 are five, seven, or ten year fixed periods on a twenty to twenty-five year amortization, with a balloon or rate reset at the end of the fixed period, rates in the mid six to high seven percent range, and loan-to-value of seventy to eighty percent on purchases and sixty-five to seventy-five percent on cash-out. The trade is flexibility and a relationship in exchange for balloon risk and a guarantee. Start the relationship before you need the loan: open accounts there, meet the commercial lender, and show them your deals as you do them." },
        { carry: "Agency loans cap at 10 financed properties under Fannie Mae. DSCR loans have no count cap but cost more. At about 10 doors or any 5-plus-unit building, move to portfolio or commercial debt from a community bank: full docs, deposits, recourse, 5–10 year fixed with a balloon, DSCR about 1.20–1.25." },
        { trap: "Walking into a community bank cold at deal fifteen. Banks lend to people they know. Open the accounts and meet the lender at deal three." },
        { sources: [
          { t: "Fannie Mae Selling Guide B2-2-03, Multiple Financed Properties (limit of 10)", u: "https://selling-guide.fanniemae.com/sel/b2-2-03/multiple-financed-properties-same-borrower" },
          { t: "DSCR vs portfolio bank loan comparison, 2026", u: "https://dscrauthority.com/compare/dscr-vs-portfolio-bank-loan/" },
          { t: "1–4 unit versus 5-plus unit financing (residential vs commercial)", u: "https://www.instalend.com/blog/loans-for-multifamily-homes-1-4-unit-vs-5-unit-financing" }
        ] }
      ]
    },
    {
      id: "m16-04",
      title: "1031 Trade-Ups: Houses into Small Multifamily",
      minutes: 10,
      blocks: [
        { h: "What a 1031 exchange is", p: "Section 1031 of the Internal Revenue Code lets you sell real property held for business or investment and buy other real property held for business or investment without paying capital gains tax at the time of the sale, as long as you follow the rules. The tax is deferred, not forgiven; your old basis carries into the new property. For a scaling investor this is how five single-family rentals with $50,000 of equity each become one twelve-unit building without losing a chunk of that equity to taxes along the way." },
        { h: "The rules that matter", p: "Both the property you sell and the one you buy must be real property held for investment or business use. Since the 2018 Tax Cuts and Jobs Act, 1031 applies only to real property, not equipment or other personal property, and it does not apply to your personal residence or to property held primarily for sale, which means flips and wholesale contracts do not qualify. You must identify the replacement property in writing within forty-five days of closing on the sale, and you must receive the replacement property within one hundred eighty days of that sale or by your tax return due date including extensions, whichever is earlier. You cannot touch the sale proceeds; a qualified intermediary, which is a neutral third party, must hold the money between the sale and the purchase. To defer all the tax, the replacement must be of equal or greater value and you must replace the debt or add cash; any cash or debt relief you take is called boot and is taxable." },
        { formula: "45 days to identify in writing → 180 days (or tax-return due date, if earlier) to close → qualified intermediary holds the funds → equal or greater value and debt to defer all gain" },
        { example: "You sell four rentals for $800,000 total with $500,000 of loans. Within 45 days you identify a 12-unit building at $1,100,000. You close inside 180 days using the $300,000 of exchange proceeds held by the intermediary plus a new $800,000 commercial loan. Equal or greater value and debt: all gain deferred, reported on IRS Form 8824." },
        { h: "Why it fits the scaling path", p: "Houses are easy to buy and finance early on, but they are slow to manage at scale. A small apartment building has one roof, one lot, one insurance policy, and one loan for twelve rent checks. Trading up through a 1031 lets you consolidate management and move into commercial debt in one step. The sequence many investors follow is to BRRRR houses until the portfolio has real equity, then exchange groups of houses into multifamily. Line up the replacement property before you list the houses; forty-five days is short." },
        { h: "Cautions", p: "The timelines are strict and there is no extension for missing a deadline. Selling to a related party, holding a property for a very short time, or treating a flip as an exchange invites IRS challenge. Each exchange has intermediary fees. And the deferred gain comes due if you ever sell without exchanging again, although current law gives a step-up in basis to heirs at death, which is part of the family-office thinking in lesson eight. Confirm all of this with a CPA before you sell anything." },
        { carry: "1031: real property for real property, investment use only, 45 days to identify, 180 days to close, intermediary holds the funds, equal or greater value and debt, Form 8824. Confirm with a CPA." },
        { trap: "Closing the sale, putting the cash in your account, then calling an intermediary. Once you have touched the money the exchange is dead and the gain is taxable." },
        { sources: [
          { t: "IRS Instructions for Form 8824, Like-Kind Exchanges (45/180-day rules, real property only)", u: "https://www.irs.gov/instructions/i8824" },
          { t: "IRS Fact Sheet FS-2008-18, Like-Kind Exchanges Under IRC Section 1031", u: "https://www.irs.gov/pub/irs-news/fs-08-18.pdf" },
          { t: "Ohio IT 1040 instructions (Ohio return begins from federal adjusted gross income)", u: "https://dam.assets.ohio.gov/image/upload/tax.ohio.gov/forms/ohio_individual/individual/2025/it1040-booklet.pdf" }
        ] }
      ]
    },
    {
      id: "m16-05",
      title: "The Hiring Order and What It Costs",
      minutes: 11,
      blocks: [
        { h: "Hire for the constraint, in this order", p: "The order is virtual assistant, then acquisitions help, then transaction coordinator, then property manager, then bookkeeper, with one exception: if you are holding rentals from deal one and have a job, the property manager often comes first in practice, because tenants call at two in the morning and you cannot answer from work. Every other hire waits until the task is written down and you have done it yourself enough to judge whether it is being done well. Cost ranges below are approximate, drawn from 2026 industry sources, and will differ by market." },
        { h: "Virtual assistant", p: "A virtual assistant, or VA, is a remote contractor who handles repeatable work: pulling and skip-tracing lists, loading leads into the CRM, sending first-touch texts you approve, scheduling, and data entry. Many investors hire overseas, and one 2026 rate guide puts Filipino VAs at roughly five to nine dollars an hour for lead-generation and telemarketing roles and seven to twelve dollars an hour for real estate support such as transaction help and property research, with experienced specialists higher. Start at ten to twenty hours a week. Give them the checklist, not the judgment. Remember that any outbound calling or texting they do on your behalf is still subject to the TCPA and state telemarketing laws covered in the AI module." },
        { h: "Acquisitions", p: "An acquisitions manager talks to sellers, runs appointments, and makes offers, which is the highest-value and hardest-to-delegate job in the business. One 2026 playbook describes three common pay structures: a base of roughly thirty to forty-five thousand dollars plus five hundred to fifteen hundred dollars per closed deal, a lower base of roughly twenty-four to thirty-six thousand plus five to ten percent of the assignment fee, or commission only at eight to fifteen percent of the fee with no base. Do not hire this role until your own conversion ratios are known, because you cannot manage what you cannot measure. Many two-partner teams never hire this role; one partner is acquisitions." },
        { h: "Transaction coordinator", p: "A transaction coordinator, or TC, manages the paperwork from signed contract to closing: title orders, deadlines, disclosures, lender documents, and communication among everyone. Most are paid per file rather than hourly. A 2026 industry article puts experienced TCs at roughly four hundred to six hundred dollars per transaction, with entry-level around three hundred fifty and full-service up to about seven hundred, and a cancellation fee of one to two hundred dollars if a deal dies. Hire a TC when you are closing more than one or two files a month and deadlines are slipping." },
        { h: "Property manager", p: "A property manager leases, collects rent, handles maintenance, and enforces the lease. The usual structure is a monthly fee of about eight to twelve percent of collected rent for single-family and small multifamily, a leasing or tenant-placement fee of fifty to one hundred percent of one month's rent or a flat five hundred to fifteen hundred dollars, and renewal fees of roughly one hundred to three hundred fifty dollars, per a 2026 fee guide. Ask about maintenance markups, which are commonly ten to fifteen percent on contractor invoices. Build the management fee into every deal analysis from day one even if you self-manage, so the deal still works when you stop." },
        { h: "Bookkeeper", p: "A bookkeeper records every transaction, reconciles accounts, and produces the monthly statements your lenders and CPA need. Basic virtual bookkeeping for a small business runs roughly one hundred to four hundred dollars a month at the low end and five hundred to twenty-five hundred for fuller packages, per one 2026 price guide, with hourly rates of about fifty to one hundred fifty dollars. Hire one the month your second property closes. Clean books are what let you get the bank loans in lesson three." },
        { carry: "Order: VA, acquisitions, TC, property manager, bookkeeper (PM first if you hold rentals with a job). Approximate 2026 costs: VA $5–$12/hr; acquisitions base plus 5–15% of fees; TC $350–$700 per file; PM 8–12% of rent plus leasing; bookkeeper $100–$400/month basic." },
        { trap: "Hiring to escape a task you never learned. You cannot judge a property manager's work if you never leased a unit yourself." },
        { sources: [
          { t: "Filipino virtual assistant rates by role, 2026", u: "https://vamasters.com/hiring-a-virtual-assistant-in-the-philippines-heres-what-it-costs/" },
          { t: "Real estate acquisitions manager compensation playbook, 2026", u: "https://dialingfordollars.co/blog/real-estate-acquisitions-manager-playbook.html" },
          { t: "Transaction coordinator fees, 2026", u: "https://www.aide-re.com/post/tc-fee" },
          { t: "Property management fees, 2026", u: "https://www.allpropertymanagement.com/resources/ask-a-pro/posts/how-much-property-managers-charge/" },
          { t: "Bookkeeper cost price list, 2026", u: "https://catalyst-cpa.com/how-much-does-a-bookkeeper-cost-2026-price-list/" }
        ] }
      ]
    },
    {
      id: "m16-06",
      title: "KPIs by Stage",
      minutes: 8,
      blocks: [
        { h: "The numbers change as you grow", p: "In the daily-operator module you learned the five pipeline KPIs: leads, conversations, appointments, offers, deals analyzed. Those never go away, but at each stage a new layer of numbers sits on top, because the thing most likely to kill the business changes." },
        { h: "Stage one and two: deal quality", p: "Add three numbers to the pipeline KPIs. Cash left in each deal, compared with your plan. Rehab variance, meaning actual rehab cost versus budget, as a percentage. Days from purchase to refinance. These tell you whether your analysis is honest. If cash left in keeps coming in high, your ARVs are optimistic. If rehab variance runs over twenty percent, your scopes are missing items. If days to refinance stretch, you are losing money to carrying costs." },
        { h: "Stage three: team output", p: "When you hire, track output per person: conversations and appointments per week for anyone touching sellers, files closed on time for a transaction coordinator, days vacant and maintenance cost per door for a property manager, and days to produce monthly statements for a bookkeeper. Also track your own hours in the business. If your hours are not falling as the team grows, you are not delegating, you are supervising." },
        { h: "Stage four: portfolio health", p: "At portfolio scale the numbers are about survival. Occupancy, as a percentage of doors rented. Collections, as rent collected versus rent billed. Portfolio debt service coverage, meaning total net operating income divided by total debt payments, which your bank will also watch. Cash reserves in months of total expenses. A calendar of every loan's balloon or rate-reset date. And net worth, meaning total property value minus total debt, updated quarterly with conservative values. These five or six numbers belong on one page you look at every week." },
        { formula: "Portfolio DSCR = Total net operating income ÷ Total annual debt service (banks typically want about 1.20–1.25)" },
        { carry: "Stage 1–2: cash left in, rehab variance, days to refi. Stage 3: output per hire and your own hours. Stage 4: occupancy, collections, portfolio DSCR, months of reserves, balloon dates, net worth." },
        { trap: "Watching only pipeline numbers at twenty doors. A portfolio dies from a missed balloon date or thin reserves, not from a slow lead week." }
      ]
    },
    {
      id: "m16-07",
      title: "Income Replacement Math",
      minutes: 10,
      blocks: [
        { h: "The honest version", p: "The question everyone eventually asks is how many doors it takes to quit the job. The formula is simple and the answer is usually bigger and slower than people hope. This lesson gives the formula, a worked example, and the bridge income that actually gets most people across." },
        { formula: "Monthly rental income needed ÷ Net cash flow per door = Doors needed" },
        { example: "You need $6,000 a month to replace a salary after taxes. If a door nets $200 a month after the payment, taxes, insurance, management, vacancy, and repair reserves, you need 30 doors. At $300 a door, 20 doors. At $150 a door, 40 doors." },
        { h: "Why cash flow alone takes years", p: "Early BRRRR deals are financed at high loan-to-value because that is what lets you recycle capital, and high leverage means thin cash flow. Two hundred dollars a door is a common planning number for a leveraged single-family rental in a moderate market, and some deals produce less once you honestly reserve for roofs and turnovers. If you add two to four doors a year, which is a realistic pace for a part-time operator, thirty doors is roughly eight to fifteen years. Rents rise and loans pay down over that time, so cash flow per door grows, but anyone telling you rentals will replace your income in two years is selling something. Rentals build net worth first and income later." },
        { h: "The bridge: active income", p: "The gap gets closed with active real estate income while the portfolio matures. Wholesaling, meaning putting a property under contract and assigning that contract to another buyer for a fee, produces lump sums without needing capital or credit; the fee is whatever spread you negotiate between your contract price and the buyer's price, and it varies widely by deal and market. Agent commissions, if one partner holds a license, add a second lump-sum stream from representing buyers and sellers; commission is negotiated on every transaction. Flipping produces larger lumps with more risk. The pattern is to let active income pay the bills and fund down payments while the rentals quietly compound. Treat lump-sum income as unpredictable: it arrives in clumps, so keep six months of personal expenses in reserve before you lean on it." },
        { h: "A combined picture", p: "Suppose by year four you have twelve doors at $200 a door, which is $2,400 a month, plus one wholesale fee every other month and a few agent transactions a year. The rental income is steady but small; the active income is lumpy but large. Together they can replace a salary years before rentals alone could. By year ten the rentals may be at twenty-five doors with higher rents and lower balances, and the active income becomes optional. That is the realistic shape of income replacement for a two-person team starting from zero." },
        { carry: "Doors needed = monthly income needed ÷ net cash flow per door. At $200 a door, $6,000 a month is 30 doors, which is many years. Wholesale fees and commissions are the bridge; rentals are the destination." },
        { trap: "Quitting the job when rental cash flow equals your salary on paper. One roof and two vacancies erase a year of thin cash flow. Keep reserves and keep the bridge income until the portfolio is seasoned." }
      ]
    },
    {
      id: "m16-08",
      title: "The Family Office Mindset",
      minutes: 9,
      blocks: [
        { h: "What a family office is", p: "A family office is simply the structure wealthy families use to manage their assets as one business across generations: holding entities, professional advisors, written policies, and a plan for who runs it next. You do not need millions to think this way. You need to decide early that you are building something that outlives the next deal, and set up the plumbing while it is cheap." },
        { h: "The holding structure", p: "A common structure places each property or small group of properties in its own limited liability company for liability separation, with those LLCs owned by a parent holding company that you and your partner own. The holding company holds the bank relationships, the bookkeeping, and the brand. Lenders will have opinions about how title is held, especially on agency loans, so coordinate the structure with your lender and attorney before closing rather than moving title afterward. Keep every entity's money separate, keep an operating agreement that spells out what happens if a partner dies, divorces, or wants out, and hold an annual meeting with written minutes even if the meeting is the two of you at a kitchen table." },
        { h: "Estate planning basics", p: "At minimum, each partner needs a will, powers of attorney for finances and health care, and current beneficiary designations on every account. Many investors use a revocable living trust to hold their ownership interests so the business does not stall in probate if one of you dies. The partnership agreement should include a buy-sell provision that says how a deceased or departing partner's share is valued and purchased, often funded with life insurance so the surviving partner is not forced to sell properties to pay the estate. Under current federal tax law, property that passes to heirs at death generally receives a basis equal to its fair market value at that date, which is why long-term holders who exchange rather than sell can pass appreciated real estate to the next generation with the deferred gain wiped out. Laws change; confirm with a CPA and an estate attorney, and confirm entity and title questions with a local real estate attorney." },
        { h: "Teaching the next generation", p: "The last part of the family office mindset is making sure the people who inherit the portfolio know how to run it or know how to hire people who do. Involve family in the annual meeting as they get older. Have them walk a property, read a lease, and sit in on a bookkeeping review. Write the operating manual you built in the systems stage so a stranger could run the business from it. A portfolio handed to someone who cannot read a rent roll gets sold cheap." },
        { carry: "Think like a family office early: property LLCs under a holding company, separate accounts, an operating agreement with a buy-sell clause, wills and powers of attorney, a trust for ownership interests, an annual meeting, and a written manual. Confirm with a CPA and attorney." },
        { trap: "Two partners with no written agreement about death or departure. One funeral or one divorce can force a sale of the whole portfolio." },
        { sources: [
          { t: "IRS Publication 551, Basis of Assets (inherited property basis)", u: "https://www.irs.gov/publications/p551" }
        ] }
      ]
    },
    {
      id: "m16-09",
      title: "The Exit Math: Net Worth Versus Cash Flow",
      minutes: 9,
      blocks: [
        { h: "Two different millions", p: "A million dollars of net worth means your properties are worth a million more than you owe on them. A million dollars of cash flow means your properties pay you a million a year after all expenses and debt. These are not the same goal, they arrive at very different times, and confusing them is why people feel poor at twenty doors." },
        { h: "Net worth comes first", p: "Go back to the ten-deal example in lesson two. Ten houses worth $1,850,000 with $1,387,500 of debt is $462,500 of equity. Twenty such houses, or ten houses plus a decade of appreciation and loan paydown, crosses a million of net worth. A part-time operator doing two to four BRRRRs a year can plausibly reach a million of net worth in roughly seven to twelve years in a moderate market, because every deal creates forty to fifty thousand of equity on day one and the market and amortization add more over time. Net worth is created by buying right. It shows up immediately." },
        { formula: "Net worth = Total property value − Total debt. Cash flow = Rent − (payment + taxes + insurance + management + vacancy + repairs + reserves)." },
        { h: "Cash flow comes much later", p: "A million a year of cash flow is about $83,000 a month. At $200 a door that is more than four hundred doors. Nobody gets there on leveraged single-family rentals. Large cash flow comes from one of three moves: paying down or paying off debt so the payment disappears, which converts equity into income slowly; moving into larger multifamily or commercial property where the income per dollar of equity is higher; or selling appreciated property and redeploying into higher-yield assets. Each of those requires net worth first. That is why the order is build equity, then convert equity into income." },
        { example: "Ten paid-off houses renting at $1,650 each gross about $198,000 a year and might net $120,000 after taxes, insurance, management, and reserves. The same ten houses leveraged at 75% net about $24,000 a year. Same properties, five times the cash flow, and the difference is the debt." },
        { h: "What this means for your plan", p: "In the early years, judge yourself on equity created and doors added, not on monthly cash flow, which will be thin by design. Keep the bridge income from lesson seven running. Somewhere past the first million of net worth, shift the strategy from acquisition to conversion: stop pulling every dollar out on refinance, begin paying down the highest-rate loans, exchange houses into buildings with better income, and let the portfolio start paying you. The exit is not a sale. The exit is the day the portfolio's income covers your life and the bridge income becomes optional." },
        { carry: "A million of net worth comes first, from buying right and holding; a million of cash flow comes later, from converting that equity by paying down debt, trading up, or redeploying. Build equity, then convert it." },
        { trap: "Measuring early years by cash flow and concluding the strategy failed. Leveraged BRRRR is an equity engine. Thin cash flow in year three is the plan working, not failing." }
      ]
    }
  ],
  cards: [
    { id: "m16-c01", type: "number", q: "What are the four scaling stages by deal count?", a: "Deal 1 learn; deals 2–5 systems; deals 6–15 team; deals 16–30 portfolio and financing shift." },
    { id: "m16-c02", type: "term", q: "What is the goal of deal one?", a: "To learn every job yourself and finish without losing money. Not to scale, not to hire. Write down every mistake." },
    { id: "m16-c03", type: "scenario", q: "You are on deal three and want to hire a VA. Right move?", a: "Not yet. Deals 2–5 are for writing checklists for every task. Hire once each task is documented and you have done it enough to judge the work." },
    { id: "m16-c04", type: "trap", q: "What is the stage mistake at deals 6–15?", a: "Still doing everything yourself while holding a job. Time is now the constraint; start the hiring order and shift from doing to checking." },
    { id: "m16-c05", type: "formula", q: "What is the cash-left-in formula?", a: "Cash left in = all-in cost − (appraised value × refinance LTV − refinance costs). Example: $140,000 − ($185,000 × 0.75 − $4,000) = $5,250." },
    { id: "m16-c06", type: "number", q: "In the module's illustrative deal, how much equity does one BRRRR create?", a: "$185,000 value minus a $138,750 loan = $46,250 of equity, with about $5,250 of cash left in." },
    { id: "m16-c07", type: "number", q: "In the ten-deal example, what does a $60,000 pot become?", a: "About $52,500 spent, ten houses worth $1,850,000 with $1,387,500 of debt: roughly $462,500 of equity and about $2,000 a month of cash flow. Illustrative, not a forecast." },
    { id: "m16-c08", type: "term", q: "What is seasoning in a refinance?", a: "The time a lender requires you to have owned a property before refinancing on its new appraised value. Fannie Mae has required 12 months for cash-out refinances since February 2023; DSCR lenders often allow less, varying by lender." },
    { id: "m16-c09", type: "scenario", q: "Your appraisal comes in $15,000 under your projection. What happens to the recycling plan?", a: "Your loan drops by 75% of $15,000, about $11,250, so cash left in jumps from $5,250 to about $16,500. Budget a cushion for low appraisals or the next deal stalls." },
    { id: "m16-c10", type: "trap", q: "Why does a 'perfect BRRRR' plan fail?", a: "It assumes every dollar comes back and no seasoning wait. Real deals leave cash in, appraisals miss, and seasoning slows cycles to one or two deals a year per pot." },
    { id: "m16-c11", type: "scenario", q: "You want to do more than two BRRRRs a year with one pot of cash. What are the options?", a: "A second pot, or a private lender who funds the next purchase while the last property seasons. Two pots roughly doubles the pace." },
    { id: "m16-c12", type: "term", q: "What is a DSCR loan?", a: "A loan qualified on the property's rent divided by its payment (debt service coverage ratio) rather than your personal income. Typical minimum ratio 1.0, better pricing above about 1.2." },
    { id: "m16-c13", type: "number", q: "How many financed properties does Fannie Mae allow a borrower with an investment-property loan?", a: "Ten, per Selling Guide B2-2-03. Many lenders stop earlier in practice." },
    { id: "m16-c14", type: "number", q: "As of mid 2026, what were typical DSCR loan terms per one industry comparison?", a: "Roughly 6.125%–7.375% rates, 75–80% purchase LTV, 70–75% cash-out LTV, 30-year fixed, 3–5 year step-down prepayment penalties, no count cap. Verify current terms." },
    { id: "m16-c15", type: "term", q: "What is a blanket or portfolio loan?", a: "One loan from a bank that keeps it on its books, secured by several properties at once. Simplifies ten payments into one; usually carries recourse and a balloon." },
    { id: "m16-c16", type: "number", q: "At what unit count does a residential building become commercial for financing?", a: "Five or more units. One-to-four units is residential financing; five-plus is commercial multifamily debt underwritten on the building's income, typically at a DSCR of about 1.20–1.25." },
    { id: "m16-c17", type: "number", q: "What do community banks typically want from an investor borrower?", a: "Tax returns, a personal financial statement, global cash flow on all properties, your deposit accounts, and a personal guarantee. Typical 2026 structure: 5, 7, or 10 year fixed on a 20–25 year amortization with a balloon." },
    { id: "m16-c18", type: "trap", q: "When should you first walk into a community bank?", a: "At deal three, not deal fifteen. Open accounts, meet the commercial lender, and show them deals as you go. Banks lend to people they know." },
    { id: "m16-c19", type: "scenario", q: "You own nine houses on nine DSCR loans and want to buy a six-unit building. What financing applies?", a: "The six-unit is commercial property, so commercial multifamily debt, not a residential DSCR loan. A community bank that knows you is the natural lender; it may also offer a blanket loan on the nine houses." },
    { id: "m16-c20", type: "term", q: "What is a 1031 exchange?", a: "Under IRC Section 1031, selling real property held for investment or business and buying other such real property, deferring the capital gains tax if the rules are followed. The old basis carries over." },
    { id: "m16-c21", type: "number", q: "What are the 1031 deadlines?", a: "Identify replacement property in writing within 45 days of the sale; receive it within 180 days or by your tax return due date including extensions, whichever is earlier. No extensions." },
    { id: "m16-c22", type: "term", q: "What is a qualified intermediary?", a: "A neutral third party that holds your sale proceeds between the sale and the purchase in a 1031 exchange. If you touch the money, the exchange fails." },
    { id: "m16-c23", type: "term", q: "What is boot in a 1031 exchange?", a: "Cash or debt relief you receive in the exchange. It is taxable. To defer all gain, buy equal or greater value and replace the debt or add cash." },
    { id: "m16-c24", type: "trap", q: "Can you 1031 a flip or a wholesale contract?", a: "No. Property held primarily for sale does not qualify, and neither does a personal residence. 1031 is for real property held for investment or business use." },
    { id: "m16-c25", type: "scenario", q: "You sell four rentals for $800,000 with $500,000 of loans and want to defer all gain into a 12-unit building. What must the purchase look like?", a: "Equal or greater value and equal or greater debt: for example $1,100,000 with the $300,000 of proceeds from the intermediary plus a new $800,000 loan, identified within 45 days and closed within 180. Report on Form 8824." },
    { id: "m16-c26", type: "state", q: "Do Florida and Ohio treat 1031 exchanges differently?", a: "FL: no state personal income tax, so only the federal deferral applies. | OH: the Ohio IT 1040 starts from federal adjusted gross income, so gain deferred federally under 1031 is generally not in Ohio taxable income that year either; confirm with a CPA." },
    { id: "m16-c27", type: "number", q: "What is the hiring order?", a: "Virtual assistant, acquisitions, transaction coordinator, property manager, bookkeeper. Exception: property manager first if you hold rentals while working a job." },
    { id: "m16-c28", type: "number", q: "What do virtual assistants cost, approximately, in 2026?", a: "One rate guide puts Filipino VAs at about $5–$9 an hour for lead generation and calling, $7–$12 for real estate support, more for specialists. Start at 10–20 hours a week." },
    { id: "m16-c29", type: "trap", q: "Your VA sends texts to a cold list for you. Who is liable under the TCPA?", a: "You are. Outsourcing the sending does not outsource the consent requirement. Approve every outbound message and keep consent records." },
    { id: "m16-c30", type: "number", q: "How are acquisitions managers commonly paid, per a 2026 playbook?", a: "Base of about $30k–$45k plus $500–$1,500 per closed deal; or base of about $24k–$36k plus 5–10% of the assignment fee; or commission only at 8–15% of the fee." },
    { id: "m16-c31", type: "scenario", q: "You want to hire an acquisitions manager but do not know your own conversion ratios. Should you?", a: "No. You cannot manage what you cannot measure. Learn your conversations-to-appointments and offers-to-contracts ratios first, then hire and hold them to those." },
    { id: "m16-c32", type: "term", q: "What does a transaction coordinator do and cost?", a: "Manages contract-to-close paperwork, deadlines, title, and lender documents. Approximately $350–$700 per file in 2026, around $500 typical, with a $100–$200 cancellation fee." },
    { id: "m16-c33", type: "number", q: "What are typical property management fees in 2026?", a: "About 8–12% of collected rent monthly for single-family and small multifamily, a leasing fee of 50–100% of one month's rent or $500–$1,500 flat, renewal fees of $100–$350, and maintenance markups of 10–15%." },
    { id: "m16-c34", type: "trap", q: "You self-manage, so you leave management out of your deal analysis. Why is that a mistake?", a: "The deal must still work when you stop managing. Build the 8–12% fee into every analysis from day one." },
    { id: "m16-c35", type: "number", q: "What does a bookkeeper cost and when do you hire one?", a: "Basic virtual bookkeeping roughly $100–$400 a month, fuller packages $500–$2,500, hourly about $50–$150, per a 2026 guide. Hire the month your second property closes." },
    { id: "m16-c36", type: "scenario", q: "A lender asks for a personal financial statement and two years of clean property statements. You have shoebox receipts. What stage mistake was made?", a: "Skipping the bookkeeper. Clean monthly books are the price of admission to bank portfolio loans. Hire one now and rebuild the last twelve months." },
    { id: "m16-c37", type: "number", q: "What KPIs are added in stages one and two?", a: "Cash left in versus plan, rehab variance as a percent of budget, and days from purchase to refinance." },
    { id: "m16-c38", type: "scenario", q: "Your rehab variance has run over 20% on three deals in a row. What does it tell you?", a: "Your scopes are missing items. Walk the next house system by system and get three bids on the written scope before offering." },
    { id: "m16-c39", type: "number", q: "What KPIs matter at team stage?", a: "Output per person: conversations and appointments per week for seller-facing roles, files closed on time for the TC, days vacant and maintenance cost per door for the PM, days to monthly statements for the bookkeeper, plus your own hours." },
    { id: "m16-c40", type: "trap", q: "Your team has grown but your hours have not fallen. What is happening?", a: "You are supervising, not delegating. Give each role a written standard and a KPI, then stop checking every step." },
    { id: "m16-c41", type: "number", q: "What are the portfolio-stage health numbers?", a: "Occupancy, collections (rent collected ÷ rent billed), portfolio DSCR, months of cash reserves, every loan's balloon or reset date, and net worth updated quarterly." },
    { id: "m16-c42", type: "formula", q: "What is portfolio DSCR?", a: "Total net operating income ÷ total annual debt service. Banks typically want about 1.20–1.25. Example: $180,000 NOI ÷ $144,000 debt service = 1.25." },
    { id: "m16-c43", type: "formula", q: "What is the income-replacement formula?", a: "Doors needed = monthly income needed ÷ net cash flow per door. Example: $6,000 ÷ $200 = 30 doors." },
    { id: "m16-c44", type: "number", q: "Why does rental cash flow alone take years to replace a salary?", a: "Leveraged BRRRR deals are thin by design, often around $200 a door after honest reserves. At two to four doors a year, 30 doors is roughly eight to fifteen years." },
    { id: "m16-c45", type: "term", q: "What is the bridge income?", a: "Active real estate income that pays the bills while rentals mature: wholesale assignment fees, agent commissions if a partner is licensed, and flips. Lumpy, so keep six months of reserves." },
    { id: "m16-c46", type: "trap", q: "Rental cash flow on paper equals your salary. Should you quit?", a: "Not yet. One roof and two vacancies erase a year of thin cash flow. Keep reserves and bridge income until the portfolio is seasoned." },
    { id: "m16-c47", type: "term", q: "What is the family office mindset?", a: "Running your properties as one multi-generational business: holding entities, separate accounts, written policies, advisors, an annual meeting, and a plan for who runs it next." },
    { id: "m16-c48", type: "term", q: "What is a common holding structure for a growing portfolio?", a: "Each property or small group in its own LLC, owned by a parent holding company the partners own. Coordinate with your lender and attorney before closing; agency lenders have title rules." },
    { id: "m16-c49", type: "term", q: "What is a buy-sell provision?", a: "A clause in the partnership agreement that says how a deceased or departing partner's share is valued and bought, often funded by life insurance so the survivor is not forced to sell properties." },
    { id: "m16-c50", type: "trap", q: "Two partners, no written agreement about death or divorce. What is the risk?", a: "One funeral or one divorce can force a sale of the entire portfolio. Put an operating agreement with a buy-sell clause in place before deal two." },
    { id: "m16-c51", type: "number", q: "What basic estate documents does each partner need?", a: "A will, financial and health care powers of attorney, current beneficiary designations, and often a revocable living trust holding the ownership interests to avoid probate. Confirm with an estate attorney." },
    { id: "m16-c52", type: "term", q: "What is the step-up in basis and why does it matter to long-term holders?", a: "Under current federal law, inherited property generally takes a basis equal to its fair market value at death (IRS Publication 551). Gain deferred through 1031 exchanges can be wiped out for heirs. Confirm with a CPA." },
    { id: "m16-c53", type: "formula", q: "What is net worth versus cash flow?", a: "Net worth = total property value − total debt. Cash flow = rent − (payment + taxes + insurance + management + vacancy + repairs + reserves). They arrive at very different times." },
    { id: "m16-c54", type: "number", q: "How many $200-a-door rentals would it take to produce $1,000,000 a year?", a: "About $83,000 a month ÷ $200 = more than 400 doors. Large cash flow does not come from leveraged single-family rentals." },
    { id: "m16-c55", type: "scenario", q: "Ten houses renting at $1,650 each: compare paid-off versus 75% leveraged cash flow.", a: "Paid off: roughly $198,000 gross, perhaps $120,000 net a year. Leveraged: roughly $24,000 net a year. Same houses, about five times the cash flow; the difference is the debt." },
    { id: "m16-c56", type: "trap", q: "In year three your cash flow is thin and you conclude BRRRR failed. What is wrong with that conclusion?", a: "Leveraged BRRRR is an equity engine. Thin early cash flow is the plan working. Judge early years on equity created and doors added." },
    { id: "m16-c57", type: "scenario", q: "You have crossed a million of net worth. How does the strategy change?", a: "Shift from acquisition to conversion: stop pulling every dollar out on refinance, pay down the highest-rate loans, exchange houses into buildings with better income, and let the portfolio start paying you." }
  ],
  quiz: [
    { id: "m16-q01", q: "What is the main purpose of deal one?", opts: ["Learning every job yourself without losing money","Maximum profit","Hiring a team","Qualifying for a bank loan"], correct: 0, explain: "Deal one teaches. You do every task yourself so you can later judge and delegate it." },
    { id: "m16-q02", q: "Using the module's formula, what is cash left in for all-in $140,000, appraisal $185,000, 75% LTV, $4,000 refi costs?", opts: ["$1,250", "$5,250", "$9,250", "$46,250"], correct: 1, explain: "$185,000 × 0.75 = $138,750; minus $4,000 = $134,750 net; $140,000 − $134,750 = $5,250. $46,250 is the equity created." },
    { id: "m16-q03", q: "In the ten-deal example, roughly how much equity does a $60,000 pot produce?", opts: ["$60,000","$185,000","$1,850,000","$462,500"], correct: 3, explain: "Ten houses worth $1,850,000 minus $1,387,500 of debt equals about $462,500 of equity." },
    { id: "m16-q04", q: "Since February 2023, how long has Fannie Mae required a first mortgage to be in place before it can be paid off in a cash-out refinance?", opts: ["3 months", "6 months", "12 months", "24 months"], correct: 2, explain: "Fannie Mae's SEL-2023-01 set a 12-month seasoning requirement for cash-out refinances, with limited exceptions. DSCR lenders set their own, often shorter, rules." },
    { id: "m16-q05", q: "What is Fannie Mae's maximum number of financed properties for a borrower with an investment-property loan?", opts: ["4", "6", "10", "Unlimited"], correct: 2, explain: "Selling Guide B2-2-03 caps it at ten. DSCR lenders have no count cap." },
    { id: "m16-q06", q: "A building with how many units is financed as commercial multifamily?", opts: ["Two or more", "Three or more", "Four or more", "Five or more"], correct: 3, explain: "One-to-four units is residential financing; five-plus is commercial, underwritten on the building's income." },
    { id: "m16-q07", q: "Which is typical of a community bank portfolio loan?", opts: ["30-year fixed, no recourse, no income docs","Qualifies only on the property's rent","No down payment","5–10 year fixed with a balloon, personal recourse, full income documentation"], correct: 3, explain: "Banks keep the loan on their books and want full docs, deposits, a guarantee, and a balloon or reset after the fixed period." },
    { id: "m16-q08", q: "What are the 1031 identification and closing deadlines?", opts: ["30 and 90 days", "45 and 180 days", "60 and 365 days", "90 and 180 days"], correct: 1, explain: "Identify in writing within 45 days; receive the replacement within 180 days or by the tax return due date including extensions, whichever is earlier." },
    { id: "m16-q09", q: "Which property qualifies for a 1031 exchange?", opts: ["A rental held for investment","Your personal residence","A house you flipped after a 3-month rehab","A wholesale contract"], correct: 0, explain: "Only real property held for investment or business use qualifies. Property held primarily for sale and personal residences are excluded." },
    { id: "m16-q10", q: "You close the sale and deposit the proceeds in your business account, then call an intermediary. What happened?", opts: ["Nothing; you have 45 days","The intermediary can fix it","You owe a penalty but can still exchange","The exchange is dead and the gain is taxable"], correct: 3, explain: "A qualified intermediary must hold the funds. Once you touch the money, the exchange fails." },
    { id: "m16-q11", q: "What is the recommended hiring order?", opts: ["Bookkeeper, PM, TC, acquisitions, VA","Property manager only","Acquisitions first, everything else later","VA, acquisitions, TC, property manager, bookkeeper"], correct: 3, explain: "VA, acquisitions, TC, PM, bookkeeper, with PM first in practice if you hold rentals while working a job." },
    { id: "m16-q12", q: "Per a 2026 fee guide, what is the typical monthly property management fee for single-family rentals?", opts: ["2–4% of rent", "8–12% of rent", "20–25% of rent", "A flat $50"], correct: 1, explain: "Eight to twelve percent of collected rent, plus leasing fees of 50–100% of one month's rent." },
    { id: "m16-q13", q: "Approximately what do experienced transaction coordinators charge per file in 2026?", opts: ["$50–$100", "$150–$250", "$400–$600", "$2,000–$3,000"], correct: 2, explain: "About $400–$600, with entry-level near $350 and full-service up to about $700." },
    { id: "m16-q14", q: "Which KPI belongs to the portfolio stage?", opts: ["Portfolio DSCR and balloon dates","Rehab variance","Conversations per day","Offers made"], correct: 0, explain: "At portfolio scale, survival depends on debt coverage, reserves, occupancy, collections, and knowing when each loan resets." },
    { id: "m16-q15", q: "You need $6,000 a month and each door nets $200. How many doors?", opts: ["12", "20", "30", "60"], correct: 2, explain: "$6,000 ÷ $200 = 30 doors." },
    { id: "m16-q16", q: "What does the module call the 'bridge income'?", opts: ["A bridge loan","Rental cash flow","Appreciation","Wholesale fees, agent commissions, and flips that pay bills while rentals mature"], correct: 3, explain: "Active income closes the gap for years while the leveraged portfolio builds equity." },
    { id: "m16-q17", q: "Why does the module say a million of net worth comes before a million of cash flow?", opts: ["Equity is created on day one by buying right; large income requires converting that equity later","Cash flow is taxed more","Net worth is easier to measure","Lenders prefer it"], correct: 0, explain: "Each BRRRR creates equity immediately. Income grows only as debt is paid down, properties are traded up, or equity is redeployed." },
    { id: "m16-q18", q: "Ten houses at $1,650 rent: roughly how does paid-off cash flow compare with 75% leveraged?", opts: ["About the same", "About twice", "About five times", "About twenty times"], correct: 2, explain: "Roughly $120,000 net paid off versus about $24,000 leveraged in the module's example. The debt payment is the difference." },
    { id: "m16-q19", q: "What does a buy-sell provision do?", opts: ["Defines how a departing or deceased partner's share is valued and purchased","Sets the price you pay for houses","Lets a lender sell your property","Replaces a will"], correct: 0, explain: "It prevents a death or divorce from forcing a portfolio sale, often funded with life insurance." },
    { id: "m16-q20", q: "Under current federal law, what basis does inherited property generally receive?", opts: ["The decedent's original purchase price", "Zero", "Fair market value at the date of death", "The outstanding loan balance"], correct: 2, explain: "IRS Publication 551 describes the stepped-up basis to fair market value at death, which can erase gain deferred through 1031 exchanges. Confirm with a CPA." }
  ],
  drills: [
    "Write down which stage you are in by deal count and the single constraint that stage has. Decide one action this week that attacks that constraint.",
    "Run the cash-left-in formula on your last or next deal with three appraisal scenarios: as planned, $10,000 low, $20,000 low. Note what happens to your next purchase in each.",
    "Open a business account at a local community bank this month and ask to meet the commercial lender. Bring a one-page summary of your deals so far.",
    "Draft your hiring order with a trigger for each role (for example, 'hire a bookkeeper when property two closes') and an approximate monthly cost next to each.",
    "Build a one-page portfolio dashboard template with occupancy, collections, portfolio DSCR, months of reserves, balloon dates, and net worth, even if the numbers are small today.",
    "Schedule a conversation with your partner about an operating agreement with a buy-sell clause, and list the estate documents each of you still needs."
  ]
});
